### ISSUE TITLE
Audio format menu is buggy

### ISSUE THREAD

**Issue by girshcatt** [JunkFood02/Seal#1004]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

In audio format menu i see bug when u tap on preffered audio format or audio quality u cant close choice menu by tap on this menu, sorry for my bad english, if u don't understand me, see screen record 

### Error reports

ㅤ

### Screenshots & Screen Records

https://github.com/JunkFood02/Seal/assets/110785596/1004dcc0-91af-4b63-9896-ccab534302af

**Comment by Marco-9456** [comment]
Tapping outside it should make it close, the little arrow on the right is just for visualizing that the menu is open

**Comment by girshcatt** [comment]
If arrow changes rotation when u open menu, by second tap it need to close menu logically.
Or at least fix that if i tap when it already open do not open it again

**Comment by JunkFood02** [comment]
Reported to Google: https://issuetracker.google.com/issues/296976686
