### ISSUE TITLE
Temporary folder/files on SD card?

### ISSUE THREAD

**Issue by ganego** [JunkFood02/Seal#1005]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hi,

using an SD card to download videos to. This works fine.  

Problem: The temporary files are created on the internal storage. Bad for big videos - I want the temporary files on my SD.
  
"Temporary directory" in the options is disabled. According to the hint I expect the temporary files to be written to the specified SD folder then. They are not.

I'm running 1.10.0-beta.5.

Thank you

### Error reports

--

**Comment by JunkFood02** [comment]
Due to the limitation of the Android OS, we can't directly read/write files from/to SD Card directory.

**Comment by ganego** [comment]
> Due to the limitation of the Android OS, we can't directly read/write files from/to SD Card directory.

Then why does this option exist in the first place?  

And why can the app write the completed file to the SD card?

**Comment by JunkFood02** [comment]
We first download the files to the internal temporary directory, and then copy the files to the sd card.

**Comment by ganego** [comment]
1) So an app can only write from internet -> internal. But then from internal -> SD?  

2) What doe the setting ""Temporary directory"" supposed to to then?

**Comment by JunkFood02** [comment]
The Temporary directory option doesn't have a effect while using SD card, this is a bug which should be fixed in next release
