### ISSUE TITLE
can't download videos from Twitter.

### ISSUE THREAD

**Issue by CharlieVSAngel** [JunkFood02/Seal#1007]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

![Screenshot_20230824_120705](https://github.com/JunkFood02/Seal/assets/85690780/84ebde5b-1c22-4473-a811-0861f40fe3f4)

**Comment by ahsee** [comment]
This will probably be #733'd but I am seeing the same issue. Can confirm browser cookies are set, and I've tried reinstalling. The same URLs work fine for yt-dlp version via terminal.

**Comment by solonovamax** [comment]
This issue is an issue with upstream yt-dlp, so seal can't do anything to fix it atm.
