### ISSUE TITLE
Temporary files are not deleted in custom command mode

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#1014]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### To Reproduce

1. Start downloading any video,
2. Cancel downloading at any percent progress,
3. Go to 'Download directory' settings, press 'Clear temporary files' -> 0 temporary files deleted,
4. Connect your phone to PC and see, that there are temporary files in download folder. like PART and YTDL files.

<details>
  <summary>Screenshots</summary>
  
![image](https://github.com/JunkFood02/Seal/assets/28785698/8b199f4c-76a1-4957-b522-991ad21990d5)
![image](https://github.com/JunkFood02/Seal/assets/28785698/48e97053-b276-475e-8676-bdeaf0a5497a)

</details>

### Additional context

App version: 1.10.0-rc.1 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by Marco-9456** [comment]
Read the comment by JunkFood.
https://github.com/JunkFood02/Seal/issues/526

**Comment by Marco-9456** [comment]
Why are you reporting this again?
https://github.com/JunkFood02/Seal/issues/526

**Comment by JunkFood02** [comment]
Specify a temporary output path with `-P temp:` when using custom commands and clear the temporary files on your own

**Comment by Botan626** [comment]
> on your own

The same way I could delete manually all temp files from download directory on my PC or phone.
Is it impossible to make Seal delete temp files **with in app button** when in custom command mode?

**Comment by Marco-9456** [comment]
No, it's not the same, The `clear temporary files` option in the app was possible to made because the temporary files are always at the same path, and what you're talking about is not possible since each user when using custom command won't use the same path for the temp files, so it's logically not possible unless we force the users to use only one path for the custom command downloads which is ridicules and nobody will like it.

**Comment by Botan626** [comment]
By "the same" I meant manual files deletion from folder, since it doesn't matter from which folder delete files manually, there is no point to set custom temp folder with `-P temp:` for this purpose.

I understand that users may set different folders for temp files, but why this button
![image](https://github.com/JunkFood02/Seal/assets/28785698/a3d101fe-7f54-447b-8d7d-6804480893ee)
can't search for temp files in this folder
![image](https://github.com/JunkFood02/Seal/assets/28785698/d2a6754c-458f-48aa-b292-809831487bba)
and delete them for users, who use custom command mode and don't set custom temp folder with `-P temp:`?

**Comment by Botan626** [comment]
So no matter, custom temp folder is set with `-P temp:` or not (don't check for that), delete temp files from here
![image](https://github.com/JunkFood02/Seal/assets/28785698/96114cf7-0b60-4cc7-a1e5-9fbbf394dd11)

that is my suggestion

**Comment by JunkFood02** [comment]
we don't know which files are temporary files and we choose to delete all the files in the directory

**Comment by Botan626** [comment]
> we don't know which files are temporary files and we choose to delete all the files in the directory

If I turn this on
![image](https://github.com/JunkFood02/Seal/assets/28785698/d9fa3043-0118-4f5a-a25b-210e0795691b)
and click 'Clear temporary files', Seal will delete everything in download folder, including downloaded files?

**Comment by JunkFood02** [comment]
The **internal** directory is inside the `/data` directory of the app and cannot be accessed outside the app. The download directory is in the external directory
