### ISSUE TITLE
Generating cookies - Website refuses WebView cleartext connection

### ISSUE THREAD

**Issue by Enzycal** [JunkFood02/Seal#1015]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Not that big of an issue but it might be confusing for some. When generating cookies for patreon.com the WebView returns the following:
`Web page not available
The web page at http://patreon.com/ could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED`

To get past this you simply need to specify that it should use https in the url: https://patreon.com

This needs fixing because some people might not know why the connection is being refused. Or in the very least it should be mentioned in the help window.

### To Reproduce

1. Open Seal
2. Navigate to Settings > Network > Cookies
3. Select Generate new cookies
4. Input the following url: patreon.com or http://patreon.com
5. Tap on Generate new cookies

### Error reports

Web page not available
The web page at http://patreon.com/ could not be loaded because:

net::ERR_CLEARTEXT_NOT_PERMITTED

### Screenshots & Screen Records

![Screenshot_20230826-202314_Seal](https://github.com/JunkFood02/Seal/assets/45462298/21f1a7e8-8418-4506-95c1-dd20b84046ee)

**Comment by Marco-9456** [comment]
Use `https` instead of `http`

**Comment by Enzycal** [comment]
> Use `https` instead of `http`

I did but some people might be unaware why this happens hence why I posted this.

**Comment by JunkFood02** [comment]
> > Use `https` instead of `http`
> 
> I did but some people might be unaware why this happens hence why I posted this.

We've made `https://` as the default prefix for urls when creating new cookies profile, thanks for your feedback
