### ISSUE TITLE
ERROR DESCARGA DE VIDEO

### ISSUE THREAD

**Issue by kksos05** [JunkFood02/Seal#1017]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

No permite descargar video en la versión v1.10.0 -rc1

### Error reports

App version: 1.10.0-rc.1 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://youtube.com/watch?v=pWfkvcG6KX4&si=UqIgQNNVkSTh72SE
WARNING: The download speed shown is only of one thread. This is a known issue
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

### Screenshots & Screen Records

![Screenshot_20230826_192729_Seal](https://github.com/JunkFood02/Seal/assets/143159515/9d235463-7a2d-4a7c-901e-2aa52e4b6af6)

### Additional context

Después de la versión 3 me paso los mismo en todas las siguientes versiones... algunas veces si se descarga el video pero no se reproducía

**Comment by JunkFood02** [comment]
Settings - General, switch yt-dlp to nightly and see if the problem persists

**Comment by kksos05** [comment]
El problema sigue después de cambiar el ajuste

App version: 1.10.0-rc.1 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://youtube.com/watch?v=T6e3QMCsdM0&si=4iNC-vtRoX5LVuo0
WARNING: The download speed shown is only of one thread. This is a known
issue
WARNING: The download speed shown is only of one thread. This is a known
issue
ERROR: [download] Got error: HTTP Error 403: Forbidden. Giving up after 10
retries
ERROR: fragment 1 not found, unable to continue

**Comment by JunkFood02** [comment]
> switch yt-dlp to nightly and update it
