### ISSUE TITLE
Custom command selection lost after restart

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#1020]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

<details>
  <summary>before restart</summary>
  
![image](https://github.com/JunkFood02/Seal/assets/28785698/a5eab261-db77-4b4e-9abd-3060438e4d1c)

</details>

<details>
  <summary>after restart</summary>
  
![image](https://github.com/JunkFood02/Seal/assets/28785698/caa26eea-f69a-4bc8-b65d-24eb583f960b)

</details>

App version: 1.10.0-rc.1 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by Marco-9456** [comment]
Update the app

**Comment by Botan626** [comment]
fixed
