### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MAHEKKUMAR** [JunkFood02/Seal#1025]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.youtube.com/live/kOGo0L1kwdw?si=FzVj_yzzG2CYXztB
ERROR: [Errno 75] Value too large for defined data type: '/data/user/0/com.junkfood.seal/cache/tmp/International Tournament 😲🔥 NXT VS NGBD 😈 #NONSTOP_LIVE \u200b\u200b \u200b#FreeFireLive #ClassyLive [kOGo0L1kwdw].webm' -> '/storage/emulated/0/Download/Seal/International Tournament 😲🔥 NXT VS NGBD 😈 #NONSTOP_LIVE \u200b\u200b \u200b#FreeFireLive #ClassyLive [kOGo0L1kwdw].webm'

### Error reports

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.youtube.com/live/kOGo0L1kwdw?si=FzVj_yzzG2CYXztB
ERROR: [Errno 75] Value too large for defined data type: '/data/user/0/com.junkfood.seal/cache/tmp/International Tournament 😲🔥 NXT VS NGBD 😈 #NONSTOP_LIVE \u200b\u200b \u200b#FreeFireLive #ClassyLive [kOGo0L1kwdw].webm' -> '/storage/emulated/0/Download/Seal/International Tournament 😲🔥 NXT VS NGBD 😈 #NONSTOP_LIVE \u200b\u200b \u200b#FreeFireLive #ClassyLive [kOGo0L1kwdw].webm'

**Comment by JunkFood02** [comment]
Try rename the file in the format selection page(click on the file name)

**Comment by fillwithjoy1** [comment]
Is this issue resolved?
