### ISSUE TITLE
AutoSkip youtube chapters labelled Intro and Introduction

### ISSUE THREAD

**Issue by MTwem** [JunkFood02/Seal#1028]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Intros rarely have interesting content. e.g. when I've clicked on a 45 mins video about zelda, I don't need _what the triforce is_ explained to me

### Describe the solution you'd like

Auto skip when the chapter label is Intro or Introduction

### Video link

https://www.youtube.com/watch?v=0n809nd4Zu4

**Comment by Marco-9456** [comment]
Seal users are not only using the app to download from Youtube, they use it for other supported websites, You can go to `Settings` --> `General` --> `SponsorBlock` --> and type the `segments names` you don't want to be included in the downloaded video and `toggle the option on`.
