### ISSUE TITLE
HUGE size on F-droid

### ISSUE THREAD

**Issue by Skaldebane** [JunkFood02/Seal#103]
For some reason, Seal's download size on F-droid seems to be around 120 MB, when the actual APK size on GitHub is no more than 30 MB.

This makes it a little too expensive to download/update it from F-droid.

**Comment by Marco-9456** [comment]
> For some reason, Seal's download size on F-droid seems to be around 120 MB, when the actual APK size on GitHub is no more than 30 MB.
> 
> This makes it a little too expensive to download/update it from F-droid.

From my understanding **F-Droid** makes its own Build from the source code, and the builds are mostly Universal so that almost everyone can use the same apk file without worrying about Architecture differences between phones.

**Comment by JunkFood02** [comment]
Check #41 for the whole discussion.
And the size of v1.0.1 on F-Droid should be around 60M I think. 🤔

**Comment by Marco-9456** [comment]
> Check #41 for the whole discussion. And the size of v1.0.1 on F-Droid should be around 60M I think. thinking

nah it's actully big 
![Screenshot_20220806-035241_Samsung Internet](https://user-images.githubusercontent.com/41828058/183229035-e613e07d-470b-48ab-be0e-40119c665d03.jpg)

**Comment by JunkFood02** [comment]
- This comment https://github.com/JunkFood02/Seal/issues/41#issuecomment-1200381037,  and a new version will appear on F-Droid in a 2-4 days delay after I release it here

**Comment by JunkFood02** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/69683722/183244601-9baf7ecc-6e20-4ee9-987c-3ce48b822299.png">

> And the size of v1.0.1 on F-Droid should be around 60M I think. 🤔

**Comment by Skaldebane** [comment]
Ah alright, so it's an issue from F-droid's side. It would've been better if it supported App Bundles, but that's irrelevant to this discussion.
Thanks!
