### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [JunkFood02/Seal#1037]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4988182775#L408

Based on https://github.com/deckerst/aves/issues/725 I guess the same fix is needed? eg. https://github.com/deckerst/aves/commit/8ad540d605d0879c246e5cd5c152dad10832ba17#diff-b846529d3b9af5e34dfb0174742f9dc3d52bcd97761555bc61271a7a868870b9R9 

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/52976b94e4e7dcb229198832a8e628e5dbf25476

**Comment by JunkFood02** [comment]
https://github.com/JunkFood02/Seal/commits/v1.10.0-fdroid_fix

**Comment by licaon-kter** [comment]
Thanks https://gitlab.com/fdroid/fdroiddata/-/commit/5f48426b8a5e68daabefa69fddc5883c7d77cf7c
