### ISSUE TITLE
Error: Couldn't fetch video info

### ISSUE THREAD

**Issue by zacharyanaji** [JunkFood02/Seal#1039]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hello Team, I'm using the preview version android app. It is the latest version when I checked for the updates.

The issue is that, one instagram video couldn't be downloaded and below is the error message.

This is the link I'm trying to download https://www.instagram.com/reel/Cv0DVEvA9U_/?igshid=MzRlODBiNWFlZA==

All the reels are getting downloaded nicely, except this one. I kept all the settings as automatic, and I didn't select anything. Everything is on default.

App version: 1.10.0 (11000)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

### Error reports

App version: 1.10.0 (11000)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: 
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cv0DVEvA9U_: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230901-022104_Seal](https://github.com/JunkFood02/Seal/assets/90532385/ee8c5df4-3390-4576-9edc-77b71536305a)

### Additional context

I believe it has to do something with the video format.

**Comment by Marco-9456** [comment]
The reel is from a private and Seal can't Download this type of Videos by default, you have to go to the `Settings-->` `Network-->` `Cookies-->` and generate cookies by logging in Instagram and enabling the cookies option at the end.

**Comment by zacharyanaji** [comment]
Thanks brother.

Keep up the good work 🙏🏻
