### ISSUE TITLE
App cant get updated 

### ISSUE THREAD

**Issue by TogeTumis** [JunkFood02/Seal#1043]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

So i cant get my app update, if i uninstall my app and installed again, all file of my song i downloaded will be gone or no?

### Error reports

So i cant get my app update, if i uninstall my app and installed again, all file of my song i downloaded will be gone or no?

### Screenshots & Screen Records

![Screenshot_2023-09-03-10-08-03-19_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/JunkFood02/Seal/assets/143918273/ab4556cd-6fdf-4fa1-96ab-0ef8cfda5ae1)

**Comment by JunkFood02** [comment]
You can manually download the apk [here](https://github.com/JunkFood02/Seal/releases/tag/v1.10.0).

> if i uninstall my app and installed again, all file of my song i downloaded will be gone or no?

The downloaded files won't get affected. Uninstalling will only remove the configuration & data of the app
