### ISSUE TITLE
Android 12 incompatibility 

### ISSUE THREAD

**Issue by OluDanielAY** [JunkFood02/Seal#1048]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I tried installing seal on different android 12.0 and it has been incompatible

**Comment by JunkFood02** [comment]
Follow the bug report issue template
