### ISSUE TITLE
[Descargar videos a la vez o en fila]

### ISSUE THREAD

**Issue by JhonLA5280** [JunkFood02/Seal#1063]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Me gustaría que añadieron una función para descargar varios videos para que sea más rápido descargarlo

### Describe the solution you'd like

Me gustaría añadan la función de descargar varios videos al mismo tiempo o tenerlos en fila para así poner varios videos al mismo tiempo y no esperar a que uno se descargue y poner otro

### Additional context

Por favor si no es mucha molestia solo es una pequeña recomendación de mi parte y si pueden hacer posible eso y si no pueden o no quieren lo entenderé ya que de todas manera la aplicación sigue siendo muy buena, gracias por su atención.

**Comment by Marco-9456** [comment]
Duplicated of:

https://github.com/JunkFood02/Seal/issues/323

https://github.com/JunkFood02/Seal/issues/324

https://github.com/JunkFood02/Seal/issues/957

https://github.com/JunkFood02/Seal/issues/995
