### ISSUE TITLE
[YouTube] Clip Video always adds 10 seconds at the beginning

### ISSUE THREAD

**Issue by fillwithjoy1** [JunkFood02/Seal#1067]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The clip video feature always adds 10 seconds at the beginning for no reason (before playing the beginning of the clipped video)

### To Reproduce

1. Download video
2. Get to format selection
3. Specify trim
4. Note the time that you start trimming (e.g. start trim at 00:30, the bug will start trimming at 00:20) for no reason
5. 10 seconds of frozen frames

### Error reports

No error, just a bug

### Screenshots & Screen Records

https://github.com/JunkFood02/Seal/assets/29514446/6dc6e7f3-d349-4909-94e0-775b994b661d

[Linkin Park - Lying From You (Protostar Remix) [Video] [4aVSqeXS6oo][30-60].webm](https://github.com/JunkFood02/Seal/assets/29514446/7632e2fe-2d3f-40cf-bab7-b5b61f41f8ae)

Original Video: https://www.youtube.com/watch?v=4aVSqeXS6oo&pp=ygUecHJvdG9zdGFyIHJlbWl4IGx5aW5nIGZyb20geW91

And no, this is not a isolated case, this occurs for every video I use

**Comment by Marco-9456** [comment]
This is a known issue but we can't do anything about it, yt-dlp Seal's engine uses FFmpeg to download a specific part from a YouTube video and they haven't found a solution for it yet

**Comment by JunkFood02** [comment]
expected behavior, read the pop-up msg when enabling the feature
