### ISSUE TITLE
320k audio

### ISSUE THREAD

**Issue by hmod17** [JunkFood02/Seal#1070]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I want to be a 320k option on the app

**Comment by JunkFood02** [comment]
#228
