### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by SamWeichman** [JunkFood02/Seal#1075]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Download start button is inaccessible on devices with low resolution screens.

### To Reproduce

Try to star download in a lower resolution device.

### Error reports

Not have error screen

### Screenshots & Screen Records

![Screenshot_2023-09-15-00-10-09](https://github.com/JunkFood02/Seal/assets/145093009/bc3ccf20-0412-43b1-9606-4a294da3fff0)

### Additional context

Device: Samsung J1 2016
Android Version: 5.1

**Comment by JunkFood02** [comment]
should be fixed in v1.11.0-beta.1
