### ISSUE TITLE
Downloading slides/images

### ISSUE THREAD

**Issue by robertsspaceindustries** [JunkFood02/Seal#1083]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

The ability to download the images from a 'slides video'.
A new section for options when downloading? When selecting the video output, "Images"?
![Downloading 'slides videos' right now](https://github.com/JunkFood02/Seal/assets/49074962/0eee75c4-29bf-4093-a90d-c2251c870ccd)
[[neurips] Media Support (Videos + Slides) · Issue #5818 · yt-dlp/yt-dlp - GitHub](https://github.com/yt-dlp/yt-dlp/issues/5818)

### Video link

[https://vm.tiktok.com/ZGJWGrGNf/](https://vm.tiktok.com/ZGJWGrGNf/)

**Comment by Marco-9456** [comment]
Seal is not and will never support image downloading.
