### ISSUE TITLE
Downloading youtube playlists

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#1086]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

1. Why 'Download playlist' setting is unable when in custom command mode?

2. No matter if this setting is on or off when in custom command mode, Seal downloads full playlist.

### To Reproduce

this link opens 10th video in the playlist, but Seal will download full playlist starting from the 1st file

https://www.youtube.com/watch?app=desktop&v=3qQe-Qn6vhw&list=PLV01nZO5frDe4fbtbewwN1IOw1noshTq8&index=10

### Additional context

App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by Marco-9456** [comment]
> ### Describe the bug
> 1. Why 'Download playlist' setting is unable when in custom command mode?

Because custom commands interfere with the presets of the app.

> 2. No matter if this setting is on or off when in custom command mode, Seal downloads full playlist.

You have to specify exactly what video you want to download from the playlist.

> ### To Reproduce
> this link opens 10th video in the playlist, but Seal will download full playlist starting from the 1st file

I don't really get what you want to say, please make a short Screenrecord of the process.

**Comment by Botan626** [comment]
this is the link for 15th video from playlist:
https://www.youtube.com/watch?v=SiDwKf9Ed8U&list=PLV01nZO5frDe4fbtbewwN1IOw1noshTq8&index=15
how can I download exactly this video and not full playlist without turning off custom command mode?

**Comment by Marco-9456** [comment]
Like this:


https://github.com/JunkFood02/Seal/assets/41828058/118efce3-c388-4bd4-aed0-34e3c6e09b4a

**Comment by Botan626** [comment]
no other way without opening browser/copying link?

**Comment by Marco-9456** [comment]
Go ask yt-dlp to support that kind of link.

**Comment by Botan626** [comment]
> You're asking in the wrong place, go ask yt-dlp to support that kind of link.

already is supported, here I downloaded 3d video from [this playlist](https://www.youtube.com/playlist?list=PLV01nZO5frDe4fbtbewwN1IOw1noshTq8), no problems
https://www.youtube.com/watch?v=Zd4RjYUFnfE&list=PLV01nZO5frDe4fbtbewwN1IOw1noshTq8&index=3&pp=iAQB

![image](https://github.com/JunkFood02/Seal/assets/28785698/4276c275-5e94-4355-82a4-fb7023486bb4)
