### ISSUE TITLE
Cancel button

### ISSUE THREAD

**Issue by nawazish095** [JunkFood02/Seal#1087]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There is no cancel button. Please add it

**Comment by Marco-9456** [comment]
You can cancel a download by clicking on the text beneath the app name.
