### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#110]
So I'm getting the following error message:

```
Usage: __main__.py [OPTIONS] URL [URL...]

__main__.py: error: --parse-metadata '%(album|Album - Operation: Doomsday (Complete))s:%(meta_album)s' is invalid; incomplete format key
```
I wanted to download this [Album](https://music.youtube.com/playlist?list=OLAK5uy_na0dlncxHSnuztIBWl5t4Ntn5670vO244&feature=share) 

I tried downloading some other albums and it worked but this one didn't 
![Screenshot_20220811-054047_Seal](https://user-images.githubusercontent.com/41828058/184061334-8a360923-74e0-4776-98c3-b47a20b40871.jpg)

**Comment by JunkFood02** [comment]
😌 v1.0.3 is coming

**Comment by Marco-9456** [comment]
> 😌 v1.0.3 is coming

🔥🔥
