### ISSUE TITLE
Custom command is broken using 1.0.3

### ISSUE THREAD

**Issue by KazKaz90** [JunkFood02/Seal#111]
I am using the same custom commands from previous versions but now they are broken, showing error `ERROR: Fixed output name but more than one file to download: -o` but fixed it by removing `-` from `o` option and it didn't show any error also removed `"` at the start and end of field `o %(extractor)s/%(uploader)s/%(title)s(%(id)s).%(ext)s` also didn't give error. Even when removing the `o` but they are not working it instead using the default template not my template even though my template is clearly selected.

Every download goes to the Seal folder, not the one specified by the commands.

RedGIFs User

**Comment by JunkFood02** [comment]
Fixed(again...)🤦
