### ISSUE TITLE
Add the cancel option separately 

### ISSUE THREAD

**Issue by EMTIAZ2003** [JunkFood02/Seal#1111]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Some times I accidentally touch the seal logo and the download get cancelled.

### Describe the solution you'd like

Adding the cancel option separately will be very helpful and easy.

**Comment by JunkFood02** [comment]
Added in v1.11.0-beta.2
