### ISSUE TITLE
Can't download to sd card

### ISSUE THREAD

**Issue by Fireball026** [JunkFood02/Seal#1113]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The option to download to sd card is unavailable. Just wondering if there anything to do about it.

### Error reports

.

### Screenshots & Screen Records

![Screenshot_20230927-025628](https://github.com/JunkFood02/Seal/assets/145714000/b94ba0dd-685e-4741-9d87-229edca9a417)

### Additional context

I have version 1.9.2

**Comment by Marco-9456** [comment]
Click on `SD card folder` text, not on the grayed out on and off button.

**Comment by JunkFood02** [comment]
Update to v1.10.0

**Comment by Fireball026** [comment]
Thank you. (I feel kinda dumb now)
