### ISSUE TITLE
Redesign the Seal app icon

### ISSUE THREAD

**Issue by Ehab-d** [JunkFood02/Seal#1116]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The current app icon is ugly and outdated, and it doesn't represent the app as well. 

### Describe the solution you'd like

Redesign app icon with a new modern, fresh, clean and beautiful design.

### Additional context

The Seal app icon among a rest of the apps in the app launcher looks awful.

**Comment by Marco-9456** [comment]
Lol

**Comment by JunkFood02** [comment]
lmao
