### ISSUE TITLE
Cannot download a playlist of videos from Youtube.  "ERROR: Incomplete data received"

### ISSUE THREAD

**Issue by twizzlebizzle** [JunkFood02/Seal#1119]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I input a link into Seal.  Then click the "download playlist" icon and press download.  I receive the error.
Video "auto" format selection are enabled.  
  

### To Reproduce

1. Share link from firefox
2. Select Seal in the share sheet
3. Tick Video  
4. Click "download Playlist"  
5. Click Download button
6. Error is shown

### Error reports

App version: 1.10.0-(F-Droid) (11004)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2023.09.24

URL: https://youtube.com/playlist?list=PLaLvSxPpI1c0z5V_T28u3fUrRtiyhwEmQ&si=qyhyYW0qPdHg-94l
WARNING: [youtube:tab] Incomplete data received. Retrying (1/3)...
WARNING: [youtube:tab] Incomplete data received. Retrying (2/3)...
WARNING: [youtube:tab] Incomplete data received. Retrying (3/3)...
ERROR: Incomplete data received

### Screenshots & Screen Records

![Screenshot_20230928-205730](https://github.com/JunkFood02/Seal/assets/11423542/9ec048d2-171e-4642-9243-f85277e1e256)

### Additional context

If I disable "Download Playlist", it will let me download the first video in the playlist.  
I have sponsorblock enabled.  
No custom commands.

**Comment by imshantanu** [comment]
![Screenshot_20230930-182006_Seal](https://github.com/JunkFood02/Seal/assets/20909543/11121e6c-1158-41c6-96ae-78f9f56a2635)
Facing the same issue while downloading any playlist.

**Comment by JunkFood02** [comment]
https://github.com/yt-dlp/yt-dlp/issues/8206

**Comment by JunkFood02** [comment]
Update your yt-dlp to the latest nightly builds 2023.10.03
