### ISSUE TITLE
Album art cover isn’t cropped right when downloading YouTube audio

### ISSUE THREAD

**Issue by cyxae** [JunkFood02/Seal#112]
Hello,

I discovered Seal and I would like to use it to download audio from YouTube. The auto tagging feature is really fantastic, however album art cover are not cropped right and have large stripes on the right and left, such as :

![signal-2022-08-12-202042_002](https://user-images.githubusercontent.com/22409918/184421896-efb35a0d-c196-4342-b902-5cff919a8a98.jpeg)

(which was downloaded from [https://www.youtube.com/watch?v=ddYW119vHP4](https://www.youtube.com/watch?v=ddYW119vHP4))

I don’t know if yt-dlp is providing the right album cover, or if it should be cropped manually by Seal, but that feature would be really appreciated to have a squared album cover !

Thank you very much for the app,

cyxae

**Comment by Marco-9456** [comment]
@cyxae `Seal/Yt-dlp` isn't cropping the cover this is just how the covers look 
like from the source 
![Screenshot_20220812-205950_Samsung Internet](https://user-images.githubusercontent.com/41828058/184425983-0a0eba70-1707-428d-806d-8415a55cf7b5.jpg)
Also Seal doesn't implement features that yt-dlp doesn't support such as changing the aspect ratio of a thumbnail, but maybe @JunkFood02 have something else to say.
Anyway I hate this too but to fix it i use an auto tagger like [AutomaTag](https://play.google.com/store/apps/details?id=com.fillobotto.mp3tagger)  which tags every album and track i have if it finds metadata for it
Ps. use [Youtube Music](https://music.youtube.com/watch?v=ddYW119vHP4&feature=share)  links to download Music with better quality

**Comment by Marco-9456** [comment]
> Hello,
> 
> I discovered Seal and I would like to use it to download audio from YouTube. The auto tagging feature is really fantastic, however album art cover are not cropped right and have large stripes on the right and left, such as :
> 
> ![signal-2022-08-12-202042_002](https://user-images.githubusercontent.com/22409918/184421896-efb35a0d-c196-4342-b902-5cff919a8a98.jpeg)
> 
> (which was downloaded from https://www.youtube.com/watch?v=ddYW119vHP4)
> 
> I don’t know if yt-dlp is providing the right album cover, or if it should be cropped manually by Seal, but that feature would be really appreciated to have a squared album cover !
> 
> Thank you very much for the app,
> 
> cyxae
![Screenshot_20220812-211335_AutomaTag](https://user-images.githubusercontent.com/41828058/184428135-30bbad43-c460-47c9-8380-fb96949e6e79.jpg)

**Comment by JunkFood02** [comment]
That's also a problem for me too 😂
Reference:
- https://github.com/yt-dlp/yt-dlp/issues/980
- https://github.com/yausername/youtubedl-android/issues/168

**Comment by JunkFood02** [comment]
- https://github.com/JunkFood02/Seal/issues/182#issuecomment-1236089616

**Comment by JunkFood02** [comment]
Add in v1.3.0-beta.1

**Comment by udaign** [comment]
> Add in v1.3.0-beta.1

Hey man, not sure if this was indeed implemented 3y ago, I only started using it like half a year ago, and all my music files that I downloaded from yt music links appear like this in the 16:9 ratio and this causes so many issues with widgets and previews inside some apps:

Nothing music player widget:
![Screenshot_20260128-094359.png](https://github.com/user-attachments/assets/74fabb59-920d-4143-87f1-bc4ea78be0c5)

Pixel Player album cards:
![Screenshot_20260128-094304.png](https://github.com/user-attachments/assets/49d8e239-8ee3-4e39-8e66-a11405e862ce)

Can you please add a toggle to choose to crop to the center 1:1 of the image and embed into the audio file or something like that.

Or am I missing something that is already implemented?
