### ISSUE TITLE
[Feature Request] Add a built-in web browser

### ISSUE THREAD

**Issue by Tarek-Hasan** [JunkFood02/Seal#1123]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Currently, if anyone wants to download video from a website, they have to go back and forth between Seal and web browser or YouTube or other apps. It's very annoying. If anyone wants to download multiple video, that quickly becomes a nightmare. 

### Describe the solution you'd like

Add a built-in web browser, like Snaptube and Vidmate have done. This will make downloading video very easy compared to current method. A simple Android webview based browser would do the trick. 
Only few basic features would be enough:
- Search
- Bookmarks
- Video playback
- AdBlocker

There are few good webview based browser out there, you can use any of those as codebase if you want.
- [FOSS Browser](https://codeberg.org/Gaukler_Faun/FOSS_Browser)
- [Fulguris](https://github.com/Slion/Fulguris)
- [Lightning Browser](https://github.com/anthonycr/Lightning-Browser)

**Comment by Marco-9456** [comment]
This is out of scope.
