### ISSUE TITLE
Can't download video

### ISSUE THREAD

**Issue by Jimmychoo011** [JunkFood02/Seal#1127]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Can't download any Instagram reel video its always showing Can't fetch video before it was working smoothly but now no use what should i do i try to download new versions of the seal app but no luck still same issue 
Please fix it as soon as possible 
Thank you 

### Error reports

WARNING: [Instagram] Cx2NNuSL1HQ: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] Cx2NNuSL1HQ: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

### Screenshots & Screen Records

![Screenshot_20231002_011318_Seal](https://github.com/JunkFood02/Seal/assets/146676182/89116638-9ca7-4b2b-a386-303baa85d532)

**Comment by Marco-9456** [comment]
@Jimmychoo011 Read the bot comment instead of spamming

**Comment by Jimmychoo011** [comment]
Just read the comments,  and for 2 times its not spamming i didn't saw it was closed *peace *
