### ISSUE TITLE
Gallery video bug

### ISSUE THREAD

**Issue by Impulse20006** [JunkFood02/Seal#1130]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The downloaded video (from twitter at least) shows up in my gallery and it cannot play, it only worked on video player but on video player, it has no length, i cannot go forward or rewind(it restarts the vid) and the end time is just a symbol (-:--)

### To Reproduce

Go on Twitter
Download a video
Go to gallery- it just shows 0:00 and doesn't play 
Go on video player - it plays but it cannot be altered (skip, fast forward, rewind etc)

### Error reports

There is none, it just wont work

**Comment by JunkFood02** [comment]
Use another video player like VLC player
