### ISSUE TITLE
Twitter downloaded videos file format is not supported

### ISSUE THREAD

**Issue by Birraque** [JunkFood02/Seal#1133]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Even after latest Seal-1.11.0-beta.1-arm64-v8a-release update all videos downloaded from Twitter (X) can't be send through WhatsApp. Error message "The file format is not supported" is always received.
How can we handle it?

![IMG_20231006_011203](https://github.com/JunkFood02/Seal/assets/44372413/186eeea9-5792-4564-a2ad-7817bc2ca92a)

### To Reproduce

1. Open Twitter (X) app and download any video using Seal
2. Send the downloaded video file through WhatsApp
3. Error message received

### Error reports

The file format is not supported

### Screenshots & Screen Records

Already annex above

### Additional context

Device: Xiaomi Poço F3 (alioth), MIUI 14, Android 13
The error message can be reproduced with all recent WhatsApp versions even Business.

**Comment by Birraque** [comment]
The downloaded from Twitter with Seal works smoothly.
The issue is related with file format.
How can we handle it?

**Comment by Marco-9456** [comment]
> The downloaded from Twitter with Seal works smoothly. The issue is related with file format. How can we handle it?


https://github.com/JunkFood02/Seal/assets/41828058/503415b8-0735-41ba-9c04-c1c8f2696f38

**Comment by Birraque** [comment]
> > The downloaded from Twitter with Seal works smoothly. The issue is related with file format. How can we handle it?
> 
>  Screen_Recording_20231006_073131_Seal.mp4

Thanks for your input but even when Legacy mode is selected sharing through WhatsApp still doesn't works.

**Comment by Marco-9456** [comment]
> > > The downloaded from Twitter with Seal works smoothly. The issue is related to the file format. How can we handle it?
> > 
> > 
> > Screen_Recording_20231006_073131_Seal.mp4
> 
> Thanks for your input but even when Legacy mode is selected sharing through WhatsApp still doesn't work.

I see,
then go back to quality and select a format that WhatsApp supports, this is an external issue on WhatsApp's side and we can't do anything about it.

**Comment by Birraque** [comment]
> > > > The downloaded from Twitter with Seal works smoothly. The issue is related to the file format. How can we handle it?
> > > 
> > > 
> > > Screen_Recording_20231006_073131_Seal.mp4
> > 
> > 
> > Thanks for your input but even when Legacy mode is selected sharing through WhatsApp still doesn't work.
> 
> I see, then go back to quality and select a format that WhatsApp supports, this is an external issue on WhatsApp's side and we can't do anything about it.

Thanks again for your input.
Unfortunate didn't works either.
Videos from Twitter can't be send through WhatsApp anymore. Regards,

**Comment by ignaciocastro** [comment]
Issue is seen on Facebook, Instagram and Whatsapp. This happens when the "hls" format is selected instead of "http". Even when the "Legacy" option is selected, the app still prefers hls over http.
Would it be possible to create a command template that only selects the http format on Twitter / X links?

![mediainfo](https://github.com/JunkFood02/Seal/assets/7141944/ad165d7a-3ea9-4a9a-92c9-5621d604e926)

**Comment by JunkFood02** [comment]
@ignaciocastro Go to Settings - Format - Format sorting, tap `import` and add `proto:https` prefix to it, this will make the app prefer formats with https proto.

But I literally don't know why and how the format is not supported

**Comment by ignaciocastro** [comment]
> @ignaciocastro Go to Settings - Format - Format sorting, tap `import` and add `proto:https` prefix to it, this will make the app prefer formats with https proto.

Can confirm using `proto:https` after -S fixes the issue, picking HTTP instead of HLS

> But I literally don't know why and how the format is not supported

No clue, but I'd say the apps don't like the idea of accepting a video with a maximum frame rate of 900 million.

**Comment by Birraque** [comment]
> > @ignaciocastro Go to Settings - Format - Format sorting, tap `import` and add `proto:https` prefix to it, this will make the app prefer formats with https proto.
> 
> Can confirm using `proto:https` after -S fixes the issue, picking HTTP instead of HLS
> 
> > But I literally don't know why and how the format is not supported
> 
> No clue, but I'd say the apps don't like the idea of accepting a video with a maximum frame rate of 900 million.

Thanks for both.
I confirm that workaround fix my reported issue too.

![IMG_20231024_183601](https://github.com/JunkFood02/Seal/assets/44372413/75a88fc7-c3cd-4c56-9db0-cd20803e04d4)
![IMG_20231024_183702](https://github.com/JunkFood02/Seal/assets/44372413/4e7c3663-df0b-4f6f-a61c-715713eb96ef)

**Comment by JunkFood02** [comment]
prefer http proto is default behavior for legacy formats in v1.11.0-rc.1

**Comment by Birraque** [comment]
> prefer http proto becomes default behavior for legacy formats in v1.11.0-rc.1

The same error message "File format is not supported" is back after latest Twitter (X) app updated to v10.16.0-release.0
I'm currently using Seal 1.11.0 with custom Format Sorting above.
Do you know what's happening again? Do you have any imports?
Thanks in advance,

**Comment by Marco-9456** [comment]
> The same error message "File format is not supported" is back after the latest Twitter (X) app is updated to v10.16.0-release.0 I'm currently using Seal 1.11.0 with custom Format Sorting above. Do you know what's happening again? Do you have any imports? Thanks in advance,

Just reencode the video after downloading it, WhatsApp doesn't make it clear what video and audio codecs are supported.

**Comment by ignaciocastro** [comment]
> > > The same error message "File format is not supported" is back after the latest Twitter (X) app is updated to v10.16.0-release.0 I'm currently using Seal 1.11.0 with custom Format Sorting above. Do you know what's happening again? Do you have any imports? Thanks in advance,
> > 
> > 
> > Just reencode the video after downloading it, WhatsApp doesn't make it clear what video and audio codecs are supported.
> 
> Seems to be the same king of issue already reported [above](https://github.com/JunkFood02/Seal/issues/1133#issuecomment-1776403015)

Actually, it probably stems from this recent issue with Twitter and their muxer. wukko/cobalt#172
