### ISSUE TITLE
Video Not Download 

### ISSUE THREAD

**Issue by Priyanshu84iya** [JunkFood02/Seal#1134]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.09.24

URL: https://youtu.be/7xSHEwXyNMY?si=Dghov4HvLbn9QAYy
[debug] Command-line config: ['--no-mtime', '-v', '-r', '1000K', '--no-playlist', '--concurrent-fragments', '8', '-S', 'vcodec:h264,ext,res:1080', '-P', '/storage/emulated/0/Download/Seal', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '--download-sections', '*15-44', '-o', '%(title).200B [%(id)s][%(section_start)d-%(section_end)d].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~VE1Z-Bo5fbQlk8zSDiLV3g==/com.junkfood.seal-1v2SieIW7dJfGPnfeRzrdA==/lib/arm64/libffmpeg.so', 'https://youtu.be/7xSHEwXyNMY?si=Dghov4HvLbn9QAYy']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.09.24 [088add956] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.4.210-qgki-gf52f2b2c1713-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Loaded 1886 extractors
[debug] Sort order given by user: vcodec:h264, ext, res:1080
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:h264(7), vext, aext, res:1080(1080.0), quality, fps, hdr:12(7), source, channels, acodec, lang, proto, size, br, asr, hasaud, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking ffmpeg downloader on "https://rr4---sn-gwpa-qxaez.googlevideo.com/videoplayback?expire=1696603418&ei=usgfZfnXNqjJjuMPrrSskAc&ip=2409%3A40d0%3A9%3A3cd7%3A4c8%3Ab9ff%3Afe71%3A5cac&id=o-ABaFJG0qnH7pNXDl_uARgyPed2vv3kAm7oCK5rH6iPRA&itag=137&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-gwpa-qxaez%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=4&pl=36&initcwndbps=512500&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=21797402&dur=43.499&lmt=1630653088830047&mt=1696581441&fvip=6&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAIxlweCs1oUw2A97BUFA8eTe1VcfBiMCRMPEbhjL8V_KAiBK-CLThhmARh5GcwzAFfr_2ohNpiM1lWrJiIzJ4kDYLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAPF9RXvM61JF8aee00TYLO4ouR-DrgT4afYENfajAQb4AiEA5tRiAFng_Y4x5LmtokiggvXjZPPPifaumZYLMerG-Rs%3D", "https://rr4---sn-gwpa-qxaez.googlevideo.com/videoplayback?expire=1696603418&ei=usgfZfnXNqjJjuMPrrSskAc&ip=2409%3A40d0%3A9%3A3cd7%3A4c8%3Ab9ff%3Afe71%3A5cac&id=o-ABaFJG0qnH7pNXDl_uARgyPed2vv3kAm7oCK5rH6iPRA&itag=140&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-gwpa-qxaez%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=4&pl=36&initcwndbps=512500&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=705758&dur=43.560&lmt=1630652993087577&mt=1696581441&fvip=6&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIgYY9Xij5wngN5aXcnuvRyBIrzPzsKMQOagrk-BIAHDBACIQCfFcHBCZeBFvItXCDcmH2EmrU7VI7q13ApQaTO-yyA_A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAPF9RXvM61JF8aee00TYLO4ouR-DrgT4afYENfajAQb4AiEA5tRiAFng_Y4x5LmtokiggvXjZPPPifaumZYLMerG-Rs%3D"
[debug] libffmpeg.so command line: '/data/app/~~VE1Z-Bo5fbQlk8zSDiLV3g==/com.junkfood.seal-1v2SieIW7dJfGPnfeRzrdA==/lib/arm64/libffmpeg.so' -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 15.0 -t 29.0 -i 'https://rr4---sn-gwpa-qxaez.googlevideo.com/videoplayback?expire=1696603418&ei=usgfZfnXNqjJjuMPrrSskAc&ip=2409%3A40d0%3A9%3A3cd7%3A4c8%3Ab9ff%3Afe71%3A5cac&id=o-ABaFJG0qnH7pNXDl_uARgyPed2vv3kAm7oCK5rH6iPRA&itag=137&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-gwpa-qxaez%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=4&pl=36&initcwndbps=512500&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=21797402&dur=43.499&lmt=1630653088830047&mt=1696581441&fvip=6&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAIxlweCs1oUw2A97BUFA8eTe1VcfBiMCRMPEbhjL8V_KAiBK-CLThhmARh5GcwzAFfr_2ohNpiM1lWrJiIzJ4kDYLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAPF9RXvM61JF8aee00TYLO4ouR-DrgT4afYENfajAQb4AiEA5tRiAFng_Y4x5LmtokiggvXjZPPPifaumZYLMerG-Rs%3D' -headers 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 15.0 -t 29.0 -i 'https://rr4---sn-gwpa-qxaez.googlevideo.com/videoplayback?expire=1696603418&ei=usgfZfnXNqjJjuMPrrSskAc&ip=2409%3A40d0%3A9%3A3cd7%3A4c8%3Ab9ff%3Afe71%3A5cac&id=o-ABaFJG0qnH7pNXDl_uARgyPed2vv3kAm7oCK5rH6iPRA&itag=140&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-gwpa-qxaez%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=4&pl=36&initcwndbps=512500&vprv=1&svpuc=1&mime=audio%2Fmp4&gir=yes&clen=705758&dur=43.560&lmt=1630652993087577&mt=1696581441&fvip=6&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIgYY9Xij5wngN5aXcnuvRyBIrzPzsKMQOagrk-BIAHDBACIQCfFcHBCZeBFvItXCDcmH2EmrU7VI7q13ApQaTO-yyA_A%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAPF9RXvM61JF8aee00TYLO4ouR-DrgT4afYENfajAQb4AiEA5tRiAFng_Y4x5LmtokiggvXjZPPPifaumZYLMerG-Rs%3D' -c copy -map 0:0 -map 1:0 -f mp4 'file:/data/user/0/com.junkfood.seal/cache/tmp/romance anime twix edit ⧸⧸ die for you [7xSHEwXyNMY][15-44].mp4.part'
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
  configuration: --prefix=/home/runner/work/build-ffmpeg/build-ffmpeg/build/ffmpeg/arm64-v8a --enable-cross-compile --target-os=android --arch=aarch64 --sysroot=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot --cc=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --cxx=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ --ld=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --ar=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar --as=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --nm=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm --ranlib=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib --strip=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --extra-cflags='-O3 -fPIC -I/home/runner/work/build-ffmpeg/build-ffmpeg/build/external/arm64-v8a/include' --extra-ldflags='-L/home/runner/work/build-ffmpeg/build-ffmpeg/build/external/arm64-v8a/lib -lm -lm -lm -lm -lz' --enable-shared --disable-static --disable-vulkan --pkg-config=/usr/bin/pkg-config --enable-protocol=https --enable-version3 --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libtwolame --enable-libspeex --enable-libvpx --enable-libwebp --enable-libfreetype --enable-libfribidi --enable-mbedtls --enable-libbluray --enable-libx264
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tcp @ 0xb40000711d2730a0] Starting connection attempt to 2405:200:1630:b27::f port 443
[tcp @ 0xb40000711d2730a0] Connection attempt to 2405:200:1630:b27::f port 443 failed: Connection timed out
[tcp @ 0xb40000711d2730a0] Connection to tcp://rr4---sn-gwpa-qxaez.googlevideo.com:443 failed: Connection timed out
https://rr4---sn-gwpa-qxaez.googlevideo.com/videoplayback?expire=1696603418&ei=usgfZfnXNqjJjuMPrrSskAc&ip=2409%3A40d0%3A9%3A3cd7%3A4c8%3Ab9ff%3Afe71%3A5cac&id=o-ABaFJG0qnH7pNXDl_uARgyPed2vv3kAm7oCK5rH6iPRA&itag=137&source=youtube&requiressl=yes&mh=tP&mm=31%2C29&mn=sn-gwpa-qxaez%2Csn-gwpa-qxae7&ms=au%2Crdu&mv=m&mvi=4&pl=36&initcwndbps=512500&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=21797402&dur=43.499&lmt=1630653088830047&mt=1696581441&fvip=6&keepalive=yes&fexp=24007246&beids=24350018&c=IOS&txp=5311224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRQIhAIxlweCs1oUw2A97BUFA8eTe1VcfBiMCRMPEbhjL8V_KAiBK-CLThhmARh5GcwzAFfr_2ohNpiM1lWrJiIzJ4kDYLg%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAPF9RXvM61JF8aee00TYLO4ouR-DrgT4afYENfajAQb4AiEA5tRiAFng_Y4x5LmtokiggvXjZPPPifaumZYLMerG-Rs%3D: I/O error

ERROR: ffmpeg exited with code 1
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1008, in main
    _exit(*variadic(_real_main(argv)))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 998, in _real_main
    return ydl.download(all_urls)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3510, in download
    self.__download_wrapper(self.extract_info)(
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3485, in wrapper
    res = func(*args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3334, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 80, in real_download
    self.report_error('%s exited with code %d' % (
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1045, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 973, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

**Comment by JunkFood02** [comment]
Network connection issue, cannot reproduce
