### ISSUE TITLE
Error downloading from tiktok

### ISSUE THREAD

**Issue by XtramCZ** [JunkFood02/Seal#1135]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hello, I am getting an error when downloading from tiktok, instagram works fine.

### To Reproduce

1. Find a video
2. Click Share -> More -> Seal
3. _Quick download_
4. wait
5. see error

### Error reports

App version: 1.10.0 (11000)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.09.24

URL: 
ERROR: [vm.tiktok] ZGJcnobAV: Unable to download webpage: <urlopen error [Errno 7] No address associated with hostname> (caused by URLError(gaierror(7, 'No address associated with hostname')))

**Comment by Marco-9456** [comment]
> But it's TikTok, not "Instagram, Facebook, and Twitter"

`Switch to yt-dlp nightly by going to Settings-> General-> click on the ⚙️ icon and select nightly-> Confirm-> click on Update yt-dlp`.

>[!IMPORTANT]
If this doesn't work the only thing you can do is wait for a fix.

**Comment by XtramCZ** [comment]
Nope that didn't work, I'll wait then
