### ISSUE TITLE
Download image using Seal. 

### ISSUE THREAD

**Issue by Xylimate** [JunkFood02/Seal#1138]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I would like to be able to download images from IG for example using Seal.

**Comment by Th3-A6add0n** [comment]
Apparently
https://github.com/JunkFood02/Seal/issues/1083#issuecomment-1725012016
