### ISSUE TITLE
UI bug ?

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#114]
This bug appears first in release 1.0.4 It's also happening sometimes in the command template menu.

<details markdown='1'><summary> Screenshot & Screen record </summary>

![Screenshot_20220813-192414_Seal](https://user-images.githubusercontent.com/41828058/184504419-55cb5a7f-1263-4936-9937-11b10d67c215.jpg)

https://user-images.githubusercontent.com/41828058/210759859-448287ab-53f8-4158-9db2-3a04ac7b0bd1.mp4

</details>

**Comment by JunkFood02** [comment]
This doesn't seem like a new bug, as I've encountered it (and other scrolling-related issues) many times. It's not really clear how to deal with this, but it's obvious that the main cause of these problems is the `nestedScroll` of the top bar and content and needs to be fixed on Google's side

**Comment by Marco-9456** [comment]
> This doesn't seem like a new bug, as I've encountered it (and other scrolling-related issues) many times. It's not really clear how to deal with this, but it's obvious that the main cause of these problems is the `nestedScroll` of the top bar and content and needs to be fixed on Google's side

Thanks for the info
