### ISSUE TITLE
Simultaneous-Downloads

### ISSUE THREAD

**Issue by ZeyadElsayed99** [JunkFood02/Seal#1142]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I start many downloads at once like 10 or even more from YouTube mainly and
I keep my phone(Huawei Y7p 2018 LDN-L21)
charging or use it while downloading but the proplem is that downloading many videos at once make the phone unusable and unstable so i prefer limiting the downloads to one video at a time for it to be quicker and more responsive because my internet connection is a bit slow like 30 mpbs download and propably that proplem isnt only occuring with me so i would like that you
add the option to limit simeltaneous downloads to a specific number and i am not sure about how to add different languages to subtitles other than English

### Describe the solution you'd like

Adding the simeltaneous downloads limiting option

**Comment by JunkFood02** [comment]
> the proplem is that downloading many videos at once make the phone unusable and unstable so i prefer limiting the downloads to one video at a time for it

Do NOT use Quick download. Currently, you can use a playlist to store the videos in it and download the whole playlist

>  i am not sure about how to add different languages to subtitles other than English

Do NOT use Quick download. Open the full app, and you will be able to select subtitles with different languages if present.
