### ISSUE TITLE
Download does work with yt-dlp but not seal app

### ISSUE THREAD

**Issue by Esokrates** [JunkFood02/Seal#1146]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I tried downloading

https://noe.orf.at/player/20231015/NN

which works fine in yt-dlp on my Desktop, however in the seal app a spinner notification appears and immediately disappears and nothing further happens.

### To Reproduce

1. Paste https://noe.orf.at/player/20231015/NN
2. Select audio
3. Press download
4. Nothing happens

### Error reports

No displayed error.

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/assets/41828058/4cf65aa2-411f-4c7d-ab96-a5e5696e444d

**Comment by Esokrates** [comment]
@Marco-9456 Thanks very much for the quick response, for whatever reason format was pre-selected as "custom" and then it did not work, when I select automatic it works as well!

**Comment by Marco-9456** [comment]
> @Marco-9456 Thanks very much for the quick response, for whatever reason format was pre-selected as "custom" and then it did not work, when I select automatic it works as well!

You use custom if you want to select a specific video/audio format, but in your case, the video/audio didn't have any formats to select from, anyway if this happens again switch to automatic and it should work.

**Comment by Esokrates** [comment]
Thanks very much again @Marco-9456!
One last question: which version of the app do you use, installed from which source? Mine (sideloaded from Github release) always pre-selects "custom" as default and the German localization is very much incomplete compared to yours (e.g. ist says "custom" instead of "Benutzerdefiniert").

**Comment by Marco-9456** [comment]
> Which version of the app do you use, installed from which source?

The app can be installed from 2 sources:

1. [GitHub releases page](https://github.com/JunkFood02/Seal/releases) 
2. F-Droid (i don't recommend it, the updates are very slow)

- The version i have is built from source, you can download the latest beta release which is almost the same as mine.
