### ISSUE TITLE
Remux not working

### ISSUE THREAD

**Issue by yant0** [JunkFood02/Seal#115]
I tried using `--remux "wav>opus/mp3"` on a soundcloud playlist that contains few .wav files using custom command. It gives me this error
```
ERROR: Postprocessing: Stream #0:0 -> #0:0 
```
Link : https://m.soundcloud.com/anthonyrusso/sets/covers
<details><summary>my command</summary>
-o "Soundcloud/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d - %(title)s.%(ext)s" --remux "wav>opus/mp3" --embed-thumbnail --parse-metadata "playlist_index:%(track_number)s" --add-metadata --embed-metadata
</details>

**Comment by JunkFood02** [comment]
I haven't found `--remux` option in the yt-dlp documents, do you mean `--remux-video` or `--audio-format`?

**Comment by Marco-9456** [comment]
> 

i think this will fix it
`-o "Soundcloud/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d - %(title)s.%(ext)s" -f opus --embed-thumbnail --parse-metadata "playlist_index:%(track_number)s" --add-metadata --embed-metadata`

**Comment by Marco-9456** [comment]
> I tried using `--remux "wav>opus/mp3"` on a soundcloud playlist that contains few .wav files using custom command. It gives me this error
> 
> ```
> ERROR: Postprocessing: Stream #0:0 -> #0:0 
> ```
> 
> Link : https://m.soundcloud.com/anthonyrusso/sets/covers
> 
> my command

i think this will fix it
`-o "Soundcloud/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d - %(title)s.%(ext)s" -f opus --embed-thumbnail --parse-metadata "playlist_index:%(track_number)s" --add-metadata --embed-metadata`

**Comment by yant0** [comment]
> I haven't found `--remux` option in the yt-dlp documents, do you mean `--remux-video` or `--audio-format`?

I triex both. --remux-video still give the same error and `--audio-format` gave this :
```
ERROR: Postprocessing: Supported filetypes for thumbnail embedding are: mp3, mkv/mka, ogg/opus/flac, m4a/mp4/mov

**Comment by yant0** [comment]
> > I tried using `--remux "wav>opus/mp3"` on a soundcloud playlist that contains few .wav files using custom command. It gives me this error
> > ```
> > ERROR: Postprocessing: Stream #0:0 -> #0:0 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Link : https://m.soundcloud.com/anthonyrusso/sets/covers
> > my command
> 
> i think this will fix it `-o "Soundcloud/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d - %(title)s.%(ext)s" -f opus --embed-thumbnail --parse-metadata "playlist_index:%(track_number)s" --add-metadata --embed-metadata`

I guess? I want to convert the downloaded wav file into opus. I dont know what `-f` exactly does. Does `-f` downloads the best format (here is wav) and then converts it, or does it downloads an mp3 then converts it?

I tried `-f ba[ext=opus]` and its size is still the same without `ba`

**Comment by yant0** [comment]
oops my bad, its `--recode` i forgot to change it since i last used dvd. Closing.

You can re-open if its a genuine bug
