### ISSUE TITLE
I can't download through yt revanced 

### ISSUE THREAD

**Issue by AanooBeta** [JunkFood02/Seal#1150]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

### To Reproduce

Just downloading on YouTube revanced 

### Error reports

fragment 1 not found, unable to continue

**Comment by Rajkdea123** [comment]
I'd like to work on it

**Comment by Marco-9456** [comment]
Looks like a network issue, if you use a VPN/DNS turn it off and try again.

**Comment by AanooBeta** [comment]
The issue was actually sponsor block there though

**Comment by Marco-9456** [comment]
> The issue was actually sponsor block there though


1. Paste the complete error code next time so that we don't have to make assumptions
2. If it's resolved, close the issue as completed.

**Comment by AanooBeta** [comment]
It's resolved after disabling sponsor block .
