### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by ankitgarg43** [JunkFood02/Seal#1158]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.10.0 (11000)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2023.10.13

URL: https://youtu.be/RC9UDlfVyLI?feature=shared
[debug] Command-line config: ['--no-mtime', '-v', '--no-playlist', '--concurrent-fragments', '8', '-x', '--audio-format', 'mp3', '--embed-metadata', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--convert-thumbnails', 'png', '--config', '/data/user/0/com.junkfood.seal/cache/configRC9UDlfVyLI.txt', '--parse-metadata', '%(release_year,upload_date)s:%(meta_date)s', '--parse-metadata', '%(album,title)s:%(meta_album)s', '--sponsorblock-remove', 'default', '--write-thumbnail', '-P', '/storage/emulated/0/Music', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffmpeg.so', 'https://youtu.be/RC9UDlfVyLI?feature=shared']
[debug] | Config "/data/user/0/com.junkfood.seal/cache/configRC9UDlfVyLI.txt": ['--ppa', 'ffmpeg: -c:v mjpeg -vf crop="\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'"']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.15.110-android14-11-ga6d7915820a0-ab10726252-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, quality, res, fps, hdr:12(7), source, vcodec:vp9.2(10), channels, acodec, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] Searching for '(?P<meta_date>.+)' in '%(release_year,upload_date)s'
[debug] Searching for '(?P<meta_album>.+)' in '%(album,title)s'
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/4eaf?service=YouTube&categories=%5B%22outro%22%2C+%22music_offtopic%22%2C+%22intro%22%2C+%22preview%22%2C+%22selfpromo%22%2C+%22sponsor%22%2C+%22interaction%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[debug] ffmpeg command line: '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].webp' -update 1 -movflags +faststart -c:v mjpeg -vf 'crop='"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'' 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png'
[debug] Invoking http downloader on "https://rr3---sn-uhvcpax0n5-vgqs.googlevideo.com/videoplayback?expire=1698336788&ei=tDs6Ze_hBbeulu8P-euYyAo&ip=2607%3Afb90%3Aa10e%3A4dbd%3A53e0%3A147a%3A615b%3A59ca&id=o-AEszTCZxpiNuLYM2vKa7t0NqsDaefeQX7-jbJ-2UNYE7&itag=251&source=youtube&requiressl=yes&mh=r_&mm=31%2C29&mn=sn-uhvcpax0n5-vgqs%2Csn-vgqsknes&ms=au%2Crdu&mv=m&mvi=3&pl=40&pcm2=no&initcwndbps=518750&spc=UWF9f7vQEWdpu0uDusvN_sCjniH0d90&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=3307005&dur=196.481&lmt=1695245139793388&mt=1698314750&fvip=1&keepalive=yes&fexp=24007246&beids=24350018&c=ANDROID&txp=6308224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cpcm2%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AGM4YrMwRAIgSNdc8N8UnepXOrQNe149eyxhqJ3QhpbscrB8dxL465kCIGF2vcxIBHCVViuFbASTwO2aw_iuJoJJ9rLv0IhhLc0d&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AK1ks_kwRgIhAIZWQUQChcT8SCWoBTbTbtiHurYDm7I5Fa9bb5vDxHyGAiEArlNGDhpqRzy8wFT8FYvVtnL7vV9I7NEzIC7wi_fJhwE%3D"
[debug] ffmpeg command line: '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffprobe.so' -show_streams 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].webm'
[debug] ffmpeg command line: '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].webm' -vn -acodec libmp3lame -q:a 5.0 -movflags +faststart -c:v mjpeg -vf 'crop='"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'' 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].mp3'
[debug] ffmpeg command line: '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].mp3' -map 0 -dn -ignore_unknown -c copy -write_id3v1 1 -metadata 'title=Rocco - hold me, never let go (Official Lyric Video)' -metadata date=20230921 -metadata 'description=“hold me, never let go” - Rocco 
Stream "Her Favorite Flowers" out on all platforms:
https://rocco.lnk.to/Apples
Lyric Video by @yondoby

Follow Rocco
TikTok: https://www.tiktok.com/@roccoyellow
Instagram: https://www.instagram.com/roccoyellow/
Facebook: www.facebook.com/roccoyellow
Spotify: https://open.spotify.com/artist/30gZl...' -metadata 'synopsis=“hold me, never let go” - Rocco 
Stream "Her Favorite Flowers" out on all platforms:
https://rocco.lnk.to/Apples
Lyric Video by @yondoby

Follow Rocco
TikTok: https://www.tiktok.com/@roccoyellow
Instagram: https://www.instagram.com/roccoyellow/
Facebook: www.facebook.com/roccoyellow
Spotify: https://open.spotify.com/artist/30gZl...' -metadata 'purl=https://www.youtube.com/watch?v=RC9UDlfVyLI' -metadata 'comment=https://www.youtube.com/watch?v=RC9UDlfVyLI' -metadata artist=Rocco -metadata 'album=Rocco - hold me, never let go (Official Lyric Video)' -movflags +faststart -c:v mjpeg -vf 'crop='"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'' 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].temp.mp3'
[debug] ffmpeg command line: '/data/app/~~OMSX9NIvN4TqTXmNWWxs1A==/com.junkfood.seal-q0mx-ixmOvZjzXtdPGYcpQ==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].mp3' -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png' -c copy -map 0:0 -map 1:0 -write_id3v1 1 -id3v2_version 3 -metadata:s:v 'title="Album cover"' -metadata:s:v 'comment=Cover (front)' -movflags +faststart -c:v mjpeg -vf 'crop='"'"'if(gt(ih,iw),iw,ih)'"'"':'"'"'if(gt(iw,ih),ih,iw)'"'"'' 'file:/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].temp.mp3'
ERROR: [Errno 1] Operation not permitted: '/storage/emulated/0/Music/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png'
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/shutil.py", line 780, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Cross-device link: '/data/user/0/com.junkfood.seal/cache/tmp/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png' -> '/storage/emulated/0/Music/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3464, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3645, in post_process
    info = self.run_pp(MoveFilesAfterDownloadPP(self), info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3604, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/movefilesafterdownload.py", line 50, in run
    shutil.move(oldfile, newfile)  # os.rename cannot move between volumes
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/shutil.py", line 794, in move
    copy_function(src, real_dst)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/shutil.py", line 426, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/shutil.py", line 259, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 1] Operation not permitted: '/storage/emulated/0/Music/Rocco - hold me, never let go (Official Lyric Video) [RC9UDlfVyLI].png'

### Error reports

Couldn't download any song

**Comment by Marco-9456** [comment]
Give the app a permission called "All files access"
to give it to the app, go to your phone `settings` and `search` for "`All files access`" and give it to the app.
This permission is needed because you're trying to download outside the Download directory.

**Comment by Marco-9456** [comment]
> Thank you a lot, this was my bad!

No problem
