### ISSUE TITLE
Finished downloading bug with custom commands

### ISSUE THREAD

**Issue by KazKaz90** [JunkFood02/Seal#116]
It says it has finished downloading, but there is still the throbber animation and no notification that the download is complete.

https://user-images.githubusercontent.com/90075041/184515981-7a29f1bb-9d04-4d8d-b0ef-044a2b98dbba.mp4

**Comment by KazKaz90** [comment]
Also can't remove the notification, it's been there for like an hour

**Comment by Marco-9456** [comment]
> Also can't remove the notification, it's been there for like an hour

Which version are you using ?

**Comment by KazKaz90** [comment]
1.0.4, but It'll actually disappear once you exit the app

**Comment by Marco-9456** [comment]
> 1.0.4, but It'll actually disappear once you exit the app

I just downloaded the same Playlist trying to reproduce the bug but it didn't happen to me I got the `Finished Downloading` message and then it cleared out automatically like it supposed to do, Try to force stop the app and then clear cache or do a clean install

**Comment by KazKaz90** [comment]
> I just downloaded the same Playlist trying to reproduce the bug but it didn't happen to me I got the `Finished Downloading` message and then it cleared out automatically like it supposed to do, Try to force stop the app and then clear cache or do a clean install

Yeah, I found another bug, this time regarding notifications. I cancelled a download, but the download progress notification did not go away however, force closing the app did.

**Comment by KazKaz90** [comment]
I may close this later because I believe I broke the app when I had the stable 1.0.0 release and just updated to 1.0.4, which could be the cause of this. Need to do more testing

**Comment by yant0** [comment]
i just got the same bug. Updated my app through github from 1.0.3 to 1.0.4. It ws running custom command.
![IMGPP_411](https://user-images.githubusercontent.com/80298071/184526913-63870d75-8872-4a3a-bc56-005c4b85f1a1.jpg)

**Comment by JunkFood02** [comment]
> i just got the same bug. Updated my app through github from 1.0.3 to 1.0.4. It ws running custom command. ![IMGPP_411](https://user-images.githubusercontent.com/80298071/184526913-63870d75-8872-4a3a-bc56-005c4b85f1a1.jpg)

I'll be looking into it

**Comment by JunkFood02** [comment]
Did you cancel a download task before the bug occurred?
@yant0

**Comment by KazKaz90** [comment]
> Did you cancel a download task before the bug occurred?
> 
> If so, I think I've found where's the issue. Reproduced on my side
> You can close the app manually for this, will be fixed in next version

Yeah, I actually don't really remember but I think I also cancelled a download first and then this bug happened, and yeah I'm using custom commands.
