### ISSUE TITLE
DESCARGAS YOUTUBE 

### ISSUE THREAD

**Issue by kksos05** [JunkFood02/Seal#1162]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

En la última actualización 1.11 beta 2 se descargan los videos de youtube pero no se puede reproducir dice "no es posible reproducir el video. el tipo de archivo no es compatible" intente cambiar al yt-dpl-nigtly, ninguna de las 2 opciones del yt-dlp me funcionan para poder reproducir el video.

### Error reports

No es posible reproducir el video, el tipo de archivo no es compatible 

### Screenshots & Screen Records

![Screenshot_20231029_001628_Gallery](https://github.com/JunkFood02/Seal/assets/143159515/6aba91f8-ffa6-4cd9-9180-1ad20524f68a)

**Comment by Marco-9456** [comment]
Use a different video player like VLC or MX Player
