### ISSUE TITLE
Extract the downloaded video from the hidden directory

### ISSUE THREAD

**Issue by swhitegx** [JunkFood02/Seal#1163]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Videos downloaded to a hidden directory cannot be moved out.
![Screenshot_20231029_201210](https://github.com/JunkFood02/Seal/assets/131721036/8b5e9ab8-e431-4d12-85f9-d94325413ff3)

### Describe the solution you'd like

The user needs a button component to move the downloaded video out of the hidden directory.
![Screenshot_20231029_200935_edit_18824834814314](https://github.com/JunkFood02/Seal/assets/131721036/da1903c1-bd7f-46ee-a228-7e51af3b5362)

**Comment by Marco-9456** [comment]
I think it's interesting, but Seal is not a file manager, if you want to move the video/audio out of the hidden folder, all you have to do is open the file manager of your phone and search in its setting for an option to display hidden folders or System folders, the folder will be in the download directory with the name `.Seal`

**Comment by JunkFood02** [comment]
> Videos downloaded to a hidden directory cannot be moved out

Just use a file manager (the built-in one is fine) to access the hidden directory
