### ISSUE TITLE
Option to rename the video that is to be downloaded.

### ISSUE THREAD

**Issue by AllenCyborg** [JunkFood02/Seal#1164]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The default titled of videos downloaded from many platforms such as Instagram are very confusing and often doesn't make any sense. This makes organising them later or even finding a particular video very hard.

### Describe the solution you'd like

A textbox in the UI that when populated renames the downloaded file (audio and/or video) to it's contents.

**Comment by AllenCyborg** [comment]
@Marco-9456 

>format selection page

do you mean the `Format` page in the `Settings`? there is an option to enable format selection, but no option to select title... I'm using the Fdroid build v1.10.0 if that matters...

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/assets/41828058/79baeaec-e292-4574-be91-8929c098a2e5
