### ISSUE TITLE
Option to rename download

### ISSUE THREAD

**Issue by AllenCyborg** [JunkFood02/Seal#1165]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The default titles of videos downloaded from many platforms are very confusing and often doesn't make any sense. This makes organising them later or even finding a particular video very hard.

### Describe the solution you'd like

A textbox in the UI that when populated renames the downloaded file (audio and/or video) to it's contents.

**Comment by AllenCyborg** [comment]
#1164 got closed by a bot by mistake, so I'm opening the same one as #1165.

**Comment by Marco-9456** [comment]
I answered you there
