### ISSUE TITLE
App disappear on back button double tap

### ISSUE THREAD

**Issue by Eyt-Lev** [JunkFood02/Seal#1167]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When going to a screen with back button direct to the home screen, and tapping it twice, the app goes to blank screen where you can just closed it and reopen it in order to continue 

### Error reports

There are no error reports

### Screenshots & Screen Records

![screenshot](https://github.com/JunkFood02/Seal/assets/130865561/55b4760e-1e2e-4792-a3e7-2d4b3f5502a2)
It's the arrow on the top left, (can be another screen , that's happening also in settings screen for example)

**Comment by Marco-9456** [comment]
I can reproduce it:
- To reproduce you have to click it twice and fast.


https://github.com/JunkFood02/Seal/assets/41828058/b63013f8-acd4-4f20-96ad-6600ed898ce0
