### ISSUE TITLE
[Improvement request] Split a video with chapters

### ISSUE THREAD

**Issue by holy-crusader-py** [JunkFood02/Seal#117]
I think that will be a pretty good idea if we have an option to split a video/music according to his chapters.

There are a repo that already do this for yt-dl (yt-splitter). The code is simple so it can be translated and implemented in the app.

I can try to do this but I'm not very good in Kotlin

**Comment by Marco-9456** [comment]
> I think that will be a pretty good idea if we have an option to split a video/music according to his chapters.
> 
> There are a repo that already do this for yt-dl (yt-splitter). The code is simple so it can be translated and implemented in the app.
> 
> I can try to do this but I'm not very good in Kotlin

You can do it by using `--split-chapters` command, yt-dlp already supports this option

**Comment by holy-crusader-py** [comment]
> > I think that will be a pretty good idea if we have an option to split a video/music according to his chapters.
> > 
> > There are a repo that already do this for yt-dl (yt-splitter). The code is simple so it can be translated and implemented in the app.
> > 
> > I can try to do this but I'm not very good in Kotlin
> 
> You can do it by using `--split-chapters` command, yt-dlp already supports this option

Oh nice! I might be able to do it then

**Comment by Marco-9456** [comment]
> > > I think that will be a pretty good idea if we have an option to split a video/music according to his chapters.
> > > There are a repo that already do this for yt-dl (yt-splitter). The code is simple so it can be translated and implemented in the app.
> > > I can try to do this but I'm not very good in Kotlin
> > 
> > 
> > You can do it by using `--split-chapters` command, yt-dlp already supports this option
> 
> Oh nice thank you! I might be able to do it then

👍
