### ISSUE TITLE
Share video link to v1.11.0-rc.2 doesn't works

### ISSUE THREAD

**Issue by Birraque** [JunkFood02/Seal#1179]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Everything was working flawlessly in previous v1.11.0-rc.1 but after upgrading to v1.11.0-rc.2 sharing video links to Seal Quick Downloader doesn't start the download anymore.
The v1.11.0-rc.2 can handle the download link only if manually copied and pasted in the Seal app.
How can we handle it?

### To Reproduce

1. Click on any open video in the Share To...
2. Select the Seal Quick Downloader option
3. The video download doesn't start as expected

### Error reports

None
Nothing happens

### Screenshots & Screen Records

https://we.tl/t-YhMtapU2XF

**Comment by Birraque** [comment]
Already rollback to  v1.11.0-rc.1 and it's working flawlessly again.
Some bug in the  v1.11.0-rc.2 that must be addressed before final build release.

**Comment by Birraque** [comment]
> Yup, quick download popup isn't showing for me.

Same for me when I was on v1.11.0-rc.2

**Comment by JunkFood02** [comment]
reinstall v1.11.0-rc.2

**Comment by Birraque** [comment]
> reinstall v1.11.0-rc.2

Does it works now?
