### ISSUE TITLE
Audio quality 

### ISSUE THREAD

**Issue by Sauceseeker** [JunkFood02/Seal#118]
And option to select audio quality
Example: 320kbps | 256 kbps

**Comment by Marco-9456** [comment]
> And option to select audio quality Example: 320kbps | 256 kbps

Seal is downloading the best quality thats avaliable automaticly, but it would be nice if the user had the option to use the `--cookies-from-browser BROWSER[+KEYRING][:PROFILE]` command to get the penefits of thier Youtube Premium Subscription and download tracks from YT-Music with the best quality
