### ISSUE TITLE
I can't download the video

### ISSUE THREAD

**Issue by Ninjasmh20** [JunkFood02/Seal#1182]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.11.0-rc.2 (11100)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.10.13

URL: https://music.youtube.com/watch?v=6SSBZWBRYng
[debug] Command-line config: ['--no-mtime', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '--add-header', 'User-Agent:Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36', '-v', '--no-playlist', '--concurrent-fragments', '24', '-S', 'vcodec:av01,res:1080,acodec:aac', '--write-auto-subs', '--extractor-args', 'youtube:skip=translated_subs', '--sub-langs', 'en.*,.*-orig', '--remux-video', 'mkv', '--embed-subs', '--embed-chapters', '--sponsorblock-remove', 'default', '--write-thumbnail', '--convert-thumbnails', 'png', '-P', '/storage/emulated/0/Movies/Youtube', '-P', 'temp:/storage/emulated/0/Download/Seal/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~AyfJdcbLvaniELQXWkndZQ==/com.junkfood.seal-mNWG3CT78a-jAUcCRKjEsQ==/lib/arm64/libffmpeg.so', 'https://music.youtube.com/watch?v=6SSBZWBRYng']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2023.10.13 [b634ba742] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.14.186-g4e5507d5edae-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Loaded 1890 extractors
[debug] [youtube] Extracted SAPISID cookie
[debug] [youtube] Extracting signature function js_5bdfe6d5_102
[debug] [youtube] Decrypted nsig aI7Ea2o0wQ_SQGBk => MHIehGJfO2hVYw
[debug] [youtube] Extracting signature function js_5bdfe6d5_106
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[debug] Sort order given by user: vcodec:av01, res:1080, acodec:aac
[debug] Sort order given by extractor: quality, res, fps, hdr:12, source, vcodec:vp9.2, channels, acodec, lang, proto
[debug] Formats sorted by: hasvid, ie_pref, vcodec:av01(11), res:1080(1080.0), acodec:aac(10), quality, fps, hdr:12(7), source, channels, lang, proto, size, br, asr, vext, aext, hasaud, id
[debug] SponsorBlock query: https://sponsor.ajay.app/api/skipSegments/dc66?service=YouTube&categories=%5B%22music_offtopic%22%2C+%22sponsor%22%2C+%22intro%22%2C+%22interaction%22%2C+%22selfpromo%22%2C+%22preview%22%2C+%22outro%22%5D&actionTypes=%5B%22skip%22%2C+%22poi%22%2C+%22chapter%22%5D
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking hlsnative downloader on "https://manifest.googlevideo.com/api/manifest/hls_timedtext_playlist/expire/1699617417/ei/KcZNZcqjEZeR9fwPsJmJ-A8/ip/110.226.180.171/id/e924816560516278/source/youtube/requiressl/yes/dur/274.233/tts_params/caps%3Dasr%26v%3D6SSBZWBRYng%26lang%3Den%26ip%3D110.226.180.171%26ipbits%3D0%26expire%3D1699617417%26sparams%3Dip,ipbits,expire,caps,v%26signature%3D2EB7A7D2767D75CC08D5E6456350A7CCA6453159.889574653839363CC1275DBB165CFBE8F39571D8%26key%3Ddg_yt0/hls_chunk_host/rr6---sn-ci5gup-cvhe7.googlevideo.com/mh/OO/mm/31,26/mn/sn-ci5gup-cvhe7,sn-qxaelnez/ms/au,onr/mv/m/mvi/6/pl/20/force_finished/1/initcwndbps/1603750/siu/1/vprv/1/playlist_type/DVR/mt/1699594866/fvip/1/short_key/1/keepalive/yes/fexp/24007246/beids/24350018/sparams/expire,ei,ip,id,source,requiressl,dur,tts_params,force_finished,siu,vprv,playlist_type/sig/ANLwegAwRQIhAP_XLbyeovu9S3YpZH2Y1htQmpgofN-bgEYBeJE3bjI-AiAG09YKDbq7mGus3uko8v0KD2dy_svIpU9_gXBX2IRDoQ%3D%3D/lsparams/hls_chunk_host,mh,mm,mn,ms,mv,mvi,pl,initcwndbps/lsig/AM8Gb2swRAIgXYiaC1rrOvMaH1B_N--FQyVxpKLTNNdGRWu6RizAqoACIHFsW5S5CE4J3OmzQrBwriZ8Ow-tu9aR7hZI6NKOuisF/playlist/index.m3u8"
ERROR: Parse error at position 35 (near 'Style:\n::cue(c.blue)')
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2921, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3175, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 4211, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3108, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 455, in download
    ret = self.real_download(filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/hls.py", line 372, in real_download
    self.download_and_append_fragments(
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/fragment.py", line 501, in download_and_append_fragments
    if not append_fragment(decrypt_fragment(fragment, self._read_fragment(ctx)), frag_index, ctx):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/fragment.py", line 475, in append_fragment
    self._append_fragment(ctx, pack_func(frag_content, frag_index))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/hls.py", line 287, in pack_fragment
    for block in webvtt.parse_fragment(frag_content):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/webvtt.py", line 363, in parse_fragment
    yield Magic.parse(parser)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/webvtt.py", line 217, in parse
    raise ParseError(parser)
yt_dlp.webvtt.ParseError: Parse error at position 35 (near 'Style:\n::cue(c.blue)')

### Additional context

I have faced this problem whenever I have tried to download a full playlist

**Comment by JunkFood02** [comment]
Disable "Embed subtitles", the subtitle you're trying to download is incompatible with it
