### ISSUE TITLE
Captions Error

### ISSUE THREAD

**Issue by mjain234** [JunkFood02/Seal#1185]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

As you can see in the video provided, it clearly displays the captions in the video which is embedded in the video itself. But after downloading through seal, the captions aren't displaying. I have tried to repeat it several times, but it's the same result. As the captions are already embedded in the video itself, the downloaded video should also be the same, right? What am I missing here?

### Error reports

Caption Error

### Screenshots & Screen Records

https://i.imgur.com/WOf8mwk.mp4

**Comment by JunkFood02** [comment]
just watch your video with its original ratio in mx player, i guess it's 16:9
