### ISSUE TITLE
File size before download 

### ISSUE THREAD

**Issue by VinNgase** [JunkFood02/Seal#1188]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Before downloading I am unable to see the file size so that I can tell how big or small the file I want to download is. I mostly use a metered connection that's why knowing the exact file size of what I want to download would be great. 

### Describe the solution you'd like

Add file size(or approximate file size) to the description of files on the download page before download.

**Comment by JunkFood02** [comment]
Use "Custom" format selection(not available in quick download) and you'll be able to view all the formats with their exact file size
