### ISSUE TITLE
The resolution before download 

### ISSUE THREAD

**Issue by carlosyoan99** [JunkFood02/Seal#1196]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When i try to download on YouTube, i have the possibility to configure the resolution on previous version (1.10). On 1.11, that is not possible. The option is inactive. 

### To Reproduce

Select the video to download, click on share, Seal. The option to configure before download must be active. Then the option fir configure the video quality is inactive. 
Don't work with any web.

### Error reports

I don't have s bugreport

### Screenshots & Screen Records

![Screenshot_20231119_165636_Seal](https://github.com/JunkFood02/Seal/assets/81061189/742b4b49-f290-4114-a535-eb549e416b3f)

**Comment by JunkFood02** [comment]
You're using custom format sorting which overrides any other format preferences
