### ISSUE TITLE
safe output templates

### ISSUE THREAD

**Issue by GfEW** [JunkFood02/Seal#1200]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm very grateful for you to create Seal. It proves extremely helpful in many cases, especially if you (like me) lack the necessary nerdiness to comprehend yt-dlp's intricate options and python based syntax in less than an entire weekend's worth of time. 

That said, titles of downloadable media frequently contain characters that make any followup file processing, bulk operations etc. in FAT32 a real PITA (and FAT32 is still commonly used on SD cards in Android). This is where I'd like to suggest an improvement, as outlined below.

In theory, filename troubles are easily prevented by flagging every string key (e. g. `%(uploader)` or `%(title)`) with '#S' rather than 's' or 'B', as explained in the yt-dlp docs, section "output template". With this format conversion, all flagged keys are restricted to safe characters, allowing the entire output template to be "sanitized" in a straightforward manner, e. g.:
`%(uploader)#S_%(playlist)#S/%(title)#.200S_%(upload_date)#S.%(ext)#S`

Alas, Seal currently (as of 1.11.0) requires every output template to contain the exact strings `%(title).200B` and `.%(ext)s`. Even if a "sanitized" title like `%(title)#.200S` is already included in a template, Seal
would still insist on adding `%(title).200B` to it, or reject the template. 

My tests with 
`%(uploader)#S_%(playlist)#S/%(title)#.200S_%(upload_date)#S.%(ext)#S____%(title).200B.%(ext)s` 
confirm that the "sanitized" part of this template (i. e. everything before the `____` separator) indeed restricts its output to safe characters. But of course, being forced by Seal to include two "non-sanitized" keys defeats the entire purpose of safe filenames.

### Describe the solution you'd like

I'd greatly appreciate if the exact, fixed `%(title).200B` and `%(ext)s` requirements were loosened to allow `s` and `S` conversion formats, along with the `#` conversion flag, and precision values lower than 200, without sacrificing security. 

As **one solution** that comes to mind, the template could be matched against the regexes
`%\(title\)#?(\.(200|1[0-9][0-9]|[1-9][0-9]?))?[BsS]` 
and 
`%\(ext\)#?[BsS]`, 
respectively.

As an **alternative solution**, the global yt-dlp option `--restrict-filenames` could be made available as a switch in Seal's "Download directory" settings.

Doing so would give a big relief to GUI users (not able to create custom commands) with FAT32 related filename troubles, whilst (provided that Seal's "downloaded file recognition" doesn't rely on special characters) the side, followup and maintenance costs should be negligible.

### Video link

https://invidious.esmailelbob.xyz/watch?v=uN6WRRns7U8&local=true

### Additional context

Maybe the strict requirement of `%(title).200B` and `.%(ext)s` in each template is meant to serve as a safeguard, making sure that even adventurous users get the basics right, or to ensure Seal has everything it needs in order to recognize downloaded files if `%(id)` is not included.

But whatever the purpose of the currently implemented strict requirement, I hope it can be achieved in a more flexible, sensible and no less secure manner that doesn't actually prevent templates to create safe filenames?

**Comment by JunkFood02** [comment]
Thanks for this detailed feature request! 

> Maybe the strict requirement of `%(title).200B` and `.%(ext)s` in each template is meant to serve as a safeguard, making sure that even adventurous users get the basics right, or to ensure Seal has everything it needs in order to recognize downloaded files if %(id) is not included.

Yes, the `%(title).200B` part is used by Seal to located the file by its name without the `id` in it. 

> As an alternative solution, the global yt-dlp option --restrict-filenames could be made available as a switch in Seal's "Download directory" settings.

This should make more sense than using regex magic to scare all of our users including me

**Comment by JunkFood02** [comment]
I've added `--restrict-filenames` to the app, you can install the [CI artifact](https://github.com/JunkFood02/Seal/actions/runs/6949529673) (arm64 only) to verify if it's working as you expected 😉

**Comment by GfEW** [comment]
> Yes, the `%(title).200B` part is used by Seal to located the file by its name without the `id` in it.

I see.

> > As an alternative solution, the global yt-dlp option --restrict-filenames could be made available as a switch in Seal's "Download directory" settings.
> 
> This should make more sense than using regex magic to scare all of our users including me

Hehe, if only regex magic was enough to create working yt-dlp custom commands! (Beware, I might not use Seal anymore!)
Actually, I meant the suggested regexes to be employed internally for template verification, and not necessarily presented to the user. However, since you state that Seal *does* rely on `%(title).200B`, the more general template verification wouldn't work so easily but rather require changes that might be too big to justify.

I agree, the global switch `--restrict-filenames` would make more sense, and suffice.

Many thanks in advance for considering this improvement!

**Comment by GfEW** [comment]
> I've added `--restrict-filenames` to the app, you can install the [CI artifact](https://github.com/JunkFood02/Seal/actions/runs/6949529673) (arm64 only) to verify if it's working as you expected 😉

Wow, **so fast!** *Crazy!* **Thank you <3** 
Of course, I'll test and report ASAP.

**Comment by GfEW** [comment]
So, I've tested the CI artifact with six videos whose names contain special characters, from three different sites. All subdirectory and file names have been properly restricted/converted to FAT32-safe characters.

That's awesome responsiveness - perfectly in line with the overall user experience of your creation, Seal. Thank you so much, @JunkFood02! 

p. s. I've still to find some way to donate via github. As soon as that works, I'll happily give you that form of appreciation, too, aside from further recommending Seal.

**Comment by uncaught** [comment]
I have a problem with `%(title).200B` being too long for my sync to my NAS. The filenames are just getting too long.

I would prefer to be able to just put `%(id)` and nothing else to keep the name short as possible.

Most of the tiktok titles are useless.. they are just a bunch of random hashtags :(

**Comment by JunkFood02** [comment]
@uncaught Hi since you're using a NAS i guess you're an advanced user, i suggest using custom commands for your downloads
