### ISSUE TITLE
Instagram videos not downloading

### ISSUE THREAD

**Issue by privacyfreak84** [JunkFood02/Seal#1206]
App version: 1.11.0-(F-Droid) (11104)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.11.16

URL: https://instagram.com/p/CmeiGzPpjW5/
WARNING: [Instagram] CmeiGzPpjW5: Instagram API is not granting access
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CmeiGzPpjW5: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by isouvikdas** [comment]
Well I tried to download the given URL above and it worked fine. I don't see any issue here, could you please elaborate what's the issue you are facing?

**Comment by isouvikdas** [comment]
> App version: 1.11.0-(F-Droid) (11104) Device information: Android 11 (API 30) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.11.16
> 
> URL: https://instagram.com/p/CmeiGzPpjW5/ WARNING: [Instagram] CmeiGzPpjW5: Instagram API is not granting access WARNING: [Instagram] unable to extract username; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U ERROR: [Instagram] CmeiGzPpjW5: Unable to extract video url; please report this issue on https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using yt-dlp -U

Well I tried to download the given URL above and it worked fine. I don't see any issue here, could you please elaborate what's the issue you are facing?

**Comment by Marco-9456** [comment]
1. Follow the issue template
2. Check [this](https://github.com/JunkFood02/Seal/issues/733)
