### ISSUE TITLE
"Clear All" isn't present in "Download finised" notifications group

### ISSUE THREAD

**Issue by esdnm** [JunkFood02/Seal#1214]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I have downloaded a playlist, having 100+ tracks in it. Now I can't clear all the Download finished notifications at once, there is no Clear All present for this app's notification group, making me clear all the notification one by one!!

### To Reproduce

Download a playlist and try to clear all download finished notifications

### Error reports

Not required.

### Screenshots & Screen Records

![image](https://github.com/JunkFood02/Seal/assets/90970080/5271bf82-829e-4539-964d-29e58c2a8911)

### Additional context

Device OS: Android 11 Go

**Comment by JunkFood02** [comment]
You can go to Settings - General - turn off Download notifications for clearing all notifications sent by the app

**Comment by Marco-9456** [comment]
> Actually I can dismiss all the notifications by swiping a notification group left or right on my device, so I believe this is an OEM-specific behavior which is not relevant to this app

![Screenshot_20231209_072542_Google](https://github.com/JunkFood02/Seal/assets/41828058/6d40bb2d-55c8-48ab-b416-af7a52833c52)

**Comment by JunkFood02** [comment]
only the "Seal is downloading" notification is for the foreground service while the rest of them being regular notifications
