### ISSUE TITLE
Audio Download

### ISSUE THREAD

**Issue by hussainmortadha** [JunkFood02/Seal#1223]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

There is two bugs :
1. When i download audio and covert it to mp3 the quality of mp3 file is only 32 kbps, In addition to that m4a file qualtiy is only 127 kbps, and OPUS file quality is only 135 kbps, While the quality I chose is 192 kbps, i hope to fix that, I also hope that an option will be added to download sounds at 320 kbps.
2. Sometimes when I try to download from YouTube or other sites, the download does not complete the first time, but rather gives me the sentence “Failed to retrieve video information” and I have to repeat the process again for the download to begin. I hope to fix this as well. 

### Error reports

I don't have it

**Comment by JunkFood02** [comment]
#953
