### ISSUE TITLE
Pause button, Spotify, 320 kbps

### ISSUE THREAD

**Issue by hussainmortadha** [JunkFood02/Seal#1224]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

There is Some feature :
1. Pause download button .
2. Possibility of downloading from Spotify .
3. (320 kbps) option for audio download options menu .

**Comment by Marco-9456** [comment]
1. No
2. No
3. No
