### ISSUE TITLE
Seal unable to embed thumbinails

### ISSUE THREAD

**Issue by Letus252** [JunkFood02/Seal#1228]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I wanted to be able to download youtube 1080p videos (preferably in mp4) with embedded thumbnails. For this reason, I decided to use custom arguments:

"bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" --embed-thumbnail -o "%(title)s.%(ext)s"

which is working without any issue on pc version of yt-dlp (in powershell, I would add "./yt-dlp.exe -f " to this command). Unfortunately, when using it through Seal, it doesn't work properly. Seal ignores the mp4 argument and instead uses webm, which doesn't support embedding thumbnails. According to the error log, Seal then tries to use mkv instead, but never does so and ends up downloading in webm.

### To Reproduce

Try downloading any youtube video using this custom command.

### Error reports

[generic] Extracting URL: bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best
[youtube] Extracting URL: https://youtu.be/vLl0CNSoFIA

[youtube] vLl0CNSoFIA: Downloading webpage
[youtube] vLl0CNSoFIA: Downloading ios player API JSON
[youtube] vLl0CNSoFIA: Downloading android player API JSON
[youtube] vLl0CNSoFIA: Downloading player d23221b6
[youtube] vLl0CNSoFIA: Downloading m3u8 information
[info] vLl0CNSoFIA: Downloading 1 format(s): 303+251
[info] Downloading video thumbnail 41 ...
[info] Writing video thumbnail 41 to: /storage/835B-0820/Download/Seal/Gaben has ZERO chill for cheaters.webp
[download] Destination: /storage/835B-0820/Download/Seal/Gaben has ZERO chill for cheaters.f303.webm
[download]   0.0% of   10.99MiB at  230.70KiB/s ETA 00:49
[download]   0.0% of   10.99MiB at  406.48KiB/s ETA 00:27
[download]   0.1% of   10.99MiB at  599.48KiB/s ETA 00:18
[download]   0.1% of   10.99MiB at 1012.24KiB/s ETA 00:11
[download]   0.3% of   10.99MiB at    1.66MiB/s ETA 00:06
[download]   0.6% of   10.99MiB at    1.20MiB/s ETA 00:09
[download]   1.1% of   10.99MiB at    2.06MiB/s ETA 00:05
[download]   2.3% of   10.99MiB at    2.67MiB/s ETA 00:04
[download]   4.5% of   10.99MiB at    3.44MiB/s ETA 00:03
[download]   9.1% of   10.99MiB at    4.14MiB/s ETA 00:02
[download]  18.2% of   10.99MiB at    4.95MiB/s ETA 00:01
[download]  36.4% of   10.99MiB at    5.26MiB/s ETA 00:01
[download]  72.8% of   10.99MiB at    5.16MiB/s ETA 00:00
[download]  90.0% of   10.99MiB at    5.19MiB/s ETA 00:00
[download]  90.1% of   10.99MiB at  Unknown B/s ETA Unknown
[download]  90.1% of   10.99MiB at  849.45KiB/s ETA 00:01
[download]  90.1% of   10.99MiB at    1.04MiB/s ETA 00:01
[download]  90.2% of   10.99MiB at    1.32MiB/s ETA 00:00
[download]  90.3% of   10.99MiB at    2.01MiB/s ETA 00:00
[download]  90.6% of   10.99MiB at    3.04MiB/s ETA 00:00
[download]  91.2% of   10.99MiB at    1.84MiB/s ETA 00:00
[download]  92.3% of   10.99MiB at    2.79MiB/s ETA 00:00
[download]  94.6% of   10.99MiB at    3.54MiB/s ETA 00:00
[download]  99.1% of   10.99MiB at    4.38MiB/s ETA 00:00
[download] 100.0% of   10.99MiB at    4.50MiB/s ETA 00:00
[download] 100% of   10.99MiB in 00:00:02 at 4.60MiB/s
[download] Destination: /storage/835B-0820/Download/Seal/Gaben has ZERO chill for cheaters.f251.webm
[download]   0.1% of  893.00KiB at  176.17KiB/s ETA 00:05
[download]   0.3% of  893.00KiB at  261.94KiB/s ETA 00:03
[download]   0.8% of  893.00KiB at  463.18KiB/s ETA 00:01
[download]   1.7% of  893.00KiB at  579.32KiB/s ETA 00:01
[download]   3.5% of  893.00KiB at    1.02MiB/s ETA 00:00
[download]   7.1% of  893.00KiB at    1.82MiB/s ETA 00:00
[download]  14.2% of  893.00KiB at    1.30MiB/s ETA 00:00
[download]  28.6% of  893.00KiB at    2.00MiB/s ETA 00:00
[download]  57.2% of  893.00KiB at    2.94MiB/s ETA 00:00
[download] 100.0% of  893.00KiB at    2.06MiB/s ETA 00:00
[download] 100% of  893.00KiB in 00:00:00 at 1.65MiB/s
[Merger] Merging formats into "/storage/835B-0820/Download/Seal/Gaben has ZERO chill for cheaters.mkv"
[EmbedThumbnail] ffmpeg: Adding thumbnail to "/storage/835B-0820/Download/Seal/Gaben has ZERO chill for cheaters.mkv"

ERROR: [generic] 'bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best" ) to search YouTube
WARNING: webm doesn't support embedding a thumbnail, mkv will be used

### Additional context

I'm not sure if Seal supports using all the arguments used in my custom command. I'm submitting this as a bug on github because, as far as I know, there isn't any other place to ask about it.

**Comment by JunkFood02** [comment]
just read the ERROR in your report

**Comment by JunkFood02** [comment]
> I would add "./yt-dlp.exe -f " to this command

So where's your `-f` for Seal?

**Comment by Letus252** [comment]
Adding -f fixed the problem. (I thought that -f was necessary only for powershell). Thanks for help.
