### ISSUE TITLE
Not downloading multiple videos from one A/c 

### ISSUE THREAD

**Issue by Artist1513** [JunkFood02/Seal#1236]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

Not downloading multiple videos from one A/c and if somehow downloaded, it didn't show 

### Screenshots & Screen Records

https://github.com/JunkFood02/Seal/assets/126226046/0e3df111-bb48-4e32-84f6-a19dfe4e0ce2

### Additional context

Yesterday I have  reported the same issue but I didn't get it the real solution 
Sir plz help me out of this 🙏

**Comment by JunkFood02** [comment]
Settings - Download directory - Output template - select the one with `id` in it
