### ISSUE TITLE
Blocking F-droid metadata on Weblate

### ISSUE THREAD

**Issue by maboroshin** [JunkFood02/Seal#1238]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

F-droid metadata blocked on Weblate for at least 1 month.

See: https://hosted.weblate.org/projects/seal/f-droid-metadata/

### Error reports

```The translation is temporarily closed for contributions due to maintenance, please come back later.```

**Comment by JunkFood02** [comment]
F-Droid only supports few languages, which means translators could have their efforts wasted on redundant strings. If you want to translate these strings, please create a pull request

**Comment by maboroshin** [comment]
@JunkFood02 : The files in the changelogs folder look like they are already old and can be deleted. It remains as a percentage of translation incomplete on Weblate. And it doesn't seem to show old change logs on F-Droid.

**Comment by JunkFood02** [comment]
the component has been removed, thx for the suggestion
