### ISSUE TITLE
Storage Selection

### ISSUE THREAD

**Issue by crumhirnd** [JunkFood02/Seal#124]
If I use the "downloads" button it says "SD card not supported", but if I manually go to downloads from the root of storage it works. Why is this?

Am using 1.0.4

![Screenshot_20220817-220240_Files](https://user-images.githubusercontent.com/83274039/185113850-cb96423c-e113-4b2f-bc9a-76566cb43cb4.png)

**Comment by JunkFood02** [comment]
Please try selecting the `Downloads/` directory from your internal storage. The 'Downloads' option is actually not a directory and cannot be recognized by the app
