### ISSUE TITLE
Should not remember checking "Audio"

### ISSUE THREAD

**Issue by ahmeds189** [JunkFood02/Seal#1242]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm downloading a bunch of videos daily for some reason, then wanted to download an audio file, next time I'm downloading videos didn't notice that I'm downloading audio files only 😅

### Describe the solution you'd like

Only check Audio if I want to.

### Additional context

Maybe skill issues of my side?

**Comment by JunkFood02** [comment]
Maybe you should just remember it on your own? As seal is an **audio/video downloader*, but not a "video downloader which also happens to have the ability to download audio"
