### ISSUE TITLE
[İssue] app itself doesn't show the downloaded video in the downloads list when custom command are used?

### ISSUE THREAD

**Issue by erickyun** [JunkFood02/Seal#1243]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hi,

When I try to download YT video with downloadtype:video the app shows video in downloadlist but when I try to download with manually command the app itself doesn't show the downloaded video in the downloads list when custom command are used?

### To Reproduce

Use custom commands

### Error reports

No error report seen

**Comment by erickyun** [comment]
> You must have the following as an output template to make the app recognize the downloaded media:
> 
> ```python
> %(title).200B.%(ext)s
> ```

I tried but it is not working?
My cmd:

```
--no-mtime --concurrent-fragments '8' --remux-video "mkv" --write-auto-subs --extractor-args 'youtube:skip=translated_subs' --sub-langs 'tur.*,en.*,.*-orig' --convert-subs ass --embed-subs --embed-metadata --embed-thumbnail --sponsorblock-mark "all" --external-downloader ffmpeg --external-downloader-args "ffmpeg_i:-ss 00.000 -to 79.000" -o "%(title).200B.%(ext)s"
```

**Comment by JunkFood02** [comment]
> I try to download with manually command the app itself doesn't show the downloaded video in the downloads list when custom command are used?

Excepted behavior, we don't and we can't record downloads in custom commands
