### ISSUE TITLE
Multiple audio download. Now days YouTube started to release videos in many languages and I also want to download them in multiple languages so please add multiple audio stream selection in download section 

### ISSUE THREAD

**Issue by BeyonderXT** [JunkFood02/Seal#1245]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

**Comment by JunkFood02** [comment]
Do you mean select one language from audio streams or https://github.com/JunkFood02/Seal/issues/1229?

**Comment by Marco-9456** [comment]
> or #1229?

**Comment by Marco-9456** [comment]
@JunkFood02 Should be closed
