### ISSUE TITLE
can u make a seal app for windows? 

### ISSUE THREAD

**Issue by Rahumi-f** [JunkFood02/Seal#1246]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by waqas-334** [comment]
It's easer to just use youtube-dl or yt-dlp on windows cmd and download whatever you want.

**Comment by Marco-9456** [comment]
Won't happen, the Android version is already enough trouble for us

**Comment by Bananaguns2** [comment]
> Won't happen, the Android version is already enough trouble for us

IDK what happened but I was able to download a video from the "hub" without paying the artist as a test & it surprisingly worked!

**Comment by juned0407** [comment]
when we get the pc version ?
 or anyone help me to replicates it for pc version ...

**Comment by Rahumi-f** [comment]
Download a yt-dlp gui its better
