### ISSUE TITLE
Unable To Download Any Audio from Youtube

### ISSUE THREAD

**Issue by kokojoco** [JunkFood02/Seal#1248]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

After trying multiple videos I haven't been able to get any to work, whether they are in a playlist or otherwise, issue has been present for the past week. Download will move through the playlist as normal, only instead of downloading the file, will say download failed.

### Error reports

App version: 1.11.0-(F-Droid) (11104)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.11.16

URL: https://m.youtube.com/watch?v=hvAHtW0SEVg&list=PL-lcCneoWMvQrY_RssNvEmFa2FgE14U6v&index=9&pp=iAQB8AUB
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by JerryHner** [comment]
Also having this problem. Downloading playlists do not work but you can download single videos, assuming you are using the lastest version of seal, this problem is prevalent in all seal versions, am using an older seal version (1.10.0 fdroid) cuz I need the custom directories setting.

**Comment by Marco-9456** [comment]
> WARNING: The download speed shown is only of one thread. This is a known issue
> ERROR: [download] Got error: HTTP Error 403: Forbidden.

- Your IP has been blocked from being granted valid video URLs by YouTube.
- Passing logged-in cookies refreshed within the past 30 minutes works around this

**Comment by JerryHner** [comment]
> Also having this problem. Downloading playlists/albums do not work but you can download single video/audio, assuming you are using the lastest version of seal, this problem is prevalent in all seal versions, am using an older seal version (1.10.0 fdroid) cuz I need the custom directories setting. So this might be a yt dlp problem, not a seal problem.

A
