### ISSUE TITLE
Netscape Cookies

### ISSUE THREAD

**Issue by Cyxcix** [JunkFood02/Seal#1249]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I wanted to download a gif from Twitter and I got this error

### To Reproduce

1.Configuration
2.Network and Internet
3.Cookies
4.Create new Cookies
5.Sign in to Twitter
6.Copy link
7.Ready
8.Paste
9.Download

### Error reports

App version: 1.10.0 (11000)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.12.26.232752

URL: https://x.com/GuilhermeRM_69/status/1740543157207433584?s=20
[debug] Command-line config: ['--no-mtime', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '--add-header', 'User-Agent:Mozilla/5.0 (Linux; Android 13; CPH2365 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36', '-v', '--no-playlist', '--concurrent-fragments', '24', '-x', '-f', 'http-832', '--embed-metadata', '--embed-thumbnail', '--convert-thumbnails', 'jpg', '--convert-thumbnails', 'png', '--parse-metadata', '%(release_year,upload_date)s:%(meta_date)s', '--parse-metadata', '%(album,title)s:%(meta_album)s', '--write-thumbnail', '-P', '/storage/emulated/0/Download/Seal/Audio', '-P', 'temp:/data/user/0/com.junkfood.seal/cache/tmp', '-o', '%(title).200B [%(id)s].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~33xVWvdRwe27JP0AYfdWUQ==/com.junkfood.seal-3Q1Vr0SVlwAhZ8ugjyqwKw==/lib/arm64/libffmpeg.so', 'https://x.com/GuilhermeRM_69/status/1740543157207433584?s=20']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version nightly@2023.12.26.232752 from yt-dlp/yt-dlp-nightly-builds [225cf2b83] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.19.152-perf+-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1798 extractors
[debug] [twitter] Extracting from video info: 1740543146562367490
[debug] Sort order given by extractor: res, proto:m3u8, br, size
[debug] Formats sorted by: hasvid, ie_pref, res, proto:m3u8(8), br, size, lang, quality, fps, hdr:12(7), vcodec:vp9.2(10), channels, acodec, asr, vext, aext, hasaud, source, id
[debug] Searching for '(?P<meta_date>.+)' in '%(release_year,upload_date)s'
[debug] Searching for '(?P<meta_album>.+)' in '%(album,title)s'
[debug] ffmpeg command line: '/data/app/~~33xVWvdRwe27JP0AYfdWUQ==/com.junkfood.seal-3Q1Vr0SVlwAhZ8ugjyqwKw==/lib/arm64/libffmpeg.so' -y -loglevel repeat+info -f image2 -pattern_type none -i 'file:/data/user/0/com.junkfood.seal/cache/tmp/GuilhermeRM_nsfw🔞 Commissions PAUSE - Pixel commission for @xlb_ffxiv [1740543146562367490].jpg' -update 1 -movflags +faststart 'file:/data/user/0/com.junkfood.seal/cache/tmp/GuilhermeRM_nsfw🔞 Commissions PAUSE - Pixel commission for @xlb_ffxiv [1740543146562367490].png'
[debug] Invoking http downloader on "https://video.twimg.com/ext_tw_video/1740543146562367490/pu/vid/avc1/540x540/gj-IwlBgpIGLMV5o.mp4?tag=12"
[debug] ffmpeg command line: '/data/app/~~33xVWvdRwe27JP0AYfdWUQ==/com.junkfood.seal-3Q1Vr0SVlwAhZ8ugjyqwKw==/lib/arm64/libffprobe.so' -show_streams 'file:/data/user/0/com.junkfood.seal/cache/tmp/GuilhermeRM_nsfw🔞 Commissions PAUSE - Pixel commission for @xlb_ffxiv [1740543146562367490].mp4'
ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3489, in process_info
    replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3669, in post_process
    info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3651, in run_all_pps
    info = self.run_pp(pp, info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3629, in run_pp
    files_to_delete, infodict = pp.run(infodict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 23, in run
    ret = func(self, info, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/common.py", line 128, in wrapper
    return func(self, info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/postprocessor/ffmpeg.py", line 495, in run
    raise PostProcessingError('WARNING: unable to obtain file audio codec with ffprobe')
yt_dlp.utils.PostProcessingError: WARNING: unable to obtain file audio codec with ffprobe

### Screenshots & Screen Records

![Screenshot_2023-12-28-19-00-34-92_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/JunkFood02/Seal/assets/123632625/85a9b308-bcd3-4508-843b-3b1714a1bd4c)

**Comment by JunkFood02** [comment]
gif is not supported

**Comment by Marco-9456** [comment]
> gif is not supported

It's Supported, I can download it

**Comment by JunkFood02** [comment]
According to the log, you're trying to download the audio from the video which cause the error
