### ISSUE TITLE
[Bug Report] 🐛 App crashes if rotating the screen before download finishes

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#127]
### Describe the bug

The app crashes in a rare case when rotating the phone.

### To Reproduce

1. Open Seal
2. Paste a [Link](https://music.youtube.com/watch?v=Jb6gcoR266U&feature=share)  to download from
3. Click on download button
4. Rotate the phone 
5. Click on clipboard or download.

### Error reports & Screenshots

https://user-images.githubusercontent.com/41828058/185292456-df13b37a-a80f-482b-9307-056fc7deac89.mp4

### Device info

1.0.5 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]

### Additional context

The app tells me that the error was copied to the clipboard but it wasn't,
Detailed output was enabled.

**Comment by JunkFood02** [comment]
Reproduced
