### ISSUE TITLE
Modern App Icon Redesign

### ISSUE THREAD

**Issue by Ehab-d** [JunkFood02/Seal#1273]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The current app icon doesn't look good and is outdated.

### Describe the solution you'd like

I suggest creating a new, modern icon that matches the design of Material.

### Additional context

Please take this seriously. The current app icon really looks awful in the app launcher.

**Comment by JunkFood02** [comment]
cry about it

**Comment by Ehab-d** [comment]
@JunkFood02 
Please listen to users. I'm not the only one who says this. Seal is a beautiful app, and of course it needs a modern icon. 💙
