### ISSUE TITLE
[Bug Report] The `Year` tag contains wrong data

### ISSUE THREAD

**Issue by cyxae** [JunkFood02/Seal#128]
### Describe the bug

The year tagged on audio files is wrong,
For example when downloading https://www.youtube.com/watch?v=nbtEkZIvMAg as audio, the data tagged in the `Year` field is `20141108` whereas it should be `2014`

By the way, the date which is tagged is the publication date on YouTube whereas it should be the release date of the song ! (This latter data is normally provided by YouTube) So the `year` field should in fact be `1967` !

### To Reproduce

Download https://www.youtube.com/watch?v=nbtEkZIvMAg as audio

Check the `Year` tag

### Device info

1.0.5 (API 32)
[arm64-v8a, armeabi-v7a, armeabi]

### Additional context

Thanks for the app ;)

**Comment by JunkFood02** [comment]
I tested [this link](https://youtu.be/76HfHmtaAJM) and also get `20150321` for [the `Date` field](https://github.com/yt-dlp/yt-dlp#modifying-metadata) instead of the date in the description. I believe that this is the only information we can get from YouTube's side. Also, yt-dlp only provides the `Date` field for metadata.

Seal is a GUI for yt-dlp, so the behavior of embedding metadata is not in our control.

**Comment by cyxae** [comment]
Hi,

I finally managed to read part of yt-dlp documentation (!), and found that the "date" tag is automatically filled with "upload_date" whereas a "release_year" tag exists for most Youtube Music links.

So the solution is to add an option « --parse-metadata "release_year:%(meta_date)s" » to the download command.

It could be like [this line](https://github.com/JunkFood02/Seal/blob/089dc1904e521d3475d54061c81ca8c4f0a51c33/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L232), and be

```
if (releaseYearAsDate) {
    addOption("--parse-metadata", "release_year:%(meta_date)s")
}
```

with `releaseYearAsDate` being associated to a slider in the settings, so we could choose if we want to replace the default behavior of yt-dlp.

I’ve not set up my development environment for Android, so if you think it is not so complicated and you have time I would really appreciate that you implement it :) However if you don’t want to, tell me and I’ll create a pull request !

Thank you very much,

cyxae

**Comment by cyxae** [comment]
Hello !

I’m sorry to raise the issue again, but I found that in the yt-dlp known issues, there is the same case as that one, and the **recommended command** as provided in https://github.com/yt-dlp/yt-dlp/issues/3766 (External issues -> Wrong year in metadata in M4A, MP4, FLAC format) is :

`--parse-metadata "%(release_year,upload_date).4s:(?P<meta_date>.+)"`

(to be replaced at that line https://github.com/JunkFood02/Seal/blob/d67278daba23d101f8e2b32d7db795167997319f/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L346)

So when the release_year is not available, the upload_date is cropped to have only the year in the date tag.

Thank you very much for your work again, this is a _great_ piece of software !
