### ISSUE TITLE
[Feature Request] Add to play store

### ISSUE THREAD

**Issue by Donkey-Doug** [JunkFood02/Seal#129]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Reach a browder audience.

### Describe the solution you'd like

Release app on google play store

**Comment by Marco-9456** [comment]
This is Impossible, because Google is not allowing apps that download content from YouTube or YouTube Music
