### ISSUE TITLE
[Bug Report] Partial downloads are still on the device

### ISSUE THREAD

**Issue by Donkey-Doug** [JunkFood02/Seal#130]
### Describe the bug

A partial download (one that was cancelled) is still stored on the device. It can be found using a file explorer.

### To Reproduce

1. Download a video
2. Cancel download
3. Use a file explorer and go to storage path
4. There is a partial download

### Device info

Version 1.0.4

**Comment by JunkFood02** [comment]
This is an intended behavior, you can resume your download with this `.part` file. But it would be better if we provide an option to clean up the temp files

**Comment by Donkey-Doug** [comment]
Maybe add auto-delete after 1 week

**Comment by JunkFood02** [comment]
You may test the "clear temp files" feature with the CI artifacts of [the latest commit](https://github.com/JunkFood02/Seal/actions/runs/2985099737)
