### ISSUE TITLE
can't dl any yt vids

### ISSUE THREAD

**Issue by trentwexler** [JunkFood02/Seal#1301]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

every time I try to download a video with a youtube url I receive the same error. it loads the thumbnail just fine, but can't actually download anything.

### To Reproduce

1. copy youtube video url
2. open seal
3. paste url into "video link" field
4. tap download 

### Error reports

App version: 1.11.3 (11132)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.12.30

URL: https://youtu.be/NfuaPwUMOF0
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Screenshots & Screen Records

https://github.com/JunkFood02/Seal/assets/158208079/65f79425-f92c-4bf3-9191-0277f9226194

### Additional context

only seems to be an issue with youtube videos specifically. I tried using cookies and logging in to my yt account to see if that made a difference but it didn't.

Samsung s10+ no root

**Comment by JunkFood02** [comment]
your ip is banned by youtube, nothing much to do on our side, try change your network environment or use a vpn

**Comment by mkstvns** [comment]
> your ip is banned by youtube, nothing much to do on our side, try change your network environment or use a vpn

Holy moly, I must be banned too then. Came to report the same error. Is this common? I'd hardly say I've been overdoing it on the YT downloads...

**Comment by trentwexler** [comment]
yeah I even tried using it behind a vpn routing my connection through
another country entirely and I'm still getting the error. I'm not the most
techy person but I feel like that should be an effective workaround? idk
what else to try lol.
