### ISSUE TITLE
Hide the Keyboard after Download Button pressed.

### ISSUE THREAD

**Issue by bienvenuelisis** [JunkFood02/Seal#132]
**Describe the bug**
When you paste a video link, in the url form field and tap on Download Button, the download bottom sheet appears, but behind the keyboard. So you need to dismiss the keyboard. The behaviour i expect is the keyboard to be dismissed automatically, after the download action started.

**To Reproduce**
Open Seal
Paste a video link in the form field
Tap on download button (do not dismissed the keyboard before this action)
Download bottom sheet appears, but behind the keyboard.

**Device info**
Version 0.0.9-alpha08

**Image**
[https://drive.google.com/file/d/1YQeq1zPNdDdH9i0V8b3ZD6o7NuomxKcL/view?usp=sharing](Image hosted on GoogleDrive)

**Comment by JunkFood02** [comment]
#66
