### ISSUE TITLE
Could not fetch video info to specific video 

### ISSUE THREAD

**Issue by twjohnon** [JunkFood02/Seal#1331]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.11.3 (11132)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.12.30

URL: https://youtube.com/watch?v=0-BKiesiaxE&si=Sa0nytG2J4nEN7fM
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Screenshots & Screen Records

![Screenshot_2024-02-07-00-40-28-85_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/JunkFood02/Seal/assets/154605253/5fc72ac0-8c81-413c-b9c5-e712ecf7ed5d)

**Comment by JunkFood02** [comment]
please refer to #1161
