### ISSUE TITLE
320kbps

### ISSUE THREAD

**Issue by Admincomand** [JunkFood02/Seal#1336]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

It doesn't have 320kbps audio quality 
And 
Multi downloading 

### Describe the solution you'd like

I am asking you to add 320kbps quality for audio
The site I used to use is not working anymore
So can you please upload this 
And 
Multi downloading to

**Comment by JunkFood02** [comment]
#228
