### ISSUE TITLE
Unable to copy or share video title or uploader name from the three-dots menu in the "Downloads" section

### ISSUE THREAD

**Issue by incIined** [JunkFood02/Seal#1338]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When going into the Downloads section of the Seal app, clicking the three dots on the side will give you the video's title, uploader, and YouTube video link. 

Out of the three, only the video link can tapped on to be copied. The title and username can be highlighted, but no "Copy" dialogue/popup shows up.

This means in order to copy the title/uploader name, I have to copy the link from Seal, open a browser in Incognito Mode, paste the link & go, then copy it down from the YouTube mobile site. 

### To Reproduce

1. Click the "Downloads" button at the top right of the main screen (where you enter the URL)
2. Locate a downloaded YouTube video, click the three dots 
3. You can highlight the video title and uploader, but cannot copy the text itself. 
4. Hitting "Share" will only share the downloaded video file itself, not the text you have selected 

### Error reports

N/A

### Screenshots & Screen Records

![Screenshot_20240212-075750_Seal](https://github.com/JunkFood02/Seal/assets/30244311/7849aef1-1170-433a-a9e7-d357047d9676)

![Screenshot_20240212-075754_Seal](https://github.com/JunkFood02/Seal/assets/30244311/1acdf55b-0ea9-4c14-9999-f7e15af9c014)

### Additional context

I swear this feature used to work in past versions, I used to be able to copy from that popup. Not sure what happened to break it.

Thanks.

**Comment by JunkFood02** [comment]
Fixed in v1.12.0-beta.1
