### ISSUE TITLE
[Bug Report] Notification issues

### ISSUE THREAD

**Issue by Donkey-Doug** [JunkFood02/Seal#134]
### Describe the bug

Notifications are not handled correctly. One download causes 60+ notifications. I think every time the progress report updates, a new notification is created.

Also,  there are two groups of notifications. Both are called download. 

### To Reproduce

1. Download anything
2. Go to settings > notifications
3. One download causes many notifications

### Error reports & Screenshots

![Screenshot_20220818-193607_Settings](https://user-images.githubusercontent.com/50382414/185459053-31ec3605-b28e-46f4-bfec-f5b69cdb7498.png)

### Device info

1.0.4

**Comment by JunkFood02** [comment]
This is a compatibility issue, will be fixed in next version

**Comment by JunkFood02** [comment]
Fixed in v1.1.0

**Comment by Donkey-Doug** [comment]
@JunkFood02 Both categories are still called Download. Maybe rename one to Download progress and keep Download for the other.
