### ISSUE TITLE
Limit the cookie expose to matched website

### ISSUE THREAD

**Issue by CanglanXYA** [JunkFood02/Seal#1341]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

If you want to download some video from A website using cookie, but forget to cancel "use cookie" button at B website. Im concerned that it will leak your A web's credentials to B web(can be a malicious pishing website), which is dangerous and a privacy nightmare

### Describe the solution you'd like

Link the cookie to A website, so only when you try to download a video from A website the cookie will be used if it exists. Download from B web wont automatically activate the cookie option if there is no credentials link to B website.

Its will be more convenient to add an "Always use cookie for this site" option button at cookie management page for better automation if you dont always want to use cookie for some sites by default.

### Video link

like twitter (cookie required) and other website

**Comment by JunkFood02** [comment]
> leak your A web's credentials to B web

please refer to https://github.com/yt-dlp/yt-dlp/security/advisories/GHSA-v8mc-9377-rwjj
