### ISSUE TITLE
Better errors

### ISSUE THREAD

**Issue by BlueDude11** [JunkFood02/Seal#1342]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I make a playlist of music on YouTube then I put the link in seal to download it but it would be nicer if I could see which videos were unable to download then redownload that video again

### Describe the solution you'd like

Add a way (maybe in the three dots) to redownload that video in the video history

### Video link

All of them

**Comment by Marco-9456** [comment]
> @Marco-9456 when does 2.0 come out?
> 

In the Near future
