### ISSUE TITLE
acc

### ISSUE THREAD

**Issue by Kevnil04** [JunkFood02/Seal#1347]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

So I try to use acc format but it continues to get stuck at moving it to my selected storage path

### Error reports

No error codes

### Screenshots & Screen Records

![Screenshot_20240220_100701_ReVanced Extended](https://github.com/JunkFood02/Seal/assets/156114208/38d79c0f-e120-42b5-aeed-78ebdb944e49)

**Comment by JunkFood02** [comment]
the file is large and it take time to convert the audio, don't convert audio if unneccesary
