### ISSUE TITLE
[Feature Request] Option to hide the thumbnails in the app when downloading a video

### ISSUE THREAD

**Issue by KazKaz90** [JunkFood02/Seal#135]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Nothing, just want to hide the thumbnails because I download mainly *nsfw* stuff and you know it's risky

### Describe the solution you'd like

Just an option to hide  the thumbnails

### Video link

DoodStream links

**Comment by BobbyESP** [comment]
With this what you mean? yt-dlp has the option to dont write the thumbail in the video

**Comment by KazKaz90** [comment]
> With this what you mean? yt-dlp has the option to dont write the thumbail in the video

Nah, that's not what I'm talking about, I'm talking about the thumbnails in the app, it's showing when you download a video, also I said "hide" not "remove".

**Comment by JunkFood02** [comment]
Added in v1.3.3
