### ISSUE TITLE
Include Support for WAV conversion.

### ISSUE THREAD

**Issue by 1982FenceHopper** [JunkFood02/Seal#1353]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Usually I download MP3 audio, but recently, I've been noticing sound audio degradation, particularly due to the audio file being moved around a lot. So I wanted to download WAV only but saw that no convert to WAV option was available.

### Describe the solution you'd like

Within the audio settings, add extra option for converting to WAV.

**Comment by JunkFood02** [comment]
#228
