### ISSUE TITLE
Support Translation for Subtitle

### ISSUE THREAD

**Issue by 1YuvrajS** [JunkFood02/Seal#1371]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

1. If we download YT Videos from Korean Auto Generated or French Subtitle, it should be translated to another language like English etc.

2. When I downloaded YT Video with Suggested Subtitle and One Automatic Captions in English, I will not see English Subtitle and but seeing orignal Korean Subtitle in MX Player.

3. Use Translation to get proper Subtitles in English.

4. Using YT Translate Subtitle, but it doesn't do well.

**Comment by JunkFood02** [comment]
video link?

**Comment by 1YuvrajS** [comment]
> video link?

Here you go:-

https://youtu.be/ZXRGOJQEow8?si=JA1ZuKCJpaLjgITu

**Comment by JunkFood02** [comment]
Update to v1.12.0-beta.1, go to settings - format - subtitle, and enable auto-translated subtitles
