### ISSUE TITLE
download cc / subtitles / trascript

### ISSUE THREAD

**Issue by gabrielparca** [JunkFood02/Seal#1373]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

The possibility of downloading subtitles.

### Additional context

I am used to this from HandBreak.

**Comment by JunkFood02** [comment]
why asking for a feature we've already had
