### ISSUE TITLE
Malfunction on quality

### ISSUE THREAD

**Issue by Tranups** [JunkFood02/Seal#1375]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I've been using Seal for downloading tiktoks on the best quality possibly (usually 1080p). But a few days ago it didn't download a tiktok and after that problem it started to download the tiktok videos on a lower quality despite having the 1080p mark checked on the specifications, including that it doesn't erase the tiktok watermark. I re installed the app but it didn't do anything. 

### To Reproduce

I just use the button thats on "Share", then "More", select "Seal" and "Quick Download" (i don't know if its says specifically "Quick Download" since i use the app on Spanish). All of this on tiktok.

### Error reports

I don't have the text since i tried to uninstall and re install the app. 

### Screenshots & Screen Records

![Screenshot_20240314_171125_VLC](https://github.com/JunkFood02/Seal/assets/163463890/6fc4e902-3d02-4a0f-804b-abf800ccd420)

That's before the problem (a few days ago).

![Screenshot_20240314_171132_VLC](https://github.com/JunkFood02/Seal/assets/163463890/86ff074a-b52a-46d8-98b0-10c5151f56a5)

And this is from today, after the problem.

### Additional context

nothing more, thanks!

**Comment by JunkFood02** [comment]
#1376
