### ISSUE TITLE
Automatic Captions Bug

### ISSUE THREAD

**Issue by 1YuvrajS** [JunkFood02/Seal#1377]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

1. There is a bug in Automatic Caption Section in Subtitle dialogue. 

2. I downloaded version beta release 1.12.0 beta-1.

3. I enabled Auto Translation in setting.

4. When I want to any video then I have to deselect all Automatic Captions. (Screenshot Uploaded)

5. When I ignore automatically selected app Automatic Captions it will give download error. 

### Error reports

Nil

### Screenshots & Screen Records

![Screenshot_2024-03-15-14-11-26-274_com junkfood seal](https://github.com/JunkFood02/Seal/assets/93419850/f81686bb-c053-4dfa-afc2-5816f179ae15)

**Comment by 1YuvrajS** [comment]
> what error?
@JunkFood02 

**subtitles for 'km-en': HTTP Error 429: Too Many Requests**.

7. I have to deselect in every download in given Screenshot.

**Comment by JunkFood02** [comment]
just don't download too many subtitles i guess?
