### ISSUE TITLE
Instagram download error

### ISSUE THREAD

**Issue by LegendCriminal** [JunkFood02/Seal#1380]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [x] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

10% download done and 90% download failed
Its look like first download from Instagram going successfully but then any download just show error message

### Error reports

App version: 1.11.3 (11131)
Device information: Android 10 (API 29)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://www.instagram.com/reel/C4dIBAGNOV2/?igsh=YXo2MnZkYjNqc3Nv
WARNING: [Instagram] C4dIBAGNOV2: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C4dIBAGNOV2: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials

### Screenshots & Screen Records

![Screenshot_20240316_084722_com junkfood seal](https://github.com/JunkFood02/Seal/assets/95860642/66cd21fe-8204-4df9-9ee6-1c6e625b7fc1)

### Additional context

It just happened with Instagram for me

**Comment by JunkFood02** [comment]
#733
