### ISSUE TITLE
Outrageous storage consumption 

### ISSUE THREAD

**Issue by xandro0777** [JunkFood02/Seal#1382]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hi, didn't use it for a couple of months, removed all videos from the internal list and App info shows like 3.5GB storage use. 

Suspect that some downloaded or intermediate files got stuck in internal memory?

Downloads go to /SD card and should not contribute to this?

### To Reproduce

Have used various versions over 2 years and downloaded videos from various places 

### Error reports

Does not display any errors.

**Comment by JunkFood02** [comment]
> intermediate files got stuck in internal memory?

Probably this, if you have never cleared your temporary files and haven't updated for several versions.

Settings - Download directory - Clear temporary files might help

**Comment by xandro0777** [comment]
Wow.. said deleting 20 temporary files and storage usage went down to 134MB (from 3.5GB).

I use F-Droid and always update when there is a new version.

Those temporary files must have been there many months. Should not they be in cached files? Could not the user be warned upon invocation if there are many months old temporary files? After a while they are pretty useless unless the user can somehow get context information about those files.. I don't know what files that might have been and not the slightest idea how to restart the downloads either.

**Comment by JunkFood02** [comment]
Temporary files are primarily used for resume an interrupted download, but sometimes users might need them if they are downloading a video livestream or an endless radio program.

The cache directory was not used for a reason. In a recent update, we moved the temporary directory to external storage from internal storage for immediate files.Now the temporary directory is accessible through file managers in external storage, addressing this issue.

Alerting users about obsolete temporary files makes sense, will do take it into consideration 🤞
