### ISSUE TITLE
Lỗi

### ISSUE THREAD

**Issue by Duccutoh** [JunkFood02/Seal#1383]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Lỗi không tải được video full hd và xoá logo của tiktok

### To Reproduce

Lỗi

### Error reports

Lỗi

### Screenshots & Screen Records

![Screenshot_2024-03-15-19-31-49-569_com junkfood seal](https://github.com/JunkFood02/Seal/assets/163671249/1223cdb8-d619-4de9-befc-354b9e5f34ec)

### Additional context

Lỗi

**Comment by JunkFood02** [comment]
#1376
