### ISSUE TITLE
Connect to PC via SSH

### ISSUE THREAD

**Issue by airisama019** [JunkFood02/Seal#1385]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Download on phone becomes slow if the screen is off and battery drain is tough

### Describe the solution you'd like

Connect to PC via SSH and download there

**Comment by JunkFood02** [comment]
if you know ssh why not using yt-dlp on your pc?

**Comment by airisama019** [comment]
> if you know ssh why not using yt-dlp on your pc?

?? yeah but an automated solution would be nice
