### ISSUE TITLE
A specific video won't download in best quality.

### ISSUE THREAD

**Issue by AtlantisTheLostEmpire** [JunkFood02/Seal#1389]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

A specific 1080p YouTube video won't download in said quality, even when the Seal download settings are set to "best quality", or if changed to 1080p.

No other video had done this before, and I've downloaded dozens in various different qualities (mostly 1080p or above), and from different websites. My settings have always been set to "best quality".

### To Reproduce

1. Download this 1080p video: https://youtu.be/K40ZFeiA9a4
2. Look at the video's file details and you'll see it's a 360p video.

### Error reports

None.

**Comment by JunkFood02** [comment]
Use Custom format selection
