### ISSUE TITLE
Removing Watermarks

### ISSUE THREAD

**Issue by Jeddyoba** [JunkFood02/Seal#1391]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

This feature is regarding removing Watermarks from tiktok videos. I noticed the all has recently starred downloading tiktok videos with the watermark 

### Describe the solution you'd like

I'd like for it to be fixed 
Or an option should be created to allow users be able to download tiktok videos with the watermark or without the watermark.

**Comment by Jeddyoba** [comment]
I'd like a swift response to this
Thanks so much

**Comment by JunkFood02** [comment]
#1376
