### ISSUE TITLE
ظهور علامة مائية 

### ISSUE THREAD

**Issue by 5alidion** [JunkFood02/Seal#1393]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

عند التحميل من تيك توك يظهر بعد التحميل الفيديو علامة مائية بأسم المستخدم ارجوا حل المشكلة
When downloading from TikTok, a watermark appears after downloading the video with the user name. Please solve the problem

### Error reports

When downloading from TikTok, a watermark appears after downloading the video with the user name. Please solve the problem

### Screenshots & Screen Records

![Screenshot_٢٠٢٤٠٣١٩_٠٤٠٣٣٢](https://github.com/JunkFood02/Seal/assets/163946585/0a8e6744-c863-4098-953b-81faef7214f6)

**Comment by JunkFood02** [comment]
#1376
