### ISSUE TITLE
I can't download any video from any platform

### ISSUE THREAD

**Issue by LUIGIXV07** [JunkFood02/Seal#1397]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I try to dowload any video it gives an error.

### To Reproduce

Just copy any link from any platform for exemple YouTube or TikTok, put into the box "video link" and try to download the video.
Spoiler it can't for me.

### Error reports

App version: 1.11.3 (11131)
Device information: Android 14 (API 34)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://vm.tiktok.com/ZGePcYQV2/
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
WARNING: [TikTok] 7347483291743702305: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
ERROR: [TikTok] 7347483291743702305: Video not available, status code 0; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20240321_082035_Seal](https://github.com/JunkFood02/Seal/assets/164315036/16494fea-d6e8-4440-b17b-fced11cec473)

### Additional context

It is strange that I can olny download the oudio from the video but not the video itself.

**Comment by JunkFood02** [comment]
#1376
