### ISSUE TITLE
Removing Watermarks 

### ISSUE THREAD

**Issue by Jeddyoba** [JunkFood02/Seal#1398]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

After updating yt-dlp nightly downloading tiktok videos without watermarks worked for a while. Few days later it reverted back and has continued to download tiktok videos with the watermark. 

Please this issue should be fixed

**Comment by harrysof** [comment]
Im having the same problem when downloading tiktok videos

**Comment by JunkFood02** [comment]
#1376

**Comment by Jeddyoba** [comment]
It's still haven't the same issue even after updating yt-dlp nightly which I specifically included in the complaint I made earlier.
Please find a way to resolve this issue as quickly as possible.
