### ISSUE TITLE
watermarks

### ISSUE THREAD

**Issue by Samm246** [JunkFood02/Seal#1405]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Unfortunately, there were still watermarks on the videos i download from tiktok. I don't know why it just stopped doing its thing but it's starting to annoy me because some of the people's username do actually cover the words from the video.

I don't know how to fix this because i really want to keep downloading videos without any watermarks included since i really like it when there's no watermarks being in the way

### Describe the solution you'd like

i would love to receive a solution, any if possible.. but if you want a specific solution, i would prefer giving me step by steo on how to fix my problem of not being able to get rid of watermarks in tiktok videos. (e.g, 1. Go to settings
                      2. Go to account)

 or if can't, you could try doing your thing on how to fix this problem because obviously i don't know hoe the app can be fixed at all.

### Video link

https://github.com/JunkFood02/Seal/assets/164641300/3993137f-cd62-4d66-ab85-cf7f0b3972e8

just example, this video.. the username is covering the texts from the video and sometimes it could be challenging trying to read some words that were covered by the watermarks..

### Additional context

It all happened suddenly, it has been happening for probably few weeks now (3-4 weeks). I found out that it stopped removing the usernames once i watched the video i downloaded and was slightly confused and disappointed because i really love this app and helping me.

i hope you guys can hell and fix this problem, thank you very much.

**Comment by ducanh141** [comment]
I have the same error as you, did you fix it?

**Comment by JunkFood02** [comment]
#1376
