### ISSUE TITLE
Tiktok problem

### ISSUE THREAD

**Issue by BruhLove** [JunkFood02/Seal#1406]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Whenever I try to download a video from TikTok, it gives an error.

### To Reproduce

1. share on tiktok
2. seal fast download
3. press download
4. starting to download
5. and it gives an error

### Error reports

App version: 1.11.1-(F-Droid) (11114)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://vm.tiktok.com/ZMMD9VxQr/
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
WARNING: [TikTok] 7349616375717121286: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Screenshots & Screen Records

![Screenshot_20240323-222454_Seal](https://github.com/JunkFood02/Seal/assets/91030199/72a06332-0365-4148-91fd-af9f0479d95c)

**Comment by JunkFood02** [comment]
#1376
