### ISSUE TITLE
Seal - Could not fetch video info

### ISSUE THREAD

**Issue by OtterX** [JunkFood02/Seal#1414]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Sometimes, which has been happening quite a lot lately, Seal can't fetch the video info from a TT Video because, yt-dlp expects valid json data but receives an empty string.

### To Reproduce

I'm just gonna use this video for the example,
https://vm.tiktok.com/ZGe5q5NQW/
Clicking on share > ... > ~more~ > Seal

### Error reports

WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 1 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 2 of 4)
WARNING: [TikTok] Expecting value in '': line 1 column 1 (char 0). Retrying... (attempt 3 of 4)
WARNING: [TikTok] 7324367492191685921: Failed to parse JSON (caused by JSONDecodeError("Expecting value in '': line 1 column 1 (char 0)")); trying with webpage
ERROR: Unable to download video: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Screenshots & Screen Records

[Bug Report Video](https://youtube.com/shorts/Jph1-eQ5AzI?si=fzY8Lz71sJR7PQq4)

### Additional context

I hope this Issue can be fixed quickly, thanks!

**Comment by JunkFood02** [comment]
#1376
