### ISSUE TITLE
Error 02

### ISSUE THREAD

**Issue by Shivamisback** [JunkFood02/Seal#1417]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Error 02

### To Reproduce

App version: 1.11.3 (11132)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://youtu.be/7l5UgtWfnw0?si=5vIW8p9pmllwvq-M
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Error reports

App version: 1.11.3 (11132)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://youtu.be/7l5UgtWfnw0?si=5vIW8p9pmllwvq-M
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Screenshots & Screen Records

App version: 1.11.3 (11132)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://youtu.be/7l5UgtWfnw0?si=5vIW8p9pmllwvq-M
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Additional context

App version: 1.11.3 (11132)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.03.10

URL: https://youtu.be/7l5UgtWfnw0?si=5vIW8p9pmllwvq-M
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

**Comment by JunkFood02** [comment]
#1161

**Comment by GfEW** [comment]
@JunkFood02 
Given that #1161 is still open, did you close this as _completed_ by mistake, or are there any news to "Errno 2" that I've missed? 

On another note, I tend to think the 2 s per issue to reliably label clear-cut duplicates as _duplicate_ might actually pay off, as it makes bug reporters' preliminary `is:issue -label:duplicate foo bar` check for existing issues much more efficient, and thereby helps them to minimize duplicates and focus more on proper bug reporting.
