### ISSUE TITLE
Water mark

### ISSUE THREAD

**Issue by Wert64** [JunkFood02/Seal#1419]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Hello, I have noticed that when I download a video on Tiktok it appears with the watermark when it was not like that before, I would like to know if it is an update or some configuration is needed so that it does not appear, thanks for reading, I look forward to your response

**Comment by JunkFood02** [comment]
#1376
