### ISSUE TITLE
Request to redistribute apk files for Armeabi-v7a in F-Droid Repository.

### ISSUE THREAD

**Issue by itsmeralph09** [JunkFood02/Seal#142]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Additional context

Request to redistribute apk files for Armeabi-v7a in F-Droid Repository. Please do consider, thank you.

**Comment by JunkFood02** [comment]
Currently, we cannot enable auto-update if we publish multiple apks on F-Droid (see #41). I'll recommend devices only support armeabi-v7a arch to switch to the GitHub version. Also, please paste your output in About - Version here.

**Comment by itsmeralph09** [comment]
Ohh, okay Sir. I get it now why the apk support for Armeabi-v7a in the F-droid repo is dropped. Btw, I already downloaded the latest release version for arm-v7a in the GitHub repo releases section. Thank you so much.
