### ISSUE TITLE
Not able to change download directory to SD card

### ISSUE THREAD

**Issue by AadityaGeek** [JunkFood02/Seal#1420]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I want to check the download directory location from internal storage to SD card but it shows error "This directory is not supported". I tried this in different folders but the error is same
![Screenshot_2024-03-29-10-21-05-678_com junkfood seal](https://github.com/JunkFood02/Seal/assets/127582609/36b1c68b-6832-4d95-825f-f2584af33cda)

### To Reproduce

Go to settings
Go to download directory
Go to video/audio folder
Select the folder where I want to store the downloaded files
Allow seal to access files in that folder
Got the erroe

### Error reports

Don't know how to do this

**Comment by JunkFood02** [comment]
Not a bug, intended
