### ISSUE TITLE
 weird issue when using TalkBack

### ISSUE THREAD

**Issue by aryanchoudharypro** [JunkFood02/Seal#1425]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

So when using TalkBack and toggling any cheque box in the settings it doesn't pronounce the state of the checkbox correctly

### To Reproduce

1. Go to settings 2. And try tougling any checkbox with TalkBack turned on

### Error reports

No error reports

**Comment by JunkFood02** [comment]
Please rollback to [v1.12.0-beta.1](https://github.com/JunkFood02/Seal/releases/tag/v1.12.0-beta.1) or previous stavle versions for a temporary workaround

**Comment by JunkFood02** [comment]
please install this ci artifact https://github.com/JunkFood02/Seal/actions/runs/8506587567 and see if this get resolved

**Comment by aryanchoudharypro** [comment]
Hello. Thanks for the APK you provided it works great now 😉

**Comment by aryanchoudharypro** [comment]
clozing this as this has been fixed a long while ago
