### ISSUE TITLE
F-Droid version is behind the GitHub release

### ISSUE THREAD

**Issue by mmahdium** [JunkFood02/Seal#1429]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The F-Droid version is always behind yhe latest release from GitHub

### Describe the solution you'd like

Update F-Droid version more frequently

**Comment by Marco-9456** [comment]
That is a known issue that was caused by a commit on the f-droid repo.

For now, switch to the GitHub releases and go to Settings --> About --> Auto Update --> Select an update channel and Enable auto-update.
If you do this you'll get the latest releases moments after they are published here

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14808

**Comment by linsui** [comment]
@JunkFood02 https://gitlab.com/fdroid/fdroiddata/-/jobs/6547769215 Any idea why the version code is not set correctly? It seems the baseAbiCode is always 2.

**Comment by linsui** [comment]
@JunkFood02 It seems the `abiCodes[name]` is null somehow... https://gitlab.com/linsui/fdroiddata/-/jobs/6559145090

**Comment by JunkFood02** [comment]
@linsui Please try with [this commit](https://github.com/JunkFood02/Seal/commit/e016faab64c10f5a2498cd2b7c19b58871eccf96)

**Comment by linsui** [comment]
It works, thanks!
