### ISSUE TITLE
[Feature Request]Add download info on main screen

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#143]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

While downloading video, it'll be very handy to be able to see the following info on the main screen:
total downloading size, left downloading size, speed, ETA.

I think all this info could be placed above video thumbnail.

### Additional context

I'm aware, that I can see all this info in the notification, but I still would like to see it on the main screen.

**Comment by JunkFood02** [comment]
Settings - Download - Enable "Detailed output"
