### ISSUE TITLE
Watermark present after downloading TikTok Video + Downloaded Video doesn't appear in Seal App

### ISSUE THREAD

**Issue by OtterX** [JunkFood02/Seal#1434]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When downloading a video from TikTok, It doesn't remove the Watermark anymore like it used to as well as not showing up in Seal when it downloaded successfully.

I tested this on the latest version of Seal, 
App version: 1.12.0 (11202)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.04.232729

### To Reproduce

1. SHARE
2. MORE
3. SEAL
4. DOWNLOAD VIDEO

### Error reports

There is no error code but I am able to provide a video showing that the Watermark appears after downloading a TT Video.

### Screenshots & Screen Records

[VIDEO](https://youtube.com/shorts/ipdYsgX_gq8)

**Comment by JunkFood02** [comment]
Update yt-dlp to nightly build

**Comment by OtterX** [comment]
> Update yt-dlp to nightly build

It has been set to nightly build from the start.
![Screenshot_20240406_144608_Seal](https://github.com/JunkFood02/Seal/assets/81021615/a0668253-fdee-43b2-a74d-bbfcc06659b1)
