### ISSUE TITLE
Download options menu opens above the navigation bar

### ISSUE THREAD

**Issue by Ehab-d** [JunkFood02/Seal#1435]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When using gestures instead of navigation bar in Android, the download options menu opens over the navigation bar area even though it is not there.

### To Reproduce

1. Enable swipe gestures in Android settings
2. Note the area of the download options menu

*Android 10 x OPPO A15

### Error reports

I'm not a developer.

### Screenshots & Screen Records

![Screenshot_2024-04-06-16-34-07-31](https://github.com/JunkFood02/Seal/assets/129071698/6f34a46d-f1fa-439b-98fa-883f71bdcb0f)

### Additional context

The issue did not exist in a previous version of Seal.

**Comment by Ehab-d** [comment]
Now fixed in 1.12.1 … Why you didn't close the issue yet?

**Comment by JunkFood02** [comment]
thanks for bringing this up i just constantly forgot closing issues
