### ISSUE TITLE
convert downloaded webm to mp4

### ISSUE THREAD

**Issue by aigc-anime** [JunkFood02/Seal#1440]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I have some webm video and i would like to share them with someone who can only plan h264

### Describe the solution you'd like

Add an option to convert downloaded webm to mp4 using ffmpeg on the phone.

**Comment by JunkFood02** [comment]
Currently this is blocked by upstream issue which requires an update of ffmpeg, but you can download the h264 videos by setting the format preference to legacy for now

**Comment by NewNewPipe** [comment]
There is also a problem as of late with the latest version of Seal 1.12.0 also downloading comments.
