### ISSUE TITLE
Sponsorblock removed segments causes major desync

### ISSUE THREAD

**Issue by NightshadeGS** [JunkFood02/Seal#1444]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Most videos I download that have sponsor segments get massive desync between audio and video only after the spot where the removed segment would be.

Example video:

https://m.youtube.com/watch?v=7rMdwqissE0

Every attempt of downloading this one with sponsorblock set to remove just sponsors causes desync. I just tested it several times with the same results.

### To Reproduce

1. Enable sponsorblock
2. Set segment to remove to only sponsors
3. Download a video that has a sponsor segment
4. Try playing back video and see desync

### Error reports

No error report.

### Additional context

Just updated Seal a few minutes ago and made sure ytdlp version is latest. Using app on a Samsung J7 Crown running Android 9. Primarily downloading the combined 720 30fps option at the bottom of the pre-download quality/format selection menu. But same problem happens on "best" option recommended at the top of the menu. No desync if simply downloading the video at any quality without sponsorblock. Only having desync when using sponsorblock.

**Comment by JunkFood02** [comment]
expected behavior when editing videos without recoding
