### ISSUE TITLE
Issues about downloading videos from iq.com

### ISSUE THREAD

**Issue by error-reporting** [JunkFood02/Seal#1448]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

a reproduceable download error in https://www.iq.com/

### To Reproduce

step to reproduce 1 :come to https://www.iq.com/
2 : copy a iq video link in the page
3 : enter the copied video link into seal click the download icon then choose any download options
4 error PhantomJS not found

### Error reports

App version: 1.12.0 (11202)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.09.232723

URL:  https://www.iq.com/play/1o8m1pwt3pw?lang=vi_vn&sh_pltf=4
ERROR: [iq.com] 1o8m1pwt3pw: PhantomJS not found, Please download it from https://phantomjs.org/download.html

### Screenshots & Screen Records

Uploading Record_2024-04-13-13-26-09_2b0c70832456616f1f794bb05bb8d2fa.mp4…

### Additional context

I'm using android 10 i canot install PhantomJS
because PhantomJS require x86 Architecture while i was using Arm Architecture

**Comment by error-reporting** [comment]
i don't know why it says PhantomJS not found
while PhantomJS it is only installable on x86 devices

**Comment by error-reporting** [comment]
why no one response to my issue

**Comment by JunkFood02** [comment]
You can't use PhantomJS on Android, use yt-dlp on a PC if you want to download from this site
