### ISSUE TITLE
Could not download video from crunchyroll because of clip video feature

### ISSUE THREAD

**Issue by Khushxx** [JunkFood02/Seal#1457]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I am facing downloading problem in seal when I try to download crunchyroll app video especially when i use clip video feature the clip video does not download however if i download full video there is not any error in download

### Error reports

App version: 1.12.0 (11202)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.09

URL: https://www.crunchyroll.com/watch/GN7UD7EDK?utm_medium=android&utm_source=share
[debug] Command-line config: ['--no-mtime', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '--add-header', 'User-Agent:Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Pro Build/QKQ1.190915.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36', '-4', '-v', '--no-playlist', '--downloader', 'libaria2c.so', '--external-downloader-args', 'aria2c:"--summary-interval=1"', '--add-metadata', '--no-embed-info-json', '-S', 'vcodec:vp9.2', '--remux-video', 'mkv', '--merge-output-format', 'mkv', '-P', '/storage/emulated/0/Seal/Video ', '-P', 'temp:/storage/emulated/0/Download/Seal/tmp', '--download-sections', '*756-845', '-o', '%(title).200B [%(section_start)d-%(section_end)d].%(ext)s', '--no-cache-dir', '--ffmpeg-location', '/data/app/com.junkfood.seal-ydYP7LdAM21seGMAHiLUuw==/lib/arm64/libffmpeg.so', 'https://www.crunchyroll.com/watch/GN7UD7EDK?utm_medium=android&utm_source=share']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version stable@2024.04.09 from yt-dlp/yt-dlp [ff0779267] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-4.14.117-perf-g02abc55-aarch64-with-libc (OpenSSL 1.1.1t  7 Feb 2023, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: Cryptodome-3.17, mutagen-1.46.0, sqlite3-3.30.1
[debug] Proxy map: {}
[debug] Request Handlers: urllib
[debug] Loaded 1810 extractors
[debug] [crunchyroll] Using cxApiParam=cr_web
[debug] Sort order given by user: vcodec:vp9.2
[debug] Formats sorted by: hasvid, ie_pref, vcodec:vp9.2(10), lang, quality, res, fps, hdr:12(7), channels, acodec, size, br, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking ffmpeg downloader on "https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GN7UD7EDK/evs3/e0fc1f78f6304c8080c6d89eaffe32cb/assets/p/bea76c8f608b119ce42a6bf60f1ef63f_,4293816.mp4,4293817.mp4,4293815.mp4,4293813.mp4,4293814.mp4,470.txt,.urlset/manifest.mpd?playbackGuid=05-830bb5b0-5e0c-4f25-98a0-505036419766&accountid=fca766a7-d8a9-45b1-9a5c-9602dfa45df5", "https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GN7UD7EDK/evs3/e0fc1f78f6304c8080c6d89eaffe32cb/assets/p/bea76c8f608b119ce42a6bf60f1ef63f_,4293816.mp4,4293817.mp4,4293815.mp4,4293813.mp4,4293814.mp4,470.txt,.urlset/manifest.mpd?playbackGuid=05-830bb5b0-5e0c-4f25-98a0-505036419766&accountid=fca766a7-d8a9-45b1-9a5c-9602dfa45df5"
[debug] libffmpeg.so command line: /data/app/com.junkfood.seal-ydYP7LdAM21seGMAHiLUuw==/lib/arm64/libffmpeg.so -y -loglevel verbose -headers 'User-Agent: Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Pro Build/QKQ1.190915.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 756.0 -t 89.0 -i 'https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GN7UD7EDK/evs3/e0fc1f78f6304c8080c6d89eaffe32cb/assets/p/bea76c8f608b119ce42a6bf60f1ef63f_,4293816.mp4,4293817.mp4,4293815.mp4,4293813.mp4,4293814.mp4,470.txt,.urlset/manifest.mpd?playbackGuid=05-830bb5b0-5e0c-4f25-98a0-505036419766&accountid=fca766a7-d8a9-45b1-9a5c-9602dfa45df5' -headers 'User-Agent: Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Pro Build/QKQ1.190915.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us,en;q=0.5
Sec-Fetch-Mode: navigate
' -ss 756.0 -t 89.0 -i 'https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GN7UD7EDK/evs3/e0fc1f78f6304c8080c6d89eaffe32cb/assets/p/bea76c8f608b119ce42a6bf60f1ef63f_,4293816.mp4,4293817.mp4,4293815.mp4,4293813.mp4,4293814.mp4,470.txt,.urlset/manifest.mpd?playbackGuid=05-830bb5b0-5e0c-4f25-98a0-505036419766&accountid=fca766a7-d8a9-45b1-9a5c-9602dfa45df5' -c copy -map 0:1 -map 1:5 -f matroska 'file:/storage/emulated/0/Download/Seal/tmp/Fire Force (English Dub) Episode 1 – Shinra Kusakabe Enlists [756-845].mkv.part'
ffmpeg version 5.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with Android (8490178, based on r450784d) clang version 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)
  configuration: --prefix=/home/runner/work/build-ffmpeg/build-ffmpeg/build/ffmpeg/arm64-v8a --enable-cross-compile --target-os=android --arch=aarch64 --sysroot=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot --cc=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --cxx=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ --ld=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --ar=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar --as=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang --nm=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm --ranlib=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib --strip=/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --extra-cflags='-O3 -fPIC -I/home/runner/work/build-ffmpeg/build-ffmpeg/build/external/arm64-v8a/include' --extra-ldflags='-L/home/runner/work/build-ffmpeg/build-ffmpeg/build/external/arm64-v8a/lib -lm -lm -lm -lm -lz' --enable-shared --disable-static --disable-vulkan --pkg-config=/usr/bin/pkg-config --enable-protocol=https --enable-version3 --enable-gpl --enable-libaom --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-libtwolame --enable-libspeex --enable-libvpx --enable-libwebp --enable-libfreetype --enable-libfribidi --enable-mbedtls --enable-libbluray --enable-libx264
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
[tcp @ 0x7a45e530a0] Starting connection attempt to 52.221.134.233 port 443
[tcp @ 0x7a45e530a0] Successfully connected to 52.221.134.233 port 443
https://cr-play-service.prd.crunchyrollsvc.com/v1/manifest/GN7UD7EDK/evs3/e0fc1f78f6304c8080c6d89eaffe32cb/assets/p/bea76c8f608b119ce42a6bf60f1ef63f_,4293816.mp4,4293817.mp4,4293815.mp4,4293813.mp4,4293814.mp4,470.txt,.urlset/manifest.mpd?playbackGuid=05-830bb5b0-5e0c-4f25-98a0-505036419766&accountid=fca766a7-d8a9-45b1-9a5c-9602dfa45df5: Server returned 401 Unauthorized (authorization failed)

ERROR: ffmpeg exited with code 1
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
    yt_dlp.main()
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1072, in main
    _exit(*variadic(_real_main(argv)))
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 1062, in _real_main
    return ydl.download(all_urls)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3572, in download
    self.__download_wrapper(self.extract_info)(
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3547, in wrapper
    res = func(*args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 2982, in process_video_result
    self.process_info(new_info)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3395, in process_info
    success, real_download = self.dl(temp_filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3169, in dl
    return fd.download(name, new_info, subtitle)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/downloader/external.py", line 80, in real_download
    self.report_error('%s exited with code %d' % (
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1073, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1001, in trouble
    tb_data = traceback.format_list(traceback.extract_stack())

### Screenshots & Screen Records

![Screenshot_2024-04-17-11-08-16-282_com junkfood seal](https://github.com/JunkFood02/Seal/assets/139647014/79c20753-2e5d-4b99-bf32-20e4ae9476a4)

**Comment by JunkFood02** [comment]
FFmpeg doesn't support downloading from CR
