### ISSUE TITLE
Sorry, I have a question 

### ISSUE THREAD

**Issue by Woodzilla** [JunkFood02/Seal#1458]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I would like to know, if it's possible quit the TikTok mark on the downloads.
Sorry for the inconvenience... And thanks for this wonderful app. ❤️

### Error reports

This isn't an error.

### Additional context

Sorry for use this medium to do my question.

**Comment by slorard** [comment]
I also want to remove the mark and download the videos with higher quality, I get the impression that it doesn't download at maximum quality, since when I upload it to WhatsApp it looks very bad and that doesn't happen to me with other videos
