### ISSUE TITLE
[Feature Request] Clear Downloads

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#146]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Please add a button 'Clear all' or 'Clear list' on Downloads page.

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/83#issue-1323463957 duplicated

**Comment by Botan626** [comment]
> [#83 (comment)](https://github.com/JunkFood02/Seal/issues/83#issue-1323463957) duplicated

I don't see a request for 'clear the whole list' button there.

**Comment by JunkFood02** [comment]
Added in v1.2.0-beta.2

**Comment by Botan626** [comment]
There is no 'Clear all' button in v1.2.0-beta.2

**Comment by Botan626** [comment]
Unclickable for me.
6.5" screen, 1600 x 720 res

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/186847776-01363e85-9272-4a56-8714-ec77defc2856.png)

</details>

**Comment by JunkFood02** [comment]
> Unclickable for me. 6.5" screen, 1600 x 720 res
> 
> Screenshot

Yeah this is a specific bug occurs in 3-Buttons Navigation, will get fixed soon
