### ISSUE TITLE
error when downloading video on youtube

### ISSUE THREAD

**Issue by lebgdu543** [JunkFood02/Seal#1462]
# **not important**

### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [ ] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [ ] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

What is this message?

### To Reproduce

Install this playlist: https://www.youtube.com/watch?v=fbKgZBYcHn0

### Error reports

App version: 1.12.0-(F-Droid) (11202)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.13.232802

URL: https://www.youtube.com/watch?v=fbKgZBYcHn0
The video has been downloaded. If this is not the expected behavior, please check your download archive.

**Comment by Marco-9456** [comment]
Not a bug, you have the `Download archive` option on, it's an option that records every video/audio ID to prevent duplicated downloads, turn the option from the `General settings` off if you want to download the video again or tab on the option and look for the video/audio id in the list and delete it.

**Comment by lebgdu543** [comment]
Thank you for your explication and for your attention. <3
