### ISSUE TITLE
Youtube Playlist Autonumbering Option 

### ISSUE THREAD

**Issue by TheNamelessMan** [JunkFood02/Seal#1471]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Some videoplayers detect videos in folders as a playlist but do not have option for list folders by creation date. Sets default option as list by name.

And I dont really know how to use yt dlp custom command(I dont know if I can solve this issue using custom commands either).

I tried to use the autonumber command but couldnt make it work.

### Describe the solution you'd like

An option for adding list number IN FRONT (or an option if in front or after) of the names of the videos.

### Additional context

Sorry for bad english

**Comment by JunkFood02** [comment]
You can use a custom [output template](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template) (Settings - Download directory - Output template) for this, just add `%(playlist_index&{} - |)s` before the built-in template
