### ISSUE TITLE
Can't download specific videos from YouTube 

### ISSUE THREAD

**Issue by kelvitz716** [JunkFood02/Seal#1472]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

There's specific videos that won't download from certain creators. I have downloaded from another creator, but this creator I have found 3 videos I can't download.

### Error reports

App version: 1.12.1 (11212)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.21.232710

URL: https://youtube.com/watch?v=SrGENEXocJU
ERROR: [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

### Screenshots & Screen Records

![Screenshot_20240422-080447](https://github.com/JunkFood02/Seal/assets/47320787/bf85b287-26e5-4b61-8638-ba7460692529)

**Comment by Richard38907** [comment]
It is strange, your URL works fine on my phone🤔. Seal says download finished.

**Comment by kelvitz716** [comment]
It's working now for me too. Weird.
