### ISSUE TITLE
Custom format selection when using a command

### ISSUE THREAD

**Issue by JailSeed** [JunkFood02/Seal#1478]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Now in order to download videos from TikTok without watermark we need to use our `IID` as a parameter for the extractor, example:
`--extractor-args 'tiktok:api_hostname=api16-normal-c-useast1a.tiktokv.com;app_info=MY_IID'`
But if we choose the download type "commands", we cannot select the format selection as "custom", i.e. the format selection window does not appear before downloading

### Describe the solution you'd like

Several solutions come to my mind:
1) Add to the settings the ability to specify parameters for extractors
2) Add to the "configure before download" window the ability to specify parameters for extractors (only allow --extractor-args, ignore other commands) when choosing "video"/"audio" download type
3) Add to the "configure before download" window the ability to choose "custom" format selection If the -f flag is not present in the command template

**Comment by JunkFood02** [comment]
> But if we choose the download type "commands", we cannot select the format selection as "custom", i.e. the format selection window does not appear before downloading

Is the format you want to select has a static format code for it? If so, you can use `-f "code"` to specify it explicitly

> Add to the "configure before download" window the ability to specify parameters for extractors (only allow --extractor-args, ignore other commands) when choosing "video"/"audio" download type

Noted.
