### ISSUE TITLE
[Feature Request] aria2c and multi-threaded downloads 

### ISSUE THREAD

**Issue by adithya-s-sekhar** [JunkFood02/Seal#148]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Some sites throttle downloads from them if you use a single connection, YouTube does it randomly with some videos at random times. 

The only consistent example I can find is an adult website. Multi threaded download with those sites massively speeds up yt-dlp on termux.

### Describe the solution you'd like

yt-dlp already has a multi threaded download option but it only applies to DASH and HLS streams with multiple fragments.

It does not apply to regular single file streams. Those are still downloaded with just 1 connection. 

yt-dlp automatically does threading for all downloads with aria2c if we pass `--external-downloader aria2c` but it requires aria2c to be shipped with the app.

### Video link

The YouTube ones which were slow for me might be faster for others and I don't know if adult site links are appropriate here.

### Additional context

Using --external-downloader will replace yt-dlp's native downloader, so the current native threaded download option will conflict.

Even if implementing this isn't possible I'd still like to thank you for making Seal. This is the perfect yt-dlp on termux replacement I've found and it's just great.

Cheers.

**Comment by JunkFood02** [comment]
@xibr What do you think about it? [Reference](https://github.com/devgianlu/aria2-android)

**Comment by xibr** [comment]
Good idea, but `'aria2c'` should be renamed to `'libaria2c.so'` will it work? or it gives us the error:
```yt-dlp: error: No such external downloader "libaria2c.so"```

Or do we need some changes from yt-dlp for this to work?
command for example.

```yt-dlp -f 22 --downloader aria2c URL```

but in youtubedl-android
```yt-dlp -f 22 --downloader bin path/libaria2c.so URL```

**Comment by xibr** [comment]
I did some tests and got this

command
```
/libpython.so /yt-dlp --no-mtime -o /storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.%(ext)s -f 136+140 --downloader /libaria2c.so --ffmpeg-location /libffmpeg.so https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

output 
```
[youtube] dQw4w9WgXcQ: Downloading webpage
[youtube] dQw4w9WgXcQ: Downloading android player API JSON
[info] dQw4w9WgXcQ: Downloading 1 format(s): 136+140
[download] Destination: /storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.f136.mp4
[#8235a6 2.5MiB/16MiB(15%) CN:16 DL:4.0MiB ETA:3s]
[#8235a6 6.1MiB/16MiB(36%) CN:16 DL:3.7MiB ETA:2s]
[#8235a6 8.3MiB/16MiB(50%) CN:16 DL:3.2MiB ETA:2s]
[#8235a6 10MiB/16MiB(65%) CN:14 DL:3.0MiB ETA:1s]
[#8235a6 12MiB/16MiB(76%) CN:12 DL:2.7MiB ETA:1s]
[#8235a6 14MiB/16MiB(90%) CN:8 DL:2.6MiB]
[#8235a6 15MiB/16MiB(96%) CN:4 DL:2.4MiB]
[#8235a6 16MiB/16MiB(98%) CN:2 DL:2.1MiB]
[#8235a6 16MiB/16MiB(99%) CN:1 DL:1.9MiB]

[libaria2c] Downloaded 17369458 bytes

[download] 100% of 16.56MiB in 00:09 at 1.78MiB/s
[download] Destination: /storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.f140.m4a
[#1b3dfc 2.3MiB/3.2MiB(70%) CN:1 DL:2.8MiB]
[#1b3dfc 2.3MiB/3.2MiB(70%) CN:1 DL:1.2MiB]
[#1b3dfc 2.3MiB/3.2MiB(71%) CN:1 DL:854KiB ETA:1s]
[#1b3dfc 2.3MiB/3.2MiB(72%) CN:1 DL:639KiB ETA:1s]
[#1b3dfc 2.4MiB/3.2MiB(73%) CN:1 DL:513KiB ETA:1s]
[#1b3dfc 2.4MiB/3.2MiB(74%) CN:1 DL:430KiB ETA:1s]
[#1b3dfc 2.4MiB/3.2MiB(75%) CN:1 DL:371KiB ETA:2s]
[#1b3dfc 2.5MiB/3.2MiB(76%) CN:1 DL:328KiB ETA:2s]
[#1b3dfc 2.5MiB/3.2MiB(77%) CN:1 DL:295KiB ETA:2s]
[#1b3dfc 2.5MiB/3.2MiB(78%) CN:1 DL:268KiB ETA:2s]

[libaria2c] Downloaded 3433514 bytes

[download] 100% of 3.27MiB in 00:10 at 318.49KiB/s
[Merger] Merging formats into "/storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.mp4"
Deleting original file /storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.f136.mp4 (pass -k to keep)
Deleting original file /storage/emulated/0/Download/Rick Astley - Never Gonna Give You Up Official Music Video.f140.m4a (pass -k to keep)
```
But it only worked after modifying yt-dlp
```diff
diff --git a/yt_dlp/downloader/external.py b/yt_dlp/downloader/external.py
index 9859a7b33..635a8d867 100644
--- a/yt_dlp/downloader/external.py
+++ b/yt_dlp/downloader/external.py
@@ -239,7 +239,7 @@ def _make_cmd(self, tmpfilename, info_dict):
         return cmd


-class Aria2cFD(ExternalFD):
+class Libaria2cFD(ExternalFD):
     AVAILABLE_OPT = '-v'
     SUPPORTED_PROTOCOLS = ('http', 'https', 'ftp', 'ftps', 'dash_frag_urls', 'm3u8_frag_urls')
```

**Comment by JunkFood02** [comment]
Looks good! Maybe there's something to be done for parsing the progress text. Should we ping the maintainer of yt-dlp or file an issue there?

**Comment by JunkFood02** [comment]
Add in v1.2.0-beta.5

**Comment by adithya-s-sekhar** [comment]
It works! Downloads no longer throttled, it's going at full speed.
