### ISSUE TITLE
Cant select preferred video format

### ISSUE THREAD

**Issue by orelt06** [JunkFood02/Seal#1481]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I dont know why but after i updated the app to the latest version when i opened the app the screen was white and it didn't work... so i cleaned the storage through the Samsung settings and then the app works but deleted all my download history but kept the directory with those files on my phone's storage. Also i cant seem to select preferred video format which i remember that i could have done that before... any help?

### Error reports

Dont have any

### Screenshots & Screen Records

![Screenshot_20240427_234947_Seal](https://github.com/JunkFood02/Seal/assets/78733606/47dc918c-d5f2-4177-acff-ceecb0b2f030)

![Screenshot_20240427_235641_Seal](https://github.com/JunkFood02/Seal/assets/78733606/80babda7-da32-484c-94ec-eee7b08a4fe1)

**Comment by JunkFood02** [comment]
disable format sorting
