### ISSUE TITLE
No sync between subtitle and video

### ISSUE THREAD

**Issue by hastakim** [JunkFood02/Seal#1489]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The subtitle of the video remain unsync like someone speak in the video and the subtitle remain on screen with upcoming subtitle instead of when someone speak it should disappear and only appear when someone speaks

others video downloader like TubeMate does not have this problem but i like this app and this problem should be fixed.

### To Reproduce

1

### Error reports

No error

### Screenshots & Screen Records

2

### Additional context

2

**Comment by JunkFood02** [comment]
video link?

**Comment by hastakim** [comment]
Just download any video of youtube with subtitle by Seal App and Tubemate
and see the difference between subtitle appearing on video
on seal subtitle are not sync but on TubeMate subtitle are sync with audio
of video

**Comment by JunkFood02** [comment]
Since there's no examples to reproduce this bug, this issue will be closed
