### ISSUE TITLE
Rename Downloaded Song

### ISSUE THREAD

**Issue by Glitchy-Tozier** [JunkFood02/Seal#1495]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

NewPipe has this really nice feature where it lets you edit the song's name before downloading it. I really miss being able to remove stuff like "[OFFICIAL MUSIC VIDEO]" from the title of a song.

### Describe the solution you'd like

It would be great if there was a small text box when downloading a song (with the original song's name preinserted) that lets you edit the songs name before downloading.

### Additional context

You can check out NewPipe for their implementation. It's really nice! :)

**Comment by JunkFood02** [comment]
use "custom" format selection, then tap on the three-dot button in the format selection page

**Comment by Glitchy-Tozier** [comment]
What do you mean? I really for the life of me can't find what you're describing.
Could you post a screenshot of how to get there?

**Comment by Glitchy-Tozier** [comment]
That button is disabled on my device. Any clue how to enable it?
![Screenshot_20240603-090908_Seal.jpg](https://github.com/JunkFood02/Seal/assets/59611881/af744724-3290-497b-b329-543aaecbda3e)

**Comment by JunkFood02** [comment]
Disable "download playlist"
