### ISSUE TITLE
[Feature Request] backup Command Templates

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#151]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

What about a feature to backup Command Templates and import them 🤔

**Comment by JunkFood02** [comment]
Good suggestion. Currently the db is quite simple so we can just import/export them from/to clipboard as plain texts

**Comment by Marco-9456** [comment]
> Good suggestion. Currently the db is quite simple so we can just import/export them from/to clipboard as plain texts

Great 👍

**Comment by JunkFood02** [comment]
Added in v1.2.0-beta.2

**Comment by Marco-9456** [comment]
> Added in v1.2.0-beta.2

Thanks
