### ISSUE TITLE
Tiktok Video Downloader

### ISSUE THREAD

**Issue by JustineLoing** [JunkFood02/Seal#1510]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm want to download tiktok video with no Watermark. since i update the Seal app. and when i download the tiktok video, it will downloaded with watermark...at the older version i forget the version of when i use it, maybe around 1.9 or 1.10+ i use seal to download tiktok video, and there's no watermark in it. and when i follow the update about the Seal apk, i get the tiktok video with watermark in it.

**Comment by ModernLobby** [comment]
Tiktok change the way app can download the video on their app.
We just need to wait for yt-dlp to update it to work for it to works with Seal.
