### ISSUE TITLE
Download error from YouTube 

### ISSUE THREAD

**Issue by Kidohan** [JunkFood02/Seal#1514]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.12.1 (11212)
Device information: Android 8.0.0 (API 26)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.04.09

URL: https://youtube.com/watch?v=g197xdRZsW0&si=SVksBb7hy2G-zHfr
ERROR: Unable to download video subtitles for 'en-orig': [Errno 2] No usable temporary directory found in ['/data/data/com.termux/files/usr/tmp', '/']

**Comment by rudelf** [comment]
Duplicate #1161
