### ISSUE TITLE
Downloaded Clip duration bug

### ISSUE THREAD

**Issue by hoemaker6969** [JunkFood02/Seal#1515]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When downloading a clip from selection, a bug occur about the length, it shows the full length of the original video that got clipped not the true length of the clip

### Error reports

![Uploading Screenshot_2024-05-28-14-27-08-996_pl.solidexplorer2-edit.jpg…]()

**Comment by JunkFood02** [comment]
expected behavior
