### ISSUE TITLE
Can't download youtube videos

### ISSUE THREAD

**Issue by Mcju1** [JunkFood02/Seal#1524]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I copy the link into the link bar, go to download it and it says I must sign in to confirm I'm not a bot 

### To Reproduce

1. Copy youtube link
2. Paste into box
3. Go to download it
4. It will give the error

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.06.01.232725

URL: https://youtu.be/tHAwCqXyIc8?si=_0AsXFM3QhLugEBK
ERROR: [youtube] tHAwCqXyIc8: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Screenshots & Screen Records

![Screenshot_20240607_231212_Seal](https://github.com/JunkFood02/Seal/assets/127199632/4195dc8e-041b-4ef4-91be-d25a9ad6ec60)

**Comment by Dev-Obele** [comment]
I also have this issue. I hope this gets fixed soon...
