### ISSUE TITLE
Ability to change file name before downloading

### ISSUE THREAD

**Issue by fvo-git** [JunkFood02/Seal#1527]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Sometimes I try to download videos but they don't download.   [Errno] (typo ?? maybe) File name too long. I tried downloading a video on Twitter, but was unable to do so. 
![Screenshot_20240609_193650](https://github.com/JunkFood02/Seal/assets/172225198/ca85e967-b043-45e2-aa41-61600249503b)

### Describe the solution you'd like

The option of changing the file name to anything like what can be done on browsers when downloading something

**Comment by JunkFood02** [comment]
Settings - Download directory - Restrict filenames
