### ISSUE TITLE
Play with VLC instead of downloading 

### ISSUE THREAD

**Issue by read8873** [JunkFood02/Seal#1528]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Play with VLC instead of downloading 

### Additional context

https://www.videolan.org/vlc/download-android.html

**Comment by JunkFood02** [comment]
You can long press a format in the format selection page to share/copy the stream URL to VLC(or any other player you want)

Related: #544

**Comment by read8873** [comment]
is it possible to play both video and audio at the same time in vlc?

**Comment by JunkFood02** [comment]
just use the stream URL which contains both video and audio
