### ISSUE TITLE
Source Code does not have Layout Files.plz add these files also.its of no use for us without layout files.

### ISSUE THREAD

**Issue by hamza0786** [JunkFood02/Seal#1538]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Source Code does not have Layout Files.plz add these files also.its of no use for us without layout files.

### Describe the solution you'd like

Source Code does not have Layout Files.plz add these files also.its of no use for us without layout files.

### Additional context

Source Code does not have Layout Files.plz add these files also.its of no use for us without layout files.

**Comment by JunkFood02** [comment]
cry about it
