### ISSUE TITLE
[Feature Request] Comments download options

### ISSUE THREAD

**Issue by Fehertukor** [JunkFood02/Seal#154]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I would like to download video comments "with a press of a button".
 

### Describe the solution you'd like

yt-dlp --write-comments VIDEO_URL

### Video link

Any YouTube video.

### Additional context

Hello, 
I still love your work and thank you for it! 
Would it be possible to implement this feature?

Extra would be, an ability to convert it to csv automatically or to xlsx or some useful format because basic format is json.

Thank you very much!

**Comment by JunkFood02** [comment]
Creating a command template would suit your use case I think?
`--write-comments --skip-download`
Also, converting (comments) json into other formats is not supported in yt-dlp
