### ISSUE TITLE
Unable to download video data

### ISSUE THREAD

**Issue by pramanakenzo** [JunkFood02/Seal#1541]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.06.20.232815

URL: https://youtu.be/DFlu2Df652M?si=-pFvHgEesF15Ewg8
ERROR: unable to download video data: HTTP Error 403: Forbidden

### Error reports

ERROR: unable to download video data: HTTP Error 403: Forbidden

### Screenshots & Screen Records

![Screenshot_20240621-173458_Seal](https://github.com/JunkFood02/Seal/assets/163126272/d76c9a97-e11b-4769-9124-edf6a630d917)

**Comment by Richard38907** [comment]
Strange🤔, I tested your link and it works fine for me.

**Comment by pramanakenzo** [comment]
> Strange🤔, I tested your link and it works fine for me.

I tried it again and now it works, maybe it's because of my internet data are so slow
