### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by kali786linux** [JunkFood02/Seal#1555]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I took a like from YouTube and pasted it in the url and the error given below was shown

### Error reports

App version: 1.12.1 (11212)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

URL: https://youtu.be/8ocWUGARCB0?si=ym5jPFvBzYZWVmzz
java.io.IOException: Cannot run program "/mnt/asec/com.junkfood.seal-Gh8ynvbm0In4RvBa/lib/arm64/libpython.so": error=13, Permission denied

**Comment by JunkFood02** [comment]
you can't run seal on sd cards
