### ISSUE TITLE
Inicio de sesión en YouTube 

### ISSUE THREAD

**Issue by Alister0901** [JunkFood02/Seal#1558]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Al internet descargar un audio, me marca el error que debo iniciar una sesión cuando ya está activa , de antemano gracias por la ayuda 

### To Reproduce

Paso 1 Copiar el enlace 
Paso 2 Pegar el enlace en la app
Paso 3 Escoger la preferencia en del formato de audio y luego descargar 
Luego sucede el error 

### Error reports

App version: 1.12.1-(F-Droid) (11212)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.06.24.232830

URL: https://youtube.com/watch?v=wrQt3JfVuyQ&si=uphulJNOJiqbqEOV
ERROR: [youtube] wrQt3JfVuyQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Screenshots & Screen Records

![Screenshot_2024-06-29-12-45-07-97_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/JunkFood02/Seal/assets/174209148/857ab969-37c9-41e9-a62d-b39f60ab5453)

### Additional context

Desconozco si debo iniciar sesión en YouTube o tal vez se deba iniciar sesión en la aplicación, pero en YouTube tengo la seción activa

**Comment by Pablo07gpe** [comment]
Lo solucionaste amigo
