### ISSUE TITLE
Bitchute after new site has been launched

### ISSUE THREAD

**Issue by FRANKLYIE** [JunkFood02/Seal#1560]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

For a couple days before was a sparce error, now after the redesigning of it, i can't downoad anything out of bitchute, the site itself works really bad and i do not know if it is Europe's censorship or what but i could download videos before this. P.s. in the browser is playable. 

### To Reproduce

App version: 1.12.1-(F-Droid) (11212)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.05.27

URL: https://www.bitchute.com/video/CGZIh9R0OiaI/
ERROR: [BitChute] CGZIh9R0OiaI: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.

### Error reports

App version: 1.12.1-(F-Droid) (11212)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.05.27

URL: https://www.bitchute.com/video/CGZIh9R0OiaI/
ERROR: [BitChute] CGZIh9R0OiaI: Video is unavailable. Please make sure this video is playable in the browser before reporting this issue.

**Comment by NewNewPipe** [comment]
Confirmation. There is a problem with Bitchute. Download via Seal don't working.

**Comment by NewNewPipe** [comment]
After updating the script yt-dlp on one of the videos worked. Update yt-dlp and then it will be known if the problem is solved after the script upgrade.

**Comment by FRANKLYIE** [comment]
> After updating the script yt-dlp on one of the videos worked. Update yt-dlp and then it will be known if the problem is solved after the script upgrade.

I am already using the last yt dlp. I tried with last stable and last nightly with no luck.

**Comment by NewNewPipe** [comment]
I tried downloading that video file you can't download and in my case it downloads without any problem. I don't know what it could be about that it doesn't work in your case.

**Comment by JunkFood02** [comment]
just switch to the nightly version of yt-dlp

https://github.com/yt-dlp/yt-dlp/issues/10293
