### ISSUE TITLE
Video not download error:- 403

### ISSUE THREAD

**Issue by Vaibhav9537** [JunkFood02/Seal#1575]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 

URL: https://www.youtube.com/live/qzgdtjNtz0c?si=epR9uUUh6eG-Fuyt
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...
WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
WARNING: [youtube] Unable to download API page: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] qzgdtjNtz0c: nsig extraction failed: You may experience throttling for some formats
         n = LbqxYDh9p_0sZ1LskmB ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
WARNING: [youtube] qzgdtjNtz0c: nsig extraction failed: You may experience throttling for some formats
         n = W5xzBR8BX32Lk3ybZeW ; player = https://www.youtube.com/s/player/8d9f6215/player_ias.vflset/en_US/base.js
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by ryannewcomer** [comment]
How do u solve this? I got the same error

**Comment by ordoviejo** [comment]
I had the same problem, what I could do to fix it was Go to the app settings, then press settings and change the channel I left in the screenshot. 

<img width="720" height="1600" alt="Image" src="https://github.com/user-attachments/assets/fb57513f-ae26-45aa-8bc2-eac3fc941d23" />
