### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by Haritsa90** [JunkFood02/Seal#1576]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I would like to download audio & video files without thumbnails. How can I? I tried selecting/deselected the "save thumbnail". But it's for different purpose I understand, to save the thumbnail separately. I don't want the thumbnails to be downloaded at all. Please advice if this feature is already available, or kindly provide an option for the same. Thanks.

### Describe the solution you'd like

A checkbox to select / deselect to download thumbnails with the file

### Video link

NA

**Comment by JunkFood02** [comment]
if you mean audios, disable "embed metadata" in the format settings also disabled the thumbnail embedding

**Comment by Haritsa90** [comment]
That worked. Thanks.

Thanks for the app 🙂👍🏼
