### ISSUE TITLE
It won't let me download videos to my SD card

### ISSUE THREAD

**Issue by REYTILIN96** [JunkFood02/Seal#1577]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Lately I have tried to download videos and some have given me an error and it won't let me download them to my SD card, before it was only with TikTok but now it happens to me with X

### Error reports

App version: 1.12.1 (11211)
Device information: Android 10 (API 29)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.09

URL: https://x.com/Padre_Maker/status/1812307010605420549?t=MJtCF6KkDyEobMnFYt5shQ&s=19
Failed to touch /mnt/media_rw/2C43-9971/Download/Seal/ℙ𝔸𝔻ℝ𝔼𝕄𝔸𝕂𝔼ℝ - https：⧸⧸t.co⧸tN0WEZ4xnC [1812306992163094528].mp4: java.io.IOException: Invalid argument

### Screenshots & Screen Records

![Screenshot_2024-07-13-23-44-05-309_com junkfood seal](https://github.com/user-attachments/assets/6bab598f-4504-4f94-bd17-13202325ed09)

**Comment by claymorwan** [comment]
I get the same bug, but only when I download Twitter videos, even tho I did the cookie thingy

**Comment by JunkFood02** [comment]
we don't support download to sd card directly + we can't support this due to restrictions from android
