### ISSUE TITLE
Translation of README to Spanish

### ISSUE THREAD

**Issue by 7zLT** [JunkFood02/Seal#1580]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

_Sorry, Im still figuring out how to contribute to projects on GitHub_

### Describe the solution you'd like

I want to contribute by translating the README file to spanish. I didn't find/figure out any place to do so on Seal's [Hosted Weblate page](https://hosted.weblate.org/projects/seal/glossary/es/#information) so I thought I might request it as an issue

**Comment by JunkFood02** [comment]
You can submit a pull request, take a look at the [merged ones](https://github.com/JunkFood02/Seal/pulls?q=is%3Apr+is%3Aclosed+readme)
