### ISSUE TITLE
App version: 1.12.1 (11210) Device information: Android 14 (API 34) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2024.07.14.232743  URL: https://youtube.com/shorts/O9ak9oBCFdQ?si=waVOxu3ZOUp2jHGH ERROR: [youtube] O9ak9oBCFdQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### ISSUE THREAD

**Issue by Amyr252** [JunkFood02/Seal#1589]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.12.1 (11210)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.07.14.232743

URL: https://youtube.com/shorts/O9ak9oBCFdQ?si=waVOxu3ZOUp2jHGH
ERROR: [youtube] O9ak9oBCFdQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

**Comment by cyber-unknown0** [comment]
App version: 1.13.0 (11300)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.01.232843

URL: https://www.instagram.com/reel/C1o48M-pYQ6/?igsh=MXhiNXV2N2Ezem05bg==
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
WARNING: [Instagram] C1o48M-pYQ6: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] C1o48M-pYQ6: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, --netrc-cmd, or --netrc (instagram) to provide account credentials
Plz solve the error
