### ISSUE TITLE
[Feature Request] Implement Android 13 Themed Icon support

### ISSUE THREAD

**Issue by sicknn** [JunkFood02/Seal#160]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by BobbyESP** [comment]
I've tried to implement this but i wasn't able, so idk @JunkFood02

**Comment by JunkFood02** [comment]
The current icon needs to be redesign to support this, so please stay tuned

**Comment by JunkFood02** [comment]
Please give a try with the CI artifact of [the latest commit](https://github.com/JunkFood02/Seal/actions/runs/2949717126)

**Comment by BobbyESP** [comment]
Artifact output files cant be downloaded. They dont appear for me

**Comment by Marco-9456** [comment]
> Artifact output files cant be downloaded. They dont appear for me

![Screenshot_20220829-174321_Chrome](https://user-images.githubusercontent.com/41828058/187240523-84a95594-e5e7-4b00-925e-041ac2a4d2ac.jpg)

**Comment by BobbyESP** [comment]
> > Artifact output files cant be downloaded. They dont appear for me
> 
> ![Screenshot_20220829-174321_Chrome](https://user-images.githubusercontent.com/41828058/187240523-84a95594-e5e7-4b00-925e-041ac2a4d2ac.jpg)
> 

Thanks!! Haha im so silly, didn't saw that

**Comment by Marco-9456** [comment]
> > > Artifact output files cant be downloaded. They dont appear for me
> > 
> > 
> > ![Screenshot_20220829-174321_Chrome](https://user-images.githubusercontent.com/41828058/187240523-84a95594-e5e7-4b00-925e-041ac2a4d2ac.jpg)
> 
> Thanks!! Haha im so silly, didn't saw that

Don't worry 😃
