### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by tired-creating-those-usernames** [JunkFood02/Seal#1621]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

for the moment App allows only to 'separate' audio from video and put downloads to separate folders. There is no `local` possibility to put the file in a desired folder for every new download.

### Describe the solution you'd like

implement an option to choose destination folder in the same window with audio/video format and other settings for every download.

**Comment by JunkFood02** [comment]
try [ytdlnis](https://github.com/deniscerri/ytdlnis)
