### ISSUE TITLE
Cant Download Any Video

### ISSUE THREAD

**Issue by Alex04754654** [JunkFood02/Seal#1623]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I've been using seel for a long time but some times ago it's stopped working when I download from app it's shows error downloading 
![Screenshot_20240809-011324](https://github.com/user-attachments/assets/07ba4686-13e0-4657-afce-5f0ea7b8615d)
and also while downloading from any other apps by quick download option 
![Screenshot_20240809-011718](https://github.com/user-attachments/assets/4ff0165a-b743-43cd-8c9b-b2d089461e2d)
Please Help Me Soon With This Problem

### Error reports

ERROR: unable to open for writing: [Errno 1] Operation not permitted: '/storage/emulated/0/Download/Seal/tmp/Avengers Cast ｜ Who Said It？ ＂We have a Hulk.＂😂 #shorts #avengers #marvel #tomhiddleston #chrisevans [3HTfPjzMLdA].f399.mp4.part'
ERROR: unable to open for writing: [Errno 1] Operation not permitted: '/storage/emulated/0/Download/Seal/tmp/Avengers Cast ｜ Who Said It？ ＂We have a Hulk.＂😂 #shorts #avengers #marvel #tomhiddleston #chrisevans [3HTfPjzMLdA].f251.webm.part'

**Comment by JunkFood02** [comment]
maybe it's the emoji in the filename, try enable settings - general - restrict filename
