### ISSUE TITLE
YouTube download issue

### ISSUE THREAD

**Issue by delano316** [JunkFood02/Seal#1625]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

YouTube is rejecting my request to download a video and gives the message "Sign in to confirm you’re not a bot. This helps protect our community."

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.04.232814

URL: https://youtu.be/lER5hZXD-BY?si=tCBWqEv4XQSLeh3w
ERROR: [youtube] lER5hZXD-BY: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Screenshots & Screen Records

![Screenshot_2024-08-08-20-34-40-23_f56d448df78e8512261d4bfbcb3978c7](https://github.com/user-attachments/assets/b380dc01-4911-4fdb-a009-e3b2ceac68fa)

**Comment by greentea-cup** [comment]
Confirmed.
Looks like youtube has new policy now.
Anyway, I got it working (for now at least).

Settings -> Net/Web -> Cookies -> Generate new cookies
Enter "https://youtube.com", then "Generate".
This will open youtube web page where you need to log in to save cookies.

After that enable cookies when downlading from youtube (bottom button in download options dialogue).
