### ISSUE TITLE
New Download bug

### ISSUE THREAD

**Issue by Thefactorypilot** [JunkFood02/Seal#1630]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When attempting to download audio from a YouTube video, the seal app isn't allowed to even access the video from the link. 

### To Reproduce

1. Go to youtube app
2. Find desired video
3. Click Share
4. Choose Seal
5. Choose to download and convert to mp3
6. Press download

### Error reports

App version: 1.12.1 (11212)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2024.08.06.232802

URL: https://youtube.com/watch?v=FoaJjbe-d9Q&si=265AdzE34YAiEjkm
ERROR: [youtube] FoaJjbe-d9Q: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

### Screenshots & Screen Records

![Screenshot_20240811-184744](https://github.com/user-attachments/assets/e231154e-a2e1-406f-ad2d-a38e85f6c210)

### Additional context

The error mentions "make sure to sign in. Im currently signed in to my youtube account.

**Comment by wayne-ch** [comment]
Me too

**Comment by Thefactorypilot** [comment]
> Me too

Do you have any other android apps for YouTube audio ripping to recommend until they fix seal?
