### ISSUE TITLE
Need:Automatic Link Recognition

### ISSUE THREAD

**Issue by Zolllon** [JunkFood02/Seal#1634]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

in the current version of Seal, adding extra words before the link Seal will reports an error, it's neccessary to add a automatic-link-recognition to fix it

**Comment by JunkFood02** [comment]
use the paste button instead of pasting to the textbox on your own
