### ISSUE TITLE
Downloading YouTube Shorts Resets the Scroll Position to the Start 

### ISSUE THREAD

**Issue by bacevs** [JunkFood02/Seal#1641]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When browsing through YouTube Shorts, if I download a short, the scroll position resets, causing the Shorts to start from the very first one again. For example, after scrolling through 20 shorts, downloading one will cause the list to jump back to the first short.

### To Reproduce

Go to YouTube Shorts within the app.
Scroll through multiple shorts.
Download one of the shorts.
Notice that after the download, the list scrolls back to the first short.

### Error reports

No specific error code, the issue is with the scroll reset behavior.

### Screenshots & Screen Records

https://youtu.be/TEBPA9NULtI?si=KXpJ20e9i4pUT3KN

**Comment by JunkFood02** [comment]
looks like a youtube issue
