### ISSUE TITLE
无法更新yt-dlp组件

### ISSUE THREAD

**Issue by MisakaSakura** [JunkFood02/Seal#1645]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

无法更新yt-dlp组件
![Screenshot_2024-08-19-00-18-15-48_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/user-attachments/assets/ed725454-05bb-488e-a02a-9f16c1a8db95)
提示检查与github的连接情况

### To Reproduce

正常点击

### Error reports

正常点击更新yt-dlp组件无法更新，提示检查与github的连接情况，稳定版和每夜班都一样

### Screenshots & Screen Records

同上

### Additional context

这个必须勾选允许在最新版的yt-dlp的选项不太合理，因为不是所有bug问题都是下载视频的问题，我遇到的刚好是本身无法更新yt-dlp组件的问题

**Comment by JunkFood02** [comment]
Your IP probably hit the rate limit of github API. There's nothing much could be do on our side, maybe try changing your IP with a (or another) VPN
