### ISSUE TITLE
The file finishes but error pops up at the end.

### ISSUE THREAD

**Issue by GalenRhys** [JunkFood02/Seal#1651]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The download will not save. Everything is downloaded but it won't move the file to any directory.

### To Reproduce

1. Download any file and wait.

### Error reports

App version: 1.12.1-(F-Droid) (11212)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.06

URL: https://youtu.be/07cAA1Ywqlw?si=6F4cf9EHz6cifY1o
Failed to touch /storage/4A21-0000/Seal DL/I USED the ＂Ladder 🪜｜ NOT Technique＂ & IT Manifested in 6 Days!! ✅ 100% Results ｜ Neville Goddard [07cAA1Ywqlw].mp4: java.io.IOException: Invalid argument

**Comment by JunkFood02** [comment]
Settings - General - Restrict filenames
