### ISSUE TITLE
Incorrent Default App Opening for APK file during Update

### ISSUE THREAD

**Issue by sweetpotato-yee** [JunkFood02/Seal#1653]
### Checklist

- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

## Description
After entering the application, I noticed a new release version and pressed the download button. Upon completion of the download, my device open the updated APK file via Termux.

## Expected Behavior
I expected the system's app chooser to appear (the "Open with..." dialog), allowing me to select the appropriate application to handle the APK file, specifically the "Package Installer" (formerly known as "Android Application Installer").

## Actual Behavior
Instead of the app chooser appearing, the APK file was opened directly with Termux. It seems that certain applications, such as Termux and Terabox, are set to support all types of files, which overrides the system's default behavior and prevents the "Package Installer" from being selected as the default application for handling APK files.

## Steps to Reproduce
1. On a device running Android 6.0, install an application that supports all file types (e.g., Termux).
2. Install an older version of the Seal application.
3. Within the Seal application, download the latest update.
4. Attempt to open the downloaded APK file directly from the Seal application.
5. Observe that the APK file is not opened with the "Package Installer," and the app chooser is not displayed.

## Environment
- **Device:** HTC Desire 10 Pro (HTC d10i)
- **App Version:** v1.12.1 to v1.13.0 (Stable)

## Possible Solutions
- Adjust the update logic of the application to ensure that when an APK file is opened, the app chooser is prompted. This would allow users to select the "Package Installer" as the default application for handling APK files.

## Additional Information
This issue may also affect other apps that are configured to handle all types of files, leading to similar problems with the default app selection.

Please let me know if further details are required or if there are any suggestions for resolving this issue.

### Error reports

N/A

**Comment by JunkFood02** [comment]
You can go to the settings and try clearing your "Default apps" or something that makes the action "open install package" default to termux
