### ISSUE TITLE
App version: 1.13.0 (11302) Device information: Android 14 (API 34) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2024.08.19.232821  URL: https://www.instagram.com/reel/C-x2L9TofxX/?igsh=MTh3NmNucjg5NjRoag== WARNING: [Instagram] C-x2L9TofxX: No csrf token set by Instagram API WARNING: [Instagram] C-x2L9TofxX: General metadata extraction failed (some metadata might be missing). ERROR: [Instagram] C-x2L9TofxX: Unable to download webpage: [Errno 7] No address associated with hostname (caused by TransportError('[Errno 7] No address associated with hostname'))

### ISSUE THREAD

**Issue by Akii256** [JunkFood02/Seal#1654]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The app doesn't fetch the video which the link is attached to especially YouTube 
![Screenshot_20240823_195205_Seal](https://github.com/user-attachments/assets/f251c82c-8a7c-459f-bb9c-56ba0ff12d94)

### To Reproduce

Go to the app
Paste your link 
Click the download button 
And click it again to confirm confirmation 

### Error reports

App version: 1.13.0 (11302)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.19.232821

URL: https://www.instagram.com/reel/C-x2L9TofxX/?igsh=MTh3NmNucjg5NjRoag==
WARNING: [Instagram] C-x2L9TofxX: No csrf token set by Instagram API
WARNING: [Instagram] C-x2L9TofxX: General metadata extraction failed (some metadata might be missing).
ERROR: [Instagram] C-x2L9TofxX: Unable to download webpage: [Errno 7] No address associated with hostname (caused by TransportError('[Errno 7] No address associated with hostname'))

### Screenshots & Screen Records

![Screenshot_20240823_195205_Seal](https://github.com/user-attachments/assets/27075cfa-e508-4ead-af0b-c6c3ca9096e1)

### Additional context

Its acting up with every link from everywhere

**Comment by Biswajit123333** [comment]
App version: 1.13.1 (11312)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.22.232922

URL: App version: 1.13.1 (11312)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.22.232922

URL: https://www.facebook.com/share/r/127eNYDq5WS/
ERROR: [facebook] 1571651380115386: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

ERROR: [generic] 'App version: 1.13.1 (11312)\nDevice information: Android 14 (API 34)\nSupported ABIs: [arm64-v8a, armeabi-v7a, armeabi]\nYt-dlp version: 2024.10.22.232922\n\nURL: https://www.facebook.com/share/r/127eNYDq5WS/\nERROR: [facebook] 1571651380115386: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:App version: 1.13.1 (11312)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.22.232922

URL: https://www.facebook.com/share/r/127eNYDq5WS/
ERROR: [facebook] 1571651380115386: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U" ) to search YouTube
