### ISSUE TITLE
Remove comma from English String

### ISSUE THREAD

**Issue by ShareASmile** [JunkFood02/Seal#1659]
Remove comma from following English string after word "subtitles":
https://hosted.weblate.org/translate/seal/strings/en/?checksum=557db13caa9409a9

Correct string shall be:-
Choose from formats, subtitles and customize further

Sorry for not filling Issue template as it was not presented in OctoDroid, a github Client app.

**Comment by JunkFood02** [comment]
https://en.wikipedia.org/wiki/Serial_comma

don't think it's grammatically incorrect tho
