### ISSUE TITLE
How to fetch all links ( audio, video) of url ?

### ISSUE THREAD

**Issue by hamaz562006** [JunkFood02/Seal#166]
How to fetch all links ( audio, video) of url ? example if url is facebook, fetch sd and hd links with a request.

**Comment by JunkFood02** [comment]
`-f all` But why would you need to do this?

**Comment by hamaz562006** [comment]
YoutubeDLRequest request = new YoutubeDLRequest(url);

File youtubeDLDir = getDownloadLocation();
request.addOption("-o", youtubeDLDir.getAbsolutePath() + "/%(title)s.%(ext)s");

request.addOption("-f", "all");

Disposable disposable = Observable.fromCallable(() -> YoutubeDL.getInstance().getInfo(request))
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(youtubeDLResponse -> {
                    Log.d("Links",youtubeDLResponse.getUrl());
                }, e -> {
                    e.printStackTrace();
                });
compositeDisposable.add(disposable);

this fetch only a link??

**Comment by JunkFood02** [comment]
Closing this because it's not related to Seal's functionality and usages
