### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Shakti8260** [JunkFood02/Seal#1679]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I copy the link from Amazon mini tv and paste it in seal apk then after some few seconds it shows download error 

### Error reports

App version: 1.13.0 (11302)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.06

URL: https://www.amazon.in/minitv/tp/9eeae655-616c-4981-af7d-b18ba325b38b?refMarker=ams_s
ERROR: [AmazonMiniTV] 9eeae655-616c-4981-af7d-b18ba325b38b: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>)

### Screenshots & Screen Records

![Screenshot_2024-09-08-10-39-34-237_com junkfood seal](https://github.com/user-attachments/assets/0eb1032f-64b4-406f-8f5a-78a7e8515fb8)

**Comment by JunkFood02** [comment]
https://github.com/yt-dlp/yt-dlp/issues/10308
