### ISSUE TITLE
Can't fetch YouTube videos/audios 

### ISSUE THREAD

**Issue by Btagedits** [JunkFood02/Seal#1680]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I'm trying to download some videos and audio for my editing purposes but whenever I press the "download" button seal processes for some time and says "we couldn't fetch the video" and it had happened before too and this is too much now I want some exact solution for this 

### Error reports

App version: 1.13.0 (11302)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.09.07.232731

URL: https://youtube.com/watch?v=XyDsjxs8Y7c&si=MgN6TZ0_wJlCKhTK
WARNING: [youtube] Unable to download webpage: [Errno 7] No address associated with hostname
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (1/3)...
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (2/3)...
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [Errno 7] No address associated with hostname (caused by TransportError('[Errno 7] No address associated with hostname'))
WARNING: [youtube] Unable to download webpage: [Errno 7] No address associated with hostname
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (1/3)...
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (2/3)...
WARNING: [youtube] [Errno 7] No address associated with hostname. Retrying (3/3)...
WARNING: [youtube] Unable to download API page: [Errno 7] No address associated with hostname (caused by TransportError('[Errno 7] No address associated with hostname'))
ERROR: [youtube] XyDsjxs8Y7c: Failed to extract any player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20240908-165632_Seal](https://github.com/user-attachments/assets/abeff0aa-b49a-4ca5-bd19-efa265f6edd7)
![Screenshot_20240908-165545_YouTube](https://github.com/user-attachments/assets/70558dbe-e716-4284-a29e-6e4ebd20a379)
![Screenshot_20240908-165545_YouTube](https://github.com/user-attachments/assets/9ca3f664-128f-4810-a8cb-c3dbe943bbac)

**Comment by JunkFood02** [comment]
DNS issue with your internet
