### ISSUE TITLE
Errno 36 File name too long

### ISSUE THREAD

**Issue by ManuelReschke** [JunkFood02/Seal#1697]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Diffrent Videos has a to long fiilename ...

X
X
SOLUTION: if error occur, short the filename to a random string
X
X

### To Reproduce

Try to download this video from X  (i/status/1835378350048645632)

### Error reports

ERROR: unable to open for writting:: [Errno 36] File name to long

**Comment by seanmavley** [comment]
Ooh good, it's been reported. 
Just happened to me trying to download a post from LinkedIn 

```
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
WARNING: [generic] Falling back on generic information extractor
ERROR: unable to open for writing: [Errno 36] File name too long: '/storage/emulated/0/Download/Seal/tmp/Naomi Kodua Ofosu on LinkedIn： #interiordesign #animation #3d #buildingdesign #architecture… ｜ 11 comments [naomi-s-kodua_interiordesign-animation-3d-activity-7249728746138529792-d-ZZ？utm_source=social_share_video&utm_medium=android_app&utm_campaign=share_via].mp4.part'
```

**Comment by seanmavley** [comment]
Fix is to enable restrict file name under download section

![Screenshot_20241010_081932_Seal](https://github.com/user-attachments/assets/6797dab8-d347-4261-b09f-ba24e13499a0)
