### ISSUE TITLE
Adding Queue downlosd feature

### ISSUE THREAD

**Issue by Egymus** [JunkFood02/Seal#1698]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Additional context

I hope we can see queue download feature in Seal so we save time for waiting for download to finish to download another one.

**Comment by ArmandBernard** [comment]
This is a duplicate for #324

**Comment by Egymus** [comment]
> This is a duplicate of #324

Wow. I didn't expect it was here since 2022
