### ISSUE TITLE
Add a pop-up window if the video has been shared from the other app instead of opening Main Activity

### ISSUE THREAD

**Issue by kastentop2005** [JunkFood02/Seal#170]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Just add a pop-up video when video is shared, like NewPipe does

### Video link

Any

**Comment by JunkFood02** [comment]
Duplicated #152
