### ISSUE TITLE
Error tiktok 

### ISSUE THREAD

**Issue by coder2020x** [JunkFood02/Seal#1703]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Error downloadApp version: 1.13.0-(F-Droid) (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.06

URL: https://vm.tiktok.com/ZMhNHB62W/
ERROR: Postprocessing: Error opening input files: Invalid data found when processing input

### Error reports

App version: 1.13.0-(F-Droid) (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.08.06

URL: https://vm.tiktok.com/ZMhNHB62W/
ERROR: Postprocessing: Error opening input files: Invalid data found when processing input
![Screenshot_20240919-113707](https://github.com/user-attachments/assets/45290ed7-4f37-4068-b90a-832a5d6f19e6)

### Screenshots & Screen Records

![Screenshot_20240919-113707](https://github.com/user-attachments/assets/ab5e4fd9-4a3d-459d-aaba-46e1ee71ca46)

**Comment by seanmavley** [comment]
Experiencing same issue

**Comment by DEadMan10sds** [comment]
Same issue here
