### ISSUE TITLE
Cancelling operation cause app crash when "download playlist" option enabled to download a single video

### ISSUE THREAD

**Issue by hamaz562006** [JunkFood02/Seal#171]
### Describe the bug

when config Download playlist, don't work properly only single link is downloaded.
after click to cancel app is crashed

### Device info

1.1.0 API 26 (Android 8.0)

**Comment by JunkFood02** [comment]
Please provide the link to the playlist as well

**Comment by hamaz562006** [comment]
> Please provide the link to the playlist as well

every link example : https://www.tiktok.com/@tyga/video/6806520676862774533

**Comment by JunkFood02** [comment]
Reproduced, will get fixed in next version. For now, please don't use the "download playlist" option for a single video
