### ISSUE TITLE
Can't dowload videos and Audio from tiktok

### ISSUE THREAD

**Issue by Josue4710** [JunkFood02/Seal#1718]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Several days ago it won't let me download videos and audio from tiktok and the problem is still going on

### Error reports

App version: 1.13.0 (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.09.17.232940

URL: https://vm.tiktok.com/ZMhYngWmS/
ERROR: Preprocessing: Conversion failed!
ERROR: Preprocessing: Conversion failed!
ERROR: Postprocessing: WARNING: unable to obtain file audio codec with ffprobe

App version: 1.13.0 (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.09.17.232940

URL: https://vm.tiktok.com/ZMhYngWmS/
ERROR: Postprocessing: Error opening input files: Invalid data found when processing input

### Screenshots & Screen Records

![Screenshot_20240922_233203](https://github.com/user-attachments/assets/5979a55d-fe80-4260-9eb7-f51e92d13daa)
![Screenshot_20240922_233307](https://github.com/user-attachments/assets/9b43b662-db2f-4cb9-8361-ca9bee2448eb)

**Comment by Ammar506tamim** [comment]
Like your problem, what's the solution?

**Comment by BreadJS** [comment]
Exact same issue here

**Comment by 1LuckyLizard** [comment]
I'm getting the same error from the last image. I've tried with different TikTok videos and it's not working :(
