### ISSUE TITLE
[Bug Report] Blank Screen

### ISSUE THREAD

**Issue by dead8309** [JunkFood02/Seal#173]
### Describe the bug

Is that a bug in Navigation in Compose library ?
I also face the same bug in my app when navigating to other screens 

### To Reproduce

1. Repeatedly navigating to other screens will throw a blank screen.

### Error reports & Screenshots

https://user-images.githubusercontent.com/68665948/187888648-9ebb5f36-96a6-4d7b-b56a-9c42961299be.mp4

### Device info

1.0.5 (API 29)
[arm64-v8a, armeabi-v7a, armeabi]

**Comment by JunkFood02** [comment]
I guess repeated execution of `navHostController.popBackStack()` causes this problem, which can be solved by de-duplication.

**Comment by BobbyESP** [comment]
This also happens to me but when i open the app. Just by clicking the screen one time the problem it's fixed

**Comment by JunkFood02** [comment]
> 

Please file another issue about this

**Comment by BobbyESP** [comment]
> > This also happens to me but when i open the app. Just by clicking the screen one time the problem it's fixed
> 
> Please file another issue about this

Okey!
