### ISSUE TITLE
App is blank when opened

### ISSUE THREAD

**Issue by BobbyESP** [JunkFood02/Seal#177]
### Describe the bug

When you open the app with the Welcome Dialog without being dismissed, Seal opens correctly, but if you try to open the app with the dialog already dismissed, the app will be in blank until you dont update the screen (scrolling down, not just clicking)

### To Reproduce

Steps to reproduce:
1. Open Seal by the first time (or clean data for the Welcome Dialog to appear)
2. You can see that by that way works.
3. Click in Don't show again and close the dialog.
4. Close the app (not just letting it in background)
5. Open it another time and you can see the problem.

### Error reports & Screenshots

https://user-images.githubusercontent.com/60316747/188087518-67722251-9290-4f2b-a17e-c501e64e8836.mp4

### Device info

App version: 1.2.0-beta.5 (10100)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2272 x 1078

### Additional context

I need to say that this also happened with one of the apps that i've made, so probably is a Xiaomi bug.
I also checked that this problems only happens when the night mode is enabled or defauly by the system

**Comment by JunkFood02** [comment]
This is a known issue with MIUI and the Jetpack Compose. Still not clear how this should be resolved
- https://github.com/Ashinch/ReadYou/issues/53
