### ISSUE TITLE
TikTok Video Download

### ISSUE THREAD

**Issue by ARD0NIZ** [JunkFood02/Seal#1788]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Just getting the error that a Python version is deprecated 

### To Reproduce

Just clicked download 

### Error reports

App version: 1.13.0 (11302)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.07.232845

URL: https://vm.tiktok.com/ZGdJGHdjo/
Deprecated Feature: Support for Python version 3.8 has been deprecated. Please update to Python 3.9 or above
ERROR: [TikTok] 7419901159625854240: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

https://github.com/user-attachments/assets/16bf097d-719f-4e7a-9128-2e518209ff64

### Additional context

Nothing to add

**Comment by AKGamerTech** [comment]
Changed the yt-dlp version to the regular from nightly and it fixed the issue.

**Comment by NekoZ410** [comment]
Try pre-release version instead
