### ISSUE TITLE
Automatic background playlist sync

### ISSUE THREAD

**Issue by ondrejnedoma** [JunkFood02/Seal#1794]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I have a fairly big YouTube playlist with songs I need to have available offline. I've used seal to download the playlist, but whenever I make changes to the YouTube playlist, I have to manually download/delete local files.

### Describe the solution you'd like

Make Seal be able to use the playlist sync option flag of yt-dlp (which stores the IDs of already downloaded videos in a txt file) AND periodically run a background task on the user's preferred playlists every x hours (how often the user prefers it)

**Comment by JunkFood02** [comment]
Use [ytdlnis](https://github.com/deniscerri/ytdlnis)

**Comment by ondrejnedoma** [comment]
Thanks for the recommendation, however it's definitely a shame you don't want to add this feature to Seal...

**Comment by JunkFood02** [comment]
https://github.com/sponsors/JunkFood02
