### ISSUE TITLE
Unusual error 

### ISSUE THREAD

**Issue by arvindkini0** [JunkFood02/Seal#1796]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.13.0 (11302)
Device information: Android 14 (API 34)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.11.232837
![Screenshot_20241012-224813_Seal](https://github.com/user-attachments/assets/200de757-2a27-4d4c-b73d-9ea5d4dd093b)

### Screenshots & Screen Records

Screenshot attached of the error 
![Screenshot_20241012-224813_Seal](https://github.com/user-attachments/assets/ad8d7612-59c9-47e3-80e0-af9985eac29c)

**Comment by JunkFood02** [comment]
#1399
