### ISSUE TITLE
Youtube Login to Download High Quality Audio

### ISSUE THREAD

**Issue by salihmarangoz** [JunkFood02/Seal#1799]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

A login option so that yt-dlp can download high quality audio from Youtube.

**Comment by JunkFood02** [comment]
settings - network -  cookies

**Comment by Carter0108** [comment]
> settings - network - cookies

This doesn't work for YouTube Premium high quality. Seal still only lists the medium and low quality formats.
