### ISSUE TITLE
[Bug Report] - Click to cancel not working.

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#180]
### Describe the bug

The _**click to cancel**_ button is not canceling the job when downloading from  Crunchyroll

### To Reproduce

1. Downlosd [THIS](https://beta.crunchyroll.com/de/watch/G69XGG44R/ryomen-sukuna) 
2. Cancel the download after a few seconds.
3. Go to the download path and you'll see that the Job is still running in background.

### Error reports & Screenshots

https://user-images.githubusercontent.com/41828058/188202989-f98f95ff-88fe-4679-a99a-ba45a39e0608.mp4

### Device info

App version: 1.2.0-beta.5 (10100)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

**Comment by JunkFood02** [comment]
Reproduced. We currently kill the process of yt

**Comment by Marco-9456** [comment]
> Reproduced. We currently kill the process of yt-dlp to cancel a download. It seems like yt-dlp just create a new process for downloads from crunchyroll beta
> 
> Edited: crunchyroll beta encrypts their video stream so there's a new process for decrypting, which is out of our control

I see, thank you for the explanation 👍
