### ISSUE TITLE
App not installed as app isn't compatible with your phone

### ISSUE THREAD

**Issue by YannMagnin** [JunkFood02/Seal#1800]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Unable to install the fresh 1.13.1 version, Android 14 show me this message `App not installed as app isn't compatible with your phone`.

### To Reproduce

N/a

### Error reports

App not installed as app isn't compatible with your phone

### Additional context

I tried to uninstall my previous 1.13.0 version of the application, but the same error appears again and again

**Comment by Iowerth** [comment]
Same thing. Moreover I've tried to uninstall previous version to install the latest and after installing I got this:
![Screenshot_2024-10-16-12-28-40-125_com junkfood seal](https://github.com/user-attachments/assets/eb6419a2-7fe4-438e-9295-ce5f2d0b586c) ![Screenshot_2024-10-16-12-28-46-279_com junkfood seal](https://github.com/user-attachments/assets/543faee3-0d6e-4dd7-8cc9-639f4a7f54b6)

**Comment by JunkFood02** [comment]
sorry for the inconvenience, the updated packages have fixed this issue
