### ISSUE TITLE
Cannot link executable libpython.so 

### ISSUE THREAD

**Issue by KindlyOnes** [JunkFood02/Seal#1805]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

There is no Python library or the app cannot find it.

### To Reproduce

1. Copy yt url 
2. Paste
3. See the error

### Error reports

App version: 1.13.1 (11311)
Device information: Android 5.0.1 (API 21)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2024.10.16.232911

URL: https://youtu.be/y3zk7pAhpno?si=c9JKJyahshfq2vX4
CANNOT LINK EXECUTABLE: empty/missing DT_HASH in "/data/app/com.junkfood.seal-1/lib/arm/libpython.so" (built with --hash-style=gnu?)

### Screenshots & Screen Records

![Screenshot_2024-10-18-14-52-11](https://github.com/user-attachments/assets/a99bb253-53a5-483d-8e7c-8c1a6af657ab)

### Additional context

This is old device for using as media player.

**Comment by KindlyOnes** [comment]
I know that support for SDK 21 has been discontinued in Alpha versions.   I would appreciate it if you keep the SDK21 supporting version running until then.

**Comment by JunkFood02** [comment]
We are sorry but due to upstream requirements we have no choice but to drop support for Android 5

**Comment by KindlyOnes** [comment]
> We are sorry but due to upstream requirements we have no choice but to drop support for Android 5

It's not a problem, but can this libpython.so file not found error be fixed?

**Comment by JunkFood02** [comment]
> this libpython.so file not found error be fixed?

We've updated the python in v1.13.1 and it was compiled with minimum supported sdk 24. That's the root of this error
