### ISSUE TITLE
[Feature Request] Please add an option to export the configs (templates) as txt files.

### ISSUE THREAD

**Issue by impulsar** [JunkFood02/Seal#181]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Additional context

It will be really helpful in case there's a reset.

**Comment by JunkFood02** [comment]
Already added in v1.2.0-beta.2
