### ISSUE TITLE
[Bug Report] Command works fine when kept inside a config, but gives error when used as a template

### ISSUE THREAD

**Issue by impulsar** [JunkFood02/Seal#182]
# Describe the bug

This is a command that crops thumbnails to square and embeds them to the audio file. I tried escaping quotes, apostrophes etc. with backslash but no luck.

Here is the command:
--embed-thumbnail

--ppa "ffmpeg: -c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""

--convert-thumbnails png

--add-metadata

-f bestaudio

--extract-audio

-o "%(artist)s - %(title)s.%(ext)s"

--no-mtime

### Error reports & Screenshots

Screenshot:
![Screenshot_2022-09-03-13-15-58-16_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/30704893/188261390-02bf9b49-6680-4854-a4e3-aec5efef0ea8.jpg)

Error Log:
`ERROR: [generic] '\'if(gt(ih,iw),iw,ih)\':\'if(gt(iw,ih),ih,iw)\'""' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'""" ) to search YouTube
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 40: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 39: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 38: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 37: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 36: HTTP Error 404: Not Found
`

### Device info

1.1.0 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]

**Comment by JunkFood02** [comment]
This is a problem with the command parsing. I'll look into it

**Comment by JunkFood02** [comment]
- #112

**Comment by JunkFood02** [comment]
Will be solved in next pre-release version

**Comment by impulsar** [comment]
Thanks alot ✌️

**Comment by JunkFood02** [comment]
```
[
    {
        "id": 0,
        "name": "Crop thumbnail",
        "template": "--embed-thumbnail\n--ppa \"EmbedThumbnail+ffmpeg_o:-c:v png -vf crop=\\\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\\\"\"\n--add-metadata\n--extract-audio\n--audio-format mp3\n--audio-quality 0\n-o \"%(artist)s - %(title)s.%(ext)s\"\n--no-mtime"
    }
]
```

Copy this and import it in the latest version v1.2.0-beta.6

**Comment by impulsar** [comment]
> ```
> [
>     {
>         "id": 0,
>         "name": "Crop thumbnail",
>         "template": "--embed-thumbnail\n--ppa \"EmbedThumbnail+ffmpeg_o:-c:v png -vf crop=\\\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\\\"\"\n--add-metadata\n--extract-audio\n--audio-format mp3\n--audio-quality 0\n-o \"%(artist)s - %(title)s.%(ext)s\"\n--no-mtime"
>     }
> ]
> ```
> 
> Copy this and import it in the latest version v1.2.0-beta.6

Works fine! 👌

On a side note, I would also like to suggest probably a bigger box for editing commands.

**Comment by impulsar** [comment]
A little heads up, I thought I should tell you this in case you wish to implement cropped thumbnails.

The command you provided works fine for mp3, but if fails to crop thumbnail for other formats opus & m4a.

This is the command I came with, it works with all formats -

--embed-thumbnail
--ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
--add-metadata
-f bestaudio
-x
--audio-quality 0
-o "%(artist)s - %(title)s.%(ext)s"
--no-mtime

**Comment by Marco-9456** [comment]
> A little heads up, I thought I should tell you this in case you wish to implement cropped thumbnails.
> 
> The command you provided works fine for mp3, but if fails to crop thumbnail for other formats opus & m4a.
> 
> This is the command I came with, it works with all formats -
> 
> --embed-thumbnail --ppa "ffmpeg: -c:v png -vf crop="'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'"" --add-metadata -f bestaudio -x --audio-quality 0 -o "%(artist)s - %(title)s.%(ext)s" --no-mtime

It doesn't crop the artwork and ends like this: 
```
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
ERROR: Postprocessing: Conversion failed!
```

**Comment by impulsar** [comment]
> > A little heads up, I thought I should tell you this in case you wish to implement cropped thumbnails.
> > The command you provided works fine for mp3, but if fails to crop thumbnail for other formats opus & m4a.
> > This is the command I came with, it works with all formats -
> > --embed-thumbnail --ppa "ffmpeg: -c:v png -vf crop="'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'"" --add-metadata -f bestaudio -x --audio-quality 0 -o "%(artist)s - %(title)s.%(ext)s" --no-mtime
> 
> It doesn't crop the artwork and ends like this:
> 
> ```
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ERROR: Postprocessing: Conversion failed!
> ```

Type backslash in these two positions 
--embed-thumbnail
--ppa "ffmpeg: -c:v png -vf crop=[backslash]"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'[backslash]""
--add-metadata
-f bestaudio
-x
--audio-quality 0
-o "%(artist)s - %(title)s.%(ext)s"
--no-mtime

**Comment by Marco-9456** [comment]
> 

It worked thanks

**Comment by JunkFood02** [comment]
Thx!

**Comment by Marco-9456** [comment]
@impulsar I tried using --cookies option with it but it didn't work

```
--embed-thumbnail
--ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
--add-metadata
-f bestaudio
-x
--audio-quality 0
-o "%(artist)s - %(title)s.%(ext)s"
--no-mtime
--cookies /storage/emulated/0/Download/Seal/YT-Music.txt
```
What am I doing wrong

**Comment by JunkFood02** [comment]
> 

Android prohibits the app to access any other files than the ones Seal creates, including these `cookies.txt` files

**Comment by impulsar** [comment]
> @impulsar I tried using --cookies option with it but it didn't work
> 
> ```
> --embed-thumbnail
> --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> --add-metadata
> -f bestaudio
> -x
> --audio-quality 0
> -o "%(artist)s - %(title)s.%(ext)s"
> --no-mtime
> --cookies /storage/emulated/0/Download/Seal/YT-Music.txt
> ```
> 
> What am I doing wrong

Did cookies work for you earlier? For some weird reason it never worked for me. I tried to get rid of 429 error with cookies but no luck.

I haven't yet tried the inbuilt cookies functionality in the latest beta though.

**Comment by Marco-9456** [comment]
> > @impulsar I tried using --cookies option with it but it didn't work
> > ```
> > --embed-thumbnail
> > --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> > --add-metadata
> > -f bestaudio
> > -x
> > --audio-quality 0
> > -o "%(artist)s - %(title)s.%(ext)s"
> > --no-mtime
> > --cookies /storage/emulated/0/Download/Seal/YT-Music.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What am I doing wrong
> 
> Did cookies work for you earlier? For some weird reason it never worked for me. I tried to get rid of 429 error with cookies but no luck.
> 
> I haven't yet tried the inbuilt cookies functionality in the latest beta though.

Yes see #140

**Comment by impulsar** [comment]
> Android prohibits the app to access any other files than the ones Seal creates, including these `cookies.txt` or `config.txt` files. So my solution for this is to read raw strings input by users, create a empty file and write into it for every download

I generated the cookies file from Seal and edited it with my values, but it didn't work.

Is there any other way to escape 429 error?

**Comment by JunkFood02** [comment]
> Is there any other way to escape 429 error?
I don't think there'll be something can be done on our side since the 429 error means your IP has been block by the YouTube (or other platforms). Maybe use a VPN for an IP change could help

**Comment by impulsar** [comment]
> > > @impulsar I tried using --cookies option with it but it didn't work
> > > ```
> > > --embed-thumbnail
> > > --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> > > --add-metadata
> > > -f bestaudio
> > > -x
> > > --audio-quality 0
> > > -o "%(artist)s - %(title)s.%(ext)s"
> > > --no-mtime
> > > --cookies /storage/emulated/0/Download/Seal/YT-Music.txt
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > What am I doing wrong
> > 
> > 
> > Did cookies work for you earlier? For some weird reason it never worked for me. I tried to get rid of 429 error with cookies but no luck.
> > I haven't yet tried the inbuilt cookies functionality in the latest beta though.
> 
> Yes see #140 But you need to delete the cookies.txt file once a while because it stops working without giving a error. All you need to do is:
> 
>     1. Delete the file
> 
>     2. And run your custom command so that Seal creates a new cookies file
> 
>     3. And then edit the content of it

Your command looks fine to me, I have no idea what's going wrong.

Which version are you on? The latest beta has inbuilt cookies functionality, if you're on it then it might be conflicting with the default cookies.txt. Maybe copy pasting the cookies to Seal might help.

**Comment by Marco-9456** [comment]
> > > > @impulsar I tried using --cookies option with it but it didn't work
> > > > ```
> > > > --embed-thumbnail
> > > > --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> > > > --add-metadata
> > > > -f bestaudio
> > > > -x
> > > > --audio-quality 0
> > > > -o "%(artist)s - %(title)s.%(ext)s"
> > > > --no-mtime
> > > > --cookies /storage/emulated/0/Download/Seal/YT-Music.txt
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > What am I doing wrong
> > > 
> > > 
> > > Did cookies work for you earlier? For some weird reason it never worked for me. I tried to get rid of 429 error with cookies but no luck.
> > > I haven't yet tried the inbuilt cookies functionality in the latest beta though.
> > 
> > 
> > Yes see #140 But you need to delete the cookies.txt file once a while because it stops working without giving a error. All you need to do is:
> > ```
> > 1. Delete the file
> > 
> > 2. And run your custom command so that Seal creates a new cookies file
> > 
> > 3. And then edit the content of it
> > ```
> 
> Your command looks fine to me, I have no idea what's going wrong.
> 
> Which version are you on? The latest beta has inbuilt cookies functionality, if you're on it then it might be conflicting with the default cookies.txt. Maybe copy pasting the cookies to Seal might help.

It worked i just forgot to refresh the cookies file like i mentioned above.

**Comment by impulsar** [comment]
> > > > > @impulsar I tried using --cookies option with it but it didn't work
> > > > > ```
> > > > > --embed-thumbnail
> > > > > --ppa "ffmpeg: -c:v png -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\""
> > > > > --add-metadata
> > > > > -f bestaudio
> > > > > -x
> > > > > --audio-quality 0
> > > > > -o "%(artist)s - %(title)s.%(ext)s"
> > > > > --no-mtime
> > > > > --cookies /storage/emulated/0/Download/Seal/YT-Music.txt
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > What am I doing wrong
> > > > 
> > > > 
> > > > Did cookies work for you earlier? For some weird reason it never worked for me. I tried to get rid of 429 error with cookies but no luck.
> > > > I haven't yet tried the inbuilt cookies functionality in the latest beta though.
> > > 
> > > 
> > > Yes see #140 But you need to delete the cookies.txt file once a while because it stops working without giving a error. All you need to do is:
> > > ```
> > > 1. Delete the file
> > > 
> > > 2. And run your custom command so that Seal creates a new cookies file
> > > 
> > > 3. And then edit the content of it
> > > ```
> > 
> > 
> > Your command looks fine to me, I have no idea what's going wrong.
> > Which version are you on? The latest beta has inbuilt cookies functionality, if you're on it then it might be conflicting with the default cookies.txt. Maybe copy pasting the cookies to Seal might help.
> 
> It worked i just forgot to refresh the cookies file like i mentioned above.

Great. What's your telegram? I'd love to have a chat with you :P

**Comment by Marco-9456** [comment]
@impulsar  

@B_I_G_MO7
