### ISSUE TITLE
[Bug Report] Unable to complete downloading task

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#183]
### Describe the bug

Seal gets stuck on merging stage, though the final file is ready and I can play it.
Cancel button works at this moment.
Tried it with multiple downloads, same behaviour.

### To Reproduce

Download any youtube video.

### Error reports & Screenshots

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/28785698/188262399-7918fd2e-b5e8-4b62-b799-8882756cb842.png)

</details>

### Device info

App version: 1.2.0-beta.5 (10100)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1464 x 720

### Additional context

'Configure before down...', 'Detailed output' and 'Download playlist' settings are on.
yt-dlp v2022.09.01

**Comment by JunkFood02** [comment]
Fixed in 1.2.0-beta.6 (maybe)

**Comment by Botan626** [comment]
I'd say it's fixed, 4 videos downloaded, this issue was not noticed.
