### ISSUE TITLE
--Ffmpeg-location error on oxygenOS 15 beta

### ISSUE THREAD

**Issue by MayankRathee9** [JunkFood02/Seal#1837]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Cannot download audio (music) because of --ffmpeg-location error

### To Reproduce

Just the usual downloading process

### Error reports

App version: 1.13.1 (11312)
Device information: Android 15 (API 35)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2024.10.31.232951

URL: https://youtu.be/gset79KMmt0?feature=shared
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location

### Screenshots & Screen Records

![Screenshot_2024-11-03-00-18-23-79_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/user-attachments/assets/29274de5-c535-45ca-b20c-6dc588116400)

### Additional context

I don't really know why it's happening because the same downloading process worked just fine before

**Comment by JunkFood02** [comment]
you've installed the wrong version, install the arm64-v8a one

**Comment by JunkFood02** [comment]
did you try reinstalling?

**Comment by MayankRathee9** [comment]
> did you try reinstalling?

Yes but nothing happened, the same issue appears

**Comment by kapiljhajhria** [comment]
Same issue with me on oneplus 12

**Comment by Techie-irfu** [comment]
Same issue with me using OnePlus 12 oxygen os 15

**Comment by MayankRathee9** [comment]
@JunkFood02 any fix please? :(

**Comment by nicnms** [comment]
Same issue with OnePlus 12 oxygen OS 15. Everything was okay with oxygen is 14. I updated to oxygen os 15 yesterday and this error keep popping up whenever I try to download videos from YouTube or FB.

**Comment by Fynexfif** [comment]
So it looks like everyone is having same issue with oxygenOS 15, Is it Android 15 issue or just oxygenOs 15, Even apps like YTDLnis and Newpipe are giving same error, they weren't able to find ffmpeg location or something like that.

**Comment by MayankRathee9** [comment]
Idk tbh, OnePlus is one of the first to roll out android 15

**Comment by qingchunnh** [comment]
My phone is oppo X8 pro , also have this problem, also android 15

**Comment by Mr-Blacker** [comment]
My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.

**Comment by nicnms** [comment]
> My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.

How do you install ffmpeg ? I tried installing it via termux but no luck

**Comment by Mr-Blacker** [comment]
> > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> 
> How do you install ffmpeg ? I tried installing it via termux but no luck

I did it with termux:
pkg update
pkg install ffmpeg
(You'll have to input "y" to confirm the installation)
To get installed version:
ffmpeg -version
To get the location where it's installed:
Which ffmpeg

**Comment by Fynexfif** [comment]
This won't work if you have secondary space or on cloned system.

**Comment by JunkFood02** [comment]
https://www.reddit.com/r/termux/comments/1gks9mf/announcement_termux_broken_on_android_15_for/

**Comment by JunkFood02** [comment]
https://github.com/termux/termux-app/issues/4219

**Comment by Hallo951** [comment]
Is there already a solution for the error?

**Comment by Fynexfif** [comment]
This all started with Android 15 update, imma rollback and never upgrade to android 15, so many restrictions OnePlus put on their devices.

**Comment by nicnms** [comment]
> This all started with Android 15 update, imma rollback and never upgrade to android 15, so many restrictions OnePlus put on their devices.

Wait for the subsequent os15 updates bro. Os15 in OnePlus 13 has fixed termux error and ffmpeg location error.

**Comment by borish127** [comment]
> 
> 
> 
> > > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> > 
> > How do you install ffmpeg ? I tried installing it via termux but no luck
> 
> I did it with termux:
> pkg update
> pkg install ffmpeg
> (You'll have to input "y" to confirm the installation)
> To get installed version:
> ffmpeg -version
> To get the location where it's installed:
> Which ffmpeg

And how do you then apply the --ffmpeg-location argument?

**Comment by swapnilwajpe** [comment]
> > > > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> > > 
> > > 
> > > How do you install ffmpeg ? I tried installing it via termux but no luck
> > 
> > 
> > I did it with termux:
> > pkg update
> > pkg install ffmpeg
> > (You'll have to input "y" to confirm the installation)
> > To get installed version:
> > ffmpeg -version
> > To get the location where it's installed:
> > Which ffmpeg
> 
> And how do you then apply the --ffmpeg-location argument?

Fix for Ffmpeg not installed error in Seal on Oxygen OS 15.

    Install Termux from playstore (important as fdroid and GitHub versions don't seem to be working)
    Open Termux and type pkg upgrade.
    Press Y.
    After that type pkg install ffmpeg.
    Press Y.
    After it finished type which ffmpeg.
    Tap and hold on the path and copy it.
    Open Seal and go to settings.
    Goto Custom Command.
    Toggle Use Custom Command.
    Tap on Command Template, and in Label give it any name you like.
    In command template box clear everything and type --ffmpeg-location give a space and paste the copied path from Termux.
    Tap on Done on top right.
    Go back to your main screen of Seal and tap on Download icon.
    For some reason Seal doesn't show and progress on the main screen.
    Tap on Tasks icon on top right and you will see your video being downloaded.
    Access the Seal folder in your internal memory and you will see your video completely downloaded.
Hope this helps

**Comment by borish127** [comment]
> > > > > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> > > > 
> > > > 
> > > > How do you install ffmpeg ? I tried installing it via termux but no luck
> > > 
> > > 
> > > I did it with termux:
> > > pkg update
> > > pkg install ffmpeg
> > > (You'll have to input "y" to confirm the installation)
> > > To get installed version:
> > > ffmpeg -version
> > > To get the location where it's installed:
> > > Which ffmpeg
> > 
> > And how do you then apply the --ffmpeg-location argument?
> 
> Fix for Ffmpeg not installed error in Seal on Oxygen OS 15.
> 
>     Install Termux from playstore (important as fdroid and GitHub versions don't seem to be working)
>     Open Termux and type pkg upgrade.
>     Press Y.
>     After that type pkg install ffmpeg.
>     Press Y.
>     After it finished type which ffmpeg.
>     Tap and hold on the path and copy it.
>     Open Seal and go to settings.
>     Goto Custom Command.
>     Toggle Use Custom Command.
>     Tap on Command Template, and in Label give it any name you like.
>     In command template box clear everything and type --ffmpeg-location give a space and paste the copied path from Termux.
>     Tap on Done on top right.
>     Go back to your main screen of Seal and tap on Download icon.
>     For some reason Seal doesn't show and progress on the main screen.
>     Tap on Tasks icon on top right and you will see your video being downloaded.
>     Access the Seal folder in your internal memory and you will see your video completely downloaded.
> Hope this helps

It worked, thank you.
A last question, Is there a list of all available commands? Because when using the custom command I can't download as audio, or select the format and quality. Knowing the commands I could create templates for each type of task I want to perform. Thank you very much.

**Comment by nicnms** [comment]
> > > > > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> > > > 
> > > > 
> > > > How do you install ffmpeg ? I tried installing it via termux but no luck
> > > 
> > > 
> > > I did it with termux:
> > > pkg update
> > > pkg install ffmpeg
> > > (You'll have to input "y" to confirm the installation)
> > > To get installed version:
> > > ffmpeg -version
> > > To get the location where it's installed:
> > > Which ffmpeg
> > 
> > 
> > And how do you then apply the --ffmpeg-location argument?
> 
> Fix for Ffmpeg not installed error in Seal on Oxygen OS 15.
> 
> ```
> Install Termux from playstore (important as fdroid and GitHub versions don't seem to be working)
> Open Termux and type pkg upgrade.
> Press Y.
> After that type pkg install ffmpeg.
> Press Y.
> After it finished type which ffmpeg.
> Tap and hold on the path and copy it.
> Open Seal and go to settings.
> Goto Custom Command.
> Toggle Use Custom Command.
> Tap on Command Template, and in Label give it any name you like.
> In command template box clear everything and type --ffmpeg-location give a space and paste the copied path from Termux.
> Tap on Done on top right.
> Go back to your main screen of Seal and tap on Download icon.
> For some reason Seal doesn't show and progress on the main screen.
> Tap on Tasks icon on top right and you will see your video being downloaded.
> Access the Seal folder in your internal memory and you will see your video completely downloaded.
> ```
> 
> Hope this helps

Yeah. It definitely works. but download speed is visibly slower. 😅

**Comment by swapnilwajpe** [comment]
> > > > > > My "failed" downloads were in downloads/seal/tmp, you can copy tem out and tag them normally as you would... (I'm trying to find a fix) I was able to install ffmpeg and yt-dlp and they work, maybe it's a "repacking" error inside Seal bc it cant locate ffmpeg. Idk how to tell it where it could find it....) I might be totally wrong tho, so don't take this as a fact.
> > > > > 
> > > > > 
> > > > > How do you install ffmpeg ? I tried installing it via termux but no luck
> > > > 
> > > > 
> > > > I did it with termux:
> > > > pkg update
> > > > pkg install ffmpeg
> > > > (You'll have to input "y" to confirm the installation)
> > > > To get installed version:
> > > > ffmpeg -version
> > > > To get the location where it's installed:
> > > > Which ffmpeg
> > > 
> > > 
> > > And how do you then apply the --ffmpeg-location argument?
> > 
> > 
> > Fix for Ffmpeg not installed error in Seal on Oxygen OS 15.
> > ```
> > Install Termux from playstore (important as fdroid and GitHub versions don't seem to be working)
> > Open Termux and type pkg upgrade.
> > Press Y.
> > After that type pkg install ffmpeg.
> > Press Y.
> > After it finished type which ffmpeg.
> > Tap and hold on the path and copy it.
> > Open Seal and go to settings.
> > Goto Custom Command.
> > Toggle Use Custom Command.
> > Tap on Command Template, and in Label give it any name you like.
> > In command template box clear everything and type --ffmpeg-location give a space and paste the copied path from Termux.
> > Tap on Done on top right.
> > Go back to your main screen of Seal and tap on Download icon.
> > For some reason Seal doesn't show and progress on the main screen.
> > Tap on Tasks icon on top right and you will see your video being downloaded.
> > Access the Seal folder in your internal memory and you will see your video completely downloaded.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps
> 
> It worked, thank you. A last question, I found the list of commands available in yt-dlp, but I'm having the problem that if I use the -x command or some other command, the --ffmpeg-location command stops working. I don't know if there is a specific way to write it to make it work. I managed to get it to work to download the video but not as audio. Thank you very much.

Same here. I just downloaded the video and converted them to audio on my pc. I am trying to find a way around for this as well

**Comment by tdas777** [comment]
I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.

**Comment by Fynexfif** [comment]
> > This all started with Android 15 update, imma rollback and never upgrade to android 15, so many restrictions OnePlus put on their devices.
> 
> Wait for the subsequent os15 updates bro. Os15 in OnePlus 13 has fixed termux error and ffmpeg location error.

Yeah, I waited and just updated, seems they actually did fix everything, every app depending on ffmpeg is working fine now.

**Comment by Fynexfif** [comment]
> I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.
Don't worry, OnePlus fixed this issue in latest update, install the latest update and reinstall those apps, everything should work fine.

**Comment by Fynexfif** [comment]
> I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.

Don't worry, OnePlus fixed that issue in latest update, update your system and reinstall those apps that depend on ffmpeg.

**Comment by tdas777** [comment]
> > I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.
> 
> Don't worry, OnePlus fixed that issue in latest update, I too own OP12 and had this issue, update your system and reinstall those apps that depend on ffmpeg.

My op12 is on CPH2573-15.0.0.206(EXO1), and showing "Version up to date". Which version is ur op12 on?

**Comment by borish127** [comment]
> > > I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.
> > 
> > Don't worry, OnePlus fixed that issue in latest update, I too own OP12 and had this issue, update your system and reinstall those apps that depend on ffmpeg.
> 
> My op12 is on CPH2573-15.0.0.206(EXO1), and showing "Version up to date". Which version is ur op12 on?

They released the version that integrates the November security patch and the AI news. It was deployed in India yesterday and today and will reach the rest of the world next week. Be patient and it will arrive.

**Comment by Fynexfif** [comment]
> > > I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.
> > 
> > 
> > Don't worry, OnePlus fixed that issue in latest update, I too own OP12 and had this issue, update your system and reinstall those apps that depend on ffmpeg.
> 
> My op12 is on CPH2573-15.0.0.206(EXO1), and showing "Version up to date". Which version is ur op12 on?

I have CPH2573-15.0.0.305, it's the version which fixed that issue.

**Comment by tdas777** [comment]
> > > > I'm using Seal on oneplus12 oos15 android 15. I'm facing this issue. I tried the fix to download/install the ffmpeg. But issue is not resolved. Still getting the same error.
> > > 
> > > 
> > > Don't worry, OnePlus fixed that issue in latest update, I too own OP12 and had this issue, update your system and reinstall those apps that depend on ffmpeg.
> > 
> > 
> > My op12 is on CPH2573-15.0.0.206(EXO1), and showing "Version up to date". Which version is ur op12 on?
> 
> They released the version that integrates the November security patch and the AI news. It was deployed in India yesterday and today and will reach the rest of the world next week. Be patient and it will arrive.

Yesterday I updated the op12 with 15.0.0.305, the issue is resolved.

**Comment by MayankRathee9** [comment]
@JunkFood02 please close this thread since the issue has been resolved

**Comment by MayankRathee9** [comment]
Fixed
