### ISSUE TITLE
[Bug Report] - Update Button broken

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#184]
### Describe the bug

The in app update doesn't seem to work

### To Reproduce

1. Go to settings
2. About
3. Click check for updates

### Error reports & Screenshots

![Screenshot_20220903-124853_Seal](https://user-images.githubusercontent.com/41828058/188267078-b6ca9f30-8130-46e6-9c89-65a7ca6450ca.jpg)

### Device info

App version: 1.2.0-beta.5 (10100)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

**Comment by JunkFood02** [comment]
Intended behavior, it'll only check updates for stable versions
