### ISSUE TITLE
Add a button in video card to share downloaded file

### ISSUE THREAD

**Issue by BoBkiNN** [JunkFood02/Seal#1854]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When i want to share downloaded video i need to open it (view) in my gallery and then use share button in gallery app

### Describe the solution you'd like

I need a button to directly open android share menu somewhere inside video card

### Additional context

Maybe something like this:
![Untitled](https://github.com/user-attachments/assets/acc41269-5889-43d9-a616-df9181412572)

**Comment by JunkFood02** [comment]
you can do it in download history

**Comment by BoBkiNN** [comment]
Uh, that's far
