### ISSUE TITLE
[Bug Report] Releases link in README.md

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#186]
### Describe the bug

It opens this link: https://github.com/JunkFood02/Seal/releases/tag/v1.1.0
instead if this: https://github.com/JunkFood02/Seal/releases

**Comment by JunkFood02** [comment]
It opens https://github.com/JunkFood02/Seal/releases/tag/latest, then automatically redirect to the latest release (not pre-release ones).

**Comment by Botan626** [comment]
But readme says "Or download the latest apk from [releases](https://github.com/JunkFood02/Seal/releases/latest)"
Latest apk can be in beta release too.
I think this line should say "Or download the latest release from [releases](https://github.com/JunkFood02/Seal/releases/latest)" then.
