### ISSUE TITLE
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location ERROR: Postprocessing: ffmpeg not found.

### ISSUE THREAD

**Issue by XfiVoid0** [JunkFood02/Seal#1861]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I am getting "ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location" error while downloading audio from YouTube.

### To Reproduce

Android Oxygen 15.0 (Oneplus 12)
Download YouTube video as audio

### Error reports

ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Preprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location
ERROR: Postprocessing: ffmpeg not found. Please install or provide the path using --ffmpeg-location

**Comment by AHITMAN** [comment]
I'm having this same problem with the same Oxygen OS 15 android 15 and I am on OnePlus 12 NA. Tried multiple versions of seal, multiple versions of yt-dlp stable and nightly and all gives same error.

**Comment by giwrgosmant** [comment]
Same issue OnePlus 12 OxygenOS 15, can't download Instagram videos. Previously was working fine.

**Comment by JunkFood02** [comment]
#1837

**Comment by swapnilwajpe** [comment]
Fix for Ffmpeg not installed error in Seal on Oxygen OS 15.
1. Install Termux from playstore (important as fdroid and GitHub versions don't seem to be working)
2. Open Termux and type pkg upgrade.
3. Press Y.
4. After that type pkg install ffmpeg.
5. Press Y.
6. After it finished type which ffmpeg.
7. Tap and hold on the path and copy it.
8. Open Seal and go to settings.
9. Goto Custom Command.
10. Toggle Use Custom Command.
11. Tap on Command Template, and in Label give it any name you like.
12. In command template box clear everything and type --ffmpeg-location give a space and paste the copied path from Termux.
13. Tap on Done on top right.
14. Go back to your main screen of Seal and tap on Download icon.
15. For some reason Seal doesn't show and progress on the main screen.
16. Tap on Tasks icon on top right and you will see your video being downloaded.
17. Access the Seal folder in your internal memory and you will see your video completely downloaded.

**Comment by AHITMAN** [comment]
The above is tested and working in Oxygen OS 15 video downloads but still gives error/warning about ffmpeg not found.
