### ISSUE TITLE
App not installed as app isn't compatible with your phone.  S23U 

### ISSUE THREAD

**Issue by RohithKumarSp** [JunkFood02/Seal#1875]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checked that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Even from F Droid can't install the app on Samsung S23u 

### To Reproduce

Click install apk

### Error reports

App not installed as app isn't compatible with your phone.

### Screenshots & Screen Records

![Screenshot_20241118_224156_Package installer](https://github.com/user-attachments/assets/a289fbcd-1b6e-41ac-8fe2-22561b0cf2cb)

**Comment by seproDev** [comment]
Going by the highlighted link, you probably downloaded the x86_64 version. Your phone (and nearly every other modern phone) is arm64. You need to download the appropriate version.
