### ISSUE TITLE
How to download multiple url from txt file? 

### ISSUE THREAD

**Issue by johnredfield2099** [JunkFood02/Seal#191]
Hi , thank very much for the app. Is amazing,

I want download multiple links url from a text file , in one command 
Usin this custom command
I want to put the Batch download of txt URL list command in this . 

-S res:480 -o "%(upload_date>%Y.%m.%d)s %(title)s.%(ext)s" --no-overwrites

How cant i do  this.

**Comment by JunkFood02** [comment]
This cannot be done in current versions, but you can put the first URl in the "video link" text field and paste rest of them to the last of the template for a workaround like this:

```
-S res:480 -o "%(upload_date>%Y.%m.%d)s %(title)s.%(ext)s" --no-overwrites URL2 URL3 URL4 ...
```
And input `URL1` in the text field to avoid "empty link" error

**Comment by johnredfield2099** [comment]
Thanks .

**Comment by KazKaz90** [comment]
You can use termux as alternative, using the `-i` flag, e.g `yt-dlp -i yt.txt` we already have cookies support and maybe it would be better to also have it in the future as well.

**Comment by Botan626** [comment]
Terrific idea to download videos with links from txt file. Can't wait for it to get implemented.

**Comment by Botan626** [comment]
Terrific idea to download videos with links from txt file. Can't wait for it to get implemented.

**Comment by BobbyESP** [comment]
@JunkFood02 Is working on multi-tasking and it will be avaliable soon. A good to way to download multiple videos i think that should be by pressing "Enter" once by video link, so that would be easy to code (just like searching for "\n")

**Comment by Botan626** [comment]
> wraps

parentheses?

I tried latest commit and Seal successfully downloaded videos, separated by space.
But:
1. I could't understand on this screenshot, custom command is selected or not?

<details>
  <summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/28785698/188734943-cd44d64a-704d-4dd1-8b38-6bec67478faf.png)

</details>

2. On the same screenshot you can see russian words, though english is selected as display language.
3. It would be nice, if we could to choose video quality and format in custom command mode too.
4. Video thumbnail did not change after 2nd video started downloading.

**Comment by JunkFood02** [comment]
0. Linebreaks or `\n` 😂 sorry for my poor vocabulary 
1. This is a new feature which let you store multiple templates and choose one when starting a download.
<details>

![Screenshot_20220907-120346](https://user-images.githubusercontent.com/69683722/188786277-5caeed9e-3fd0-4223-841c-5315e0ee8209.png)

</details>

2. https://github.com/JunkFood02/Seal/issues/192#issuecomment-1236393117

3. Just add the yt-dlp options you need in your templates
4. Information like thumbnails and titles are only necessary in general download mode to store them in the database. We don't store info for custom command mode 
5. Not planned, see https://github.com/JunkFood02/Seal/issues/182#issuecomment-1236119559

**Comment by Botan626** [comment]
1. I meant this part of the screenshot. It's hard to say, whether 'Custom command' button is pressed (selected) or not.
![image](https://user-images.githubusercontent.com/28785698/188836189-12ed7db6-5fa0-4d81-b65c-1e6e6c7cd6bd.png)

4. "We don't store info for custom command mode" --- but Seal showed video thumbnail and title for the 1st video, maybe it could change them when it starts downloading next video?

**Comment by JunkFood02** [comment]
If the "Custom command" option is not enabled, the "New template" and the "Edit" button will grey out. Also, the switch between "Template selection" and "Additional settings" indicates the status changes well so I don't see anything unclear here.

> when it starts downloading next video?

No, we know nothing about which video it is downloading. Seal just executes another separate yt-dlp command to fetch the info **only once**.

**Comment by Botan626** [comment]
Can we not have video thumbnail and title on screen in custom command mode at all then?

**Comment by Saleh-Mumtaz** [comment]
@JunkFood02 
Hi, thank you for your great work!
I wanted to know, is it possible that multiple links in "video link" field to work with the general download mode, not just the custom command? I mean, when i have selected options like auto format selection, legacy best quality audio unlimited, with cookies and subtitle english, seal just perform it on all the video links i have provided
