### ISSUE TITLE
[Bug Report] - Import from clipboard broken

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#192]
### Describe the bug

The import from clipboard button doesn't work on the stabel release

### To Reproduce

1. Go to settings
2. Scroll all the way down
3. Click on Command Template
4. Click on the 3 dots menu
5. Click import from clipboard

### Error reports & Screenshots

<details markdown='1'><summary> **Show Screenshots** </summary>

![Screenshot_20220904-183116_Seal](https://user-images.githubusercontent.com/41828058/188323856-1ee7b050-3209-4119-afc5-691c14836a60.jpg)

</details>

### Device info

App version: 1.2.0 (10200)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

### Additional context

Exporting works fine.

**Comment by JunkFood02** [comment]
Can't reproduce. Could you paste your exported Jason here, or are you importing exactly existing templates?

**Comment by Marco-9456** [comment]
[
    {
        "id": 1,
        "name": "Befehlsvorlage",
        "template": "--no-mtime -f \"bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b\""
    },
    {
        "id": 14,
        "name": "Crunchyroll 🥐",
        "template": "-u \n-p \n--downloader libaria2c.so\n-N 16\n--remux-video mkv\n--sub-lang arME\n--write-sub\n--embed-subs"
    },
    {
        "id": 15,
        "name": "SoundCloud 🔊 ☁️",
        "template": "--ignore-errors --yes-playlist --extract-audio -f bestaudio --audio-quality 0 --embed-thumbnail --parse-metadata %(album,playlist,title)s:%(meta_album)s --embed-metadata -o %(playlist_title)s/%(title).60s.%(ext)s --cookies /storage/emulated/0/Download/Seal/Soundcloud.txt"
    },
    {
        "id": 16,
        "name": "YT-Music Albums 🎶 🎸",
        "template": "--embed-thumbnail\n--ppa \"ffmpeg: -c:v png -vf crop=\\\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\\\"\"\n--add-metadata\n-f ba\n-x\n--audio-quality 0\n-o \"%(artist)s - %(title)s.%(ext)s\"\n--no-mtime\n--cookies /storage/emulated/0/Download/Seal/YT-Music.txt"
    },
    {
        "id": 17,
        "name": "Google Drive",
        "template": "--ignore-errors --yes-playlist\n--no-mtime -f \"bv*+ba/b / bv*+ba/b\"\n--cookies /storage/emulated/0/Download/Seal/Google-Drive.txt"
    },
    {
        "id": 18,
        "name": "YT-Music-Singles 🎶 🎸",
        "template": "--embed-thumbnail\n--ppa \"ffmpeg: -c:v png -vf crop=\\\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\\\"\"\n--add-metadata\n-f bestaudio\n-x\n--audio-quality 0\n-o \"%(artist)s - %(title)s.%(ext)s\"\n--no-mtime\n--cookies /storage/emulated/0/Download/Seal/YT-Music.txt"
    }
]

**Comment by JunkFood02** [comment]
<details>

![Screenshot_20220905-005249](https://user-images.githubusercontent.com/69683722/188324646-802efa59-68fb-4765-a2fa-544135c30bcf.png)


</details>
🤔

**Comment by Marco-9456** [comment]
> ![Screenshot_20220905-005249](https://user-images.githubusercontent.com/69683722/188324646-802efa59-68fb-4765-a2fa-544135c30bcf.png)
> 
> 🤔

Wtf am i doing wrong 🤣🤣

**Comment by Marco-9456** [comment]
@JunkFood02 but I've noticed to other bugs they are old but I didn't mention 
them before because I can't really explain them that well

1. When changing the app language the default command template name doesn't change from the device default language in my case German (Befehlsvorlage)
<details markdown='1'><summary>Show Screenshot</summary>

![Screenshot_20220904-190706_Seal](https://user-images.githubusercontent.com/41828058/188325220-8eeaf488-ac7f-4b57-8e5e-2c24de936d1c.jpg)


</details>

2. Clearing cash and deleting app data and uninstalling doesn't delete the command templates, it also remembers the app settings and templates that I've deleted days ago.
<details markdown='1'><summary>Show screen record</summary>


https://user-images.githubusercontent.com/41828058/188326142-0aa64c98-b96a-49ec-b427-7017e2183917.mp4



</details>

**Comment by senolfndk** [comment]
gives download error
version 1.2.0 
Samsung galaxy a21s
Android 12
![Screenshot_20220904-204153_Seal](https://user-images.githubusercontent.com/52818836/188326674-f079ae9c-f9de-49e0-bef3-ac1f304a5f6f.jpg)

**Comment by Marco-9456** [comment]
> gives download error version 1.2.0 Samsung galaxy a21s Android 12 ![Screenshot_20220904-204153_Seal](https://user-images.githubusercontent.com/52818836/188326674-f079ae9c-f9de-49e0-bef3-ac1f304a5f6f.jpg)

Create a new issue please

**Comment by senolfndk** [comment]
> > 1.2.0 sürümü indirme hatası veriyor Samsung galaxy a21s Android 12
> 
> Göstermek
> Yeni bir konu oluşturun lütfen

ok

**Comment by JunkFood02** [comment]
The default template is created in the first launch only to avoid an empty database, so its label would be initialized as the system language without changing.
For the data, I'd say it's something about the OEM or the ROM manufacturer

**Comment by Marco-9456** [comment]
> For the data, I'd say it's something about the OEM or the ROM manufacturer

Thanks for the info
