### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by senolfndk** [JunkFood02/Seal#193]
### Describe the bug

gives download error

### Error reports & Screenshots

gives download error
![Screenshot_20220904-204153_Seal](https://user-images.githubusercontent.com/52818836/188327237-4ea73908-891e-4846-81ea-402965a42920.jpg)

### Device info

![Screenshot_20220904-205703_Settings](https://user-images.githubusercontent.com/52818836/188327259-ff8d4eb1-9538-4fbe-8431-15551c397c61.jpg)
![Screenshot_20220904-205713_Settings](https://user-images.githubusercontent.com/52818836/188327263-1512610d-4b10-452d-b7a3-3aa9e8de51c9.jpg)

### Additional context

![Screenshot_20220904-205733_Seal](https://user-images.githubusercontent.com/52818836/188327281-1589f9e9-ba70-4685-a9ff-919a0f8cf1e9.jpg)

**Comment by senolfndk** [comment]
https://user-images.githubusercontent.com/52818836/188327824-3c01bc1d-76ab-465c-9a2a-984d351a3d8d.mp4

**Comment by JunkFood02** [comment]
We're not able to save files to the `Video/` on Android 10+, please switch to `Download/`
