### ISSUE TITLE
--max-downloads NUMBER gives blank error

### ISSUE THREAD

**Issue by KazKaz90** [JunkFood02/Seal#196]
Using `--max-downloads NUMBER` gives a blank error when it will reach the input number. Also probably a suggestion to disable automatic clipboard error would be great.

**Comment by JunkFood02** [comment]
Try v1.3.0-beta.1

**Comment by KazKaz90** [comment]
> Try v1.3.0-beta.1

Kinda works but not actually, it's stuck

Screenshots
![Screenshot_20220908-071027.png](https://user-images.githubusercontent.com/90075041/188998949-d819b189-77c6-44bc-afcc-f260136f8117.png)

![Screenshot_20220908-071041.png](https://user-images.githubusercontent.com/90075041/188998977-d8321c13-65f5-4431-b69d-4645eb7d0da6.png)

**Comment by KazKaz90** [comment]
Using latest stable release, the app is crashing when  `--max-downloads NUMBER` reached the input `NUMBER` 😅

**Comment by JunkFood02** [comment]
Idk but maybe you download the wrong APK right after I uploaded it, which I have already replaced with the right one?
