### ISSUE TITLE
Editable metadata

### ISSUE THREAD

**Issue by arijit4** [JunkFood02/Seal#200]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The youtube music video title contains a lot of text like title, author, type (lyric/remix etc) which I don't usually need.
Also the youtube channel name is set as the author of a mp3 file which is not always correct.

### Describe the solution you'd like

It would be great if I had control over the title, date, lyric and all other metadata. This might not be available in yt-dlp. But maybe with some other?

**Comment by JunkFood02** [comment]
Haven't used things like this but 
- https://github.com/JunkFood02/Seal/issues/112#issuecomment-1213432760

**Comment by arijit4** [comment]
I recently noticed that `mutagen` is being used which is antag editor.

I was suggesting if there could be a promt to edit audio tags like `lyrics, album, title, author...`

**Comment by arijit4** [comment]
@JunkFood02 is it going to happen?😶‍🌫️

**Comment by JunkFood02** [comment]
Editing metadata isn't this app's primary function, so I'll suggest to use another app like the one I've mentioned earlier to do this
