### ISSUE TITLE
[Bug Report] Can't paste multiline video links

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#209]
### Describe the bug

In custom command mode I copy video links in this format:
videolinkurl01
videolinkurl02
videolinkurl03
videolinkurl04
videolinkurl05

Seal pastes only 1st URL with a button, but if I click Paste on the screenshot below, all links are copied.
![image](https://user-images.githubusercontent.com/28785698/189335156-8a379684-dabf-4ecb-9045-cec7ecf33789.png)

### Device info

App version: 1.3.0-beta.1 (10210)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1464 x 720

**Comment by JunkFood02** [comment]
Currently, the paste button will match only the first link that appeared in the clipboard. This is for some apps whose share content contains not only links but also some other text
