### ISSUE TITLE
请求功能：视频下载合并完成后，移除原始的视频流和音频流。

### ISSUE THREAD

**Issue by din1028** [JunkFood02/Seal#211]
如题，不然文件夹里混一堆视频音频文件，比较麻烦。

**Comment by JunkFood02** [comment]
是华为/荣耀手机吗？

**Comment by din1028** [comment]
> 是华为/荣耀手机吗？

是的，鸿蒙系统

**Comment by JunkFood02** [comment]
所有的临时文件都会被应用删除，但鸿蒙系统对 Android 的文件系统实现做了修改，会阻止应用自行删除文件，我个人手头也没有鸿蒙系统的设备，对于这个问题暂时没有好的解决方法

**Comment by JunkFood02** [comment]
请尝试安装 GitHub Actions 里的[这个安装包](https://github.com/JunkFood02/Seal/actions/runs/3032663531)，我对鸿蒙的这个功能的实现做了一些猜测，但手头没有鸿蒙设备，还请麻烦帮我验证一下 :thinking:

**Comment by din1028** [comment]
> 请尝试安装 GitHub Actions 里的 [这个安装包](https://github.com/JunkFood02/Seal/suites/8235785178/artifacts/359618552)，我对鸿蒙的这个功能的实现做了一些猜测，但手头没有鸿蒙设备，还请麻烦帮我验证一下 🤔

测试下载了两个视频和一个音频，能正常删除临时文件
