### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by crumhirnd** [JunkFood02/Seal#212]
### Describe the bug

--embed-thumbnail custom command does not work

### To Reproduce

Set --embed-thumbnail as custom command and download the video.

After downloading, the video disappears.

### Device info

App version: 1.3.0-beta.2 (10210)
Device information: Android 10 (API 29)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2148 x 1080

**Comment by JunkFood02** [comment]
Please provide the link to the video

**Comment by crumhirnd** [comment]
I just checked and it seems the missing video was a one off. Embed
thumbnail does not seem to work though, tested with both shorts and regular
length videos.

https://youtu.be/Cb8AuIL86eE

https://youtube.com/shorts/ctGEF9AAM3k

**Comment by JunkFood02** [comment]
Cannot reproduce this problem. Maybe you can try adding `--compat-options embed-thumbnail-atomicparsley`
