### ISSUE TITLE
Clear all notifications

### ISSUE THREAD

**Issue by rancidfrog** [JunkFood02/Seal#214]
Currently after using seal to download many files, they are all bundled into one, but there is no way to clear all.
You have to swipe one by one, swiping main collapsible notification does not work either.
Having a clear all would be helpful

**Comment by JunkFood02** [comment]
Try [this build](https://github.com/JunkFood02/Seal/suites/8251436570/artifacts/360698614), toggle off the notification switch in settings will also clear all of the notifications
