### ISSUE TITLE
[Feature Request] Export/Import song list

### ISSUE THREAD

**Issue by JustFanta01** [JunkFood02/Seal#220]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Hello, I'm a web developer and unfortunately I'm still a beginner in the android world.
Some time ago I started a project in python that starting from a list of youtube links saved on a file (practically the equivalent of a youtube playlist) downloaded all the songs and kept them synchronized with the _local->remote_ and _remote->local_ variations.

Now I wanted to convert this python script into an android application for convenience, your application has almost everything I had in mind to develop, only one feature is missing: the ability to backup/restore the songs database.
Could I help in any way? I downloaded the source code and am trying to work on it.

### Describe the solution you'd like

The ability to export/import the song list.
In case of new installation re-download the songs not already present in the device.

**Comment by JunkFood02** [comment]
Export/import can be done simply by converting objects in database into/from json. If you have a basic understanding of Kotlin/Android, you can take a look at how Seal [handles templates  ](https://github.com/JunkFood02/Seal/blob/main/app/src/main/java/com/junkfood/seal/util/DatabaseUtil.kt#L57)
