### ISSUE TITLE
Can't download from discoveryplus.com/it

### ISSUE THREAD

**Issue by Gittore54** [JunkFood02/Seal#222]
Hi,
I've tried to download from this link https://www.discoveryplus.com/it/video/fratelli-di-crozza/stagione-6-episodio-13, I've also copypasted all from cookies.txt in Netscape format but It tells me that It isn't if I use a custom command and that cookies are needed if I don't, I've exported them from Firefox Nightly for Android extension Cookie Quick Manager.

An account is needed, tell me if you need it, but you can create a free one and try it for yourself with a custom command, but same "free" non DRM videos are also available in other countries I think.

**Comment by JunkFood02** [comment]
Please organize your words better. I don't get what your mean about the cookies.

**Comment by Gittore54** [comment]
Reading from previous issues I tried to copypaste all from cookies.txt file exported in Netscape format in related option in Seal settings as said but when I try to download with custom command It says that It isn't in Netscape format.

**Comment by JunkFood02** [comment]
If you're okay with sharing account credentials for testing, send it to my email junkfood02@proton.me
