### ISSUE TITLE
Downloading shorts from the app doesn't work

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#227]

**Comment by JunkFood02** [comment]
Please provide the link to the video

**Comment by BobbyESP** [comment]
For me, shorts downloading works fine. Pls go to Settings > Downloads and click Yt-dlp version to check that you have the last version of the library. Also can you tell us if you're using Custom Commands? Thank you!

**Comment by BobbyESP** [comment]
Try to download some video/s, if you can, with a VPN active in your phone just for testing.

**Comment by BobbyESP** [comment]
No problem! Thank you for asking. So that maybe it's a regional/ISP issue :(
If you have any other problem, please, send us another issue. All Feedback is welcome!
