### ISSUE TITLE
pls add .flac for songs

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#228]
opus bad format for quality

**Comment by JunkFood02** [comment]
Converting compressed format to lossless format is not a good idea. This cannot bring any improvement for audio quality but only cause increase in size of files. For most cases, the original format is the best one you can get

**Comment by chris122380** [comment]
> Converting lossy format to lossless format is not a good idea. This cannot bring any improvement for audio quality but only cause increase in size of files. For most cases, the original format is the best one you can get

In this case it's about the file format not the quality. Sometimes it's about having consistency in file formats not necessarily in the quality. 

If the YouTube video or audio quality is poor to begin with then the file format really shouldn't matter.
