### ISSUE TITLE
Extract only url's

### ISSUE THREAD

**Issue by Doktor-X** [JunkFood02/Seal#23]
Hello, i just installed your app and im wondering is it possible to add function to just extract url of video or audio stream and display it so that then this direct url can be used in something else

**Comment by Doktor-X** [comment]
Ok, i'll guess i'll still use dvd then

**Comment by JunkFood02** [comment]
I think you can achieve this with v1.7.0 now. 🤔

**Comment by Doktor-X** [comment]
Sorry, but i dont see any obvious way to do that what i want

**Comment by JunkFood02** [comment]
> Long-press to copy the stream URL of the media in the format selection page

Added in beta.4,

**Comment by Doktor-X** [comment]
Ah ok, ill give it a try
