### ISSUE TITLE
Gray screen

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#231]
### Describe the bug

When I rotate the screen 2 times, I get a gray screen. It can be fixed by pressing "back" 2 times and exiting the app. After restarting the app, everything works

In the menu where you enter the link this is fixed, but it also shows up for a second. Elsewhere it is not fixed

### To Reproduce

Rotate the screen twice in "settings"

### Device info

App version: 1.3.1 (10310)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2263 x 1078
MIUI 13.0.5

**Comment by BobbyESP** [comment]
See #177 and #173. This is a MIUI problem, at least in Global and EEA ROMs

**Comment by BobbyESP** [comment]
There'a quick fix that i've made in #194, but it just works at the start of the app

**Comment by BobbyESP** [comment]
Because i thought that it happened just at the start of the app

**Comment by BobbyESP** [comment]
Can you check if this still happens with light mode?

**Comment by BobbyESP** [comment]
Okay, thanks. I've also tried in my Xiaomi and happens the same. I'm gonna do some research and i tell you.

**Comment by BobbyESP** [comment]
I found [this](https://stackoverflow.com/questions/71363125/compose-navhost-start-the-white-screen/72119807#72119807) but the thing is that we don't handle the navigation that way, so need more research

**Comment by BobbyESP** [comment]
Maybe

**Comment by JunkFood02** [comment]
> When I rotate the screen 2 times, I get a gray screen. It can be fixed by pressing "back" 2 times and exiting the app. After restarting the app, everything works

Does manually swiping (not tapping) on the screen work?

**Comment by BobbyESP** [comment]
If it's in the same case as me, this is what happens.
https://user-images.githubusercontent.com/60316747/190851268-5e350865-e1c3-481f-83ed-6e17daac6386.mp4
