### ISSUE TITLE
Crash everytime I click download

### ISSUE THREAD

**Issue by freMea** [JunkFood02/Seal#232]
### Describe the bug

Crashes no matter the link. Download list is empty. No log or output.

### To Reproduce

0. Download last version of yt-dlp
1. Paste a link (tested with https://youtu.be/JR9jhfDhQa0)
2. Click download

The main app disappears. Only a toast *fetching video info...* is displayed then nothing.

### Error reports & Screenshots

I enabled detailed output. But nothing is shown. I search entry for `com.junkfood.seal` in `/storage/emulated/0/Android/data`. The directory doesn't exist. So I went to `/data/data/com.junkfood.seal` to see if a log exist. Nope.

If it writes a log, please tell me where to find it.

Meanwhile here is a filtered logcat: https://pastebin.com/BP6MZRtn

Started just before clicking download and right after the crash.

I'm surprised the didn't ask storage permission. It can't have any. Is it normal?
![iMarkup_20220917_015641](https://user-images.githubusercontent.com/22337329/190832006-46cd7868-61be-4668-a475-fb4a6a07c4a0.jpg)

### Device info

App version: 1.3.1 (10310)
Device information: Android 11 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2074 x 1079

### Additional context

Tested with the two releases:
- Seal-1.3.1-armeabi-v7a-release.apk
- Seal-1.3.1-arm64-v8a-release.apk

_No response_

**Comment by JunkFood02** [comment]
Thanks for you detailed bug report!
According to the log attached, the problem seems to be caused by a Toast and cannot reproduced with my Emulator (API 30)
I've disabled all of the Toast in the app [in this build](https://github.com/JunkFood02/Seal/actions/runs/3072165478), please install it and see if it works

**Comment by freMea** [comment]
Still crashes. It seems the problem is the icon in status bar.
![Screenshot_20220917-084744_Logcat_Reader_1.png](https://user-images.githubusercontent.com/22337329/190844478-2bded2f3-a7e3-4713-89fe-479551f106c6.png)

**Comment by JunkFood02** [comment]
https://github.com/JunkFood02/Seal/actions/runs/3072648935

**Comment by freMea** [comment]
> https://github.com/JunkFood02/Seal/actions/runs/3072648935

👍 Yes at last. No crash.
