### ISSUE TITLE
[Bug Report]米游社档案馆视频下载合并过程错误

### ISSUE THREAD

**Issue by MisakaSakura** [JunkFood02/Seal#233]
### Describe the bug

我其实不太清楚这个软件支不支持米游社视频的下载，但是抱着试一试的心态下了崩3档案馆的《因你而在的故事》没想到还真成功了![成功案例](https://i.imgur.com/ZezzSuQ.jpg)
![圣芙蕾雅档案馆视频](https://i.imgur.com/r6gT9UR.jpg)
然后当我尝试下载第二个视频的时候，大概是合并过程出错了![正常下载过程](https://i.imgur.com/lexGTpo.jpg)
![下载完成后的报错](https://i.imgur.com/G3S39bM.jpg)

> WARNING: [generic] Falling back on generic information extractor
ERROR: [Errno 17] File exists: '/storage/emulated/0/Download/Seal/detail (1).png'

不知道作者能不能查下原因修复一下，如果能够提供支持下载就更好了（目前资源获取是没问题的，除开提到的问题外只是没有获取到视频标题和封面）   

### Error reports & Screenshots

WARNING: [generic] Falling back on generic information extractor
ERROR: [Errno 17] File exists: '/storage/emulated/0/Download/Seal/detail (1).png'

### Device info

![Screenshot_2022-09-17-14-55-54-17_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/30547550/190844738-d7365ff8-6c08-48a2-b905-0cc655c15893.jpg)
系统信息

**Comment by JunkFood02** [comment]
看起来不是出错，yt-dlp目前不支持这个站点，下载这个链接使用的是通用提取器，所以标题和封面之类的信息提取不出来是正常的，这个报错应该是下载视频封面还是什么图片的时候发生的错误

**Comment by MisakaSakura** [comment]
@JunkFood02 意思是只能寄希望于上游适配吗，修不了的话我就关闭issue了
