### ISSUE TITLE
[Feature Request] Rename option before downloading

### ISSUE THREAD

**Issue by Fred-Vatin** [JunkFood02/Seal#234]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Some files from HLS have no title. Just a suite of random chars.

### Describe the solution you'd like

When clicking the download button, add an input in the dialog prefiled by the title or the file name it detects so user can edit it before.

**Comment by BobbyESP** [comment]
This can be done with custom commands. Anyway, i'll make it an option soon.

**Comment by venkat2305** [comment]
> This can be done with custom commands.

Please start a discussion explaining how to do it with custom commands. Many who use seal are not aware of custom commands and the solution to every issue users face is custom commands it's not a smooth experience

**Comment by JunkFood02** [comment]
> ...custom commands it's not a smooth experience

Custom commands will never have a smooth user experience. It's for "advanced" users who already know what yt-dlp is and how to use it. If someone considers picking the right one from the tons of options of yt-dlp is tough, then developing and migrating such options into a GUI with smooth UX is much more difficult.

I understand that this kind of issue is quite annoying, but hard solutions are better than none. If you want a feature to be implemented in Seal, submit an issue or vote for it.

**Comment by Marco-9456** [comment]
> > This can be done with custom commands.
> 
> Please start a discussion explaining how to do it with custom commands. Many who use seal are not aware of custom commands and the solution to every issue users face is custom commands it's not a smooth experience

Here you go https://github.com/JunkFood02/Seal/discussions/454#discussion-4694105

**Comment by soymadip** [comment]
> > ...custom commands it's not a smooth experience
> 
> Custom commands will never have a smooth user experience. It's for "advanced" users who already know what yt-dlp is and how to use it. If someone considers picking the right one from the tons of options of yt-dlp is tough, then developing and migrating such options into a GUI with smooth UX is much more difficult.
> 
> I understand that this kind of issue is quite annoying, but hard solutions are better than none. If you want a feature to be implemented in Seal, submit an issue or vote for it.

Someone implemented it  and opened pull request :- 
https://github.com/JunkFood02/Seal/pull/290
Please accept the pull request
