### ISSUE TITLE
[Bug Report] A11Y: Seal doesn't announce the status of checkboxes in settings when using TalkBack screen reader

### ISSUE THREAD

**Issue by schulle4u** [JunkFood02/Seal#237]
### Describe the bug

A11Y: Seal doesn't announce the states of checkboxes in settings when using TalkBack screen reader

When using Seal with the TalkBack screenreader, the status of certain options (checked or unchecked) is not reported to the accessibility service. This for example applies to options found under download settings, e. g. download as audio. 

### To Reproduce

1. Open Android settings, go to accessibility and start the TalkBack screen reader. Be aware that TalkBack changes the behaviour of gestures, use a double-tab to activate elements.
2. Open Seal, tab the settings page and go to download settings.
3. Try to double-tab the "download as audio" option. TalkBack will not report the status of this and other options.

### Device info

App version: 1.3.0-(F-Droid) (10300)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2155 x 1079

**Comment by JunkFood02** [comment]
Thanks for your report. I'll look into it asap

**Comment by JunkFood02** [comment]
Please give a try with [this build](https://github.com/JunkFood02/Seal/actions/runs/3076590981)

**Comment by schulle4u** [comment]
wow, that was quick. Many thanks for your efforts, option selection now works as expected. 👍 Only two more glitches I stumpled on: 

* In dialogs such as the "convert audio" and theme selection, the selected entry still has no selection status spoken. The selection however can be seen after hitting confirm, so this is just a minor issue. 
* There are a lot of completely unlabelled buttons On top of the display settings page which I'm not sure what they do, probably something related to color settings?

**Comment by JunkFood02** [comment]
I have completed refactoring to improve the accessibility of Seal, including removing redundant semantics, optimizing switches and checkbox selection states, etc. Please install [this build](https://github.com/JunkFood02/Seal/actions/runs/3078044801). Feel free to reach out to me if you have any other suggestions for a11y. 😺

**Comment by schulle4u** [comment]
Thanks, now even better than expected. No further issues for the moment, so I'm approving this for the next release. 🙂
