### ISSUE TITLE
[Feature Request] Changelogs in Fdroid

### ISSUE THREAD

**Issue by Donkey-Doug** [JunkFood02/Seal#239]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Quality of life update

### Describe the solution you'd like

Make it possible fdroid can access the changelogs.

### Video link

-

### Additional context

-

**Comment by JunkFood02** [comment]
In fact, I don't know how F-Droid deals with the changelogs. I can only see changelogs for the latest version on their websites but not on their client.

**Comment by Donkey-Doug** [comment]
Short discussion here: https://github.com/deckerst/aves/issues/154

**Comment by JunkFood02** [comment]
> I can only see changelogs for the latest version on their websites but not on their client.

If the changelogs are not shown on their apps, I think it's not necessary to ship the changelogs with the releases
