### ISSUE TITLE
[Bug Report] - Text Field bug

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#242]
### Describe the bug

The bug appears while creating or editing a Command Template

### To Reproduce

1. Edit or create a long command template.
2. Long press to highlight the template
3. Move the first or the last pointer
4. As a result the "text zoom tool" will appear and stuck.

### Error reports & Screenshots

<details markdown='1'><summary> Show Screen record </summary>

https://user-images.githubusercontent.com/41828058/191105458-912c5615-d938-4b81-b778-27fa77e52405.mp4

https://user-images.githubusercontent.com/41828058/191108666-d11152c0-086a-499f-8018-95406170c065.mp4

</details>

### Device info

App version: 1.3.2 (10320)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

### Additional context

This bug is old but I didn't have time to report it.

**Comment by BobbyESP** [comment]
Thanks for the info and the screen recordings, we'll take a look into it as fast as possible. Anyway, it seems to not be a very hard to solve problem.

**Comment by JunkFood02** [comment]
After some tests, I think the problem is on Google's side (again), and there's no too much we can do for now 🤕

**Comment by BobbyESP** [comment]
Yeah, probably Jetpack Compose thing...

**Comment by Marco-9456** [comment]
> After some tests, I think the problem is on Google's side (again), and there's no too much we can do for now 🤕

Thanks for the info brother,
I feel like google is just creating bugs with every android version they made and just provide new features without focusing on solving bugs.
Damn you google

**Comment by BobbyESP** [comment]
I think this might help https://stackoverflow.com/questions/72833025/jetpack-compose-textfield-doenst-lose-focus-on-click-outside-of-it

**Comment by JunkFood02** [comment]
There's nothing to blame Google in the meantime 😌 Without them creating such a great UI toolkit (Jetpack Compose), there'll be no such fluent development experience for Seal or the whole app itself. This is a very new framework and the Material You library hasn't been stable yet (moving from alpha to beta recently). Seal introduces these libraries even before Google does in their own apps

**Comment by BobbyESP** [comment]
Yeah kekw. They still preffer xml framework
