### ISSUE TITLE
an option on whether to crop the audio covers or not

### ISSUE THREAD

**Issue by rickdtc** [JunkFood02/Seal#247]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

In update 1.3.0 album art on audio was set to be cropped by default.

It would be really appreciated if a check box or something was added to let the user decide if it really should be cropped or not.

**Comment by BobbyESP** [comment]
If #248 is approved, you'll be able to choose!

**Comment by rickdtc** [comment]
Thanks, hope it gets merged, sorry for replying late

**Comment by BobbyESP** [comment]
No problem!
