### ISSUE TITLE
SD card support

### ISSUE THREAD

**Issue by crumhirnd** [JunkFood02/Seal#25]
Please add support for downloading to SD cards like DVD.

**Comment by JunkFood02** [comment]
Thanks for your suggestion. This App directly download video to a directory. But directly writing to SD card is not supported in Android. Meanwhile dvd copy the downloaded file into destination directory. I would like to try this but I don't have a device with SD card, so it may take some time for the SD card support.

**Comment by JunkFood02** [comment]
After a bit research, it turns out that direct writing to SD card become impossible since Android 4.4+.
So the only thing we can do is just copy the files from internal storage to SD card, and delete the original files (just like what dvd does). Meanwhile you can move them to SD card manually. If you still want this to be done automatically, please let me know.

**Comment by crumhirnd** [comment]
It would be nice to have this feature, though its fine if its too much
trouble.

**Comment by ValjarVII** [comment]
> After a bit research, it turns out that direct writing to SD card become impossible since Android 4.4+. So the only thing we can do is just copy the files from internal storage to SD card, and delete the original files (just like what dvd does). Meanwhile you can move them to SD card manually. If you still want this to be done automatically, please let me know.

How can I automatize this process you described? I don't want to set an alarm once a week just for moving audio files to SD.

**Comment by JunkFood02** [comment]
@ValjarVII We've already implemented this feature. Go to Settings - Download directory - Tap on SD card directory to set it up

**Comment by ValjarVII** [comment]
Yes, but my phone didn't let me. I chose a different phone. It works now.
Thank you.
