### ISSUE TITLE
Every video outputs as an mkv. file

### ISSUE THREAD

**Issue by SamuelSHrk** [JunkFood02/Seal#252]
No matter what video format I choose (MP4 or webm) it's all mkv for some reason.

**Comment by JunkFood02** [comment]
Please provide the link to the video

**Comment by SamuelSHrk** [comment]
> Please provide the link to the video

It's to every video though, I tried it with some reddit videos which was awesome cuz it worked but they outputted as mkv files regardless of audio format. I seen it with YouTube videos as well. I'm on Android 11 and got it off F-Droid.

**Comment by JunkFood02** [comment]
If you enabled "Embed subtitles", it would remux every video into mkv. If not so, maybe there's really only mkv format provided.

**Comment by SamuelSHrk** [comment]
> If you enabled "Embed subtitles", it would remux every video into mkv. If not so, maybe there's really only mkv format provided.

Ah so that's the reason? Only subtitles work with mkv?

**Comment by SamuelSHrk** [comment]
> > > If you enabled "Embed subtitles", it would remux every video into mkv. If not so, maybe there's really only mkv format provided.
> > 
> > 
> > Ah so that's the reason? Only subtitles work with mkv?
> 
> No subtitles work with other video containers like `mp4` and `webm` but subtitles in format like `.ass` will not work properly with these containers that's why Seal is `remuxing` it to `mkv` which works perfectly in my opinion with almost every subtitle format. But if you really want it in `mp4` or other containers then you can always use `a Custom Command` to do it For more information on this topic see this #102

ah ok i just didnt know why everything was in mkv. i was trying to upload it to Discord but no embed would display but thats a separate issue for a separate software. Thanks though!
