### ISSUE TITLE
Disable Download History Recording

### ISSUE THREAD

**Issue by rjm831** [JunkFood02/Seal#257]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

An option to disable any record-keeping of downloads.  I realize the download history can be erased, but privacy-wise would be better if no record was kept at all.

**Comment by JunkFood02** [comment]
Added in v1.3.3
