### ISSUE TITLE
My experience with Seal! One of the best!

### ISSUE THREAD

**Issue by Fehertukor** [JunkFood02/Seal#26]
Hello @JunkFood02 !

First of all thank you for your time in this project!
Beautiful, clean, user-friendly 
and more importantly it is suggestable to others!
(Dark mode, custom colors, download personalisation ...
)
1. One suggestion to be more noob friendly, think about renaming:
Extract audio to save as audio.

2. Would it be possible to save audios in separate folder (I don't want to mix it with video files for podcast reasons)

3. In the downloaded playlist.
When I select to remove a file, add an option to always remember to delete files.

+ It works with Twitch too!

Thank you again!

**Comment by JunkFood02** [comment]
I'm more than happy you like it! 😊 And thanks for your feature requests, I would consider including them in next updates.

**Comment by JunkFood02** [comment]
Check [v0.0.9-alpha03](https://github.com/JunkFood02/Seal/releases/tag/v0.0.9-alpha03)

**Comment by JunkFood02** [comment]
Make sense. This would come with a UI update, so stay tuned for it. Btw I'm currently working on an RSS podcast app. 😄

**Comment by Fehertukor** [comment]
Please @ me if it is ready to test:)!

**Comment by Fehertukor** [comment]
Thank you!
I have tested the v0.0.9-alpha04 and I could set the new audio location but when I tried to download it gave me this!
![audio download bug](https://user-images.githubusercontent.com/68952092/176410868-bb1de8ee-e78c-491c-af9b-c6d8962a3d2b.jpg)
I tried other new locations and the old one download/seal got the same couldn't download the thumbnail bug.
But as a video everything downloads as charm!

**Comment by JunkFood02** [comment]
Could you provide a link to the video which causes error?

**Comment by Fehertukor** [comment]
https://www.youtube.com/watch?v=1ZGIfsZ4YiE

I have to correct myself because in the original directory downloads/seal the audio downloads works.
But in any other location get that bug.

**Comment by JunkFood02** [comment]
Reproduced successfully on my side. Let me look into this. 🤔

**Comment by JunkFood02** [comment]
I'll close this and open a new one for SAF support
