### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by adarshmk354** [JunkFood02/Seal#264]
### Describe the bug

can't change the quality,
![Screenshot_20221006-213623_Seal](https://user-images.githubusercontent.com/115174923/194363327-b706770b-037a-4479-a8fd-11537597bfca.png)
when we press to change quality no option to change quality is shown

**Comment by Marco-9456** [comment]
> ### Describe the bug
> can't change the quality, ![Screenshot_20221006-213623_Seal](https://user-images.githubusercontent.com/115174923/194363327-b706770b-037a-4479-a8fd-11537597bfca.png) when we press to change quality no option to change quality is shown
> 
> ### To Reproduce
> _No response_
> 
> ### Error reports & Screenshots
> _No response_
> 
> ### Device info
> _No response_
> 
> ### Additional context
> _No response_


See this https://github.com/JunkFood02/Seal/issues/261#issuecomment-1265658404

**Comment by JunkFood02** [comment]
If you're using F-Droid builds, please wait for the v1.3.4 release
