### ISSUE TITLE
[Bug Report] Undesired behavior on tapping on a download that has been deleted from filesystem

### ISSUE THREAD

**Issue by cwpwd** [JunkFood02/Seal#267]
### Describe the bug

If a downloaded item which has been deleted via another app is tapped, the app brings a system's app choice dialog. I consider this as unexpected. 

### To Reproduce

1. download an item
2. delete it from another app, like a file manager
3. tap on that item in the Downloads list

### Error reports & Screenshots

Error reports: none
Screenshots: if asked

### Device info

version: latest github

**Comment by JunkFood02** [comment]
Try installing [this build](https://github.com/JunkFood02/Seal/actions/runs/3203935229)
