### ISSUE TITLE
b站合集视频下载错误

### ISSUE THREAD

**Issue by yijiluokong** [JunkFood02/Seal#276]
### Describe the bug

当我用手机端b站客户端分享到seal下载时，只能下载合集中第一个视频，无论我是选中了合集里哪个视频，再分享到seal去下载

### To Reproduce

1. 在手机端b站客户端的合集视频界面选择分享到seal下载，或者在分享页面选择复制链接，再复制到seal下载，比如这个合集：https://b23.tv/oSnddv3
2. 只能分析出并下载合集中的第一个视频，无论我在分享前选中的是哪个视频

### Error reports & Screenshots

并没有显示错误报告，但解析错误和下载错误确实存在

### Device info

App version: 1.3.5 (10350)
Device information: Android 10 (API 29)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2112 x 1078

### Additional context

这个问题只存在于手机端b站客户端，网页版没有这个问题，可以正确解析并下载，可能是因为手机端b站分享的是短链接

**Comment by JunkFood02** [comment]
请勾选 下载播放列表

**Comment by yijiluokong** [comment]
问题解决了，谢谢

**Comment by JunkFood02** [comment]
可以确定是短链接的解析问题，我这里应该没有能修的地方
