### ISSUE TITLE
Unable to download a Twitter video

### ISSUE THREAD

**Issue by leapofazzam123** [JunkFood02/Seal#277]
### To Reproduce

1. Paste a Twitter link with a video
2. Click Download

### Error reports & Screenshots

![Screenshot_20221015-083146](https://user-images.githubusercontent.com/76893443/195963124-405b29b2-2811-4f5b-a3ce-83da9baf6513.png)

### Device info

App version: 1.3.5 (10350)
Device information: Android 10 (API 29)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1488 x 718

**Comment by JunkFood02** [comment]
please provide the complete error report and the link to the video

**Comment by leapofazzam123** [comment]
nvm i just enabled cookies without realizing i need a netscape cookie file
