### ISSUE TITLE
[Feature Request] Prefer AV1

### ISSUE THREAD

**Issue by DavidH-2022** [JunkFood02/Seal#280]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When using yt-dlp, and when ffmpeg is installed, `yt-dlp` can merge the AV1 video (typically 1080p AV1 is video format 399) with opus audio (251) 

### Describe the solution you'd like

A clear and easy option to merge the videos for users without command line knowledge

### Video link

https://www.youtube.com/watch?v=jo6Q6Xbn0Zk (HDR+8K)

**Comment by Hokyps** [comment]
I'd also like mkv merging.

**Comment by JunkFood02** [comment]
MKV merging doesn't seem like a feature. Almost all kinds of the videos/audio track can be merged into an MKV container, meanwhile WebM video itself is an MKV file. 
Since AV1 haven't been compatible with most of the device yet, I think adding a "prefer AV1 encoding" option is ideal

**Comment by DavidH-2022** [comment]
Edited the title.
