### ISSUE TITLE
[Feature Request] Import custom templates from a public repo

### ISSUE THREAD

**Issue by Gittore54** [JunkFood02/Seal#282]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I think that everyone can contribute to publish their own custom templates and make them available for all the users, maybe something like a repo with json intent import method or... I'dont know exactly how to make it work.

**Comment by JunkFood02** [comment]
The export/import option is only for backup currently. Yt-dlp communities have a lot of active users sharing and discussing it, maybe you can join them for more information 😉

**Comment by venkat2305** [comment]
@JunkFood02 it would be great to have a lot of  ready made custom commands for different use cases.
