### ISSUE TITLE
[Feature Request] instagram post/status/reel download

### ISSUE THREAD

**Issue by firofame** [JunkFood02/Seal#284]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by BobbyESP** [comment]
This is a yt-dlp feature and it's already made. You can download that kind of content. Maybe you need Netscape cookies to bypass login for downloading histories from private accounts.
