### ISSUE TITLE
[Feature Request] Add 240p and 144p as video quality download options

### ISSUE THREAD

**Issue by Gissyup4** [JunkFood02/Seal#287]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm on a metered network. It drains more data than needed as I don't always need to download in 360p from youtube.

### Describe the solution you'd like

Add these resolutions to the video quality choices.

**Comment by JunkFood02** [comment]
How about simply add an option for "smallest size" or "worst quality"?
