### ISSUE TITLE
[Feature Request] Multiple concurrent downloads ?

### ISSUE THREAD

**Issue by Mrnofish** [JunkFood02/Seal#288]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I've only recently discovered Seal, it's a very neat app. However, it does seem that it only supports downloading one file at a time?

While this may be no biggie for static videos, it's a bummer for live streams.

### Describe the solution you'd like

The ability to start multiple concurrent downloads, i.e. having several instances of yt-dlp running at the same time.

**Comment by JunkFood02** [comment]
You can now running multiple instances of yt-dlp for running custom commands
