### ISSUE TITLE
Register to open URLs from other apps

### ISSUE THREAD

**Issue by Noitarud** [JunkFood02/Seal#298]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [x] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

How about register the app to open links in android? If I press and hold a link in the Monocles browser I get the option to open in app, but SEAL is not in the list.

**Comment by Noitarud** [comment]
This has exposed a problem in Monocles, the options given each has a problem and I have opened an issue there "Open in app" should not be so constrained.

As for the discussion of having it registerable for taking URLs in #511, As far as I know this only influences Android settings and user can set a preferred browser other than seal. I use Seal as a download manager at this time too, but of course I want to browse, and had desired for Seal to pass the URL to another app…

**Comment by Noitarud** [comment]
This seems to not be working now, any reason? V1.9.2. Does not seem to be moved to options.

The other app i use this in is the Android native HTML reader, as seen here, If this works i will be happy with that. but there is more to this since it also shows VLC as an option, but in second image there are a number of "*" apps.

![Screenshot_20230514-002013](https://github.com/JunkFood02/Seal/assets/98794719/1e77b615-986a-433d-bf63-04be49993dc4)

So its not this setting:
![Screenshot_20230514-001258](https://github.com/JunkFood02/Seal/assets/98794719/3a1dcc3c-707a-4d20-b0ca-e7f2ce0636d1)

**Comment by JunkFood02** [comment]
Reference: [Official developer document](https://developer.android.com/guide/components/intents-common)
> Starting in Android 12 (API level 31), a generic web intent resolves to an activity in your app only if your app is approved for the specific domain contained in that web intent. If your app isn't approved for the domain, the web intent resolves to the user's default browser app instead.

We can all agree that Seal is **not** a browser app and we don't want to confuse users with misinformation either. I noticed that you're using an html file which hosts your links for regular download tasks.

I suggest switch to create custom commands for separate sites to achieve this:

Let's say you have got already a template which consists of `--no-mtime --no-part`, and you can insert your link into the beginning of this template like `https://www.example.com --no-mtime --no-part`, and start the task with an empty URL.

**Comment by Noitarud** [comment]
I was (unknowingly) wrong to use "monocles'" as an example (as said in 26/4 post), I am considering starting a fresh issue with content of 14/5 post. And I have android 10.
