### ISSUE TITLE
Brief on file size and length

### ISSUE THREAD

**Issue by Noitarud** [JunkFood02/Seal#299]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I had the URL on clipboard, from search engine that gave result no image.
It was not until after I had downloaded it that I realised it was >2h long (and I only found out the MB size later, I had preset 360p).
I changed settings to see some more info, change was not immediately obvious, only showed something there after beginning negotiations (i prematurely said no effect here since i saw popup messages and no status info before i cancelled it and wrote, as seen in image below)

### Describe the solution you'd like
Maybe a query button at least, to show image, etc. the image could apear behind the download options and the etc can be on the download options page, if you want to go that way (but might encourage you to offerthis per format)

### Additional context

Same vein, #74

(Image shows no status messages, made me think that details setting had no effect. Showed after negotiations)
![Screenshot_20221025-130643](https://user-images.githubusercontent.com/98794719/197674303-78e9079a-a724-48e1-8414-ab8b00973d29.png)

**Comment by Lutra-Fs** [comment]
I'd like to have a look at this issue and make a PR for that.
