### ISSUE TITLE
Concealed status

### ISSUE THREAD

**Issue by Noitarud** [JunkFood02/Seal#300]
### Describe the bug

I don't mind overlap, saves screen space, the problem is the end of the progress bar is covered by the clipboard button during run. Not saying to get rid of it. Landscape issue only on this device.
![Screenshot_20221025-130643](https://user-images.githubusercontent.com/98794719/197674303-78e9079a-a724-48e1-8414-ab8b00973d29.png)

### Device info

Seal-1.4.0-beta.3-arm64-v8a

**Comment by Lutra-Fs** [comment]
I'd like to try to fix this issue

**Comment by JunkFood02** [comment]
> I'd like to try to fix this issue

Have you already got any ideas about this? I think just decreasing the width in horizontal mode could work

**Comment by Lutra-Fs** [comment]
Yes, that will work. Can I work on this? I think that allowing users to scroll content above the FAB when the content exceeds the FAB is also a choice.
