### ISSUE TITLE
[Feature Request] Add Galician to the translation

### ISSUE THREAD

**Issue by BobbyESP** [JunkFood02/Seal#301]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I liked to add the Galician language to the app. I accidentally already created the language in Weblate because later of doing that i've remberbered that i should have asked, sorry :(

**Comment by JunkFood02** [comment]
😂 Translation won't need a permission from anyone

**Comment by BobbyESP** [comment]
Haha okeyy, thanks!
