### ISSUE TITLE
[Bug Report] Metered network detection

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#303]
### Describe the bug

1.1.1.1 w/ WARP (default settings) + Wi-Fi  is detected as metered network.
https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone

### Error reports & Screenshots

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/198053464-f3a17eb0-a1e7-4508-8392-d0dadc2e0bd6.png)

</details>

### Device info

App version: 1.3.5 (10350)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1464 x 720

**Comment by Lutra-Fs** [comment]
The setting is basically not detecting the cellular network, but metered network. See https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean) 
From Android API 29, the default value for VPNService to detect if it is metered or not will be true.

**Comment by Lutra-Fs** [comment]
See this article
https://support.google.com/android/answer/9654714?hl=en-GB#zippy=%2Ccontrol-data-use-with-metered-wi-fi
You can force your wifi connection treated as unmetered

**Comment by Botan626** [comment]
> The setting is basically not detecting the cellular network, but metered network. See https://developer.android.com/reference/android/net/VpnService.Builder#setMetered(boolean) From Android API 29, the default value for VPNService to detect if it is metered or not will be true.

This link says:
> boolean: true if VPN network should be treated as metered regardless of underlying network meteredness
Is there a way to make VPN network treated as unmetered network?

**Comment by Botan626** [comment]
> See this article https://support.google.com/android/answer/9654714?hl=en-GB#zippy=%2Ccontrol-data-use-with-metered-wi-fi You can force your wifi connection treated as unmetered

Didn't help. I set my Wi-Fi connection to unmetered network, Seal still refused to download video with VPN on with 'Download using cellular' setting set to off.

**Comment by JunkFood02** [comment]
The problem seems to be not on our side. The network detection is done by [this line](https://github.com/JunkFood02/Seal/blob/d0f1a82132e9e52b2fe766d3172813f5d66dca12/app/src/main/java/com/junkfood/seal/ui/page/download/DownloadViewModel.kt#L207) from Android OS.

**Comment by Botan626** [comment]
> The problem seems to be not on our side. The network detection is done by [this line](https://github.com/JunkFood02/Seal/blob/d0f1a82132e9e52b2fe766d3172813f5d66dca12/app/src/main/java/com/junkfood/seal/ui/page/download/DownloadViewModel.kt#L207) from Android OS.

Then why Seal downloaded its update?

**Comment by JunkFood02** [comment]
update is not controlled by this option
