### ISSUE TITLE
Error trying to download with MP3

### ISSUE THREAD

**Issue by BobbyESP** [JunkFood02/Seal#311]
### Describe the bug

When trying to download a video from YouTube (in this case) and clicking on save audio as MP3, the video is downloaded but in the final process of converting, the app throws an error about ffprobe, like it',s not installed.

### To Reproduce

Get a YouTube link and try to download it with the option Convert to audio enabled and selecting MP3.

### Error reports & Screenshots

https://user-images.githubusercontent.com/60316747/198278704-c8eda78d-5b15-4c2f-ac88-403851d8e67c.mp4

### Device info

App version: 1.4.0 (10400)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2272 x 1078

**Comment by Marco-9456** [comment]
Can't reproduce, it's working for me

https://user-images.githubusercontent.com/41828058/198280710-3d70ca2f-a054-4c6b-893d-244ee822fc9e.mp4

**Comment by BobbyESP** [comment]
Okay! Im gonna reinstall the app
