### ISSUE TITLE
video compression, large video compression

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#314]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

video compression, large video compression

into an archive. e.g. zip, 7z, zstd, lz4

maybe some other way of compression

### Video link

https://youtu.be/dQw4w9WgXcQ

### Additional context

you asked to follow the issue template, as you see nothing has changed

**Comment by JunkFood02** [comment]
> Seal is and will remain a simple GUI for yt-dlp, providing most of the functionality of yt-dlp as is, without modifications. Thus, we'll not take requests for features that yt-dlp does not support.
