### ISSUE TITLE
Fix UI on landscape mode

### ISSUE THREAD

**Issue by xmha97** [JunkFood02/Seal#320]
### Describe the bug

Hi, Please fix UI on landscape mode
![Screenshot_2022-10-31-23-40-42-140_com junkfood seal](https://user-images.githubusercontent.com/23485114/199101347-61eaf8de-c5c1-486e-a184-da0361173b56.jpg)

**Comment by JunkFood02** [comment]
Landscape mode is for large screen devices only.
