### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by KhaledKhaled0909** [JunkFood02/Seal#322]
### Describe the bug

When I download An mb3 file that has it's thumbnail A rectangle it crops it to a square one.

### Error reports & Screenshots

![Screenshot_20221102-231903_Seal](https://user-images.githubusercontent.com/117318181/199607459-602c506a-4b6f-49fe-b5c2-78ebf227d649.png)
![غردي يا روح   مشاري راشد العفاسي تسجيل جديد  t_9-WdMqUi0](https://user-images.githubusercontent.com/117318181/199607467-d409fd2e-cc70-4f58-8945-dbe42eef83fc.png)
![Screenshot_20221102-231628_Poweramp](https://user-images.githubusercontent.com/117318181/199607475-69c4475a-8aeb-418a-9650-cd4f5662b927.png)

### Device info

App version: 1.4.0-(F-Droid) (10404)
Device information: Android 9 (API 28)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2155 x 1079

**Comment by Marco-9456** [comment]
> ### Describe the bug
> When I download An mb3 file that has > it's thumbnail A rectangle it crops
> it to a square one.

This is normal, Music tracks and Albums are always in this aspect ratio `1:1` so that your music library doesn't look wired at the end 😀

**Comment by KhaledKhaled0909** [comment]
At least Man give me the option to the aspect ratio or consider adding it in the future updates😇
