### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Yadavbipin1** [JunkFood02/Seal#327]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Yes, I want to make a request about the features of downloading the highlights and stories from Instagram. 

### Describe the solution you'd like

I would like to have the features of downloading the any videos available on the internet. To be honest the app works awesome.

**Comment by JunkFood02** [comment]
- https://github.com/yt-dlp/yt-dlp/issues/5338
