### ISSUE TITLE
希望有WIN版本的，目前yt-dlp和aria的工具好像都没有。

### ISSUE THREAD

**Issue by SONGjiemo** [JunkFood02/Seal#329]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

1、希望开发一个win的exeGUI和aria的工具
2、希望支持yt-dlp剧集的下载

**Comment by JunkFood02** [comment]
剧集下载？可以提供一下链接吗

**Comment by SONGjiemo** [comment]
> 剧集下载？可以提供一下链接吗

https://www.youtube.com/watch?v=x4VJnpExiNc&list=PLkuKHvw9NmzRyt9HX90D_G9AvdBQPYcmp

剧集链接 都有个  list 这个关键标记

**Comment by JunkFood02** [comment]
下载播放列表
