### ISSUE TITLE
[Bug Report] Does not work on Galaxy S22+

### ISSUE THREAD

**Issue by jferris-** [JunkFood02/Seal#330]
### Describe the bug

When trying to download any Twitter video, the app presents a 'could not download' error message.

App works fine on my other devices.

Using default Seal app settings.

### Error reports & Screenshots

Factory/stock Galaxy S22+, Android 13, One UI 5.0

### Device info

App version: 1.4.0-(F-Droid) (10404)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2222 x 1080

**Comment by JunkFood02** [comment]
Please enable "Detailed output" and try again

**Comment by BobbyESP** [comment]
Do you have some VPN?

**Comment by jferris-** [comment]
V1.5 fixed issue.
