### ISSUE TITLE
[Feature Request] enable embedding metadata option

### ISSUE THREAD

**Issue by Waa11a** [JunkFood02/Seal#337]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Add option to enable --embed-metada argument

### Additional context

--embed-metada argument adds artist name and description, date, album name

**Comment by JunkFood02** [comment]
It's already enabled by default in when downloading in audio

**Comment by Frikortreat** [comment]
I think it refers an option to alter the Metadata from a model of the user
