### ISSUE TITLE
Storage Access Framework support for download directories

### ISSUE THREAD

**Issue by JunkFood02** [JunkFood02/Seal#34]
- [x] Use [SAF](https://developer.android.com/guide/topics/providers/document-provider) to move downloaded files to other directories.

**Comment by JunkFood02** [comment]
For devices running Android 10 (API 29) or higher, App gain write permission to Download/ and Documents/ by default. But the only way for accessing or writing files outside these two directories is to use Storage Access Framework. 
Seal does not support SAF currently. As a result, any download outside these two directories would get a Permission Denied error.

**Comment by JunkFood02** [comment]
With SAF support, we could manually copy downloaded files to destination and delete origin files after finish downloading without permission problems.
SAF could also provide SD Card support #25
Reference: [dvd](https://github.com/yausername/dvd/blob/master/app/src/main/java/org/yausername/dvd/work/DownloadWorker.kt)

**Comment by farabox1** [comment]
![Screenshot_2022-07-29-23-52-52-083_com.junkfood.seal.jpg](https://user-images.githubusercontent.com/99221084/181830064-3f4cb059-72f7-4286-abef-2bc57ac83e72.jpg)

What can I must do ???

**Comment by JunkFood02** [comment]
@farabox1 Hi, you can just uninstall/reinstall the app or clear the data of app to reset the download directory

**Comment by Donkey-Doug** [comment]
#85

**Comment by TPAXcc** [comment]
🥰

**Comment by xibr** [comment]
Check this maybe it helps
https://github.com/anggrayudi/SimpleStorage

**Comment by ganchair** [comment]
also see: https://github.com/K1rakishou/Fuck-Storage-Access-Framework

**Comment by achanta8** [comment]
Hi

**Comment by Marco-9456** [comment]
Check this project out, you'll probably get references on how to implement a way to access other directories then Download

https://github.com/deniscerri/ytdlnis

**Comment by JunkFood02** [comment]
> references on how to implement a way to access other directories then Download

The use case in Seal could be much more complicated than this and dvd. Such as custom command, temporary files management, and resume download with `.part` files, some of these features may conflict with the SAF.

**Comment by Marco-9456** [comment]
> > references on how to implement a way to access other directories then Download
> 
> The use case in Seal could be much more complicated than this and dvd. Such as custom command, temporary files management, and resume download with `.part` files, some of these features may conflict with the SAF.

I see, anyway I thought it would help a little 😃

**Comment by BobbyESP** [comment]
We haven't implemented yet SAF, a storage framework that Google made for making the file saving more secure and controllable by the users. In Seal this is kinda hard to implement because it probably means to a rewrite of the basic functions lf the app.

**Comment by Jeffdow85** [comment]
I'm using latest beta as of writing this and mine is saving audio only to music as selected in that system file access manager and YouTube folder which is default for seal anyway I think. I get what you're saying about adding the function to make this problem go away but be nice if we could dismiss the warning once understood if possible. Lovely ui and app thankyou!

**Comment by BobbyESP** [comment]
@JunkFood02 I'm trying to implement SAF in the app that I'm actually developing. If I'm able to do it I'm gonna share the code with you so we can add it to Seal. I know that there are some files like config.txt or cookies.txt that can't be saved with SAF because they need to be localizable to the app in all moment, but according to [Android Developers documentation](https://developer.android.com/training/data-storage), there is an App-specific file storing so we can use that for both of that files and SAF for the Downloads.

**Comment by JunkFood02** [comment]
> @JunkFood02 I'm trying to implement SAF in the app that I'm actually developing. If I'm able to do it I'm gonna share the code with you so we can add it to Seal. I know that there are some files like config.txt or cookies.txt that can't be saved with SAF because they need to be localizable to the app in all moment, but according to [Android Developers documentation](https://developer.android.com/training/data-storage), there is an App-specific file storing so we can use that for both of that files and SAF for the Downloads.

`config.txt` and `cookies.txt` are already created in app's internal storage. The real problem of SAF migration is not the plain implementation but actually the conflict with other features, since many of them needs directly access to the file system

**Comment by BobbyESP** [comment]
Yeah, true... I need to think about it

**Comment by Noitarud** [comment]
Temporary solution could be to allow parts…
Either finalise each video or emulate zip file creation (no compression).

**Comment by BobbyESP** [comment]
#455 Workaround PR for being able to use SD cards in Seal. It was only tested in Android 12. The changes can be reverted/changed.

**Comment by JunkFood02** [comment]
Added in [v1.8.0-beta.1](https://github.com/JunkFood02/Seal/releases/tag/v1.8.0-beta.1), please help test this new feature out, we're ready to hear your feedback 🙌

**Comment by BobbyESP** [comment]
Going to test it in a few minutes

**Comment by BobbyESP** [comment]
SD downloading works fine!

**Comment by BobbyESP** [comment]
I'm gonna test OTG cable because we were having issues in my PR

**Comment by RuhulBoss** [comment]
Isu
