### ISSUE TITLE
[Feature Requests]

### ISSUE THREAD

**Issue by some1onLSD** [JunkFood02/Seal#340]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

*Annoying toast messages
*Disbling previews leaves you with no details of what you're downloading whatsoever

### Describe the solution you'd like

*Add option to disable toast messages because thy are annoying.
*When disabling download previews show the file name (currently shows only downloading percentage without any detail of the file name).

**Comment by Marco-9456** [comment]
See this

`toast might get remove in next releases with multitasking support`


_Originally posted by @JunkFood02 in https://github.com/JunkFood02/Seal/issues/139#issuecomment-1221245389_

**Comment by JunkFood02** [comment]
> When disabling download previews show the file name (currently shows only downloading percentage without any detail of the file name).

This is by design. If you want to know the name of file without preview, just toggle on the notification
