### ISSUE TITLE
[Bug Report] Song downloaded at an impossible bitrate

### ISSUE THREAD

**Issue by IRanOutOfIdeasForMyUsername** [JunkFood02/Seal#344]
### Describe the bug

I downloaded the song ''Take Me To Church'' by Hozier. It downloaded at 390 kbps (AAC).

### To Reproduce

1. Paste this URL:  https://music.youtube.com/watch?v=6A3PMQA5c74  into the URL text box in the seal app.
2. Download.
3. Check metadata and file size.
4. Badda Boom: Impossible bitrate.

### Error reports & Screenshots

![image](https://user-images.githubusercontent.com/112100517/201500159-1a8b4d85-bbe5-4ec2-8ce2-15fe8b7c9018.png)
![image](https://user-images.githubusercontent.com/112100517/201500171-269d31a9-d7e9-4aa1-85d8-a6a7bcf83abb.png)

### Device info

App version: 1.5.0-(F-Droid) (10502)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2295 x 1080

### Additional context

This was a test run, and while the song downloaded extremely fast, I am quite confused about the download itself. To be fair, this isn't necessarily the WORST thing in the world, but it's more than a little confounding.

**Comment by JunkFood02** [comment]
Download and convert to m4a/mp3 causes recoding of the audio file. The abnormal high bitrate is the result of `--audio-quality 0`, and converting formats could always cause increase in file size and loss in audio quality.
See also #228 
I'll consider adding a warning for this

**Comment by IRanOutOfIdeasForMyUsername** [comment]
> Download and convert to m4a/mp3 causes recoding of the audio file. The abnormal high bitrate is the result of `--audio-quality 0`, and converting formats could always cause increase in file size and loss in audio quality.
> See also #228 
> I'll consider adding a warning for this

So you're saying it's my fault ;p

Lol, I guess that makes sense, and that's good to know.

**Comment by PsychoAnees** [comment]
bro can you plz tell me the name of the music player you used to check bitrate

**Comment by Marco-9456** [comment]
> bro can you plz tell me the name of the music player you used to check bitrate

[Oto Music](https://play.google.com/store/apps/details?id=com.piyush.music)

**Comment by IRanOutOfIdeasForMyUsername** [comment]
> bro can you plz tell me the name of the music player you used to check bitrate

Retro Music Player. I'd recommend installing the latest beta release here on GitHub because the developers are no longer working on the app. A shame, because it's pretty darn good.
