### ISSUE TITLE
Can't change download location 

### ISSUE THREAD

**Issue by DangerousCoder-ADITYA** [JunkFood02/Seal#347]
### Describe the bug

For some reason, I'm unable to change my video and audio download location from default. Everytime I try switching it, it shows that "this directory is not supported". 

### To Reproduce

To reproduce the bug I'm experiencing:- 
1) Go to "settings"
2) "Download directory"
3) "Video folder" or "Audio folder"
(Takes you to another app to choose the directory to give access to)
(After navigating)
4) "Use this folder"
(Shows the above mentioned message, that "this directory is not supported")

### Device info

App version: 1.5.0 (10500)
Device information: Android 11 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1136 x 720

### Additional context

I wanted to switch my download location to my SD card (yeah I still use that sh*t), but that doesn't seem to work. To be exact, I'm not able to change my download location to anywhere other than the default. It just shows the messege i mentioned before.

**Comment by JunkFood02** [comment]
#25
