### ISSUE TITLE
[Feature Request] Be usable with ReVanced Download package name.

### ISSUE THREAD

**Issue by ferivoq** [JunkFood02/Seal#351]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by JunkFood02** [comment]
Context?

**Comment by XRedCubeX** [comment]
> Context?

I don't know what the OP meant but subjectively I think making sure that when the youtube revanced download button calls Seal, Seal doesn't appear as a fully app but as a window overlaying Youtube, a bit like NewPipe.  What the Revanced download button does is basically call up an app of your choice specified in the settings.  It's like clicking share.

**Comment by JunkFood02** [comment]
If so like @XRedCubeX said.
Duplicated with #152

**Comment by XRedCubeX** [comment]
> Context?



> If so like @XRedCubeX said. Duplicated with #152

I don't know if that was what the OP meant of course, this is how I see it
