### ISSUE TITLE
an option to know whether sponsorblock is online or not

### ISSUE THREAD

**Issue by venkat2305** [JunkFood02/Seal#352]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

- an option to know whether the sponsor block is online or not. preferably on the home screen. You don't have to search for the segments if it is not online.
- what's happening is that, if we enable the sponsor block in the settings and the servers are not online, it says the video is not downloaded even though it downloaded the video. and this video is not present in the download history.

### Describe the solution you'd like

- small element/div on the homepage saying whether the sponsor block is online or not.
-  if the sponsor block is not active, don't search for the segments and show the video in the download history

**Comment by JunkFood02** [comment]
Please post the error report

**Comment by venkat2305** [comment]
> Please post the error report

https://user-images.githubusercontent.com/55329452/202719375-f708be53-363e-4d0a-815f-818ae930458d.mp4

**Comment by JunkFood02** [comment]
> an option to know whether the sponsor block is online or not. preferably on the home screen. You don't have to search for the segments if it is not online.

Though this cannot be implemented on our side, simply make the yt-dlp ignore the errors may work. I'll give it a try.
