### ISSUE TITLE
download error with file authorization

### ISSUE THREAD

**Issue by balialyui** [JunkFood02/Seal#354]
### Describe the bug

ERROR: [Errno 1] Operation not permitted: '/storage/emulated/0/Download/Seal/xxxx.mp4

the recent version not support Android12 now？the file authorization may be something changed and it can’t written file to the disk。

### Error reports & Screenshots

ERROR: [Errno 1] Operation not permitted: '/storage/emulated/0/Download/Seal/

### Device info

App version: 1.5.0-(F-Droid) (10502)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2328 x 1176

**Comment by JunkFood02** [comment]
The app is tested to work on device from Android 6 to Android 13. Could you please provide a screen recording about the error?

**Comment by balialyui** [comment]
> The app is tested to work on device from Android 6 to Android 13. Could you please provide a screen recording about the error?
When I setting the default save folder again it ask me to provide the file authorization and now its OK。maybe its my phone’s problem，because i use huawei with Harmony os3....

**Comment by balialyui** [comment]
> The app is tested to work on device from Android 6 to Android 13. Could you please provide a screen recording about the error?

When I setting the default save folder again it ask me to provide the file authorization and now its OK。maybe its my phone’s problem，because i use huawei with Harmony os3....

**Comment by JunkFood02** [comment]
🤣👌another typical huawei problem
