### ISSUE TITLE
Not installing on A13 QPR Beta 3.1 Pixel 6

### ISSUE THREAD

**Issue by Aarekaz** [JunkFood02/Seal#355]
### Describe the bug

For some reason the app is not being installed on my Pixel 6 running QPR Beta 3.1. It gives the following error message:

![Uploading Screenshot_20221120-001051.png…]()

### To Reproduce

Download the apk from f-droid
Tap to install

### Error reports & Screenshots

![Screenshot_20221120-001051](https://user-images.githubusercontent.com/36888347/202866004-dfe8b64a-521d-448c-8796-e1089afd03f1.png)

### Device info

Android 13 QPR Beta 3.1 
Pixel 6

### Additional context

My phone is rooted

**Comment by Aarekaz** [comment]
An update:
I downloaded the Seal-1.6.0-beta.1-arm64-v8a-release.apk from the releases page and that got installed.
No idea why the f-droid one is not installing.

**Comment by JunkFood02** [comment]
Install version 10502 or the GitHub apk compatible with "arm64-v8a" arch

**Comment by JunkFood02** [comment]
> why the f-droid one is not installing.

- https://github.com/JunkFood02/Seal/issues/41#issuecomment-1293832177
