### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by theadams** [JunkFood02/Seal#356]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

hi Dear Developer please open "Seal" app on youtube. like a popup. like "powertube" for example. 

When I click the download button on youtube, it works, but it directs me to the "seal" app. I would appreciate it if you could code it to work on youtube. this will be more nice and useful.. thanks

**Comment by BobbyESP** [comment]
Please, see #152
