### ISSUE TITLE
[Feature Request] browser inside the app to make cookies 

### ISSUE THREAD

**Issue by uomar8** [JunkFood02/Seal#362]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Some people don't know how to make a cookies file and it takes time to make one 

### Describe the solution you'd like

A browser inside the app to create cookies file for the app so you could sign in to website easily and it will automatically create cookies file for you

**Comment by JunkFood02** [comment]
Added in v1.7.0-beta.4

**Comment by uomar8** [comment]
> Added in v1.7.0-beta.4

Just tested out it works great, thank you

I would like to suggest 2 things

1- new button "add to exist cookies" to support multiple websites

2- a warning that you didn't insert URL instead of white screen
