### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by khf1f2** [JunkFood02/Seal#370]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Can you try to support the download of live streaming?

### Describe the solution you'd like

Read the M3U8 file at any time, use FFMPEG to codec。

### Video link

xxx.m3u8

**Comment by JunkFood02** [comment]
m3u8 download is already supported by yt-dlp

**Comment by khf1f2** [comment]
live streaming😢
