### ISSUE TITLE
[Bug Report] High Contrast Dark Theme

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#371]
### Describe the bug

Some parts of the UI are not themed

### To Reproduce

See screen record

### Error reports & Screenshots

https://user-images.githubusercontent.com/41828058/204310857-b2ffa7d9-65d8-426c-a9f8-b0dc862c596f.mp4

### Device info

App version: 1.6.0 (10600)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

**Comment by JunkFood02** [comment]
High contrast doesn't mean mono-color. I think these two components(Top App Bar & Bottom App Bar) still need to be contrasted with the content beneath. 🤔
