### ISSUE TITLE
[Bug Report]: SDCARD Support Needed

### ISSUE THREAD

**Issue by cyberlog69** [JunkFood02/Seal#372]
### Describe the bug

SD card/TF card storage is not supported. 

### To Reproduce

1.Goto Settings
2.Click On Download Directory
2.Click on Video/Audio Folder. 

### Device info

App version: 1.6.0 (10600)
Device information: Android 11 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1536 x 720

### Additional context

Please add support for SD card downloads.

**Comment by BobbyESP** [comment]
See #34
