### ISSUE TITLE
Duplicate Thumbnails when downloading playlists [Bug Report]

### ISSUE THREAD

**Issue by GentDushi** [JunkFood02/Seal#377]
### Describe the bug

When downloading a youtube playlist, all of the audio files are going to have the same thumbnail as the first downloaded audio file. Instead of each audio having its own specified thumbnail as is the case when downloading individual audio files. The images are actually downloaded, but they only reference the first thumbnail and label it as an album cover which causes all of the audios to have the same thumbnail.

### To Reproduce

1. Download the following playlist; https://www.youtube.com/playlist?list=PLCOU8ShENLKJJwplMhdruKXhvFHi4mNC6
        1.1. Use the following settings; _Save as Audio, Download playlist, Save thumbnail_, No custom command and no 
        conversion.
2. Check the playlist using a media player, i used _Auxio_

### Error reports & Screenshots

![Screenshot_20221130_174759_Auxio](https://user-images.githubusercontent.com/44119281/204858631-cf03667b-94f1-4e3a-9824-762427999598.jpg)
![Screenshot_20221130_174817_Auxio](https://user-images.githubusercontent.com/44119281/204858639-578bc2b7-c363-4992-a4fa-145b10492f28.jpg)

### Device info

App version: 1.5.0-(F-Droid) (10502)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2986 x 1439

**Comment by GentDushi** [comment]
Seems to be an issue with the media player, tried VLC fixed all of them but just one thumbnail references another one.

**Comment by JunkFood02** [comment]
> all of the audio files are going to have the same thumbnail as the first downloaded audio file.

This is actually a complicated problem.

Save as audio tries to tag audio without album data with the name of playlist. And for most of the music players, one album would only has one album art(reasonable tho). That's also why you can see the files are tagged with `chill_2` as their album name.
