### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yurua** [JunkFood02/Seal#378]
### Error reports & Screenshots

![Screenshot_20221201-090016~2](https://user-images.githubusercontent.com/55480948/204978122-e162ee17-9510-4a3c-9ce4-44ef431c5529.png)

### Device info

Pixel 6 Pro
Android 13 QPR1 BETA 3.1

### Additional context

Duplicate string after download video.

**Comment by JunkFood02** [comment]
Please report translation issues at Hosted Weblate
