### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Miraclegabriel** [JunkFood02/Seal#382]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When clicking or posting a video link and we are ask to choose the video quality to download. We don't know how much data or size the video will consume which is really a problem 

### Describe the solution you'd like

It will be nice for us to see how much data and size of a the video quality we choose like tubemate and sanptube does.

**Comment by Marco-9456** [comment]
> ### Is your feature request related to a problem? Please describe.
> When clicking or posting a video link and we are ask to choose the video quality to download. We don't know how much data or size the video will consume which is really a problem
> 
> ### Describe the solution you'd like
> It will be nice for us to see how much data and size of a the video quality we choose like tubemate and sanptube does.

See **JunkFood02** comment for more information 

https://github.com/JunkFood02/Seal/issues/74#issuecomment-1200168247

**Comment by Miraclegabriel** [comment]
Yes exactly, did is a downside for seal.

**Comment by JunkFood02** [comment]
🫡 I think I've got some ideas about it

**Comment by Miraclegabriel** [comment]
You mean you will bring an update with that feature?
