### ISSUE TITLE
[Bug Report] Custom Command notification Bug Nr.1

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#384]
### Describe the bug

Canceling a download from notification when using custom command doesn't really cancel the download

### To Reproduce

1. Use any custom command and try to cancel it from notification.

### Error reports & Screenshots

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'https://rr2---sn-4g5e6nsz.googlevideo.com/videoplayback?expire=1670121427&ei=c7OLY_GTM9iK7gPWsJb4Ag&ip=84.60.182.67&id=o-ACExmM1HOsUSNhBZnQQjxjJP0K_98iG6-Pr2OwFJfC3b&itag=137&source=youtube&requiressl=yes&mh=_Z&mm=31%2C29&mn=sn-4g5e6nsz%2Csn-4g5edndz&ms=au%2Crdu&mv=m&mvi=2&pl=20&gcr=de&initcwndbps=1317500&spc=SFxXNtFvswH0XBGZKA_1o1KhXF5iJmY&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=1968501218&dur=8960.159&lmt=1669405755022834&mt=1670099350&fvip=1&keepalive=yes&fexp=24001373%2C24007246&c=ANDROID&txp=5535434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cgcr%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgGdJacB5D2awTzEAqOvHwUCoe3x3F5tqzpSETf3vgWOcCIQCs5QApQgcUf7grCmdejX-nYU15xRLnO11DmfUFd0ZDGA%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgZV9NTm8tKXjk6qNLBeEVff4gk3s1Z0FtxRVd_FG7Q8kCIHIbwX3vcwEXlf_cZi1CR7sxbGVx_lqDGHabY2UBgZx8':
  Metadata:
    major_brand     : dash
    minor_version   : 0
    compatible_brands: iso6avc1mp41
    creation_time   : 2022-11-25T18:57:06.000000Z
  Duration: 02:29:20.16, start: 0.000000, bitrate: 1757 kb/s
  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 1 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
    Metadata:
      creation_time   : 2022-11-25T18:57:06.000000Z
      handler_name    : ISO Media file produced by Google Inc.
      vendor_id       : [0][0][0][0]

```

https://user-images.githubusercontent.com/41828058/205461619-c6d70e87-d964-4628-b6ab-6de351e7ee6b.mp4

### Device info

App version: 1.7.0-beta.2 (10610)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

### Additional context

Sometimes clicking on Error report from notification doesn't copy anything to the clipboard

**Comment by JunkFood02** [comment]
Other bugs aside, the "cannot cancel" error seems like another "subprocess" issue like in #180 because it invokes FFmpeg to download

**Comment by Marco-9456** [comment]
> Other bugs aside, the "cannot cancel" error seems like another "subprocess" issue like in #180 because it invokes FFmpeg to download

Why is everything is related to #180 

![1667581049686](https://user-images.githubusercontent.com/41828058/205508912-b45c3a85-dec6-4584-80a4-e332c62ccad3.png)
