### ISSUE TITLE
[Bug Report] Custom Command notification Bug Nr.2

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#385]
### Describe the bug

After a custom command download finishes,  the `Download finished. Click to open.` notification will stuck and it doesn't open the video or audio file.

### To Reproduce

1. Download using any custom command
2. Try to clearly notification.

### Error reports & Screenshots

https://user-images.githubusercontent.com/41828058/205461964-33aea788-3e53-4838-99c1-0015e071909f.mp4

### Device info

App version: 1.7.0-beta.2 (10610)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2281 x 1080

### Additional context

I want also to mention that the downloaded file whether it's a Video or Audio it doesn't show up in the App Downloads Tap

**Comment by JunkFood02** [comment]
Download history is only for general mode

**Comment by Marco-9456** [comment]
> Download history is only for general mode See also [#244 (comment)](https://github.com/JunkFood02/Seal/issues/244#issuecomment-1253958770)

Completely forgot about it.
