### ISSUE TITLE
[Feature Request] Please enable the "Configure before download" to come up as a independent pop up window instead of opening the entire app, like Powertube or NewPipe does.

### ISSUE THREAD

**Issue by fedonr** [JunkFood02/Seal#388]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Example for apps like Revanced which gives a direct download option, it gives pop up for download configuration (when using NewPipe or Powertube) without closing the Revanced App. 

While when I use Seal for the downloads it opens up the Seal home screen closing the Revanced app.

### Describe the solution you'd like

The Configure before download pop up can come independently without opening the Seal Home screen it would be great.

### Additional context

I'm attaching the download pop-up that shows in Revanced while using NewPipe and Powertube compared to Seal.
![Screenshot_20221207-141600](https://user-images.githubusercontent.com/120009841/206131614-e4e64150-87f6-4a4f-b3af-27835b1102bd.png)
![Screenshot_20221207-141633](https://user-images.githubusercontent.com/120009841/206131624-dcc1c620-fc28-4740-9384-ba720bd9d818.png)
![Screenshot_20221207-141725](https://user-images.githubusercontent.com/120009841/206131632-c48fe096-49f9-436d-9623-c85fb637bef0.png)

**Comment by venkat2305** [comment]
This feature would be great

**Comment by JunkFood02** [comment]
Duplicated #152

**Comment by fedonr** [comment]
@JunkFood02 thank you for the response, I'm just confused if this feature is not planned based on close remark or is that been worked upon? As #152 is showing up as pending and open.

**Comment by Marco-9456** [comment]
> This feature has been requested a few times. The difficulty here is that we are using a very new UI framework to build this application, while "system sharing" uses an old-fashioned API, so it may require a UI refactoring to implement. Also, the focus of the next release is on multitasking support, so any other UI changes will be put on hold.
