### ISSUE TITLE
How to build the code source.

### ISSUE THREAD

**Issue by BobbyESP** [JunkFood02/Seal#39]
Hi! I wanted to contribute to the project but i don't know how to build the source in Android Studio because i need the keystore.properties file. I don't know if you have something to build without it.

**Comment by BobbyESP** [comment]
Well, i skipped the signature process and now i can build

**Comment by JunkFood02** [comment]
Hi! You can just comment these lines safely. This file is only needed by me for signing debug apks. By the way, could you share which part you're looking forward to improving? Maybe we can discuss it here.

**Comment by BobbyESP** [comment]
Okey! By the moment i've just added the Spanish translation of the app

**Comment by JunkFood02** [comment]
I just removed some redundant strings from the resources. Please check the latest commit in branch main

**Comment by BobbyESP** [comment]
Okey!

**Comment by BobbyESP** [comment]
Tomorrow i make PR about Spanish translations.
