### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by hardikrathod003** [JunkFood02/Seal#391]
### Describe the bug

Youtube shorts are not downloading

**Comment by Marco-9456** [comment]
> ### Describe the bug
> Youtube shorts are not downloading
> 
> ### To Reproduce
> _No response_
> 
> ### Error reports & Screenshots
> _No response_
> 
> ### Device info
> _No response_
> 
> ### Additional context
> _No response_

- Fill the Bug report correctly so that someone can help you.
- it's working fine.

**Comment by hardikrathod003** [comment]
After a recent update it is working fine
