### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by venkat2305** [JunkFood02/Seal#393]
Can't download this video from Twitter
https://twitter.com/1FinanceHQ/status/1599643414680993792?t=4XHsEZ_yqnb3P79Q_uo-pg&s=19

![Screenshot_2022-12-08-20-08-45-474_com.junkfood.seal.jpg](https://user-images.githubusercontent.com/55329452/206474951-5f082ac5-7b4e-454e-ac38-fc322ca5b894.jpg)

**Comment by Marco-9456** [comment]
- Not reproducible.
![Screenshot_20221208_160653_Seal](https://user-images.githubusercontent.com/41828058/206481851-356074ba-628f-446f-b178-ee986112fbd2.jpg)

- if you want to report a error or request a feature, please Use the already provided issue template.
