### ISSUE TITLE
Azerbaijani language is locked in Weblate.

### ISSUE THREAD

**Issue by Dertyiula** [JunkFood02/Seal#395]
![Screenshot_20221209-011104_Chrome](https://user-images.githubusercontent.com/119277871/206575015-326d9ce2-4e82-4e48-b1c5-fb3084c1a928.jpg)

**Comment by Marco-9456** [comment]
Refresh the site, I just added it.

**Comment by Marco-9456** [comment]
> ![Screenshot_20221209-011104_Chrome](https://user-images.githubusercontent.com/119277871/206575015-326d9ce2-4e82-4e48-b1c5-fb3084c1a928.jpg)

Refresh the site, I just added it.

**Comment by Dertyiula** [comment]
Thank you!
