### ISSUE TITLE
Download a certain part of the video

### ISSUE THREAD

**Issue by Dertyiula** [JunkFood02/Seal#396]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Cut the desired part of the video and download it.

### Describe the solution you'd like

Cut the desired part of the video and download it.

### Video link

https://www.youtube.com/watch?v=OfkmRrec_SA&t=0

### Additional context

![Screenshot_20221209-023046_Editor Lite](https://user-images.githubusercontent.com/119277871/206580973-66c9a502-48f4-4e61-920c-a4136cf3f44f.jpg)

Similar to this, cut and download

**Comment by Marco-9456** [comment]
> ### Checklist
> * [ ]  This feature I'm requesting is already implemented in yt-dlp.
> * [ ]  This feature is merely a UI/UX update.
> * [ ]  This feature is suitable for primary users with little knowledge about yt-dlp.
> * [x]  This feature is available for most websites, not only the video platform I use.
> * [x]  This feature is suitable for a large variety of videos.
> * [x]  This feature is not going to conflict with many of the existing options.
> 
> ### Is your feature request related to a problem? Please describe.
> Cut the desired part of the video and download it.
> 
> ### Describe the solution you'd like
> Cut the desired part of the video and download it.
> 
> ### Video link
> https://www.youtube.com/watch?v=OfkmRrec_SA&t=0
> 
> ### Additional context
> ![Screenshot_20221209-023046_Editor Lite](https://user-images.githubusercontent.com/119277871/206580973-66c9a502-48f4-4e61-920c-a4136cf3f44f.jpg)
> 
> Similar to this, cut and download

```
--no-mtime -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b"
--external-downloader ffmpeg --external-downloader-args "ffmpeg_i:-ss 01:55:34.00 -to 01:56:23.00"
```

**Comment by Dertyiula** [comment]
Is it possible to add?

**Comment by Dertyiula** [comment]
It says that Video format is not supported.But the sound is played.

**Comment by Marco-9456** [comment]
You need to change the time in the command .

**Comment by Dertyiula** [comment]
How?

**Comment by Dertyiula** [comment]
"ffmpeg_i:-ss 01:55:34.00 -to 01:56:23.00"
I changed them, nope.

**Comment by Dertyiula** [comment]
01:00>02:00

**Comment by Dertyiula** [comment]
![Screenshot_20221209-123846_Gallery](https://user-images.githubusercontent.com/119277871/206660370-29b1ced5-3184-4dc9-94ed-f96386adcd95.jpg)

**Comment by Marco-9456** [comment]
> 01:00>02:00

Then you need to change it like this 
`"ffmpeg_i:-ss 00:01:00.00 -to 00:02:00.00"`

**Comment by Dertyiula** [comment]
> ![Screenshot_20221209-123846_Gallery](https://user-images.githubusercontent.com/119277871/206660370-29b1ced5-3184-4dc9-94ed-f96386adcd95.jpg)

See this problem.

**Comment by Marco-9456** [comment]
> 

What problem ?

**Comment by Dertyiula** [comment]
The format is not supported.

**Comment by Marco-9456** [comment]
> The format is not supported.

Before downloading the same video again you need to delete the previous downloaded one and the try again

**Comment by Marco-9456** [comment]
> The recording video was downloaded, but there is no video that can be searched everywhere.

Send a screen record, I'm not getting what you mean.

**Comment by Dertyiula** [comment]
Uploading XRecorder_09122022_132111.mp4…
