### ISSUE TITLE
[Feature Request] a wizard to help with custom commands

### ISSUE THREAD

**Issue by Noitarud** [JunkFood02/Seal#398]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

With original program i can use --help if i wanted info on commands;(such custom command doesnt seem to work in seal, nor is there a Help option or otherwise to query for it) i propose a wizard to help build a command list and give some info.

### Additional context

Here was some info (with my notes) only accessible after inputting --list-formats:

format/code/extension/resolution/note
171         webm      audio only  DASH audio , audio@ 48k (worst)
140         m4a       audio only  DASH audio , audio@128k
160         mp4       144p        DASH video , video only
242         webm      240p        DASH video , video only
133         mp4       240p        DASH video , video only
243         webm      360p        DASH video , video only
134         mp4       360p        DASH video , video only
17          3gp       176x144
36          3gp       320x240
5           flv       400x240
43          webm      640x360
18          mp4       640x360     (best)

and another example which adds 480p, 720p, 1080p (although 720 is selected as best):
format code extension resolution  note
171         webm      audio only  DASH audio , audio@ 48k (worst)
140         m4a       audio only  DASH audio , audio@128k
160         mp4       144p        DASH video , video only   (....
242         webm      240p        DASH video , video only   (....
133         mp4       240p        DASH video , video only
243         webm      360p        DASH video , video only   (....
134         mp4       360p        DASH video , video only
244         webm      480p        DASH video , video only   (854wide)
135         mp4       480p        DASH video , video only ---- that means -- NO SOUND - download an audio stream and merge.
247         webm      720p        DASH video , video only   (1280wide)
136         mp4       720p        DASH video , video only
248         webm      1080p       DASH video , video only   (....
137         mp4       1080p       DASH video , video only
17          3gp       176x144
36          3gp       320x240
5           flv       400x240
43          webm      640x360
18          mp4       640x360
22          mp4       1280x720    (best)

some mysterious new ones which all come up as "OPUS AUDIO at 1536kbps 48000khz". Please note that although the compression is better, MP4Box does not support embedding it - as yet.
249         unknown_videounknown  L (better than 171/140)
250         unknown_videounknown  M (better than 171/140)
251         unknown_videounknown  H

**Comment by Marco-9456** [comment]
> ### Checklist
> * [ ]  This feature I'm requesting is already implemented in yt-dlp.
> * [ ]  This feature is merely a UI/UX update.
> * [x]  This feature is suitable for primary users with little knowledge about yt-dlp.
> * [ ]  This feature is available for most websites, not only the video platform I use.
> * [ ]  This feature is suitable for a large variety of videos.
> * [ ]  This feature is not going to conflict with many of the existing options.
> 
> ### Is your feature request related to a problem? Please describe.
> With original program i can use --help if i wanted info on commands;(such custom command doesnt seem to work in seal, nor is there a Help option or otherwise to query for it) i propose a wizard to help build a command list and give some info.
> 
> ### Describe the solution you'd like
> _No response_
> 
> ### Video link
> _No response_
> 
> ### Additional context
> Here was some info (with my notes) only accessible after inputting --list-formats:
> 
> format/code/extension/resolution/note 171 webm audio only DASH audio , audio@ 48k (worst) 140 m4a audio only DASH audio , audio@128k 160 mp4 144p DASH video , video only 242 webm 240p DASH video , video only 133 mp4 240p DASH video , video only 243 webm 360p DASH video , video only 134 mp4 360p DASH video , video only 17 3gp 176x144 36 3gp 320x240 5 flv 400x240 43 webm 640x360 18 mp4 640x360 (best)
> 
> and another example which adds 480p, 720p, 1080p (although 720 is selected as best): format code extension resolution note 171 webm audio only DASH audio , audio@ 48k (worst) 140 m4a audio only DASH audio , audio@128k 160 mp4 144p DASH video , video only (.... 242 webm 240p DASH video , video only (.... 133 mp4 240p DASH video , video only 243 webm 360p DASH video , video only (.... 134 mp4 360p DASH video , video only 244 webm 480p DASH video , video only (854wide) 135 mp4 480p DASH video , video only ---- that means -- NO SOUND - download an audio stream and merge. 247 webm 720p DASH video , video only (1280wide) 136 mp4 720p DASH video , video only 248 webm 1080p DASH video , video only (.... 137 mp4 1080p DASH video , video only 17 3gp 176x144 36 3gp 320x240 5 flv 400x240 43 webm 640x360 18 mp4 640x360 22 mp4 1280x720 (best)
> 
> some mysterious new ones which all come up as "OPUS AUDIO at 1536kbps 48000khz". Please note that although the compression is better, MP4Box does not support embedding it - as yet. 249 unknown_videounknown L (better than 171/140) 250 unknown_videounknown M (better than 171/140) 251 unknown_videounknown H

![Screenshot_20221209_031635_Seal](https://user-images.githubusercontent.com/41828058/206608934-375dabd7-4e18-443a-afd6-e732e27581e7.jpg)

**Comment by JunkFood02** [comment]
Please stay tuned for the next releases 😉

**Comment by Noitarud** [comment]
I am assuming Marco's unworded response meant "go look at the options" (in lieu of --help).

The wizard idea was to perhaps add by checklist, if you want to add friendliness.

In Seal, --list-formats does not tell me anything, it is on that github page, but no report comes up (like nothing for --help).

I kept that list of codes from the old commandline version, as you see, because not every video has every option and I needed a list of every option (as many I could find) in order to tell it to prioritise. These could be handy to know.

**Comment by Noitarud** [comment]
My suggestion of remembering options relates to other situations also, #413
