### ISSUE TITLE
Format error while cutting video and downloading.

### ISSUE THREAD

**Issue by Dertyiula** [JunkFood02/Seal#399]
### Describe the bug

You cut and download some video and a format error occurs, the default device video player does not display the video, only the sound is played. Also, the cut and downloaded video sometimes disappears.

### To Reproduce

1.Cut the video and download it.
2.Video cannot be played.
3.Format not supported.

### Error reports & Screenshots

![Screenshot_20221209-162416_Gallery](https://user-images.githubusercontent.com/119277871/206702625-3c8ceeae-8aa9-408a-96cf-c51facbd361d.jpg)

https://user-images.githubusercontent.com/119277871/206702635-480d9139-b6fd-413f-9611-e18b790d2ca7.mp4

My device does not support this format.

### Device info

App version: 1.6.1 (10610)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1447 x 719

### Additional context

I checked all formats in settings.

**Comment by Dertyiula** [comment]
However, it supports H.264 and MPEG-4.

**Comment by Dertyiula** [comment]
It is not unrelated.

**Comment by Dertyiula** [comment]
The video cannot be viewed due to format issues.

**Comment by Dertyiula** [comment]
This is what happens in videos.Don't you see?

**Comment by JunkFood02** [comment]
Please provide the custom command you're using and the link to the video

**Comment by Dertyiula** [comment]
This is observed in several videos.
Example:https://www.youtube.com/watch?v=-7vQ3PzrQ0o&t=0

**Comment by Dertyiula** [comment]
![Screenshot_20221209-182352_Seal](https://user-images.githubusercontent.com/119277871/206723434-76eaa811-ebcd-4d71-afa2-87144535b9cd.jpg)

**Comment by Dertyiula** [comment]
This function needs to be improved.🙃

**Comment by JunkFood02** [comment]
It seems that you have misunderstood of what the app actually does. Seal is merely a GUI of yt-dlp, so you should know what it is and how to use it before raise an issue here. 

As far as I know, yt-dlp has not "cut up a video and download it" feature either
