### ISSUE TITLE
[Bug Report] Can't download videos

### ISSUE THREAD

**Issue by MatadorProBr** [JunkFood02/Seal#402]
### Describe the bug

Trying to download any video will result with a 'The file cannot be downloaded' error.

### To Reproduce

1. Go to 'Seal'
2. Paste the video link
3. Click on the download video button

### Error reports & Screenshots

![image](https://user-images.githubusercontent.com/71022656/206823512-c96b59ab-574d-46aa-a4b3-e241bfdc5bb0.png)
> 'The file cannot be downloaded' - translated error messsage

Also I didn't find the 'Detailed output' option in the settings so can't really send the full error log, maybe a logcat if you really want.

### Device info

App version: 1.6.1 (10610)
Device information: Android 10 (API 29)
[armeabi-v7a, armeabi]
Screen resolution: 1381 x 719

**Comment by JunkFood02** [comment]
Detailed output is in the general settings, the one below save thumbnail

**Comment by MatadorProBr** [comment]
Thanks, now I enabled and finded out that it was a SponsorBlock format issue that I made so sorry for wasting your time.

Also a suggestion, make this option on by default since it will help much people to find what is causing to not work.
