### ISSUE TITLE
Option to stop the download.

### ISSUE THREAD

**Issue by Dertyiula** [JunkFood02/Seal#408]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There should be an option to pause the video that is downloading. We want to temporarily pause the video that is being downloaded. Also, this problem causes the video that is downloading to be lost when the internet connection is lost. The download should stop when there is no internet connection and resume when it is restored.

### Describe the solution you'd like

Stop downloading video when internet connection is lost, resume when internet connection is restored.Option to pause the download

### Video link

This is useful for all videos.

### Additional context

As an additional option:

![Screenshot_20221210-195102_Snaptube](https://user-images.githubusercontent.com/119277871/206863596-9bad0995-1152-43c5-b330-dfff3192a9b6.jpg)

![Screenshot_20221210-195153_Snaptube](https://user-images.githubusercontent.com/119277871/206863637-45eaffca-3aa1-467c-82ab-80b5b3a27093.jpg)

**Comment by BobbyESP** [comment]
You can stop the download of the video that you're downloading. yt-dlp, the library that Seal uses, divides the video that you are downloading in .part files, so if the video is cancelled by any reason, you can resume the download without having to download the hole video another time.

**Comment by Dertyiula** [comment]
We want to stop manually.

**Comment by BobbyESP** [comment]
You can. When the vidwo is being downloaded, click on the text that appears below "Seal" text.

**Comment by Dertyiula** [comment]
This completely cancels the download.I want to stop.

**Comment by JunkFood02** [comment]
Not supported by yt-dlp
