### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [JunkFood02/Seal#41]
Would you consider publishing this app on F-Droid please? 

RFP: https://gitlab.com/fdroid/rfp/-/issues/2142

**Comment by JunkFood02** [comment]
Merged. Is there any other thing that needs to be done?

**Comment by linsui** [comment]
We need a static version code for auto update. We don't run the gradle code when checking update. Could you please provide it somewhere, e.g. in the tag name?

**Comment by JunkFood02** [comment]
> We need a static version code for auto update. We don't run the gradle code when checking update. Could you please provide it somewhere, e.g. in the tag name?

Is hardcoding works [here](https://github.com/JunkFood02/Seal/blob/8509ec707569bb76003152911f1883bd1bb1333a/app/build.gradle.kts#L48)?

**Comment by linsui** [comment]
Yes.

**Comment by JunkFood02** [comment]
@linsui I've made the change in the latest tag. Please check if everything works well. Thanks!

**Comment by linsui** [comment]
The short_description in en-US is too long. We have a limit the it should be shorter than 80 charactors. You can change it to `Video/audio downloader designed and themed with Material-You` since we all know that it's open source and for Android.

**Comment by linsui** [comment]
It checks the yt-dlp update on start so it connects to GitHub without any interaction. Could you make it a dialog that user can choose what to do? It crashes when the link is not support, e.g. a bilibili bangumi link.

**Comment by JunkFood02** [comment]
> It checks the yt-dlp update on start so it connects to GitHub without any interaction. Could you make it a dialog that user can choose what to do? It crashes when the link is not supported, e.g. a bilibili bangumi link.

This seems like an emerging bug, I'll fix it ASAP 🤦

**Comment by linsui** [comment]
Thanks! The app will be available in F-Droid in 2-3 days. This is the badge of F-Droid.

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.junkfood.seal)

```
[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/com.junkfood.seal)
```

**Comment by linsui** [comment]
Currently if we build multiple apks we can't enable auto update. So if you'd like to open an MR for every version as [dvd](https://gitlab.com/fdroid/fdroiddata/-/merge_requests?scope=all&state=merged&search=dvd) we can do that.

**Comment by JunkFood02** [comment]
> Currently if we build multiple apks we can't enable auto update. So if you'd like to open an MR for every version as [dvd](https://gitlab.com/fdroid/fdroiddata/-/merge_requests?scope=all&state=merged&search=dvd) we can do that.

Thx! Maybe there's something needed to be done [here](https://github.com/JunkFood02/Seal/blob/a2763801006c3904f7791148318ab115092ad833/app/build.gradle.kts#L89) and `gradle.properties`. I'll also bump up the version code to 900.

**Comment by JunkFood02** [comment]
> F-Droid app size issue fixed? Hope to get [v1.0.0](https://github.com/JunkFood02/Seal/releases/tag/v1.0.0) as multiple apks on F-Droid.
 
I've released version 10000, please take a look at it. @linsui 
According to what dvd does, switch `splitApks` to `false`, configure separate `ABI_FILTERS` in `gradle.properties`, and set the corresponding version code should do the work.

**Comment by linsui** [comment]
It should work but you still need to add new versions manully as dvd. https://gitlab.com/fdroid/fdroiddata/-/commit/7fd1b40d2c371453c55a62778956800674893295 The auto update is still enabled so I guess ot will be a universe apk?

**Comment by JunkFood02** [comment]
> 
I see. So it means that I should manually modify 'metadata/com.junkfood.seal.yml' for every new release and disable auto-update. I thought there were some ways to get things done automatically. 🤔 Releases could be updated quite frequently so I think we'd better leave the auto-update enabled.

However, the 100M+ size of the apk for an update is still painful. Since very few devices run Android with x86 or x86_64, maybe a workaround here is to package only armeabi-v7a and arm64-v8a architectures into a single F-Droid build apk.

**Comment by JunkFood02** [comment]
After a bit of search, I found [this](https://f-droid.org/docs/Build_Metadata_Reference/#VercodeOperation) mentions something about building apks for multiple ABIs with different version codes. So I'm still wondering whether there's any way to achieve this, or if we should still build a single apk. @linsui

**Comment by linsui** [comment]
It can be used to select an ABI but still only one... Currently we can't auto update for multiple apks.

**Comment by linsui** [comment]
Someone needs to make an MR for every update if they want to keep 1.0.0 as suggested.

**Comment by JunkFood02** [comment]
> I meant ~v1.0.0~ stable releases, NVM not an issue.

That's fine I think even though they're tagged as "pre-release". I'll pay more attention to releasing more stable versions.

**Comment by linsui** [comment]
Now we support auto-update for multi-abi apps.

**Comment by JunkFood02** [comment]
> Now we support auto-update for multi-abi apps.

@linsui Please let me know if I can help with this

**Comment by linsui** [comment]
@JunkFood02 Oh, there is a new version. How to build an apk for one abi? I thought I need to patch https://github.com/JunkFood02/Seal/blob/main/app/build.gradle.kts#L77?

**Comment by JunkFood02** [comment]
>  How to build an apk for one abi? 

ABI splits is for build four apks at a time, meanwhile [ABIFilters](https://github.com/JunkFood02/Seal/blob/main/app/build.gradle.kts#L68) are for building one apk for single or multiple ABIs. So if you need to execute the gradle script for four times to build multiple apks, you should manally specified the `ABI_FILTERS` in `gradle.properties` or [here](https://github.com/JunkFood02/Seal/blob/main/app/build.gradle.kts#L68)

> And what's the version scheme for different abi? 

arm64-v8a>armeabi-v7a>x86_64>x86 I think. Corresponding version codes are 14004 -> 14001

**Comment by linsui** [comment]
> arm64-v8a>armeabi-v7a>x86_64>x86 I think. Corresponding version codes are 14004 -> 14001

Do I need to set the version code manully or it's set with the ABIFilters?

**Comment by JunkFood02** [comment]
> 

Yes, the version codes should be modified manually. For a specific release like v1.4.0 (10400), add 1-4 to the version code

**Comment by linsui** [comment]
> `APK: '1.4.0-(F-Droid)' / '10400',  Expected: '1.4.0-(F-Droid)' / '10404'`

Looks like I need to patch the version code manully. Most apps use `x86_64>x86>arm64-v8a>armeabi-v7a` however.

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11980

**Comment by JunkFood02** [comment]
> Most apps use `x86_64>x86>arm64-v8a>armeabi-v7a` however.

This makes sense. 😳 Since some emulators with x86_64 arch also support arm ABIs.

**Comment by linsui** [comment]
I'll change the version code in the next version.
