### ISSUE TITLE
Option to rename the file before downloading.

### ISSUE THREAD

**Issue by Dertyiula** [JunkFood02/Seal#410]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Option to rename the file before downloading.

### Describe the solution you'd like

Rename the file before downloading.

### Video link

It does not matter.

### Additional context

No

**Comment by JunkFood02** [comment]
#234
