### ISSUE TITLE
[Feature Request]Adding Spotify Downloader (Spot-dl)

### ISSUE THREAD

**Issue by walterwhite550** [JunkFood02/Seal#411]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by JunkFood02** [comment]
#48
