### ISSUE TITLE
[Bug Report]cover size is too big!

### ISSUE THREAD

**Issue by Doiredus** [JunkFood02/Seal#418]
### Describe the bug

Hello! I use function "crop artwork", and size of artwork is too big (1 mb+)
Can u change cover format from png to jpeg, and art size from 700x700 to 600x600
At least from png to jpeg will be enought! Or add option choose formats and size art work
P.s the best app i ever usefor y downloader!

### Device info

1.6.1 and 1.7.0 beta 3

**Comment by JunkFood02** [comment]
Could you provide a sample link for test?

**Comment by Doiredus** [comment]
https://music.youtube.com/watch?v=Cy9373QEgzQ&feature=share
