### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by shuvashish76** [JunkFood02/Seal#42]
I've seen OSS projects use these sites for translation purpose
- [Crowdin](https://crowdin.com/)
- [Transifex](https://www.transifex.com/)
- [Weblate](https://weblate.org/en/)

I think Weblate is better as it's [opensource](https://github.com/WeblateOrg/weblate).

Features: https://weblate.org/en/features/
![Screenshot_2021-12-05-21-15-09](https://user-images.githubusercontent.com/48226312/144753433-4fc61e84-f12d-42d0-885e-1b9abd399061.jpeg)
https://weblate.org/en/hosting/

**Comment by JunkFood02** [comment]
I'm still waiting for the first reply from Hosted Weblate. 😢

For the UI design, I copy and paste the code of the animation part from Music You. It doesn't have a LICENSE, and you can still see it in the README of [Read You](https://github.com/Ashinch/ReadYou#credits).

For other parts, I borrowed some ideas from Read You, and most of the design pattern comes from Material Design Guidelines and the Android 12 System Settings.

I would take the suggestions for the about page into consideration, thank you!

**Comment by comradekingu** [comment]
I would think licensing the app translations to GPLv3-later instead of GPLv3-only makes for fewer problems.
https://github.com/JunkFood02/Seal/pull/55 btw :)

**Comment by JunkFood02** [comment]
@comradekingu Done!

**Comment by JunkFood02** [comment]
It seems Hosted Weblate has approved our request 🎉
