### ISSUE TITLE
App crash when downloading multiple unavailable videos from playlist

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#421]
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.junkfood.seal, PID: 20336
com.yausername.youtubedl_android.YoutubeDLException: WARNING: [youtube:tab] YouTube said: INFO - 2 unavailable videos are hidden
ERROR: [youtube] UJIKF2MTM9U: Private video. Sign in if you've been granted access to this video

	at com.yausername.youtubedl_android.YoutubeDL.execute(Unknown Source:236)
	at g8.e.b(SourceFile:78)
	at w7.i0$a$a.l(Unknown Source:30)
	at w8.a.r(Unknown Source:8)
	at n9.l0.run(Unknown Source:100)
	at s9.g.run(Unknown Source:11)
	at t9.j.run(Unknown Source:2)
	at t9.a$a.run(SourceFile:82)
	Suppressed: n9.j0: [w1{Cancelling}@8649f12, Dispatchers.IO]

App version: 1.6.1 (10610)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2263 x 1078

**Comment by Noitarud** [comment]
Maybe this is the problem: I have noticed I can go to youtube from website, and if I return to YouTube later I get a denied error, I presume you have to have evidence you have been to the site first. You tend to not know you are being tested for this.

**Comment by JunkFood02** [comment]
If you can provide the link to the playlist and the exact steps for reproducing the problem, I'll reopen it
