### ISSUE TITLE
App absolutely does not work at all

### ISSUE THREAD

**Issue by roxy47** [JunkFood02/Seal#422]
App can fetch the video info from the link, but downloading the video is always a failure.

**Comment by BobbyESP** [comment]
First of all you should have created the issue using the template. That gives to us more info for helping you, and second, in this cases you should provide a video URL for testing and reproduce the problem, so can you send to us the video link?

Check that you are not using custom commands and enable Detailed Output in general settings.

**Comment by BobbyESP** [comment]
Nice! And welcome to this world haha. I told you just to know about the templates because that makes the process of fixing the bugs easier :)
