### ISSUE TITLE
[Bug Report]Cant choose sd card for download audio/video

### ISSUE THREAD

**Issue by Doiredus** [JunkFood02/Seal#426]
### Describe the bug

Hello there! I cant choose sd card to download audio/video.
When i try to choose sd card - There's an error (this directory is not supported) 
Can u pls fix it if it possible👍👍
P.s i tried it on xiaomi(miui 13, android 12)

### Device info

App version: 1.7.0-beta.3 (10610)/1.6.1 Stable
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2252 x 1078

**Comment by BobbyESP** [comment]
#34, sorry
