### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by xmha97** [JunkFood02/Seal#428]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

youtube-dl supports proxy.
Please add the proxy setting to this app.

Like Telegram:
![Screenshot_2022-10-08-02-19-31-371_org telegram messenger web](https://user-images.githubusercontent.com/23485114/194672914-300a735e-ee72-4714-be12-b5a483809d70.jpg)

**Comment by JunkFood02** [comment]
Seal uses your system's proxy settings by default
