### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Deep4434** [JunkFood02/Seal#429]
### Describe the bug

YouTube and YT Music not downloading 

### To Reproduce

Steps to reproduce behavior
1. Open seal
2. Paste link
3. Download 

### Error reports & Screenshots

![Screenshot_20221215-221541](https://user-images.githubusercontent.com/100969739/208034742-7e484dfd-fd7f-4b44-9b23-83dc64173db9.png)

### Device info

App version: 1.6.1 (10610)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2155 x 1079

**Comment by BobbyESP** [comment]
Seems like your cookies file is not good formatted
