### ISSUE TITLE
请问Youtube下载的文件名最后一定需要加入视频id后缀吗？

### ISSUE THREAD

**Issue by sparky0915** [JunkFood02/Seal#434]
### Describe the bug

![Screenshot_2022-12-19-09-35-22-515_com android fileexplorer](https://user-images.githubusercontent.com/76830469/208331485-758a0d77-4797-470e-9dff-59d97ed35c20.jpg)
![Screenshot_2022-12-19-09-35-07-536_com android fileexplorer](https://user-images.githubusercontent.com/76830469/208331489-33d7a3bd-b549-408e-af5a-f6dc3a5f10dd.jpg)

**Comment by JunkFood02** [comment]
Seal need the id in the filename to scan the files into download history & system media database
