### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by venkat2305** [JunkFood02/Seal#437]
### Describe the bug

Black screen after downloading a video from Instagram 

### To Reproduce

Download this link
https://instagram.com/stories/shopefacial/2979904033123025769?igshid=MDJmNzVkMjY=

### Error reports & Screenshots

https://user-images.githubusercontent.com/55329452/208656960-cc51f30b-41b0-48f0-9062-f7646ce86835.mp4

**Comment by Marco-9456** [comment]
> ### Describe the bug
> Black screen after downloading a video from Instagram
> 
> ### To Reproduce
> Download this link https://instagram.com/stories/shopefacial/2979904033123025769?igshid=MDJmNzVkMjY=
> 
> ### Error reports & Screenshots
>  Screenrecorder-2022-12-20-16-14-37-939.mp4 
> ### Device info
> _No response_
> 
> ### Additional context
> _No response_

Reproducible, this happens also when Seal fails to fetch video info, i think it's related to the new Format Selection option because disabling the option will make this visual bug disappear.

**Comment by JunkFood02** [comment]
You may need valid cookies that contains your account information to download video from instagram

**Comment by Marco-9456** [comment]
> 

This is only required if you're trying to Download from a private account

**Comment by venkat2305** [comment]
Can you please tell me how to get and use those cookies to download that
At video @JunkFood02

**Comment by JunkFood02** [comment]
Settings - Network - Cookies - input https://www.instagram.com in URL field - Generate new cookies - Log-in in the browser
