### ISSUE TITLE
An option to download suggested video directly without selecting format

### ISSUE THREAD

**Issue by venkat2305** [JunkFood02/Seal#439]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

An option to download suggested video directly without selecting format

### Describe the solution you'd like

Remove this page
![Screenshot_2022-12-20-19-50-05-386_com junkfood seal](https://user-images.githubusercontent.com/55329452/208690159-b55c9e91-fc00-453f-9425-d7887a3588b6.jpg)

**Comment by JunkFood02** [comment]
Settings - Format - Turn off Format selection
