### ISSUE TITLE
Instagram Stories.

### ISSUE THREAD

**Issue by ghost** [JunkFood02/Seal#446]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I can't download Instagram stories. But yt-dlp supports this function.

### Describe the solution you'd like

Function to download videos from Instagram stories.

### Video link

https://instagram.com/stories/uzel.kerimova/2998977106964480689?utm_source=ig_story_item_share&igshid=NjcyZGVjMzk=

### Additional context

There is no

**Comment by JunkFood02** [comment]
Please wait for the next pre-release (or stable) update.

**Comment by Fidannyan** [comment]
I have downloaded the debug version but this function is still missing.

**Comment by Fidannyan** [comment]
In the latest Debug version, this function does not work or does not exist. When downloading, it says that the video data was not received.

**Comment by JunkFood02** [comment]
Use cookies and try again (why the account was deleted?)
