### ISSUE TITLE
[Bug Report] File name too long error when downloading video from twitter

### ISSUE THREAD

**Issue by cws999** [JunkFood02/Seal#448]
### Describe the bug

https://mobile.twitter.com/WG6LPjptWpPuP6S/status/1603982833143250944?s=20

1.7.0-beta.4 no log

this is 1.6.1 log

WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated token. Only one media item can be extracted
ERROR: unable to open for writing: [Errno 36] File name too long: '/data/user/0/com.junkfood.seal/files/tmp/*LONG_TITLE* [1603214616078655488].mp4.part'

### Device info

[v1.6.1](https://github.com/JunkFood02/Seal/releases/tag/v1.6.1)
[v1.7.0-beta.4](https://github.com/JunkFood02/Seal/releases/tag/v1.7.0-beta.4)

**Comment by Marco-9456** [comment]
You can use this option in a custom command template as workaround:
`--restrict-filenames`

**Comment by Marco-9456** [comment]
> You can use this option in a custom command template as workaround: `--restrict-filenames`

After some Googling i found this on [stackoverflow](https://stackoverflow.com/questions/13204807/max-file-name-length-in-android#:~:text=It%20is%20apparently,limit%20of%20127) :
![chrome_image_25 12 2022 21_36_53 MEZ](https://user-images.githubusercontent.com/41828058/209481396-45965300-8243-4de7-a586-4e6bea885bc7.png)
