### ISSUE TITLE
[Can not fetch Video Info

### ISSUE THREAD

**Issue by maxs99674** [JunkFood02/Seal#449]
### Describe the bug

this happens when trying to download Instagram reels

### To Reproduce

Go to reels 
Share it to seal

### Device info

1.6.1

### Additional context

Everything else works fine i think

**Comment by BobbyESP** [comment]
For me the reels downloading is working. 
Region: Spain

**Comment by Marco-9456** [comment]
> ### Describe the bug
> this happens when trying to download Instagram reels
> 
> ### To Reproduce
> Go to reels Share it to seal
> 
> ### Error reports & Screenshots
> _No response_
> 
> ### Device info
> 1.6.1
> 
> ### Additional context
> Everything else works fine i think

Was the video from a private account ?

**Comment by JunkFood02** [comment]
Use cookies and try again

**Comment by firofame** [comment]
same issue

Example URL: https://www.instagram.com/reel/CnzB0EyPL_3/?igshid=Yzg5MTU1MDY=

confirmed that the video is not from private account
Happens every time
confirmed that the url is good

**Comment by egakupi** [comment]
There seems to be some restrictions because of location. I can download from the link from one country and can't from another
