### ISSUE TITLE
Reliable playlist background downloads

### ISSUE THREAD

**Issue by AndrewIsBest69** [JunkFood02/Seal#45]
2 suggestions to do that:

1) Add a reminder somewhere in the app to set battery optimization to "unrestricted" for Seal in system settings
2) Create a separate notification for the playlist progress to track how many videos were downloaded out of the total videos

Thanks for creating Seal, it's already the best GUI of yt-dlp and I'm sure that when it goes to stable releases, it's going to be amazing!

**Comment by JunkFood02** [comment]
These two features are already implemented in recent commits, so please stay tuned for the next release!
