### ISSUE TITLE
[Bug Report] Incorrect Simplified Chinese translation

### ISSUE THREAD

**Issue by AzusaHana** [JunkFood02/Seal#456]
### Describe the bug

About subtitles.
In Simplified Chinese, "内嵌字幕" refers to hardsubs. The correct translation should be "内封字幕".

**Comment by JunkFood02** [comment]
内挂字幕？

**Comment by AzusaHana** [comment]
> 内挂字幕？

因为是和视频音频一起封装进去单独轨道的，所以一般叫“内封字幕”

在外面单独文件挂载的“外挂字幕”

嵌进视频图像里的是“硬字幕”或者“内嵌字幕”
