### ISSUE TITLE
Embed auto subtitle into videos from YouTube

### ISSUE THREAD

**Issue by MrBobbyNayak** [JunkFood02/Seal#457]
### Describe the bug

I have selected the embedded subtitles option but no subtitles were downloaded

### To Reproduce

1. Copy youtube link
2. Paste in seal
3. Select Embedded subtitles in advanced download settings
4. Click on download
5. Check the file whether has subtitles or not

### Device info

App version: 1.6.1 (10610)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1528 x 719

**Comment by JunkFood02** [comment]
Link?

**Comment by MrBobbyNayak** [comment]
> https://youtu.be/Qb7JITsbyKs

**Comment by Marco-9456** [comment]
> > https://youtu.be/Qb7JITsbyKs
> > Auto generated english subtitles are available but were still not downloaded

Yeah Seal doesn't download auto generated subs by default, if you want the video with auto generated subs you can use this command 
```
--write-auto-subs
--embed-subs
```
in a custom command template

**Comment by venkat2305** [comment]
@JunkFood02 as more users use this app, more people are going to request this feature. Do you plan to add this?

**Comment by MrBobbyNayak** [comment]
> @JunkFood02 as more users use this app, more people are going to request this feature. Do you plan to add this? It would be great

Yes ofcourse this would be great

**Comment by MrBobbyNayak** [comment]
This feature will be a lot helpful for people with language barriers

**Comment by venkat2305** [comment]
@MrBobbyNayak why did you close this issue. Please open it back
