### ISSUE TITLE
[Bug Report] app is not allowed download to sdcard

### ISSUE THREAD

**Issue by Doiredus** [JunkFood02/Seal#464]
### Describe the bug

At the last update, you can save file to any folders(internal storage), but still can't choose sd card to save files.

### Device info

App version: 1.7.0 (10700)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2252 x 1078

**Comment by BobbyESP** [comment]
See #455
