### ISSUE TITLE
[Bug Report] I can't download any video from youtube

### ISSUE THREAD

**Issue by geekcanion** [JunkFood02/Seal#466]
### Describe the bug

Hi, when I try to download a video from YouTube the app detects it but I can't download it, I've tried everything without success, I can't download any video from YouTube but from platforms like Twitter I can, I would really appreciate it if you could solve my issue, thank you

![IMG_20221230_073031](https://user-images.githubusercontent.com/58098324/210042385-cd3868b4-ab22-4c21-85e0-ef682901c237.jpg)

### Device info

App version: 1.7.0 (10700)
Device information: Android 13 (API 33)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2961 x 1440

**Comment by JunkFood02** [comment]
I think this could be a network problem. Can you go to Settings - Network - Cookies, then generate cookies with your YouTube account and try again?

**Comment by BobbyESP** [comment]
For me it works (the same video).

**Comment by geekcanion** [comment]
> your

Doesn't work, I have something that is blocking the download, maybe some feature of Adguard? I have deactivated "Seal" from Adguard but it still does not download, it only happens with YouTube, I don't understand ii...😥

**Comment by geekcanion** [comment]
> I think this could be a network problem. Can you go to Settings - Network - Cookies, then generate cookies with your YouTube account and try again?



> I think this could be a network problem. Can you go to Settings - Network - Cookies, then generate cookies with your YouTube account and try again?

Doesn't work, maybe I have something that is blocking the download, maybe some feature of Adguard? I have deactivated "Seal" from Adguard but it still does not download, it only happens with YouTube, I don't understand it...😥
