### ISSUE TITLE
[Feature Request] Overlay upon other apps instead of redirecting to main app

### ISSUE THREAD

**Issue by keyjeyelpi** [JunkFood02/Seal#470]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Can we overlay the download options on the app shared rather than redirecting to the Seal app? 

### Describe the solution you'd like

Here's an image of what I hope it would look like when being used:
![a1993e49-2a43-4ba4-911c-6fec666b8857](https://user-images.githubusercontent.com/49813589/210134742-4c5f31ef-1ae1-4216-a0e0-8023d22b0d34.png)

**Comment by Marco-9456** [comment]
Duplicated https://github.com/JunkFood02/Seal/issues/152
