### ISSUE TITLE
[Bug Report] Custom command mode in v1.7.0

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#472]
### Describe the bug

1. When it's on, Seal doesn't show 'Download finished' sign.
2. Why 'Detailed output" and 'Download playlist' options are now only off, when this mode is on?

To download multiple videos from multiple links this mode is still required (so I leave it on), but why it affected other options?
This makes v1.7.0 inconvenient, comparing to prior Seal versions.

### Device info

App version: 1.7.0 (10700)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1464 x 720

**Comment by Marco-9456** [comment]
Bruh it are you really that lazy:

https://user-images.githubusercontent.com/41828058/210155282-d95d8880-45ad-4517-be3f-cb71d567f9d6.mp4

**Comment by Botan626** [comment]
> Bruh it are you really that lazy:
> 
>  Screen_Recording_20221231_213451_Seal.mp4

You are trying to justify regress in program convenience usage now.
'Configure before download' was off in versions prior to v1.7.0, and Seal performed all needed tasks for me without switching something on or off every time.

**Comment by JunkFood02** [comment]
"Download playlist" and "Detailed output" has never  effects to how custom commands works. The changes in v1.7.0 move the progress to notifications

**Comment by Botan626** [comment]
Is it not possible to bring detailed outputs and 'Download finished' sign back in the app while 'Use custom command' is on?
