### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by DavidSpivey** [JunkFood02/Seal#473]
### Describe the bug

The new version allows the user to choose a video format, but does not give options for combined video and audio from audio-only and video-only sources.

For example, in most videos from YouTube I have tried, there is a 720p version that has audio+video, but NO 1080p audio+video version. However there is a 1080p video and a decent quality audio available. Most downloaders use ffmpeg to combine these two into a working video file. This option does not seem to exist in seal.

### To Reproduce

Try to download https://m.youtube.com/watch?v=bpTOcZN9JB4  as an MP4 and there will be no 1080p audio+video option.

### Device info

App version: 1.7.0-(F-Droid) (10704)
Device information: Android 11 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2772 x 1439

**Comment by DavidSpivey** [comment]
Sorry, my browser isn't allowing me to edit the title of this bug report.

**Comment by JunkFood02** [comment]
😂 Seems you've figured out how to merge video & audio
