### ISSUE TITLE
[Feature Request] Download Queue if Download Already Present

### ISSUE THREAD

**Issue by cloud1494** [JunkFood02/Seal#475]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

If a Download is already going the app currently won't let you input another Download request until the current one is done. 

### Describe the solution you'd like

I'd like a subsequent download request to be placed in a queue to be completed after the current download finishes with no limit as to the number of queue positions. 

### Video link

Any links already supported 

### Additional context

Would like to be able to input downloads at any time regardless of whether a download is already going.

**Comment by Marco-9456** [comment]
Planned https://github.com/JunkFood02/Seal/issues/324

**Comment by neonota** [comment]
+1
