### ISSUE TITLE
[Bug Report] buggy custom commands

### ISSUE THREAD

**Issue by yant0** [JunkFood02/Seal#476]
### Describe the bug

After updating to 1.7.0. The custom commands became very buggy and few other issues i faced ever since updating.

- the download notification for custom commands are just a looping bar. It used to work in previous versions.
- the download notification does not end after downloading
- ytdlp ignoring commands(??)
- there are temp files.
- maybe others i havent noticed

### To Reproduce

Tried with this [soundcloud](https://soundcloud.com/jack-zebra/sets/jack1888-mixtape). Still have some issues even with the default custom command built in from the app.

### Error reports & Screenshots

`embed-thumbnail` is ignored 
![Screenshot_20230101-212702339](https://user-images.githubusercontent.com/80298071/210174225-bd254397-0181-467d-bdb4-9553a4fb3c6c.jpg)
<details>
<summary>template</summary>
-o "Audio/Commands/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d %(title)s.%(ext)s" -f "ba[ext=opus]/ba" --embed-thumbnail --parse-metadata "playlist_index:%(track_number)s" --parse-metadata "description:(?s)(?P<meta_lyrics>.+)" --embed-metadata 
</details>
![Screenshot_20230101-212718_Bromite](https://user-images.githubusercontent.com/80298071/210174734-5572c6e0-321d-473b-b047-84df9d1dcc94.png)

### Device info

Android 11 Custom rom.
Seal 1.7.0 (F-droid)
arm64-v8a

### Additional context

The version of yt-dlp used is the same one that i used on the last update. 2022.11.11

**Comment by yant0** [comment]
Sorry if its messy, im writing this on a phone and accidentally sent it too 🤦‍♂️

**Comment by Marco-9456** [comment]
> Sorry if its messy, im writing this on a phone and accidentally sent it too 🤦‍♂️

Try this:
```
-o "Audio/Commands/%(uploader)s/%(playlist_title|YT-DLP)s/%(playlist_autonumber)02d %(title)s.%(ext)s"
-f "ba[ext=opus]/ba"
--embed-thumbnail
--parse-metadata "playlist_index:%(track_number)s"
--parse-metadata ":(?P<description>)"
--embed-metadata
```

**Comment by Marco-9456** [comment]
>the download notification for custom commands are just a looping bar. It used to work in previous versions.

This happens to me sometimes

>the download notification does not end after downloading.

This is also happening to me.

>ytdlp ignoring commands(??)

Be specific

>there are temp files.

This is normal, if you want to delete them go to `Settings > Download Directory > Clear temporary files.`

**Comment by JunkFood02** [comment]
Clear temporary files doesn't works for custom commands. But the problem you mentioned seems like a storage permission issue, have you changed your download directory? I've tried the link you provide but didn't reproduce the other issues except the first one

**Comment by yant0** [comment]
> Clear temporary files doesn't works for custom commands. But the problem you mentioned seems like a storage permission issue, have you changed your download directory? I've tried the link you provide but didn't reproduce the other issues except the first one

I suspect its on my end too (storage) i wanted to test out other links first but i accidentally click submit lol. I've tested it once again it works now. If youve known about the notification bug then i wouldnt mind the issue being closed. 👍

**Comment by JunkFood02** [comment]
Thanks for your quick reply! I pushed a change that may fix the notification problem. You can install the [CI apk](https://github.com/JunkFood02/Seal/actions/runs/3817786595) once it finishes building to see if things work well

**Comment by Marco-9456** [comment]
> I pushed a change that may fix the notification problem. You can install the [CI apk](https://github.com/JunkFood02/Seal/actions/runs/3817786595) once it finishes building to see if things work well

Still looping


https://user-images.githubusercontent.com/41828058/210179185-da10178f-d379-4ae0-aab0-c8fecd145b87.mp4

**Comment by JunkFood02** [comment]
The problem is complicated and hard to reproduce, but it seems to be related to the rate limit of notifications from the Android System. I'll take another look sooner
