### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by donmabood** [JunkFood02/Seal#477]
### Describe the bug

After the 1.7 update I can't download youtube videos in best quality. Only showing 720p with audio, 1080p is showing but no audio. What's happening. Before this update everything was just awesome. After this update when I paste a link I see two popups.

### Error reports & Screenshots

![Screenshot_2023-01-02-14-59-16-87_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/121794165/210214050-ae209bd1-db8d-4476-9943-64083e6e2a37.jpg)
![Screenshot_2023-01-02-14-59-34-18_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/121794165/210214057-a2b8f108-0511-4d1f-8458-0b838fbe66c8.jpg)
![Screenshot_2023-01-02-14-59-42-59_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/121794165/210214065-ef75f858-128f-4916-8dac-8ed049bf592e.jpg)

**Comment by JunkFood02** [comment]
Suggested format is already the best format you can get. YouTube provide audio & video stream separately, you need to select video only and audio only formats together at a time to merge them into a video. This is not a bug, if you want the app to decide the best format (suggested) for you, you can go to Settings - Format and turn off "Format selection"
