### ISSUE TITLE
[Bug Report] selfpromo section still exists although i set the sponsorblock category

### ISSUE THREAD

**Issue by AndyH0ng** [JunkFood02/Seal#481]
### Describe the bug

It does shrink the video length but play continuously anyway, showing the promo section

### To Reproduce

1. Set sponsorblock category to intro,outro,selfpromo
2. Download https://youtu.be/qBIxl_6tFfo
3. Same thing happens when i download as Webm or mp4 or opus

### Error reports & Screenshots

https://youtu.be/HF9G7EGkQ4k

### Device info

1.7.0

**Comment by JunkFood02** [comment]
SponsorBlock doesn't have info with this video
