### ISSUE TITLE
[Feature Request] Detailed output inside Seal

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#484]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [x] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Why detailed output is now in notifications exclusively?
Watching progress became much less convenient, than it was in versions prior to 1.7.0, because now the user has to manage notifications.
Please bring detailed output back into Seal and let the user decide, where he'd like to have it (notifications or Seal).

**Comment by JunkFood02** [comment]
Isn't it already in v1.8.0-rc.1?

**Comment by Botan626** [comment]
> Isn't it already in v1.8.0-rc.1?

Yes, it is. Thank you so much :slightly_smiling_face:

One thing though: I turned "Download notification" off, but there is still notification, while downloading videos.
App version: 1.8.0-rc.1 (10800)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by JunkFood02** [comment]
@Botan626 Will get fixed in next rc version

**Comment by Botan626** [comment]
Two more things:
1. I think this page should say "Log" on top, not "Logs", since it's a single Log.
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/212693502-28d8ccb3-c2e7-4b65-bead-36aaa4bc2cea.png)

</details>

2. There is no 'Download finished' message, not in log, not in pop up sign.
