### ISSUE TITLE
Lower SDK/API to at least Lollipop 5.1

### ISSUE THREAD

**Issue by Gittore54** [JunkFood02/Seal#486]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

For my parents old device

### Describe the solution you'd like

I see that LibreTube has Lollipop support, is possibile to implement also with Seal? It has similar Material You libraries, or they aren't exactly the same?

**Comment by Gittore54** [comment]
Also it was implemented in android-oss-release-tracker #10

**Comment by Gittore54** [comment]
> I do this with ApkEditor.😆

How?

**Comment by JunkFood02** [comment]
Try https://github.com/JunkFood02/Seal/releases/tag/v1.8.0-beta.2
