### ISSUE TITLE
ability to download videos to SD memory card by support SD card directories

### ISSUE THREAD

**Issue by ediotism** [JunkFood02/Seal#487]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

android phone has limited storage space whilst a 1TB memory card can be put in and store ample amount of videos

### Describe the solution you'd like

support SD card directory

**Comment by BobbyESP** [comment]
The last beta version has this function
