### ISSUE TITLE
App Crashes When Downloading Some Reddit GIFs

### ISSUE THREAD

**Issue by adarsh1001** [JunkFood02/Seal#493]
### Describe the bug

For some reason, the app crashes when the following Reddit GIF URL is given as input: 
https://www.reddit.com/r/ProgrammerHumor/comments/105xnp2/its_friday_and_i_aint_working_anymore

It works fine for other Reddit GIFs that I've tried. `yt-dlp` has no issues downloading this though.

### To Reproduce

1. Open Seal.
2. Input URL: https://www.reddit.com/r/ProgrammerHumor/comments/105xnp2/its_friday_and_i_aint_working_anymore
3. App crashes.

### Error reports & Screenshots

No error is thrown in the app, it directly crashes.

### Device info

App version: 1.7.1-(F-Droid) (10714)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
Reproduced

**Comment by JunkFood02** [comment]
seems like GIF conflicts with format selection because it's not video

**Comment by adarsh1001** [comment]
@JunkFood02 Interestingly, it works with this GIF: https://www.reddit.com/r/linuxmasterrace/comments/106fi65/4_gb_ram_and_no_nvidia_card_you_say.
