### ISSUE TITLE
Video's delayed update in Gallery

### ISSUE THREAD

**Issue by MrBobbyNayak** [JunkFood02/Seal#494]
### Describe the bug

When I download a Video ,after completion the video file is not shown in gallery immediatly after download
Evn though,I am able to access those in file manager The videos don't get updated in Gallery for days.

### To Reproduce

1.Copy link to download
2. After download completion check gallery
3. It will not be available in gallery or in seal downloads
4. Open it through file manger

### Device info

App version: 1.7.2 (10720)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
> 3. It will not be available in gallery or in seal downloads

Where you downloading using custom commands?
,
- if yes just add --no-mtime to the template this will fix it

**Comment by JunkFood02** [comment]
Downloads with custom commands will not be scanned into system media library
