### ISSUE TITLE
[Feature Request] Download Channel

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#495]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

If you try to download a whole channel that have more than one video category like `lives` `shorts` and `videos` using `Download Playlist` option it will show you the above mentioned categories as Videos with the channel 
profile picture as a thumbnail and when you select for example all of the three categories, it will download the first most recent `video,` `live stream,` `short`

- Downloading [This](https://youtube.com/@bruhsified)  channel works with `Download Playlist` option because it doesn't have videos in live or shorts categories.
- Downloading [This](https://youtube.com/@adultswimde)  channel will show what i have described above

### Describe the solution you'd like

An option with the name `Download Channel` _(or something else)_ that shows when selecting it a `Download Playlist UI` lookalike but with separated categories that the user can scroll through and select videos to download from.

### Video link

Something like this maybe
![Screenshot_20230108_213505_Seal](https://user-images.githubusercontent.com/41828058/211218310-36d8bfbe-4acf-45fa-9308-d3aafde25f1d.png)

### Additional context

The idea came up to me after some user's requests in Seal Chatroom.

>**Warning**
Don't make fun of my editing skills or this will happen to you

<details markdown='1'><summary> Show </summary>

https://user-images.githubusercontent.com/41828058/211218627-1fe93da6-3ef7-4924-977c-164ae9bb01d2.mp4

</details>

**Comment by JunkFood02** [comment]
You should use https://www.youtube.com/@adultswimde/videos to download videos in channel
