### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Beech0408** [JunkFood02/Seal#497]
### Describe the bug

The video from a private group that I am a member of is not downloading, even after creating a cookie by logging in to FB and turning on the use of cookies. 

### Error reports & Screenshots

App version: 1.7.2 (10720)
Device information: Android 8.1.0 (API 27)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://www.facebook.com/yesh.bish.9/videos/490930483184563/?idorvanity=980442772494028
ERROR: [facebook] 490930483184563: This video is only available for registered users. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (facebook) to provide account credentials

### Device info

The latest version. (1.7.2)

**Comment by BobbyESP** [comment]
You have to use the cookies option to be able to download that video.

**Comment by BobbyESP** [comment]
After that, try to download the video

**Comment by Beech0408** [comment]
Thanks for replying.
I did exactly as your video directed, and I got the following error message after pasting the link and clicking on the download button :

App version: 1.7.2 (10720)
Device information: Android 8.1.0 (API 27)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://www.facebook.com/moktasim.rahman.5/videos/685995976396449/?idorvanity=980442772494028
ERROR: [facebook] 685995976396449: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
