### ISSUE TITLE
Ability to pause when downloading. 

### ISSUE THREAD

**Issue by Beech0408** [JunkFood02/Seal#498]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm always sad whenever my downloads stop after reaching a huge percentage just because of my internet connection issue. 

### Describe the solution you'd like

It would be nice if a pause icon would be added –just enough to check out my internet issues quickly before continuing the download process! 

### Additional context

I hope you would answer my request positively. Thank you so very much for making this app and thanks in advance (for my request).

**Comment by Marco-9456** [comment]
> ### Describe the solution you'd like
> It would be nice if a pause icon would be added –just enough to check out my internet issues quickly before continuing the download process!

- You can cancel a download operation at any point and resume it by clicking on the download button again just like this;

https://user-images.githubusercontent.com/41828058/211418992-99dc3096-7bef-4ddb-9c92-a430e6b1f091.mp4

**Comment by Beech0408** [comment]
Thank you so very much for the enlightenment. Although I want to ask, what is the longest amount of time before the download link gets invalid? Thanks in advance.

**Comment by Marco-9456** [comment]
> What is the longest amount of time before the download link gets invalid?

- it's not time-related,
Seal doesn't download directly to the chosen path, it will first download in a temporary directory and if the download breaks or got interrupted you can just click on the download button again and it will resume it as long as you didn't clear temporary files 😀.


If you do what I did in the Screen record after a download gets canceled the download can't be resumed.
https://user-images.githubusercontent.com/41828058/211531070-9814fbeb-e84f-47f7-907c-0b3d6c959885.mp4

**Comment by venkat2305** [comment]
> Seal doesn't download directly to the chosen path, it will first download in a temporary directory and if the download breaks or got interrupted you can just click on the download button again and it will resume it as long as you didn't clear the temporary files

new users should be informed of this information. a lot of users have requested the pause button.

**Comment by Beech0408** [comment]
> * You can cancel a download operation at any point and resume it by clicking on the download button again just like this;
>
 
@Marco-9456 I tried to pause a download while following your instructions and it did not work.
