### ISSUE TITLE
Downloading Music 

### ISSUE THREAD

**Issue by Beech0408** [JunkFood02/Seal#501]
### Describe the bug

Please I want to download music from Spotify and the app does not do so. I checked supported sites and Spotify is among them. 

### Additional context

Thanks in advance.

**Comment by BobbyESP** [comment]
Spotify is banned from yt-dlp because DRM protection. I don't want to disturb Junkfood but you want use Spotiflyer or the library/app that I'm creating [spotdl-android](https://github.com/BobbyESP/spotdl-android)

**Comment by Beech0408** [comment]
@BobbyESP thanks for replying. I would like to use your app but I do not know how to use the library. Please is the app with v 0.1.0 working?
Also please it would be nice if you could tell me how to use the library on Android and the necessary apps to be used.
Please do not be angry with me, I am still learning.
Thanks in advance.
I await your reply.

**Comment by BobbyESP** [comment]
I'll launch a release with fixes and the app updated. Please give to me some contact address to get in contact. I don't think this is the best place to talk about it here 😅 I would love to help you!

**Comment by Beech0408** [comment]
@BobbyESP please have my email: anhydrous.salt@gmail.com. I would love to receive your help and I look very forward to getting in touch with you.

I just want to ask is it okay if I download the v0.1.0 app? Please let me know via email. 

Thank you so much for replying.
