### ISSUE TITLE
Facebook Bug

### ISSUE THREAD

**Issue by omarmohamedmoustafa** [JunkFood02/Seal#502]
### Describe the bug

App version: 1.8.0-beta.2 (10730)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://fb.watch/hZlvO-5QKI/
ERROR: [facebook] 3053042581661283: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Error reports & Screenshots

App version: 1.8.0-beta.2 (10730)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://fb.watch/hZlvO-5QKI/
ERROR: [facebook] 3053042581661283: Cannot parse data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.8.0-beta.2 (10730)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by JunkFood02** [comment]
The [full link](https://www.facebook.com/mohammed.abdelhalim.794/videos/3053042581661283/) works for me

**Comment by omarmohamedmoustafa** [comment]
The full link also not working..

App version: 1.7.3 (10730)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL:
https://www.facebook.com/mohammed.abdelhalim.794/videos/3053042581661283/
ERROR: [facebook] 3053042581661283: Cannot parse data; please report this
issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
appropriate issue template. Confirm you are on the latest version using
yt-dlp -U

**Comment by omarmohamedmoustafa** [comment]
> #497 facing the same issue with armeabi-v7a

How to know which version suitable for me

**Comment by JunkFood02** [comment]
https://github.com/yt-dlp/yt-dlp/issues/4311
