### ISSUE TITLE
Weblate is closed.

### ISSUE THREAD

**Issue by Ilhamiii** [JunkFood02/Seal#505]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Translations are locked on Weblate.

### Describe the solution you'd like

.

### Video link

.

### Additional context

.

**Comment by HoriKyoukosimp** [comment]
@Ilhamiii Oof 💀

**Comment by Marco-9456** [comment]
This isn't a feature request fill a bug report,
Also you need an account to translate on weblate

**Comment by HoriKyoukosimp** [comment]
@Ilhamiii
