### ISSUE TITLE
[Feature Request] see the command log / see the full command text in the notification

### ISSUE THREAD

**Issue by igorzhilin** [JunkFood02/Seal#509]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There is no way to see the command execution log / history.
There is no history in the app itself. 
There is some text in the notification, but it is truncated. So I can't really be sure what's happening at the moment.
![truncated](https://i.imgur.com/UmeSRMu.png) 

### Describe the solution you'd like

Have a history of commands in the app.
Or expand the notification and see the full command text there.

Cheers!

**Comment by JunkFood02** [comment]
😉 Now you can try [v1.8.0-rc.1](https://github.com/JunkFood02/Seal/releases/tag/v1.8.0-rc.1)
