### ISSUE TITLE
Prevent user from attempting to download more videos at once

### ISSUE THREAD

**Issue by Cobooz** [JunkFood02/Seal#51]
A set simple GUI enhancements
1. Use regular buttons instead of FABs. To my knowledge, the app does not display so much content that scrolling would be necessary, so normal text+icon buttons should be used.
2. Hide the text field and the buttons when download starts.
3. Kind of unrelated, but a way to cancel one download similarly to how you can cancel a playlist download would be useful

**Comment by JunkFood02** [comment]
1. The FAB is not only used upon scrollable views. It represents the "Primary Operation" of a scene, implies the "Floating" metaphor, and provides a separation from the contents below. Also, on some affordable devices with low-dpi screens, the content would appear below the buttons, so a "Floating Button" could be better here. In addition, some of the "Negative Space" could make the UI looks neater.
2. I'm planning to implement the feature of a download queue, maybe. 🤔
3. Canceling a playlist download is different from canceling a video download. You would notice that when you cancel downloading a playlist in the middle, it would always finish downloading the current video. The only way to cancel a single video download process is to close the app by force.

**Comment by JunkFood02** [comment]
The download configuration dialog is optional, so that would not be the case.
The UI design should not be either filling the whole page or leaving most of the space blank, so I'll hold my own view of this kind of balance here.
