### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by T-sukemono** [JunkFood02/Seal#510]
### Describe the bug

Idk if this is apps fault or not but when I download video from YouTube or Instagram and try to post it in my instagram story it shows unsupported video format same problem when I try to send the video too

### Error reports & Screenshots

![Screenshot_2023-01-14-12-54-32-22_1c337646f29875672b5a61192b9010f9](https://user-images.githubusercontent.com/122665845/212461181-413fb846-2ec6-434c-9b50-9548c8b99972.jpg)

**Comment by AbhiTheModder** [comment]
@T-sukemono In which specs you've downloaded the video?

**Comment by HoriKyoukosimp** [comment]
@T-sukemono Look at this

He is probably importing webm i guess 💀

**Comment by JunkFood02** [comment]
Instagram supports few video formats, maybe you can try downloading mp4 videos with AVC1+M4A codecs.
