### ISSUE TITLE
As an internet browser

### ISSUE THREAD

**Issue by kalekad** [JunkFood02/Seal#511]
What is the purpose of the app pretending to be an internet browser?

I have several internet browsers and none of them is set as default, and when I want to choose the browser in which to open the link, Seal is also offered.

I don't want Seal to be treated as an internet browser.

**Comment by JunkFood02** [comment]
https://github.com/JunkFood02/Seal/issues/298

**Comment by JunkFood02** [comment]
> Seal is not listed as a browser.

I've removed this since most ppl found it confusing, thus this can be closed now.

> [App Manager](https://github.com/MuntashirAkon/AppManager)'s Interceptor can universally handle most intents despite not being registered as a browser

<details>
<summary>Nope</summary>
<img src="https://github.com/JunkFood02/Seal/assets/69683722/b4bae4dc-a4b5-48d9-935a-acdc6574fd58" alt="" width="30%">

</details>
