### ISSUE TITLE
[Bug Report] Missing from youtubedl wiki

### ISSUE THREAD

**Issue by stefnotch** [JunkFood02/Seal#513]
### Describe the bug

https://www.reddit.com/r/youtubedl/wiki/info-guis/ has a list of all youtube-dl and yt-dlp GUIs. However, this lovely GUI is missing.

It would be lovely if you contacted the moderators to get them to add the GUI. :)

**Comment by AbhiTheModder** [comment]
@stefnotch This is not an issue, but I think it's chat relevant so yo should come into chatrpoms :)

**Comment by stefnotch** [comment]
Nice, it got added to the wiki https://www.reddit.com/r/youtubedl/wiki/info-guis/

I don't use this GUI (am a desktop user), so I don't think there's much of a reason for me to come into the chatroom. My work here is done :)

**Comment by AbhiTheModder** [comment]
@stefnotch :) 👍
