### ISSUE TITLE
[Bug Report] Tiktok video with sensitive content download/playback

### ISSUE THREAD

**Issue by msebastian100** [JunkFood02/Seal#517]
### Describe the bug

Tiktok link with [allegedly] sensitive content.
Cannot be downloaded.
No playback Possible.

### To Reproduce

https://vm.tiktok.com/ZMYe1MWJq/
I have compiled the link and inserted it into the app.

### Error reports & Screenshots

![WhatsApp Bild 2023-01-18 um 20 48 40](https://user-images.githubusercontent.com/4114151/213282197-b6106cf9-188d-4785-900b-df4b696a25e9.jpg)
![WhatsApp Bild 2023-01-18 um 21 01 11](https://user-images.githubusercontent.com/4114151/213282565-e3aa1b7a-7ea0-46b9-9877-6026997c4cfc.jpg)

### Device info

1.7.2. (F-Droid)

### Additional context

Thanks first of all for the super downloader :)
Finally a downloader that works very well.

**Comment by BobbyESP** [comment]
Seems to be a limitation/bug by yt-dlp. It isn't able to get the video info, but it can be downloaded without any problem
