### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by dimplyi** [JunkFood02/Seal#521]
### Describe the bug

Can't fetch video, it always happen, I don't know why
App version: 1.7.3 (10730)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://vm.tiktok.com/ZTRpQdRaw/
ERROR: [vm.tiktok] ZTRpQdRaw: Unable to download webpage: <urlopen error [Errno 101] Network is unreachable> (caused by URLError(OSError(101, 'Network is unreachable')))

### Error reports & Screenshots

![Uploading Screenshot_20230121_215858.jpg…]()

**Comment by JunkFood02** [comment]
Could you open the short URL in your browser and try to download the [complete link](https://www.tiktok.com/@aguilar.nix/video/7190989540398484763)?
