### ISSUE TITLE
[Feature Request] Passing parameter through input to custom commands

### ISSUE THREAD

**Issue by seaque** [JunkFood02/Seal#523]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Ability to pass parameters to commands which need user input. Instead of hard typing certain things, we could assign a section to take parameter such as %start_time% which brings a little input area for us to write, then replaces the text with the input provided by the user.

### Additional context

Would be very useful for commands like --download-sections --sub-langs that changes based on the video.

**Comment by JunkFood02** [comment]
You can use command shortcuts added in v1.8.0 for this

**Comment by seaque** [comment]
> You can use command shortcuts added in v1.8.0 for this

That's still hard typing, no? Create a shortcut `--download-sections "*0:10-0:30"` and that just adds it as a text to the end of your command. You still have to manually change the timestamps.

**Comment by JunkFood02** [comment]
Shortcuts are convenient enough for composing templates. yt-dlp has tons of "parameters" & "fields", it makes no sense to implement such features to replace "typing"
