### ISSUE TITLE
embed caption translated to a disposable language on YouTube as a subtitle 

### ISSUE THREAD

**Issue by djemaaismail** [JunkFood02/Seal#524]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

there is no subtitle in this video , but YouTube create a good caption in English, and YouTube generate auto translated other languages, we can embed this captions as a subtitle in the videos , video link example 

### Video link

https://www.youtube.com/watch?v=Lo5e7mWwQAU

### Additional context

thanks

**Comment by JunkFood02** [comment]
@djemaaismail Try v1.8.0-rc.2

**Comment by djemaaismail** [comment]
thanks , i trying, but no results, only an empty subtitles . 
can you give me an example ❓

**Comment by djemaaismail** [comment]
@djemaaismail i find downsub.com that make a double language subtitle in one file srt . 

if there is a possibility to use a template in seal app , can anyone tell me ❓

thanks

**Comment by JunkFood02** [comment]
Use VLC player to display the embedded subtitles with videos, make sure you toggle on auto-captions & embed subtitles in the settings
