### ISSUE TITLE
[Bug Report] Temporary files directory for custom command

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#526]
### Describe the bug

I clear temporary files, but they are still left in download directory `/storage/emulated/0/Download/Seal`:
`.mp4.part`, `.mp4.part-Frag6` and `.mp4.ytdl` files

### Additional context

App version: 1.8.0-rc.2 (10800)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by JunkFood02** [comment]
Clear temporary files won't work for custom commands, you'll need to delete them or specify a directory for temp files manually

**Comment by Botan626** [comment]
Maybe 'Clear temporary files' button should be unclickable, if 'Custom command' is on then.

> or specify a directory for temp files manually

How?

**Comment by JunkFood02** [comment]
`-P temp:/storage/emulated/0/Downloads/Seal/tmp`

**Comment by Botan626** [comment]
> `-P temp:/storage/emulated/0/Download/Seal/tmp`. You can change it to any valid directory (`Documents/` & `Download/`)

Thank you.

I didn't change any settings, except I turned 'Custom command' off, but 0 files were deleted with clear temp files button.
Is it ok?

**Comment by JunkFood02** [comment]
>0 files were deleted 

It means the temp directory used in general mode is empty.

> specify a directory for temp files manually

I'll add a GUI option for this in the next version

**Comment by Botan626** [comment]
> I'll add a GUI option for this in the next version

v1.9.0 will have it?
