### ISSUE TITLE
[Feature Request] Ability to download directly in Cloud storage like Google Drive

### ISSUE THREAD

**Issue by onlytanmoy** [JunkFood02/Seal#527]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

It will be great to have integration capability with GDrive, Dropbox, Mega, OneDrive etc. so that I can save the YouTube videos directly into these popular cloud storage instead of saving in my mobile local storage.

**Comment by JunkFood02** [comment]
Directories from Google Drive/OneDrive etc. are read-only and cannot be written by other apps
