### ISSUE TITLE
[Bug Report] extra notification

### ISSUE THREAD

**Issue by Monirzadeh** [JunkFood02/Seal#529]
### Describe the bug

Seal show 2 notification when you activate download progress notification.
1. `Seal is Downloading...` (show when get data about video and not start download yet)
2. download progress notification

When downloading, start first notification should be disappeared.
It should be just show download progress. Others make clutter notification space.

### To Reproduce

1. active download progress notification from settings
2. download a video
3. go home screen of phone
4. open notification

### Error reports & Screenshots

1 is unneeded when number 2 apear
![80365c8a-dec0-4857-b987-c37feb2703ec](https://user-images.githubusercontent.com/25131576/214155733-6f4789d9-626c-41dd-9bdf-7dd50e9c6993.png)

### Device info

App version: 1.7.3-(F-Droid) (10734)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

I am not familiar with android notification system, but is it possible to just have one of this notification?

**Comment by JunkFood02** [comment]
The notification ensures the app to be running in foreground and not killed by the Android OS when downloading
