### ISSUE TITLE
[Feature Request] Add support for change audio track

### ISSUE THREAD

**Issue by unilimitx** [JunkFood02/Seal#530]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Video link

https://youtu.be/NvCoK0MfjOo

**Comment by JunkFood02** [comment]
The format selection page already provides all available audio tracks
