### ISSUE TITLE
[Feature Request] 1080p Video(with audio) option

### ISSUE THREAD

**Issue by onlytanmoy** [JunkFood02/Seal#532]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

While downloading YouTube videos I only get option to download 720p video (with audio) even though the video is 4k/1080p. I do see 4k/1080p options under video (no audio) category though. Is it possible to have those resolutions available for video (with audio) section for download?

**Comment by Marco-9456** [comment]
> ### Is your feature request related to a problem? Please describe.
> While downloading YouTube videos I only get option to download 720p video (with audio) even though the video is 4k/1080p. I do see 4k/1080p options under video (no audio) category though. Is it possible to have those resolutions available for video (with audio) section for download?



https://user-images.githubusercontent.com/41828058/214685722-32a591ee-2176-4602-802d-3f7730839b62.mp4

Close the issue as completed if that solved your "problem".

**Comment by onlytanmoy** [comment]
@Marco-9456 many thanks 😊

**Comment by onlytanmoy** [comment]
@Marco-9456 Re-opening as got a related query, so under Video quality > Video resolution I am selecting 1080p as I specifically want to download 1080p and not 4k or anything but in Download screen it does not show me 1080p and only 4k under Suggested. Any way to fix that?

**Comment by berkakkaya** [comment]
Any updates on this issue? I've tried to download some YouTube videos lately and I have the same issue too.

**Comment by Marco-9456** [comment]
> Any updates on this issue? I've tried to download some YouTube videos lately and I have the same issue too.

Go to the Telegram channel and ask in the support chat, because I'm not getting what you guys having issues with

**Comment by soredake** [comment]
Youtube doesn't offer merged 1080p anymore IIUC https://gist.github.com/AgentOak/34d47c65b1d28829bb17c24c04a0096f
