### ISSUE TITLE
[Feature Request]An option to assign and use variables within the link window

### ISSUE THREAD

**Issue by KyleBroflowski** [JunkFood02/Seal#533]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

For trimming and  downloading youtube video I found the following command working 
`s=50 && yt-dlp https://youtu.be/a-NAdD09VKE --downloader ffmpeg --downloader-args "ffmpeg_i:-ss $s"` on a regular linux shell. 
Here yt-dlp is using a pre-defined custom configuration too.

### Describe the solution you'd like

But can such an option be made  available on android too?

**Comment by JunkFood02** [comment]
Executing shell script is not available because we don't have `sh` bundled in the app. 

Btw video trimming is a planned feature in v1.9.0, so please stay tuned for it

Tips: use `--download-sections` in yt-dlp

**Comment by Marco-9456** [comment]
> ### Describe the solution you'd like
> But can such an option be made available on android too?

Try this:
`ytsearch:s=50 --downloader ffmpeg --downloader-args "ffmpeg_i:-ss $s"`

**Comment by KyleBroflowski** [comment]
Thankyou for the tip.
