### ISSUE TITLE
[Feature Request] An option to specify timestamps of videos that downloads the trimmed video

### ISSUE THREAD

**Issue by KyleBroflowski** [JunkFood02/Seal#534]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [x] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

An option to download the video within a given time stamp. 
Youtube clips has a 60 second limitation otherwise those videos could have been directly downloaded. 
It should be made available as a checkbox to enable the timestamp input window, two windows for the time stamp start and end.
This should be common to custom commands and default configurations. 
The following command could work in background to achieve this 
`read $starttime ; yt-dlp <link> --downloader ffmpeg --downloader-args "ffmpeg_i:-ss $starttime" `

**Comment by seaque** [comment]
No need to use `--downloader ffmpeg`. Take a look at `--download-sections` from yt-dlp.

**Comment by JunkFood02** [comment]
Added in v1.9.0-beta.1

**Comment by muhammadsaadoon** [comment]
Can this feature be added for any mp4 link ?
❤️
