### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by sharufahmad** [JunkFood02/Seal#535]
### Describe the bug

I can't download any videos and audios.. 

### Error reports & Screenshots

![Screenshot_20230127_004113](https://user-images.githubusercontent.com/123669770/214927780-43db3395-b771-455d-8517-fdf092b25bf4.jpg)

### Device info

App version: 1.6.0 (10600)
Device information: Android 12 (API 31)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 1509 x 720

**Comment by Marco-9456** [comment]
Update to 
[v1.7.3](https://github.com/JunkFood02/Seal/releases/tag/v1.7.3) 
Or 
[v1.8.0-rc.2](https://github.com/JunkFood02/Seal/releases/tag/v1.8.0-rc.2)
