### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Rohit3522** [JunkFood02/Seal#536]
### Describe the bug

Unable to download song.

### Error reports & Screenshots

App version: 1.7.1-(F-Droid) (10714)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://music.youtube.com/watch?v=YALvuUpY_b0

ERROR: aria2c exited with code 19

### Device info

App version: 1.7.1-(F-Droid) (10714)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by HoriKyoukosimp** [comment]
@Rohit3522 Update to 1.7.3 or latest pre-release and see if it works
