### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by srao402** [JunkFood02/Seal#537]
### Describe the bug

When i paste the link from insta or use share option in insta for seal it says could not fetch video info

### To Reproduce

![Screenshot_20230127_152202_Seal](https://user-images.githubusercontent.com/123731256/215058569-e5ffae75-d927-40b7-a8b6-41615c6f278d.jpg)

### Error reports & Screenshots

![Screenshot_20230127_152202_Seal](https://user-images.githubusercontent.com/123731256/215058586-6717364b-20ac-4a0d-bf6a-4b5d25bf35b8.jpg)

**Comment by HoriKyoukosimp** [comment]
@srao402 Go to settings

Cookie

Add cookie

Login to instagram

And try again

**Comment by srao402** [comment]
I tried logging of insta and logging in again. Dint work

**Comment by HoriKyoukosimp** [comment]
@srao402 Give video link

**Comment by srao402** [comment]
Its not working for any video for me. 
https://www.instagram.com/reel/Cn4hHBQOL0N/?igshid=YmMyMTA2M2Y=

**Comment by HoriKyoukosimp** [comment]
@srao402 Try latest prerelease version

**Comment by HoriKyoukosimp** [comment]
@HoriKyoukosimp Also

Kindly sent logs please, i wanna know what error it shows

**Comment by srao402** [comment]
https://github.com/JunkFood02/Seal/releases/download/v1.3.5/Seal-1.3.5-arm64-v8a-release.apk

This one?

**Comment by HoriKyoukosimp** [comment]
@srao402 https://github.com/JunkFood02/Seal/releases/tag/v1.8.0-rc.2

**Comment by Marco-9456** [comment]
> ### Describe the bug
> When i paste the link from insta or use share option in insta for seal it says could not fetch video info

Downloading from instagram is always working from even with the link you provided, so it's probably geo restricted in your country

![Screenshot_20230127_110336_Seal](https://user-images.githubusercontent.com/41828058/215060260-24eaefc0-0b5c-491d-92cc-038d69ede64c.jpg)

**Comment by srao402** [comment]
I am in India. Is it restricted here?

**Comment by Marco-9456** [comment]
@srao402 Probably

**Comment by srao402** [comment]
Yeah it doesn't work on the pre release also

**Comment by hackifiedreborn** [comment]
@srao402 Try with 1.8.0-rc.2, It worked for me 😁

**Comment by srao402** [comment]
Are you from India?

**Comment by srao402** [comment]
> @srao402 Try with 1.8.0-rc.2, It worked for me 😁

Are you from india?

**Comment by hackifiedreborn** [comment]
@srao402 Yes 😁

**Comment by srao402** [comment]
> @srao402 Yes 😁

Can u send the link please

**Comment by hackifiedreborn** [comment]
@srao402 https://www.instagram.com/reel/Cn4hHBQOL0N/?igshid=YmMyMTA2M2Y=

**Comment by srao402** [comment]
> @srao402 https://www.instagram.com/reel/Cn4hHBQOL0N/?igshid=YmMyMTA2M2Y=

Link to download the pre realize that u told

**Comment by hackifiedreborn** [comment]
@srao402 Your video download link 
https://instagram.fvtz4-1.fna.fbcdn.net/v/t66.30100-16/10000000_1868828760123058_4745083267022175382_n.mp4?_nc_ht=instagram.fvtz4-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=8ofCjFJzoM0AX855ipX&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AfAEVIdjnzmhXqfPEoN7RzllcWPZdZuLH1m2LQe3mD586w&oe=63D5849E&_nc_sid=4f375e

Pre-releases it's available in seal GitHub under releases section.

**Comment by srao402** [comment]
> @srao402 Your video download link 
> https://instagram.fvtz4-1.fna.fbcdn.net/v/t66.30100-16/10000000_1868828760123058_4745083267022175382_n.mp4?_nc_ht=instagram.fvtz4-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=8ofCjFJzoM0AX855ipX&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AfAEVIdjnzmhXqfPEoN7RzllcWPZdZuLH1m2LQe3mD586w&oe=63D5849E&_nc_sid=4f375e
> 
> Pre-releases it's available in seal GitHub under releases section.

Same erroe. ![Screenshot_20230127_152202_Seal.jpg](https://user-images.githubusercontent.com/123731256/215063770-cd360d56-bfe9-485d-b95d-7ef25a0cf526.jpg)

**Comment by HoriKyoukosimp** [comment]
@srao402 Just

Open the link and hold finget into the video

U can download video that way
