### ISSUE TITLE
Seal doesn't work in Instagram.

### ISSUE THREAD

**Issue by Manowar79** [JunkFood02/Seal#541]
### Describe the bug

I copy the link and the app don't work. Can't download the video, Reel, document...

### Error reports & Screenshots

![Screenshot_20230128-170752](https://user-images.githubusercontent.com/123826518/215288737-afdcc1a2-e537-4bf5-9809-01e550c384de.png)

### Device info

App version: 1.8.0-rc.2 (10800)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
> ### Describe the bug
> I copy the link and the app won't work. Can't download the video, Reel, or document...

1. Try using the Cookies option (you need to figure out how to use it)
2. Seal is not a documents downloader
3. If Nr 1 didn't work try using VPN
4. If nothing from above mentioned solutions worked nothing else will make it work
> **Note**
Instagram and Facebook are geo-restricted by meta

**Comment by Marco-9456** [comment]
Also don't make false reports and close one of the 2 issues you created.
