### ISSUE TITLE
[Bug Report] fail to download videos

### ISSUE THREAD

**Issue by Myricae1** [JunkFood02/Seal#543]
### Describe the bug

When i tried to download a youtube video (first time i ever used the app)  it fails the download because it "fails to download video thumbnail", even when i toggle off the option to download the miniature.

### Error reports & Screenshots

App version: 1.7.3 (10730)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://youtu.be/AKGrmY8OSHM
WARNING: Unable to download video thumbnail 45: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 44: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 43: HTTP Error 404: Not Found
WARNING: Unable to download video thumbnail 42: HTTP Error 404: Not Found
ERROR: [Errno 1] Operation not permitted: '/storage/emulated/0/Video_audio youtube scaricati/#NSDR (Non-Sleep Deep Rest) with Dr. Andrew Huberman [AKGrmY8OSHM].opus'

### Device info

App version: 1.7.3 (10730)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

In the error it says it doesn't have the permission to storage i think, but i don't know how to resolve it! It's probably something stupid on my part, I hope to not wasting your time, and sorry if my English was wrong!

**Comment by Marco-9456** [comment]
> ### Describe the bug
> When i tried to download a youtube video (first time i ever used the app) it fails the download because it "fails to download video thumbnail", even when i toggle off the option to download the miniature.
> 
> ### To Reproduce
> _No response_
> 
> ### Error reports & Screenshots
> App version: 1.7.3 (10730) Device information: Android 12 (API 31) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.01.06
> 
> URL: https://youtu.be/AKGrmY8OSHM WARNING: Unable to download video thumbnail 45: HTTP Error 404: Not Found WARNING: Unable to download video thumbnail 44: HTTP Error 404: Not Found WARNING: Unable to download video thumbnail 43: HTTP Error 404: Not Found WARNING: Unable to download video thumbnail 42: HTTP Error 404: Not Found ERROR: [Errno 1] Operation not permitted: '/storage/emulated/0/Video_audio youtube scaricati/#NSDR (Non-Sleep Deep Rest) with Dr. Andrew Huberman [AKGrmY8OSHM].opus'
> 
> ### Device info
> App version: 1.7.3 (10730) Device information: Android 12 (API 31) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.01.06
> 
> ### Additional context
> In the error it says it doesn't have the permission to storage i think, but i don't know how to resolve it! It's probably something stupid on my part, I hope to not wasting your time, and sorry if my English was wrong!

Go to your phone settings and search for all files access and enable Seal

**Comment by Myricae1** [comment]
Thanks you brother! It works fine now

Il sab 28 gen 2023, 22:59 mohammed_9456 ***@***.***> ha
scritto:

**Comment by Myricae1** [comment]
Thanks for the fast response, i needed to enable a setting in the phone

**Comment by Marco-9456** [comment]
> 

👍
