### ISSUE TITLE
[Feature Request] Show Share menu for video streams instead of copying link

### ISSUE THREAD

**Issue by jonas99g** [JunkFood02/Seal#544]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Currently Seal is copying the stream link into clipboard
![Seal_Copy_Link](https://user-images.githubusercontent.com/51866807/215295759-0ac2269d-a226-4b6e-b647-8d58fc8a7954.png)

### Describe the solution you'd like

I like to have a share menu when long pressing on a video stream option.

Example:
DVD (https://github.com/yausername/dvd) is offering such a share menu which i really like for example to watch documentaries on demand with mpv video player.
![dvd_stream_selection_with_share](https://user-images.githubusercontent.com/51866807/215295791-a5abe24e-f553-4aef-9c91-089282b3dccb.png)
![dvd_share_menu_android_11](https://user-images.githubusercontent.com/51866807/215295793-6bc8a08e-3b8d-4d7d-971e-58ca95660b27.jpg)

**Comment by HoriKyoukosimp** [comment]
@jonas99g so for shorts...

u want seal to be able to share output link
