### ISSUE TITLE
[Bug Report] Creating a new line isn't possible

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#546]
### Describe the bug

So, after updating to `v1.8.0` I'm no longer able to create new lines when editing a custom command as you can see in the video record.

### To Reproduce

Upgrade to `v1.8.0` and try to create a new line in a template.

### Error reports & Screenshots

<details markdown='1'><summary>Using v1.8.0-rc.2:</summary>

https://user-images.githubusercontent.com/41828058/215357092-3c31b26f-1da3-4dd7-bd25-1e00966bf5c8.mp4

</details>

<details markdown='1'><summary>Using v1.8.0:</summary>

https://user-images.githubusercontent.com/41828058/215357116-d55254c4-a20f-420a-a33f-29f5fb52a0e2.mp4

</details>

### Device info

App version: 1.8.0 (10800)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by BobbyESP** [comment]
Found the bug. 

https://github.com/JunkFood02/Seal/blob/ecb95347c72739d023cdc582715ba3ca7c243d71/app/src/main/java/com/junkfood/seal/ui/page/settings/command/TemplateEditPage.kt#L146-L147

**Comment by Marco-9456** [comment]
> Found the bug.
> 
> https://github.com/JunkFood02/Seal/blob/ecb95347c72739d023cdc582715ba3ca7c243d71/app/src/main/java/com/junkfood/seal/ui/page/settings/command/TemplateEditPage.kt#L146-L147

Great 👍🏻

**Comment by BobbyESP** [comment]
But well, the real problem is this line:

https://github.com/JunkFood02/Seal/blob/ecb95347c72739d023cdc582715ba3ca7c243d71/app/src/main/java/com/junkfood/seal/ui/page/settings/command/TemplateEditPage.kt#L152

**Comment by Marco-9456** [comment]
> But well, the real problem is this line:
> 
> https://github.com/JunkFood02/Seal/blob/ecb95347c72739d023cdc582715ba3ca7c243d71/app/src/main/java/com/junkfood/seal/ui/page/settings/command/TemplateEditPage.kt#L152

Yeah, JunkFood made a lot of changes in this commit;
https://github.com/JunkFood02/Seal/commit/65a3b5cb3b5c96c94e4b8acf9289e10dae2c67c8

**Comment by BobbyESP** [comment]
They are all good and nice. That was just a oversight.

**Comment by Marco-9456** [comment]
> They are all good and nice. That was just a oversight.

Probably

**Comment by JunkFood02** [comment]
Intended, use blanks to split commands
