### ISSUE TITLE
[Bug Report] Downloading from telegram

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#547]
### Describe the bug

Yt-dlp is able to download from telegram according to their supported websites list, i tried to download several videos from it, some of them worked and others not

### To Reproduce

Try downloading from the link in the error report box

### Error reports & Screenshots

URL: https://t.me/c/1548735445/509
Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: 

### Device info

App version: 1.8.0 (10800)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

It works with this link
https://t.me/bruhcollective/314

**Comment by JunkFood02** [comment]
@Marco-9456 Cannot access to the message here, can you enable download playlist and try again?

**Comment by Marco-9456** [comment]
> @Marco-9456 can you enable download playlist and try again?

```
URL: https://t.me/c/1548735445/509
Expected start of the object '{', but had 'EOF' instead at path: $
JSON input: null

```

**Comment by JunkFood02** [comment]
@Marco-9456 It seems yt-dlp just return null for this URL because it's private content, use custom commands to see if it throws an error

**Comment by Marco-9456** [comment]
> @Marco-9456 It seems yt-dlp just return null for this URL because it's private content, use custom commands to see if it throws an error

👍🏻

**Comment by Marco-9456** [comment]
> @Marco-9456 It seems yt-dlp just return null for this URL because it's private content, use custom commands to see if it throws an error

It doesn't throw any error and says Download Completed, but nothing is downloaded
![Screenshot_20230130_121315_Seal](https://user-images.githubusercontent.com/41828058/215462025-8124de90-1959-4b41-ab51-dad2944a5aa1.jpg)

**Comment by JunkFood02** [comment]
@Marco-9456 Was the video actually downloaded? If so, use -J and post the log here, it could be a parsing error

**Comment by Marco-9456** [comment]
> 

No video is downloaded and the log gives `null`

**Comment by Marco-9456** [comment]
> @Marco-9456 Was the video actually downloaded? If so, use -J and post the log here, it could be a parsing error

But using `-vU` gives me this log;


```
[debug] Command-line config: ['-P', '/storage/emulated/0/Download/Seal/Video', '--downloader', 'libaria2c.so', '--external-downloader-args', 'aria2c:"--summary-interval=1"', '--config-locations', '/data/user/0/com.junkfood.seal/cache/config.txt', '--cookies', '/data/user/0/com.junkfood.seal/cache/cookies.txt', '--no-cache-dir', '--ffmpeg-location', '/data/app/~~XSDC-LMB-cq3Tj3LZrsaVg==/com.junkfood.seal-x2Mh2NlmNAcgVAEBJpSG8g==/lib/arm64/libffmpeg.so', 'https://t.me/c/1548735445/509']
[debug] | Config "/data/user/0/com.junkfood.seal/cache/config.txt": ['-vU']
[debug] Encodings: locale UTF-8, fs utf-8, pref UTF-8, out utf-8 (No ANSI), error utf-8 (No ANSI), screen utf-8 (No ANSI)
[debug] yt-dlp version 2022.11.11 [8b64402] (zip)
[debug] Python 3.8.0 (CPython aarch64 64bit) - Linux-5.4.147-25489110-abG996BXXS5DWA4-aarch64-with-libc (OpenSSL 1.1.1d  10 Sep 2019, libc)
[debug] exe versions: ffmpeg 5.1 (setts), ffprobe 5.1
[debug] Optional libraries: mutagen-1.46.0, sqlite3-2.6.0
[debug] Proxy map: {}
[debug] Loaded 1723 extractors
[debug] Fetching release info: https://api.github.com/repos/yt-dlp/yt-dlp/releases/latest
[debug] Downloading _update_spec from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.06/_update_spec
[debug] Downloading yt-dlp from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.06/yt-dlp
[debug] Downloading SHA2-256SUMS from https://github.com/yt-dlp/yt-dlp/releases/download/2023.01.06/SHA2-256SUMS
WARNING: Restart yt-dlp to use the updated version
Traceback (most recent call last):
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/__main__.py", line 17, in <module>
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 968, in main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/__init__.py", line 958, in _real_main
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3322, in download
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 3297, in wrapper
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 1474, in extract_info
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/YoutubeDL.py", line 784, in get_info_extractor
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 36, in __new__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/utils.py", line 5857, in __get__
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp/yt_dlp/extractor/lazy_extractors.py", line 32, in real_class
  File "/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/packages/python/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 548, in _get_data
zipimport.ZipImportError: bad local file header: '/data/user/0/com.junkfood.seal/no_backup/youtubedl-android/yt-dlp/yt-dlp'
```

**Comment by Marco-9456** [comment]
> @Marco-9456 Was the video actually downloaded? If so, use -J and post the log here, it could be a parsing error

On the video link a pasted in `additional context` using -J it downloads the video and gives me this log;

`{"id": "314", "webpage_url": "https://t.me/bruhcollective/314?single=True", "duration": 3.0, "thumbnail": "https://cdn4.telegram-cdn.org/file/kCxb7Ntz9IH8OlCLVNRWAOuCwGXVmX2CvuUB2z1FWkMBZmp_7rX49en3YtrvKMXruakiznKnr9X9mnA9rOWFMLemx1wso2MnXEry_RchjFPwnpeYmhzg9R8sqUKO6vEczgb1g1LM43GN-DpX6J7Nobe-LGDKvHYSeZM7AmqPxXgDfDGw-xozV-TGvj_tkRXF0X-EXK3s_cWBzbbY_5M4Q2R7aoEnSCjhH_WRQFkAg5oKc7HUgi_od2bPmrM6ZduvXky1ychoyS9LvZoT5b4nDlJNi6I_CpzS2U9WAPlJtRhlDaU4VtAWH5R9Y9u-WVr4HtS-jekhhzOXQ9GjMiqaNQ", "formats": [{"url": "https://cdn4.telegram-cdn.org/file/7317467c2d.mp4?token=tqMGhKs1jBvZ1BMtRFkBG9B41J1g0-KaUAYhSn8KESLPWHf8fPw5Tkj-3UKFHHHWYKahjo8q0pRtfElLt-8XPTDN4nt4ObIRDP8y-omOwjB3TA5HLjFmD0L_q6f3eAQTDskhXMN0HQfweyzN7p8ZMZlVw46p5Ycpi2zjTHcs5wJIVQv0T4L9sycs4Q6JhIqGKPhp_sRLWFHGacgDyh6JpWovJCR0hu97fP1-uNODzCYdVG-m7FuuIc_wubn3OsL4voMZPhsuP_v_ItFVS3qHIYZtAsQzX-RenAkEH6lwBep-iE6wllypufzS_v5Cr1m7Vq3egpLM8-91-uBCbvb75Q", "ext": "mp4", "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format_id": "0", "format": "0 - unknown", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}}], "title": "aaaaand more animations ;)", "description": "aaaaand more animations ;)", "channel": "bruhcollective.", "channel_id": "bruhcollective", "timestamp": 1674793389, "original_url": "https://t.me/bruhcollective/314", "webpage_url_basename": "314", "webpage_url_domain": "t.me", "extractor": "telegram:embed", "extractor_key": "TelegramEmbed", "playlist": null, "playlist_index": null, "thumbnails": [{"url": "https://cdn4.telegram-cdn.org/file/kCxb7Ntz9IH8OlCLVNRWAOuCwGXVmX2CvuUB2z1FWkMBZmp_7rX49en3YtrvKMXruakiznKnr9X9mnA9rOWFMLemx1wso2MnXEry_RchjFPwnpeYmhzg9R8sqUKO6vEczgb1g1LM43GN-DpX6J7Nobe-LGDKvHYSeZM7AmqPxXgDfDGw-xozV-TGvj_tkRXF0X-EXK3s_cWBzbbY_5M4Q2R7aoEnSCjhH_WRQFkAg5oKc7HUgi_od2bPmrM6ZduvXky1ychoyS9LvZoT5b4nDlJNi6I_CpzS2U9WAPlJtRhlDaU4VtAWH5R9Y9u-WVr4HtS-jekhhzOXQ9GjMiqaNQ", "id": "0"}], "display_id": "314", "fulltitle": "aaaaand more animations ;)", "duration_string": "3", "upload_date": "20230127", "requested_subtitles": null, "_has_drm": null, "requested_downloads": [{"url": "https://cdn4.telegram-cdn.org/file/7317467c2d.mp4?token=tqMGhKs1jBvZ1BMtRFkBG9B41J1g0-KaUAYhSn8KESLPWHf8fPw5Tkj-3UKFHHHWYKahjo8q0pRtfElLt-8XPTDN4nt4ObIRDP8y-omOwjB3TA5HLjFmD0L_q6f3eAQTDskhXMN0HQfweyzN7p8ZMZlVw46p5Ycpi2zjTHcs5wJIVQv0T4L9sycs4Q6JhIqGKPhp_sRLWFHGacgDyh6JpWovJCR0hu97fP1-uNODzCYdVG-m7FuuIc_wubn3OsL4voMZPhsuP_v_ItFVS3qHIYZtAsQzX-RenAkEH6lwBep-iE6wllypufzS_v5Cr1m7Vq3egpLM8-91-uBCbvb75Q", "ext": "mp4", "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format_id": "0", "format": "0 - unknown", "dynamic_range": "SDR", "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}, "epoch": 1675078118, "_filename": "/storage/emulated/0/Download/Seal/Video/aaaaand more animations ;) [314].mp4", "__write_download_archive": false}], "url": "https://cdn4.telegram-cdn.org/file/7317467c2d.mp4?token=tqMGhKs1jBvZ1BMtRFkBG9B41J1g0-KaUAYhSn8KESLPWHf8fPw5Tkj-3UKFHHHWYKahjo8q0pRtfElLt-8XPTDN4nt4ObIRDP8y-omOwjB3TA5HLjFmD0L_q6f3eAQTDskhXMN0HQfweyzN7p8ZMZlVw46p5Ycpi2zjTHcs5wJIVQv0T4L9sycs4Q6JhIqGKPhp_sRLWFHGacgDyh6JpWovJCR0hu97fP1-uNODzCYdVG-m7FuuIc_wubn3OsL4voMZPhsuP_v_ItFVS3qHIYZtAsQzX-RenAkEH6lwBep-iE6wllypufzS_v5Cr1m7Vq3egpLM8-91-uBCbvb75Q", "ext": "mp4", "protocol": "https", "video_ext": "mp4", "audio_ext": "none", "format_id": "0", "format": "0 - unknown", "resolution": null, "dynamic_range": "SDR", "aspect_ratio": null, "http_headers": {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36", "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "Accept-Language": "en-us,en;q=0.5", "Sec-Fetch-Mode": "navigate"}, "epoch": 1675078118, "_type": "video", "_version": {"version": "2023.01.06", "current_git_head": null, "release_git_head": "6becd25", "repository": "yt-dlp/yt-dlp"}}
`

**Comment by JunkFood02** [comment]
Reproduced on PC with warning message below:
```
[telegram:embed] Extracting URL: https://t.me/c/1548735445/509
[telegram:embed] 1548735445: Downloading embed frame
WARNING: [telegram:embed] unable to extract timestamp; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: Extractor telegram:embed returned nothing; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
```

**Comment by Marco-9456** [comment]
> Reproduced on PC with warning message below:
> 
> ```
> [telegram:embed] Extracting URL: https://t.me/c/1548735445/509
> [telegram:embed] 1548735445: Downloading embed frame
> WARNING: [telegram:embed] unable to extract timestamp; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> WARNING: Extractor telegram:embed returned nothing; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
> ```

So it's on yt-dlp side ?

**Comment by MicroBeast** [comment]
Does yt-dlp support Telegram Private Group/Channel/Chat though?

https://github.com/yt-dlp/yt-dlp/issues/2910

That talk seem indicate it didn't.

Sorry, to chime in. This conversation quiet long on TG ch.
