### ISSUE TITLE
[Feature Request] Desktop Support

### ISSUE THREAD

**Issue by AstragoDE** [JunkFood02/Seal#549]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There is not really a problem. The app is great, and support for desktop (especially Windows 10+) would be awesome. 

### Describe the solution you'd like

Since the app is made in Kotlin, it might be possible to use a Desktop Wrapper for the app. There is a project that might be using this suggested approach, which is called [SpotiFlyer](https://github.com/Shabinder/SpotiFlyer).

**Comment by BobbyESP** [comment]
@AstragoDE Seal isn't built with Jetpack Compose Multiplatform or Kotlin Multiplatform, so a rewrite is needed for that. By the way you can use Windows Subsystem for Android (but there's a problem with that; extract the files downloaded from the subsystem to your PC into an accessible route like C:\Downloads will be harder)

**Comment by AstragoDE** [comment]
Thank you very much for letting me know. Keep on the good work :)
