### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by nucleaop** [JunkFood02/Seal#551]
### Describe the bug

Can't download to my SD card after turning on the "SD card folder" as a download directory.

### Error reports & Screenshots

![Screenshot_2023-01-31-17-52-17-439_com junkfood seal](https://user-images.githubusercontent.com/124062097/215784011-2eae205b-22d8-425a-a982-442c22375358.jpg)

### Device info

App version: 1.8.0 (10800)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
> ### Describe the bug
> Can't download to my SD card after turning on the "SD card folder" as a download directory.


Click on `SD card folder` text and choose the SD card path.
Seal can't detect it automatically.
