### ISSUE TITLE
Sharing videos after downloading to many apps

### ISSUE THREAD

**Issue by l3y0nha** [JunkFood02/Seal#552]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

No

**Comment by HoriKyoukosimp** [comment]
@l3y0nha Arent the video saved to your gallery?

Just share them that way

**Comment by l3y0nha** [comment]
> 

 I know but it's much faster to do it in the app it self

**Comment by Qaz-7** [comment]
Sharing videos may lead to project closure. Video should be used for personal purposes.🤔

**Comment by JunkFood02** [comment]
Added in v1.9.0-beta.1
