### ISSUE TITLE
[Bug Report] Error when cropping a picture to embed a thumbnail

### ISSUE THREAD

**Issue by servokot** [JunkFood02/Seal#556]
### Describe the bug

Error when cropping a picture to embed a thumbnail in case if the **width** is **less** than the **height** - for example, when downloading a **vertical video** from Instagram.

As I understand it, this error is due to the use in the code for cropping only the height value in place to specify the width.

`"Seal-main\app\src\main\java\com\junkfood\seal\util\DownloadUtil.kt"`

```
     private const val CROP_ARTWORK_COMMAND =
         """--ppa "ffmpeg: -c:v mjpeg -vf crop=in_h""""
```

This method is quite suitabl - for example, for YouTube with 16:9 video (for example), where aspect ratio = 1.78, i.e. **in_w  >  in_h**

But, in the case for Instagram, the video is usually 9:16, aspect ratio = 0.56, i.e. **in_w  <  in_h**

And so the cropping error occurs

Why not use automatic determination of the best (smallest) value from the values width and height in this place of code

For example
```
     private const val CROP_ARTWORK_COMMAND =
         """ --ppa "ffmpeg:-c:v mjpeg -vf crop="'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)' """""
```

At least this crop method nice works in the custom Seal command, and yt-dlp of course.

### Device info

v1.7.3;
v1.8.0;
v1.8.1;

**Comment by JunkFood02** [comment]
Seal used this command before but I [changed it](https://github.com/JunkFood02/Seal/commit/9eae613739ce3d25452ed02aa230e3a1d1ad271f) for testing and forgot to revert. Thx for the issue

**Comment by servokot** [comment]
> Thx for the issue

Thanks for the quick reply, and cool app!
