### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by andylee516** [JunkFood02/Seal#558]
### Describe the bug

in changelog it said that add embedded chapters are on default. However, it doesnt provided this feature. Do i need to use custom commands? (if so can you share the commands please) and if when we use custom commands the default one cant use?

**Comment by JunkFood02** [comment]
1. Download a video with chapters info, like [this](https://youtu.be/Z6iFhczA3NY)
2. Use a video player that supports chapters, like VLC player
