### ISSUE TITLE
[Bug Report] Seal doesn't open properly with 'Share link' button

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#559]
### Describe the bug

I browser youtube page, long press on a video link, click on Seal icon next to 'Share link' button, this is the result:

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/216124865-b45a69fa-07c7-4126-9550-0c74de745c41.png)

</details>

Clicking on Seal window on this screenshot has no effect.

### Device info

App version: 1.8.1 (10810)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Botan626** [comment]
Same issue in v1.8.2.

**Comment by Marco-9456** [comment]
> Same issue in v1.8.2.

Could you share a Screen record?

**Comment by Botan626** [comment]
https://disk.yandex.ru/i/kBMzSvyN8GYiTQ

Message on 00:23: Seal is closed due to error.

**Comment by Marco-9456** [comment]
> https://disk.yandex.ru/i/kBMzSvyN8GYiTQ?ncrnd=1067
> 
> Message on 00:23: Seal is closed due to error.

Hmmmm, it's working fine on my side,
Did you try a clean install?
If not, please do so.

**Comment by Botan626** [comment]
> Did you try a clean install?

Not yet, I don't want to lose all my preferences.
There were some changes made on this matter in v1.9.0-beta.1?

**Comment by Marco-9456** [comment]
> 

No, but a clean install might help

**Comment by Botan626** [comment]
Clean install didn't help.

**Comment by Marco-9456** [comment]
> Download folder deletion and clean install (with configuring as before) didn't help.

Could you please wait 10 minutes we are trying somthing

**Comment by Botan626** [comment]
> > Download folder deletion and clean install (with configuring as before) didn't help.
> 
> Could you please wait 10 minutes we are trying somthing

Sure I can.

**Comment by Marco-9456** [comment]
> Download folder deletion and clean install (with configuring as before) didn't help.

Can you please try this [Build](https://github.com/Marco-9456/Seal/actions/runs/4151346371) 

>**Warning**
It's Signed with a different key so you need to uninstall previous version

**Comment by JunkFood02** [comment]
https://github.com/JunkFood02/Seal/actions/runs/4151366918 try this build

**Comment by Botan626** [comment]
> https://github.com/JunkFood02/Seal/actions/runs/4151366918 try this build and grant Seal "Display over other apps" permission in "System Settings - Special app access"

No success.

**Comment by Botan626** [comment]
I found the moment when it fails to start.

1. [v1.9.0-beta.1](https://github.com/JunkFood02/Seal/releases/tag/v1.9.0-beta.1) is installed,
2. Use custom command is on,
3. Template named '1080p' `(--no-mtime -f "bv*[height=1080]+ba/b / bv*+ba/b")` is added and selected,
4. Condigure before download is off,
5. Seal won't open via Share link.

**Comment by JunkFood02** [comment]
> "Configure before download" is off

This will not open any windows when using quick download

**Comment by Botan626** [comment]
> This will not open any windows when using quick download

What windows? If I turn Use custom command off, Seal starts successfully and shows me Format selection screen in some time.

**Comment by Botan626** [comment]
Not fixed in v1.9.0-beta.2.

**Comment by Botan626** [comment]
Not fixed in v1.9.0-rc.1. Is it going to be fixed in v1.9.0?

**Comment by fillwithjoy1** [comment]
Still an issue?

**Comment by Botan626** [comment]
> Still an issue?

no

**Comment by Marco-9456** [comment]
Great, please close the issue.

**Comment by Drook35** [comment]
I have the same problem. doesn't shows up in share menu
