### ISSUE TITLE
immediately accept the "format selection"

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#560]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

this dialog box takes a long time to open and is not necessary (I do not change the value)
make it possible to hide it

**Comment by JunkFood02** [comment]
Find it in your settings
