### ISSUE TITLE
[Bug Report] Some special characters in the video title cannot be recognized correctly

### ISSUE THREAD

**Issue by HumanMusicX** [JunkFood02/Seal#561]
### Describe the bug

Special characters in the video title cannot be recognized correctly after downloaded. It may be written in some languages, but video file was misnamed with unknown characters.

### To Reproduce

1. Copy video link.
2. Paste video link.
3. Download video.
4. Find video file in system File Manager.

### Error reports & Screenshots

![Screenshot_20230202_171634](https://user-images.githubusercontent.com/46023154/216282332-6c71337e-0312-44ea-8f69-d75e621857fe.jpg)
![Screenshot_20230202_171534_com junkfood seal](https://user-images.githubusercontent.com/46023154/216282402-8741b739-fde9-4586-90aa-e69e01ddd87c.jpg)

### Device info

App version: 1.8.1 (10810)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

Cyberpunk: Edgerunners - I Really Want To Stay At Your House - 80s Cover (feat. Mîna)

**Comment by JunkFood02** [comment]
Android OS has a limit for the length of filenames so the filename will be trimmed when too long. `[xxx]` is the id of the video
