### ISSUE TITLE
[Bug Report] Cannot dismiss all notifications at once

### ISSUE THREAD

**Issue by Mrnofish** [JunkFood02/Seal#562]
### Describe the bug

When multiple notifications for completed download are present, flicking the Seal notification block fully to the side for dismissing all the notifications at once, does not work, unlike for most other apps.

Instead, the Settings/Mute side pane appears.

The only workaround I've found is dismissing each notification individually.

### To Reproduce

1. Download multiple videos
2. Wait for the downloads to complete
3. Place your fingertip on the notification block title where it says Seal and fling to one side

### Device info

App version: 1.7.3-(F-Droid) (10734)
Device Information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by HoriKyoukosimp** [comment]
@Mrnofish Update to latest version and try again

If the bug still presist, just wait for devs to reply :)

**Comment by JunkFood02** [comment]
duplicate of #214

**Comment by Mrnofish** [comment]
1.8.1 has finally made its way to F-Droid, nevertheless I'm still experiencing the same issue ?
