### ISSUE TITLE
[Feature Request] Audio format preference for downloads

### ISSUE THREAD

**Issue by ksi** [JunkFood02/Seal#564]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I prefer to download m4a sound format but it every time suggests the default and it takes time to convert. So I have to click every time on preferred. Also quick download cannot select format at all and uses default so `quick` is much slower then general download.   

### Describe the solution you'd like

Remember the last selected format and select it by default on general download. Also use it on quick download.

**Comment by Marco-9456** [comment]
> ### Is your feature request related to a problem? Please describe.
> I prefer to download m4a sound format but it every time suggests the default and it takes time to convert. So I have to click every time on preferred. Also quick download cannot select format at all and uses default so `quick` is much slower then general download.


Go to `settings-->` `fromat-->` `enable save as audio-->` `click on Convert audio format-->` `and choose m4a;`
This will make the app always download audio in m4a.

**Comment by ksi** [comment]
Thats what I do. And it takes a lot of time in [Extracting audio] stage. Literally download in 3 seconds and extract for minute more

**Comment by Marco-9456** [comment]
> Thats what I do. And it takes a lot of time in [Extracting audio] stage. Literally download in 3 seconds and extract for minute more


https://user-images.githubusercontent.com/41828058/216618490-ee0664e6-0e00-45c3-8dbc-b47cfea42294.mp4

**Comment by ksi** [comment]
Exactly what I am talking about. Now try enable format selection and select Audit only m4a. You should see the difference

**Comment by ksi** [comment]
You have 3 minutes video and 8 seconds extraction. A have couple hours video :(

**Comment by Marco-9456** [comment]
> You have 3 minutes video and 8 seconds extraction. A have couple hours video :(

Then of course it will take time

**Comment by JunkFood02** [comment]
The feature you're actually requesting is audio format preference

**Comment by ksi** [comment]
Yes, I can select audio format. And if I select m4a it will spend a lot of time to encode opus to m4a. But YouTube itself allows to download m4a without any encodings (see screencasts several messages above). But I have to select it manually every time and cannot select it on Quick download at all.

**Comment by JunkFood02** [comment]
Added in v1.9.0-beta.1

**Comment by ksi** [comment]
I can see it is closed but still cannot understand what was done as the result. The behavior if the same. Nothing is saved between downloads

**Comment by JunkFood02** [comment]
> I can see it is closed but still cannot understand what was done as the result. The behavior if the same. Nothing is saved between downloads

could you provide the link you're trying to download from?

**Comment by ksi** [comment]
> > I can see it is closed but still cannot understand what was done as the result. The behavior if the same. Nothing is saved between downloads
> 
> could you provide the link you're trying to download from?

Actually any. For example https://youtu.be/jJsV5bVxsc4 But after update to release versions I get an error for it: 
![Screenshot_2023-03-12-15-54-44-21_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/139096/224542978-69dfce7f-6a4d-4431-a5b6-b135a7e07dbf.jpg)

And the settings were: 
![Screenshot_2023-03-12-15-56-42-54_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/139096/224543014-cca75aba-6599-4ae2-9f8a-68cdf6017e7d.jpg)

**Comment by JunkFood02** [comment]
Reproduced. Please copy the error report and file a bug report with it, I'll look into it later. Before the issue get resolved, download the opus format instead. I personally don't think there're much difference between these two formats

**Comment by ksi** [comment]
Will do... If I will be able reproduce. Because I just deleted the app and
reinstalled it and the link above is being downloaded correctly.

For me the main difference is in chapters. Afaiu opus does not support this
feature?

And still how the change from this ticket should change the behavior?
