### ISSUE TITLE
I need to add an option to download Instagram stories, Facebook stories, and even Snapchat [Feature Request]

### ISSUE THREAD

**Issue by Diga1jj** [JunkFood02/Seal#568]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by Marco-9456** [comment]
@Diga1jj

**Comment by HoriKyoukosimp** [comment]
@Diga1jj ?

**Comment by Marco-9456** [comment]
Instagram and Facebook are supported but they don't work in some countries, Snapchat is not supported make a request on yt-dlp repo regarding this.
And fill your issues properly next time.
