### ISSUE TITLE
[Feature Request] Cut the middle part of the video

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#569]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I know that the function of cutting video and audio will be added. I think there should be support for cutting the middle part of the video.

### Describe the solution you'd like

Function to cut the middle part of the video.

### Video link

https://user-images.githubusercontent.com/124310688/216776219-b54bf61e-4a6e-473a-acab-c9fc588c7476.mp4

### Additional context

In the version to be released, the middle part of the video will not be cut

**Comment by Qaz-7** [comment]
Watch the video. Thanks to the Cut function, you can cut out the middle part of the video

**Comment by JunkFood02** [comment]
Not implemented in yt-dlp
