### ISSUE TITLE
[Feature Request] The application uses a lot of memory

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#570]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The application uses a lot of memory.The total size of the application is 147 MB

Data size 69.21 MB
Application size 77.30 MB

### Describe the solution you'd like

Login as soon as you download the app and the data size is already 69 MB.This is not normal

### Video link

https://user-images.githubusercontent.com/124310688/216789020-4272c49b-b85e-4d51-9f96-e98b4f86107f.mp4

1. App size
2. Data size

### Additional context

It would be good if the application size could be reduced to around 20 MB. (Data not included)

**Comment by Qaz-7** [comment]
Why does the app collect so much data?

**Comment by JunkFood02** [comment]
FFmpeg & Python are bundled to run yt-dlp
