### ISSUE TITLE
[Feature Request] Download limit

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#571]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Option to limit the maximum number of downloads on mobile internet and Wi-Fi.

### Describe the solution you'd like

We can download multiple videos at once or limit it

### Video link

All

**Comment by KranzAklilu** [comment]
Anyone working on the? Really good feature to have imo
