### ISSUE TITLE
[Feature Request] Rename the file during download.

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#572]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Ability to change file name during download.

### Describe the solution you'd like

Add option to rename file during download.

### Video link

All

**Comment by JunkFood02** [comment]
Duplicate of #234
