### ISSUE TITLE
[Bug Report]Download does not continue when Wi-Fi is disconnected

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#574]
### Describe the bug

The download does not continue when the Wi-Fi connection is lost.

### To Reproduce

1.Download the video
2.There is no button to pause the video
3.The download does not continue after the Wi-Fi connection is lost.

### Error reports & Screenshots

No

### Device info

App version: 1.8.1 (10810)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

These are important processes.

**Comment by Marco-9456** [comment]
Hit the download button again, this will make it continue from where it stopped.

**Comment by Qaz-7** [comment]
> Hit the download button again, this will make it continue from where it stopped.

This is not the main solution to the problem.

**Comment by Marco-9456** [comment]
> > Hit the download button again, this will make it continue from where it stopped.
> 
> This is not the main solution to the problem.

I know but we can't pause a download in yt-dlp

**Comment by Qaz-7** [comment]
I think it can be made accessible.

**Comment by Marco-9456** [comment]
> I think it can be made accessible.

How ?

**Comment by Qaz-7** [comment]
By implementing an Action to pause and resume the download within the application. This does not require yt-dlp support.

**Comment by Marco-9456** [comment]
> By implementing an Action to pause and resume the download within the application. This does not require yt-dlp support.Also, the ability to download 10 videos at the same time.

Who told that it doesn't require yt-dlp support, Seal will never implement a feature that yt-dlp doesn't support. Read the contributing guidelines before creating an issue.

**Comment by Qaz-7** [comment]
> > By implementing an Action to pause and resume the download within the application. This does not require yt-dlp support.Also, the ability to download 10 videos at the same time.
> 
> Who told that it doesn't require yt-dlp support, Seal will never implement a feature that yt-dlp doesn't support. Read the contributing guidelines before creating an issue.

Whether or not you will add it is another matter. However, yt-dlp is not required.

**Comment by JunkFood02** [comment]
Since you're so confident that you know how this app works, you can fork this project and implement this feature by yourself. This is not that difficult! 😉
