### ISSUE TITLE
Can't download Reels video 

### ISSUE THREAD

**Issue by CalCodeMXLX** [JunkFood02/Seal#575]
### Describe the bug

As the Title stands I can't download Reels video in the App. Seal please fix it. 🙏

### To Reproduce

1. I pasted a link to the vid on Reels 
2. I configured the vid on 1080p and mp4 
3. I used the latest yt-dlp Version
4. I tried to download it and I became an Error

### Error reports & Screenshots

![Screenshot_20230205_145653_Seal](https://user-images.githubusercontent.com/87543371/216823982-1a8fb5d1-5ca2-4a76-a7d3-29f00ad642b8.jpg)

### Device info

App version: 1.8.0-(F-Droid) (10804)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by EmmanuelDav** [comment]
Instagram needs you to be logged in before you are allowed to access or download any of their videos
