### ISSUE TITLE
[Feature Request] Resizeable log text

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#576]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When using a command like --list-formats the logs are sometimes very hard to read.

### Describe the solution you'd like

It would be great if we were able to resize the log text by zooming in and out just like in termux.

### Video link

<details markdown='1'><summary>How it looks like</summary>

![Screenshot_20230205_204554_Seal](https://user-images.githubusercontent.com/41828058/216841508-eb6ae9ec-1e2c-4684-bb2b-1ed7f747ffff.jpg)

</details>

### Additional context

Should be easy to 👉🏼👈🏼

**Comment by JunkFood02** [comment]
@Marco-9456 Gestures in Compose are still experimental, maybe a horizontal scrolling here is fine?

**Comment by Marco-9456** [comment]
> @Marco-9456 Gestures in Compose are still experimental, maybe a horizontal scrolling here is fine?

Yes, this should do the job for now.
