### ISSUE TITLE
[Bug Report] The same video cannot be downloaded in different formats.

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#578]
### Describe the bug

Download any video in 1080p quality.Video cannot be downloaded in 720p quality.

### To Reproduce

1.Download video in 1080p
2.When finished, download in 720p quality.
3.Unable to download.

### Error reports & Screenshots

https://user-images.githubusercontent.com/124310688/216851903-42a3bed5-11ec-4bbf-9111-b41bfd864cb6.mp4

### Device info

App version: 1.8.1 (10810)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

### Additional context

It shows as if it is downloading the video, but it is not.

**Comment by JunkFood02** [comment]
yt-dlp only judges whether a video has been downloaded by the file name

**Comment by nio04** [comment]
i think, another work around could be by using custom command... just make 2 different custom command for downloading videos & as for file name changing, add "720p" for 720p video & same for 1020p video too
