### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by MonkeyDLuffy-Gang** [JunkFood02/Seal#581]
### Describe the bug

There is this serious bug/issue that I've been experiencing since the last updates from 1.7.5 to 1.8.1 for some reason every time I download a video that is age-restricted by YouTube e.g. smoking videos, the download speed will always be under 100 kbps. I have checked with my isp and such but the problem is not with them but you. If I try to download a video that isn't age-restricted immediately after I've canceled the video that is downloading slow, the non age restricted video will download fast at normal speeds like 3 mbps. Tell me what's going on? Please fix this.

### Error reports & Screenshots

[]() 
![VideoCapture_20230206-131602](https://user-images.githubusercontent.com/115345276/216958998-f6ab72b9-6e5d-4d19-8e9e-eaaba7ccb0a0.jpg)
![VideoCapture_20230206-131630](https://user-images.githubusercontent.com/115345276/216959010-ec4805fc-3409-4d2f-914a-35b4c1ad38af.jpg)

### Device info

App version: 1.8.1 (10810)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
> ### Describe the bug
> There is this serious bug/issue that I've been experiencing since the last updates from 1.7.5 to 1.8.1 for some reason every time I download a video that is age-restricted by YouTube e.g. smoking videos, the download speed will always be under 100 kbps. I have checked with my isp and such but the problem is not with them but you. If I try to download a video that isn't age-restricted immediately after I've canceled the video that is downloading slow, the non age restricted video will download fast at normal speeds like 3 mbps. Tell me what's going on? Please fix this.
> 
> ### To Reproduce
> _No response_
> 
> ### Error reports & Screenshots
> ![VideoCapture_20230206-131602](https://user-images.githubusercontent.com/115345276/216958998-f6ab72b9-6e5d-4d19-8e9e-eaaba7ccb0a0.jpg) ![VideoCapture_20230206-131630](https://user-images.githubusercontent.com/115345276/216959010-ec4805fc-3409-4d2f-914a-35b4c1ad38af.jpg)
> 
> ### Device info
> App version: 1.8.1 (10810) Device information: Android 13 (API 33) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.01.06
> 
> ### Additional context
> _No response_

Share link
