### ISSUE TITLE
[Feature Request] format selection window should be opened when video quality button is pressed instead of at the last.

### ISSUE THREAD

**Issue by soymadip** [JunkFood02/Seal#582]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Well, it's not related to a problem, but it will make the download process more time efficient.

### Describe the solution you'd like

Now if we press the 'video quality' button, it opens a window with resolution selection and file size. 
![Screenshot_2023-02-06-22-40-02-77_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/84225810/217040595-d643850a-bc5c-41ca-88b7-16d9ccb3b3ae.jpg)

The format selection window open at the last of the process. 
- Now if the format selection window opens when 'video quality' button is pressed then we can directly select video quality and format. 
- it will make the process more efficient and easier for users (specially new ones). 
- I have edited a video with my suggestion:- 

https://user-images.githubusercontent.com/84225810/217047119-225d83a7-8c38-4232-bdb5-9829d1b89d66.mp4

### Video link

https://youtu.be/C-AnrKt4UKU

### Additional context

If it loads video formats at first, it will be a huge timesaver and easier.

**Comment by JunkFood02** [comment]
Format preferences here are used to sort the formats, if you turn off format selection, Seal will always download the suggested format in that page for you.

**Comment by soymadip** [comment]
> Format preferences here are used to sort the formats, if you turn off format selection, Seal will always download the suggested format in that page for you.

Yeah, but as of now the custom format selection window comes at the end, after pressing the download button, we have to wait a few seconds and then it opens. 
If app opens the format selection window at first, like i showed in video, it will be more practical 😅

- And when format selection is off, it will download the pre selected suggested format. 
- please watch the video completely, it will clear things up .

**Comment by JunkFood02** [comment]
The info in format selection needs to be extracted from the URL and it takes time, there's no way to get rid of this. You'll still need to wait for the info gets fetched after any operations

**Comment by JunkFood02** [comment]
The info in format selection needs to be extracted from the URL and it takes time, there's no way to get rid of this. You'll still need to wait for the info gets fetched after any operations

**Comment by soymadip** [comment]
> The info in format selection needs to be extracted from the URL and it takes time, there's no way to get rid of this. You'll still need to wait for the info gets fetched after any operations

Yeah, we have to wait. 
But if app starts loading them at first, while the configaration window opens, at the time when we will be opening the format selection window, it will be loaded. 
- and one other benifit is that we can then select format from quick download window too.

**Comment by soymadip** [comment]
And it's more practical too to load at first.

**Comment by soymadip** [comment]
Here's a clip I recorded with PowerTube (now mostly outdated) :- 

https://user-images.githubusercontent.com/84225810/217055655-13a9873d-d79e-44a8-8d2a-8b94c9ca4071.mp4

**Comment by JunkFood02** [comment]
> select format from quick download window too.

That's not how things works, these two are completely different part of the UI.

Fetching info for format selection is a heavy operations needs long wait, and it's not a good practice to force users to wait by default.

**Comment by soymadip** [comment]
😅 quick download is may be another part. 
But we have to wait untill it opens format selection window right? 
Like in powertube if we can select the format at first, it feels more natural.

Well i guess it depends on you what you think😅
 I can say one thing, who has used other downloaders like powertube and Snaptube, they will definitely feel more natural. And as for time, it still takes it when it loads at last.

**Comment by soymadip** [comment]
I suggest that you should implement it in pre-release, if it feels awkward, then you can roll it back

**Comment by JunkFood02** [comment]
>  they will definitely feel more natural

Good to hear, just keep using them 👍

> I suggest that you should implement it in pre-release

PRs are welcome 👍

**Comment by Realme9i** [comment]
> > select format from quick download window too.
> 
> That's not how things works, these two are completely different part of the UI.
> 
> Fetching info for format selection is a heavy operations needs long wait, and it's not a good practice to force users to wait by default.

😅 It will be better in his suggested way I guess.

**Comment by soymadip** [comment]
> > they will definitely feel more natural
> 
> Good to hear, just keep using them 👍
Well i was saying about users, not apps😅

**Comment by JunkFood02** [comment]
You can use [YTDLnis](https://github.com/deniscerri/ytdlnis)

**Comment by soymadip** [comment]
> You can use [YTDLnis](https://github.com/deniscerri/ytdlnis)

That's what I am using now🙂
I feel more comfortable in layouts like powertube.
