### ISSUE TITLE
[Bug Report] can't pause a video downloading which is already started.

### ISSUE THREAD

**Issue by luffy07a** [JunkFood02/Seal#583]
### To Reproduce

1. Start any download
2. Now try to pause it, there is no pause button.

### Device info

App version: 1.8.1 (10810)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by MonkeyDLuffy-Gang** [comment]
It's not a bug. They don't want to add this feature for some odd reason.

**Comment by Marco-9456** [comment]
> It's not a bug. They don't want to add this feature for some odd reason.

Bruh, it's not our fault that users don't know how yt-dlp works.
Yt-dlp just doesn't have the ability to pause downloads and seal is based on it, that's why JunkFood02 can't make a GUI for a feature that doesn't exist in yt-dlp. 

So, take it or leave it.
