### ISSUE TITLE
[Bug Report] Error when opening Seal v1.9.0-beta.1

### ISSUE THREAD

**Issue by Botan626** [JunkFood02/Seal#590]
### Describe the bug

Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies' with flags 0x1: Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist

### Device info

App version: 1.9.0-beta.1 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
> ### Describe the bug
> Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies' with flags 0x1: Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist
> 
> ### Device info
> App version: 1.9.0-beta.1 (10820) Device information: Android 13 (API 33) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.01.06

That's a known issue.

**Comment by JunkFood02** [comment]
try "remove all cookies" and see if the error disappear

**Comment by Botan626** [comment]
> That's a known issue.

Firtst time I saw.

> try "remove all cookies" and see if the error disappear

That helped.

**Comment by rjm831** [comment]
It's simply a toast that pops up briefly when the app is first started.  Doesn't affect anything - the new beta works fine.  Just thought it was something I should mention.  Thanks for responding, and blessings for developing this app!
