### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by rjm831** [JunkFood02/Seal#591]
### Describe the bug

Toast shows an Error

### Error reports & Screenshots

Seal-1.9.0-beta.1-arm64-v8a-release works fine, but FYI I'm getting an error toast:
Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies': Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist

Just thought you should know.

### Device info

Using Samsung Tab A7, stock, Android 12

**Comment by Botan626** [comment]
https://github.com/JunkFood02/Seal/issues/590#issuecomment-1426756907
