### ISSUE TITLE
[Bug Report] net::ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by eliasoft** [JunkFood02/Seal#593]
### Describe the bug

See the screenshots

### To Reproduce

![Screenshot_2023-02-12-17-03-03-864_com junkfood seal](https://user-images.githubusercontent.com/40068066/218337216-389695d5-c7b4-44e5-ace7-26edae335124.jpg)
![Screenshot_2023-02-12-17-03-29-945_com junkfood seal](https://user-images.githubusercontent.com/40068066/218337235-0b5a61dc-9458-4b93-9873-82807d5e9966.jpg)
![Screenshot_2023-02-12-17-03-37-410_com junkfood seal](https://user-images.githubusercontent.com/40068066/218337238-13692855-4782-4234-b9cd-fecbcb7cd8bf.jpg)

### Device info

App version: 1.9.0-beta.1 (10820)
Device information: Android 10 (API 29)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

**Comment by Marco-9456** [comment]
What are you trying to do?

**Comment by eliasoft** [comment]
I was just testing

**Comment by Marco-9456** [comment]
> I was just testing

Ok, it's because the link you used isn't valid, you need to always use a proper like, in your case you should've used `https` instead of `http` if you changed it it'll work.

**Comment by eliasoft** [comment]
Works.  but it looks like they need to change the user agent that is used within Seal's built-in web browser
![Screenshot_2023-02-12-19-18-44-211_com junkfood seal](https://user-images.githubusercontent.com/40068066/218343540-3882b320-6c90-450a-bfb0-a05fb85e73ac.jpg)
