### ISSUE TITLE
[Feature Request] filename of downloaded audio files

### ISSUE THREAD

**Issue by eliasoft** [JunkFood02/Seal#594]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Hello developers, From now on I will start using Seal as my favorite app to download music in .opus format (from YouTube)
They have done a very good job developing this app, and in my opinion this app is perfect as it is now.
However, there is something that I want them to correct, and I will explain it to you briefly below.

After Seal successfully downloads an audio file, the file name will have the following nomenclature: "%song_title% [%extra_alphanumeric_chars%].opus"
But I want that instead of the current nomenclature, the names of the files that I download through Seal have the following nomenclature: "%song_artist(s)_if_extsts_separated_by_comma% - %song_title%.opus"

Greetings from Latin America.

**Comment by Marco-9456** [comment]
This isn't a feature request, join the telegram channel and people will help you there.

**Comment by eliasoft** [comment]
Thanks

**Comment by eliasoft** [comment]
solved
