### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by JavdanFar** [JunkFood02/Seal#599]
### Describe the bug

I could download yesterday but I cant download today
Because of this error on screenshot:

### Error reports & Screenshots

![Screenshot_20230217_012946_Seal](https://user-images.githubusercontent.com/99086411/219579650-1297bb14-e7e1-496f-989a-37531c850752.jpg)

### Device info

App version : 1.8.2 & 1.9.0

Android 13 arm64-v8a

**Comment by AI-IMED** [comment]
Update to seal 1.9.0-beta1, then go to the application settings and long press on "Yt-dlp version" and choose to update to the night version.👍

**Comment by JavdanFar** [comment]
> Update to seal 1.9.0-beta1, then go to the application settings and long press on "Yt-dlp version" and choose to update to the night version.👍

Solved. Thank you

**Comment by JunkFood02** [comment]
Settings - General - click Yt-dlp version and update it to 2023.02.17 solve the problem
