### ISSUE TITLE
[Bug Report] unable to extract uploader id

### ISSUE THREAD

**Issue by aspwil** [JunkFood02/Seal#600]
### Describe the bug

when attempting to download any video it gives an error "unable to extract uploader id"

### To Reproduce

1. download video
2. get error

### Error reports & Screenshots

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://youtu.be/IiaO9rP46WU
ERROR: [youtube] IiaO9rP46WU: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06 

### Additional context

(dont know why yall want the data twice but i pasted it)

**Comment by aspwil** [comment]
also it appears i cant read as it says to report to yt-dlp not seal... oops. ima just leave it open so people see that its a known bug though and don't open extra issues. some contributor feel free to close this when its relevant.

**Comment by aspwil** [comment]
also according to this person, https://github.com/yt-dlp/yt-dlp/issues/6247#issuecomment-1434313225

yt-dlp dev team knows of this bug and it will be solve in an update in a few hours.

thank you for your time

**Comment by aspwil** [comment]
and looking though the closed issues i can see there is a working fix here

https://github.com/JunkFood02/Seal/issues/598#issuecomment-1434252129

update to 1.9.0beta1 and go to aplication settings, long press yt-dlp version, and select the nightly branch.

again going to leave this issue open in case other people need it before it gets fixed on yt-dlps side.

**Comment by Marco-9456** [comment]
1.Download Latest beta
2. Go to `Settings`-->`General`-->`Long press on Yt-dlp Version`-->`Switch from Stable to Nightly`-->`click once on Yt-dlp version`-->`Try to download again`.

**Comment by Botan626** [comment]
fixed in new stable version of yt-dlp v2023.02.17

**Comment by aspwil** [comment]
fixed pog
