### ISSUE TITLE
Cant Download videos/Audios from YouTube 

### ISSUE THREAD

**Issue by SaltyBill** [JunkFood02/Seal#601]
### Describe the bug

It says ERROR: [youtube] 8SWhBsbxmpk: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

App version: 1.9.0-beta.1 (10820)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: 
ERROR: [youtube] 8SWhBsbxmpk: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies': Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist

**Comment by aspwil** [comment]
not just you, just open an issue (2 min ago) #600 with exact same error.

**Comment by aspwil** [comment]
there is a fix, update to 1.9.0beta1, go in apliocation settings, long press on the yt-dlp version, and select nightly.

**Comment by Marco-9456** [comment]
1.Download Latest beta
2. Go to `Settings`-->`General`-->`Long press on Yt-dlp Version`-->`Switch from Stable to Nightly`-->`click once on Yt-dlp version`-->`Try to download again`.

**Comment by Botan626** [comment]
fixed in new stable version of yt-dlp v2023.02.17, update yt-dlp
