### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by AI626-1** [JunkFood02/Seal#602]
### Describe the bug

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06
YouTube videos download problem

**Comment by Marco-9456** [comment]
1.Download Latest beta
2. Go to `Settings`-->`General`-->`Long press on Yt-dlp Version`-->`Switch from Stable to Nightly`-->`click once on Yt-dlp version`-->`Try to download again`.

**Comment by Botan626** [comment]
fixed in new stable version of yt-dlp v2023.02.17, update yt-dlp
