### ISSUE TITLE
Page remains gray generating cookies for discoveryplus.com/it

### ISSUE THREAD

**Issue by Gittore54** [JunkFood02/Seal#603]
### Describe the bug

It cannot finalize loading of the page in built in browser/WebView, probably Javascript problem, I dont know.

Previously I copypasted from cookies.txt so now rollback to stable 1.8.2, if you can reimplement manuallly insert in next beta/preview it will be really appreciated, especially because not all supported sites can be made fully compatible for this WebView even in future probably, and it will be very difficult to put credential infos in the url of the login page for every site that cannot render properly.

Thanks in advance.

### To Reproduce

Go to cookies settings and generate for that url, can try even with login page url, same result.

### Device info

Latest 1.9.0 beta

**Comment by JunkFood02** [comment]
Please install [this build](https://github.com/JunkFood02/Seal/actions/runs/4206659879) and see if the problem is resolved
