### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by DannyBrock123** [JunkFood02/Seal#604]
### Describe the bug

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.01.06

URL: https://youtu.be/YMDBNkBEUSs
WARNING: [youtube] YMDBNkBEUSs: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 9Q5vtmaNTGmKHM6o ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
ERROR: [youtube] YMDBNkBEUSs: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by Marco-9456** [comment]
1.Download Latest beta
2. Go to `Settings`-->`General`-->`Long press on Yt-dlp Version`-->`Switch from Stable to Nightly`-->`click once on Yt-dlp version`-->`Try to download again`.

**Comment by DannyBrock123** [comment]
I have no idea what your talking about. It just doesn't let me download without a bunch of errors

**Comment by Marco-9456** [comment]
> 

Downloading from youtube is currently broken, but there's a fix for it, which is what i mentioned above.

**Comment by Botan626** [comment]
fixed in new stable version of yt-dlp v2023.02.17, update yt-dlp

**Comment by herbie68** [comment]
Get this error on every download after updating to release of februari 10

**Comment by Marco-9456** [comment]
> Get this error on every download after updating to release of februari 10

Just go to general and tap on Yt-dlp version
