### ISSUE TITLE
YouTube video's not downloading 

### ISSUE THREAD

**Issue by A72010** [JunkFood02/Seal#608]
### Describe the bug

App version: 1.7.3-(F-Droid) (10733)
Device information: Android 9 (API 28)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: null
App version: 1.7.3-(F-Droid) (10733)
Device information: Android 9 (API 28)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtu.be/jCPDiPdVqKA
ERROR: [youtube] jCPDiPdVqKA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.7.3-(F-Droid) (10733)
Device information: Android 9 (API 28)
Supported ABIs: [armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by JunkFood02** [comment]
Update yt-dlp to 2023.02.17
