### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by ghost** [JunkFood02/Seal#61]
ㅤㅤ

**Comment by Skaldebane** [comment]
FIrst suggestion is okay, but the second one doesn't make a change. The design you proposed is nice, but it's not any better than the current one.

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/94

**Comment by Marco-9456** [comment]
> Change **README** to **GitHub** New description: **Check the GitHub repository and source code**
> 
> ![IMG_20220727_142058.jpg](https://user-images.githubusercontent.com/71558811/181236314-723cdcd4-f23d-48f3-a28f-5c51fb784616.jpg)
> 
> **Normal UI:**
> 
> ![IMG_20220727_143248.jpg](https://user-images.githubusercontent.com/71558811/181236771-26a40ead-f457-447d-91b1-1bd187bc7104.jpg)
> 
> **My suggestion:** (ignore the font)
> 
> ![IMG_20220727_142924.jpg](https://user-images.githubusercontent.com/71558811/181236812-76b5e892-d9d5-46ee-bc79-e50bb88168c7.jpg)

https://github.com/JunkFood02/Seal/issues/94

**Comment by Skaldebane** [comment]
That space is in line with Android 12's Design System (Material YOU) which is there for easier access on larger screens.

"Looks bad" is a very subjective statement, doesn't reflect the actual functional benefit, nor any general aesthetic benefit compared to what's been studied by professional design teams at Google.

And yeah, #94.
