### ISSUE TITLE
[Bug Report] can't download videos

### ISSUE THREAD

**Issue by MohamadBayz** [JunkFood02/Seal#611]
### Describe the bug

Im trying to download a video from YouTube and said failed to fetch with an error

### To Reproduce

Grab a link from YouTube paste it and download 

### Error reports & Screenshots

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

URL: https://youtu.be/yeLb8JB9XuM
WARNING: [youtube] yeLb8JB9XuM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = rKBN1xCbfNrq07se ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
ERROR: [youtube] yeLb8JB9XuM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

Android 13

**Comment by Marco-9456** [comment]
Go to settings --> General --> click on Yt-dlp Version. Done

**Comment by MohamadBayz** [comment]
You are right it seemed that with using some cleaner app it deleted some important files from the app

**Comment by Marco-9456** [comment]
> You are right it seemed that with using some cleaner app it deleted some important files from the app

No, it was a bug in Yt-dlp but they fixed yesterday with a release that's why i said click on Yt-dlp Version because it will trigger the app to update it.

**Comment by MohamadBayz** [comment]
> No, it was a bug in Yt-dlp but they fixed yesterday with a release that's why i said click on Yt-dlp Version because it will trigger the app to update it.

Oh, thanks for letting me know
