### ISSUE TITLE
Download all videos of the channel

### ISSUE THREAD

**Issue by HassanDalwi** [JunkFood02/Seal#612]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I want to copy the link of the channel on YouTube and download all videos on single click and choose whether audio or video like playlist.

**Comment by JunkFood02** [comment]
pass URLs like `https://www.youtube.com/CHANNEL_NAME/videos` and enable playlist download

**Comment by HassanDalwi** [comment]
> pass URLs like `https://www.youtube.com/CHANNEL_NAME/videos` and enable playlist download

Best app on the real world. Thanks a lot
