### ISSUE TITLE
Option to embade thumbnail as cover-art[Feature Request]

### ISSUE THREAD

**Issue by lewdpatriot** [JunkFood02/Seal#617]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Simply an option to embade thumbnails.
I believe the flag is `--embed-thumbnail`

### Additional context

It's very useful to me cause I download large playlists for studies and it's easier to see which video covers which chapter. And it's obviously great for downloading music.

**Comment by JunkFood02** [comment]
it's enabled by default when downloading audio

**Comment by lewdpatriot** [comment]
> it's enabled by default when downloading audio

Ok, but can you add an option to enable it for the videos as well.

**Comment by sorenkair** [comment]
> it's enabled by default when downloading audio

no way to disable that?
