### ISSUE TITLE
App version: 1.8.2-(F-Droid) (10824) Device information: Android 12 (API 31) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: null  URL: https://youtube.com/shorts/qp29nYspbJo?feature=share ERROR: [youtube] qp29nYspbJo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[Bug Report]

### ISSUE THREAD

**Issue by Abdullahshq** [JunkFood02/Seal#618]
### Describe the bug

It is not downloading the video

### Error reports & Screenshots

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtube.com/shorts/qp29nYspbJo?feature=share
ERROR: [youtube] qp29nYspbJo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtube.com/shorts/qp29nYspbJo?feature=share
ERROR: [youtube] qp29nYspbJo: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by Marco-9456** [comment]
Settings - General - click Yt-dlp version and update it to 2023.02.17 should solve the problem
