### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Johntejie62** [JunkFood02/Seal#619]
### Describe the bug

unknown error (Sqlite code 14): Could not open database, (OS error - 2:No such file or directory)

App version: 1.9.0-beta.1 (10820)
Device information: Android 7.0 (API 24)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

URL: https://youtu.be/_kfi1T4z-KU
ERROR: [Errno 1] Operation not permitted

Pls fix it

**Comment by Marco-9456** [comment]
Did you give Seal Storage permission?

**Comment by JunkFood02** [comment]
Settings - Network - Cookies - Clear all cookies
