### ISSUE TITLE
Capture streams from a website URL

### ISSUE THREAD

**Issue by yephny** [JunkFood02/Seal#62]
There are many cases where the link to a video stream is difficult to get during casual mobile browsing. It would be cool if Seal could grab video URLs itself just from a link to the website you can watch the video on. [LM videodownloader](https://github.com/hikikomoriphoenix/Beedio) already does this, but it's abandoned, unfortunately. I don't believe why Seal wouldn't be able to do it, what do you think?

**Comment by JunkFood02** [comment]
Seal is just a GUI of yt-dlp, so I'm afraid it's hard to implement features that yt-dlp doesn't support.

**Comment by yephny** [comment]
@JunkFood02 Does yt-dlp not support this? I thought that's how download managers on desktop worked, as glorified yt-dl GUIs.

**Comment by JunkFood02** [comment]
As far as I know, "download managers on desktop" like [xdm](https://github.com/subhra74/xdm) monitor all websites you access to detect a video stream (often via an extension installed). Youtube-dl is just a command line program that only executes what you input.

**Comment by yephny** [comment]
Thanks for the clarification.
