### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by KittyBloo** [JunkFood02/Seal#621]
### Describe the bug

YouTube videos (specifically) didn't download.

### To Reproduce

1. Copy video link from YouTube
2. Paste in Seal (Using the text input box through the keyboard or the designated paste button)
3. Start download

### Error reports & Screenshots

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtu.be/ih2xubMaZWI
ERROR: [youtube] ih2xubMaZWI: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

![Screenshot_20230219_230956_Seal](https://user-images.githubusercontent.com/74316613/219966911-ad846e99-c727-4069-b4be-7e85e0720c47.jpg)

### Device info

**SM-S906E/DS (Samsung Galaxy S22+)**
running OneUI5.1 based on Android13 (API 33)

**Kernel version**
5.1 0.136-android1 2-9-25884040-abS906EXXU3CWAI
#1 Mon Jan 30 10:57:01 UTC 2023

**Build number**
TP1A.220624.014.S906EXXU3CWAI

**Google Play system update**
November 1, 2022

### Additional context

Happens only with YouTube. Tried other sites; TikTok and a pure MP4 video - all work. Created cookies for https://youtube.com yet didn't download still.

**Comment by Marco-9456** [comment]
Go to settings --> General --> click on Yt-dlp Version. Done

**Comment by KittyBloo** [comment]
Issue has been resolved!

I'd like to suggest enabling automatic updates to Yt-dlp.

Thanks!!

![Screenshot_20230219_231553_Seal](https://user-images.githubusercontent.com/74316613/219967066-a358bfda-c869-4a86-8883-69399d34f1c2.jpg)

**Comment by Marco-9456** [comment]
It's enabled by default but only for GitHub releases.
