### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by KittyBloo** [JunkFood02/Seal#622]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

It's a little inconvenient to have to check on my Yt-dlp version every now and then, and it's not too pleasant when I have to grab a download quickly from YouTube.

### Describe the solution you'd like

Automatic updates to Yt-dlp. I wouldn't mind not having an option to, but I'd love to have it on by default personally.

### Video link

https://youtu.be/ih2xubMaZWI

### Additional context

There's no additional context :V
Just wanted to say I love the app. Keep up the good work!

**Comment by JunkFood02** [comment]
The app and yt-dlp are updated separately, but the auto-update option controls the behavior of these two components at the same time, which is disabled in F-Droid builds.
An separate option for auto updating yt-dlp will be added in v1.9.0

**Comment by KittyBloo** [comment]
Thanks a lot!
