### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Ayur777** [JunkFood02/Seal#627]
### Describe the bug

Does recognise video even 8f the exact url is pasted
![Screenshot_20230220-165048](https://user-images.githubusercontent.com/125879309/220091955-c603f834-9fe5-4893-a955-68fd0a8f87c4.jpg)

### Error reports & Screenshots

![Screenshot_20230220-165048](https://user-images.githubusercontent.com/125879309/220092357-82cbe81f-c6e1-45a5-b0b7-7ecfb1163fcd.jpg)

### Device info

App version: 1.6.1-(F-Droid) (10614)
Device information: Android 11 (API 30)
[arm64-v8a, armeabi-v7a, armeabi]
Screen resolution: 2352 x 1080

**Comment by JunkFood02** [comment]
update to latest version
