### ISSUE TITLE
Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies' with flags 0x1: Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist

### ISSUE THREAD

**Issue by DannyBrock123** [JunkFood02/Seal#629]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

It keeps saying this everytime I load up 

### To Reproduce

Just open program 
See error 

### Error reports

Cannot open database '/data/data/com.junkfood.seal/app_webview/Default/Cookies' with flags 0x1: Directory /data/data/com.junkfood.seal/app_webview/Default doesn't exist

### Device info

App version: 1.9.0-beta.1 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

**Comment by JunkFood02** [comment]
update to v1.9.0-beta.2
