### ISSUE TITLE
[Feature Request] Open settings by swiping from left to right.

### ISSUE THREAD

**Issue by Qaz-7** [JunkFood02/Seal#631]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I want to be able to open settings by swiping from left to right.👉

### Describe the solution you'd like

Swipe right to open settings.👉

### Video link

Not related to the video.👇

### Additional context

https://user-images.githubusercontent.com/124310688/220304827-29f7a452-0a04-4744-a503-c71d0b4e1690.mp4

**Comment by Marco-9456** [comment]
JunkFood02 mentioned before that **Gestures in Compose are still experimental** + I think implementing this will conflict with android Gesture navigation.

**Comment by Marco-9456** [comment]
> 

Gesture navigation work all over the screen
