### ISSUE TITLE
[Feature Request] Easy way to download beta versions

### ISSUE THREAD

**Issue by muhammadsaadoon** [JunkFood02/Seal#632]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

I've been wondering If I could download beta versions like the stable versions Because I don't know how to code or how to use android studio

### Additional context

None
just Thanks ❤

**Comment by Marco-9456** [comment]
https://user-images.githubusercontent.com/41828058/220322667-46c99b10-8e9d-472d-97c3-42688645e2be.mp4

**Comment by muhammadsaadoon** [comment]
Wow thanks I didn't know that 😁

**Comment by muhammadsaadoon** [comment]
This feature in beta version so I can't use that

**Comment by muhammadsaadoon** [comment]
Where is the beta apk ?

**Comment by Marco-9456** [comment]
> Where is the beta apk ?

👀https://github.com/JunkFood02/Seal/releases
