### ISSUE TITLE
Uploader ID

### ISSUE THREAD

**Issue by uluchann** [JunkFood02/Seal#633]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

A content is not downloadable because it's impossible to extract the uploader ID. Dowsngrading does not help 

### Error reports

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://www.youtube.com/watch?v=O0AKzFv7q94
ERROR: [youtube] O0AKzFv7q94: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by uluchann** [comment]
Thank you sir

**Comment by itxmfahadkhan** [comment]
> Go to Settings > General > Click on "yt-dlp version" at the very top.
> 
> You have to see that your yt-dlp version is 2023.02.17

![Uploading Screenshot_20230225_191901_Seal.jpg…]()

**Comment by itxmfahadkhan** [comment]
> Go to Settings > General > Click on "yt-dlp version" at the very top.
> 
> You have to see that your yt-dlp version is 2023.02.17

![Uploading Screenshot_20230225_191901_Seal.jpg…]()

**Comment by itxmfahadkhan** [comment]
Still not working
