### ISSUE TITLE
Not downloading 

### ISSUE THREAD

**Issue by KarthiAKPS** [JunkFood02/Seal#634]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtu.be/Np3YZTH-kzw
WARNING: [youtube] Np3YZTH-kzw: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = 63gKDUmH-GQhFbvI ; player = https://www.youtube.com/s/player/11e3a4ec/player_ias.vflset/en_US/base.js
ERROR: [youtube] Np3YZTH-kzw: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_2023_0222_193254](https://user-images.githubusercontent.com/89832954/220643078-8b646aca-3c74-4554-aae1-f2521a5aae77.jpg)

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/633#issuecomment-1440006660

**Comment by KarthiAKPS** [comment]
Worked 👍
