### ISSUE TITLE
I'm unable to download any video. 

### ISSUE THREAD

**Issue by Likhon545466** [JunkFood02/Seal#637]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Everything was fine till last night. But suddenly it stops downloading any kinda video or audio. 

### Error reports

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

URL: https://youtu.be/H00nszsqN8A
WARNING: [youtube] Unable to download webpage: The read operation timed out
WARNING: [youtube] The read operation timed out. Retrying (1/3)...
WARNING: [youtube] The read operation timed out. Retrying (2/3)...
WARNING: [youtube] The read operation timed out. Retrying (3/3)...
ERROR: The read operation timed out

### Screenshots & Screen Records

![Screenshot_20230224-110948](https://user-images.githubusercontent.com/102575935/221097115-851bade3-6c28-4086-a697-c4e51128dfab.png)

### Device info

App version: 1.8.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

**Comment by yunus476** [comment]
When i want to download any video from YouTube by seal this problem is show me and i try several times but not fix:
ERROR: unable to download video data: HTTP Error 403: Forbidden

**Comment by Zainaligggg** [comment]
Error enable to download webpage what is this error

**Comment by Zainaligggg** [comment]
Enable to download webpage what is this error

**Comment by Zainaligggg** [comment]
> ### Checklist
> * [x]  I'm reporting a bug unrelated to a specific site.
> * [x]  I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
> * [x]  I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
> * [x]  I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
> * [x]  I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
> * [x]  I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.
> 
> ### Describe the bug
> Everything was fine till last night. But suddenly it stops downloading any kinda video or audio.
> 
> ### To Reproduce
> _No response_
> 
> ### Error reports
> App version: 1.8.2 (10820) Device information: Android 13 (API 33) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.02.17
> 
> URL: https://youtu.be/H00nszsqN8A WARNING: [youtube] Unable to download webpage: The read operation timed out WARNING: [youtube] The read operation timed out. Retrying (1/3)... WARNING: [youtube] The read operation timed out. Retrying (2/3)... WARNING: [youtube] The read operation timed out. Retrying (3/3)... ERROR: The read operation timed out
> 
> ### Screenshots & Screen Records
> ![Screenshot_20230224-110948](https://user-images.githubusercontent.com/102575935/221097115-851bade3-6c28-4086-a697-c4e51128dfab.png)
> 
> ### Device info
> App version: 1.8.2 (10820) Device information: Android 13 (API 33) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.02.17
> 
> ### Additional context
> _No response_

Error enable to download webpage what is this error

**Comment by thvkia** [comment]
It could be because you're using a moded version of YouTube. Copy the link from the og version

**Comment by SERGIOovalle** [comment]
![Screenshot_20241021-012032](https://github.com/user-attachments/assets/41434852-9859-4a17-b457-4a328767d103)
Alguien sabe por q no lo puedo descargar 
Ya tengo todo actualizado e incluso hasta la última versión 😭😭😭 es realmente frustrante no poder descargar música por favor arreglen el problema 
Bastante molesto 😡😡🤬👎👎👎
