### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pwnkrptr** [JunkFood02/Seal#639]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

ERROR: Postprocessing: file:/data/user/0/com.junkfood.seal/files/tmp/SK Sir Ki Class ｜ EP1 - Chakravyuh ｜ Watch in Hindi, Tamil or Telugu ｜ TVF [dTSbcI44QkA].en.temp.vtt.concat: Math result not representable

**Comment by Marco-9456** [comment]
Fill the issue **correctly**
