### ISSUE TITLE
YouTube Video Clip 

### ISSUE THREAD

**Issue by itxmfahadkhan** [JunkFood02/Seal#640]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Download Clip from YouTube video creates the problem 

### To Reproduce

1. Paste YouTube [URL](https://youtube.com/clip/UgkxoQqL8Ucipyv05GxrdSYbMpkfxjYNvqqg) in Seal's video link section
2. Selected quality for this video is 480p and format is unspecified
3. Click download button, error will pop-up 

### Error reports

ERROR: [youtube] 3BJU2drrtCM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230225_190617_Seal](https://user-images.githubusercontent.com/115094497/221361274-33218b35-82be-404b-95ee-d10b2f2128a0.jpg)

### Device info

App version: 1.9.0-beta.2 (10820)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by BobbyESP** [comment]
https://github.com/JunkFood02/Seal/issues/633#issuecomment-1440006660
