### ISSUE TITLE
Audio unable to Download 

### ISSUE THREAD

**Issue by ImKarthik1234** [JunkFood02/Seal#641]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Why the Instagram Reels Audio aren't able to download? Shows like this. Please fix this issue and provide an update in my email. 

### Error reports

App version: 1.8.2 (10820)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

URL: https://www.instagram.com/reels/audio/1124709088184414/
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.instagram.com/reels/audio/1124709088184414/

### Screenshots & Screen Records

![Screenshot_2023-02-26-02-22-11-06_2b0c70832456616f1f794bb05bb8d2fa](https://user-images.githubusercontent.com/126358124/221379382-dc43769d-2a4e-473d-a025-41a46728a9bf.jpg)

### Device info

App version: 1.8.2 (10820)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

**Comment by EmmanuelDav** [comment]
You cant download Instagram Reals because Instagram requires you to be logged in to access their videos, i.e the videos can't be accessed without logging in on instagram
