### ISSUE TITLE
Seal can't move file to sdcard

### ISSUE THREAD

**Issue by soredake** [JunkFood02/Seal#646]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

After downloading any video it is not moved to sdcard directory.

### To Reproduce

1. Enable "SD card folder" and select directory.
2. Try to download any video.
3. After downloading file is not moved to sd card directory.

### Error reports

No errors.

### Screenshots & Screen Records

Sd card path is displayed weirdly:
![Screenshot_20230228-131352_Seal](https://user-images.githubusercontent.com/5204968/221838181-db2619a6-603a-4a33-9112-e5c3508a1464.png)

### Device info

App version: 1.8.3-(F-Droid) (10834)
Device information: Android 12 (API 32)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.02.17

**Comment by JunkFood02** [comment]
i don't have a device with sd card so it cannot be tested on my side, could you change the directory to
1. SD card root directory
2. Internal directory like `Downloads/`
and see if it's not working at all times.
Also, did you come across this issue in previous versions?

**Comment by soredake** [comment]
>SD card root directory

Can't be selected in folder picker.

>Internal directory like Downloads/

<sdcard>/Downloads/Seal -> nothing is saved.

>Also, did you come across this issue in previous versions?

Yes.

**Comment by JunkFood02** [comment]
try installing [this build](https://github.com/JunkFood02/Seal/actions/runs/4296184630) and see if the error report is available, you may have to uninstall the F-Droid build to install this apk

**Comment by soredake** [comment]
@JunkFood02 i discovered that videos aren't saving to sdcard when "private mode" option is enabled, at least in 1.8.3.

**Comment by soredake** [comment]
Same with the build you sent, no error is printed.

**Comment by soredake** [comment]
@JunkFood02 working fine now, thanks!
