### ISSUE TITLE
Please Add a Feature to Download Multiple Videos at the Same Time ( Without Playlist ) [Feature Request]

### ISSUE THREAD

**Issue by Saim1358** [JunkFood02/Seal#648]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I want to download multiple videos at same time . I try to download a video while a video is downloading . But I have to wait to add this task until the another download is completed. All other famous youtube downloader like Snaptube , Vidmate , etc allow to download or add another task while downloading .
PLEASE ADD THIS FEATURE TO SEAL .😭😭😭

### Describe the solution you'd like

You can add a Feature of pending to add another tasks while downloading. PLEASE ADD THIS FEATURE. 🥺🥺🥺

**Comment by Marco-9456** [comment]
Duplicated of:
#324 
#324 
#475
.

**Comment by Saim1358** [comment]
> Duplicated of: #324 #324 #475 .

Yes . This is very important feature ! 😭😭😭

**Comment by Marco-9456** [comment]
> > Duplicated of: #324 #324 #475 .
> 
> Yes. This is a very important feature! 😭😭😭

Dude this is already requested more than once it's harder to Archiv than you think + crying won't make it happen faster.

**Comment by Saim1358** [comment]
> > > Duplicated of: #324 #324 #475 .
> > 
> > 
> > Yes. This is a very important feature! 😭😭😭
> 
> Dude this is already requested more than once it's harder to Archiv than you think + crying won't make it happen faster.

Oh, I am sorry . 😔
