### ISSUE TITLE
Format sorting not works with links that contains master.mpd playlists/streams

### ISSUE THREAD

**Issue by Gittore54** [JunkFood02/Seal#649]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

If I set up 720 or 480/360 It will prefer always best resolution available for master.mpd playlists/streams (I haven't tried with m3u8 or other type of playlists).

It is a cookie protected link so I can't write here, but I think that It will do the same behaviour with other sites like this, even public links (site is d+).

### To Reproduce

1. Simply enable formats list and sorting res:720
2. Put an url that contains master.mpd with various bitrates and 1080 as the highest resolution
3. It will select always best available resolution

### Error reports

Not really an error.

### Device info

Tried in several devices and both architectures, same result.

**Comment by JunkFood02** [comment]
can you enable format selection and post screenshot of the output here?

**Comment by Gittore54** [comment]
> can you enable format selection and post screenshot of the output here?

Sorry for late answer

![Screenshot_20230304-223736_Seal.jpg](https://user-im![Screenshot_20230304-223442_Seal.jpg](https://user-images.githubusercontent.com/113577927/222929716-f240dee5-141e-47c1-955d-2a655e6a9f3a.jpg)

0-8d1c-4ee9-a419-0a24b317e6e3.jpg)

![Uploading Screenshot_20230304-223442_Seal.jpg …]()

![Screenshot_20230304-223729_Seal.jpg](https://user-images.githubusercontent.com/113577927/222929715-d07a1be2-59c6-4dd1-9af9-9a0eebf9b48e.jpg)

![Screenshot_20230304-223450_Seal.jpg](https://user-images.githubusercontent.com/113577927/222929714-ff1ae401-7950-4286-92b6-7474331b5922.jpg)

**Comment by JunkFood02** [comment]
i think the problem might be the unknown resolution of formats. could you specify a sorting parameter for "vbr"(video bitrate) and see if it works?

**Comment by Gittore54** [comment]
> i think the problem might be the unknown resolution of formats. could you specify a sorting parameter for "vbr"(video bitrate) and see if it works?

Disabling format selection list It downloads the right resolution, so I think that I can keep It disabled when downloading from this site and specify only approx filesize, bitrate or other parameters in format sorting when there are more than one format of the same resolution.

Maybe you can add some of these -S parameters in general GUI.

Thanks for the help, if you want can close the issue now as here It depends on user choice.
