### ISSUE TITLE
Custom output

### ISSUE THREAD

**Issue by yant0** [JunkFood02/Seal#65]
I used to configure dvd to seperate downloads to their own playlist name when downloading songs using `-o %(playlist_title)`. It would be great if that or maybe the feature to add custom output when #34 is done to get custom directories without the default video/audio option greyed out. Thanks for the great app 👍

**Comment by JunkFood02** [comment]
For Android 10+, the custom directory works in any subdirectories(recursively) under `Downloads/` and `Documents/`, so you can just simply create a new folder for a playlist download task.

**Comment by yant0** [comment]
Good to know. But some weird artists use obsecure ascii to title their stuff, you can find this just about anywhere on soundcloud. Requesting this for the sake of convenience.

**Comment by JunkFood02** [comment]
Make sense. The title output template is [here](https://github.com/JunkFood02/Seal/blob/92e9b16794870f24e6ff4d02e034877f22dad905/app/src/main/java/com/junkfood/seal/util/DownloadUtil.kt#L142), and a modification is not so difficult. Could you please provide a SoundCloud playlist link with weird characters for testing?

**Comment by yant0** [comment]
For sure
- not in the alphabet
https://m.soundcloud.com/curiosityshoppp/sets/cole-longanecker-cocoon
- emojis
https://m.soundcloud.com/liluzivert/sets/red-white-ep
- ascii
https://m.soundcloud.com/curiosityshoppp/sets/cole-longanecker-cocoon

**Comment by JunkFood02** [comment]
I will only make this available to the output path (the `-P` option in yt-dlp) but not the filename due to some corner cases I don't want to handle. Stay tuned for the next release! 🤞

**Comment by JunkFood02** [comment]
Please preview and test the two features you requested here👇

https://drive.google.com/file/d/1fwR2qVEv_JqrOOH20QDy7AVF-Q40yJbs/view?usp=sharing

**Comment by yant0** [comment]
hm. Custom path works flawlessly but im still getting 0 for track numbers. I usually use `"playlist_index:%(track_number)s"` for soundcloud.

Also for would u like me to make a seperate issue for custom made preset for websites? Im quite happy with just two of these feature.

**Comment by JunkFood02** [comment]
> i'm still getting 0 for track numbers. I usually use `"playlist_index:%(track_number)s"` for soundcloud.
> 
>
>I would suggest not to hard code the track numbers into native download option. In soundcloud, we can download whole >discog and in my preference i would have the track numbers to be 0 since there could be new releases.
>

Are these two you mentioned just contradictory to each other?

**Comment by yant0** [comment]
It does. But, i use 0 as track number only for singles and put them in all in one folder, and i need that track number to be 0 to not mess the sorting. I mention discography and not playlist/albums since you can download an artist's whole uploads by `soundcloud.com/artist/tracks`. i believe, since we are downloading a user, it puts their name as an album (and if we turn on the custom directories we got their name as a folder) so theoretically i just need to tag the songs on that album and move it elsewhere. 

> I put artists singles into one folder. So when i batch download a artist i would like to put their singles there in the singles folder without the track numbers being mixed up.
> 
> Thats just my use case. Im fine with it being hard coded but i need to retag each one of them and put it in the folder.
> 
> Edit : actually nvm i can batch retag songs. So ignore what i just said

What i meant by not being hardcoded is there needs to be an option to turn it on, instead of being inside the native downloader that normal users cant access

And as i said last on that quote. Im fine being it hardcoded since i realized i can batch retag them now.

I apologize for not clarifying things properly.

**Comment by JunkFood02** [comment]
I see. So you use the playlist download to download all tracks from users/albums. And yt-dlp would extract different information from these two "playlists", causing all the problems and complexity. I think this cannot be avoided and should be solved manually. In addition, I want to keep the app simple and straightforward to use, so I'll not provide options for the custom metadata controls.

**Comment by yant0** [comment]
Whats ur thoughts on premade commands for specific websites mentioned in #95? This way i can set up commands when i want to download singles and albums separately.

**Comment by JunkFood02** [comment]
> Whats ur thoughts on premade commands for specific websites mentioned in #95? This way i can set up commands when i want to download singles and albums separately.

Do you mean having multiple templates stored in the app for "custom command" mode?

**Comment by yant0** [comment]
Yes

**Comment by JunkFood02** [comment]
> Yes

Make sense. Will be added in v1.0.1 🤞
