### ISSUE TITLE
No download fro yt possible since 1.8.2

### ISSUE THREAD

**Issue by herbie68** [JunkFood02/Seal#656]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

URL: https://youtu.be/4J4NmO_sOrM
WARNING: [youtube] 4J4NmO_sOrM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = wRVqy05nLHrhFs9 ; player = https://www.youtube.com/s/player/7862ca1f/player_ias.vflset/en_US/base.js
ERROR: [youtube] 4J4NmO_sOrM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### To Reproduce

Select a video on youtube
Shareware to Seal
Start dowload
After 1 or two seconde this error will apear
Or sometimes another error, but download is never possible

### Error reports

App version: 1.8.3-(F-Droid) (10834)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2022.11.11

URL: https://youtu.be/4J4NmO_sOrM
WARNING: [youtube] 4J4NmO_sOrM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = wRVqy05nLHrhFs9 ; player = https://www.youtube.com/s/player/7862ca1f/player_ias.vflset/en_US/base.js
ERROR: [youtube] 4J4NmO_sOrM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.8.3-(F-Droid) (10834)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2022.11.11

**Comment by BobbyESP** [comment]
https://github.com/JunkFood02/Seal/issues/633#issuecomment-1440006660
