### ISSUE TITLE
feature request. Mass download video

### ISSUE THREAD

**Issue by Wjxfi** [JunkFood02/Seal#661]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

I need to download the entire playlist in newpipe. There are hundreds of links copied when you click the "share" button in newpipe, and seal can't download it. I want it to be possible. It copies like this: link to video, go to another line, link to video
https://github.com/TeamNewPipe/NewPipe

https://user-images.githubusercontent.com/113500363/223747801-81332d0b-b35a-4ffc-9454-68d5dcde106c.mp4

**Comment by tusharchopra07** [comment]
Bro you can type playlist link or share playlist to seal ☺️

Hare Krishna 🙏❤️🚩

**Comment by tusharchopra07** [comment]
> 

I don't know about newpipe as I never used it but if you want to download a playlist from youtube then it is done 
i thought you were talking about yt 
Sorry for misunderstanding 🙏☺️
