### ISSUE TITLE
Can't download videos from Instagram or Facebook  v8a version 

### ISSUE THREAD

**Issue by AlvaroBuelvas** [JunkFood02/Seal#664]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Hi, I have an issue when trying to download a video either from Instagram or Facebook. I get a toast message that the information of the video could not be loaded / obtained.

The weird thing is that it only happens on the v8a version of the APK. When I download the v7a version it works great. This happens with the stable and also the RC versions.

I'm logged to IG and Facebook via the apps and chrome browser 

### To Reproduce

1. Copy link of the video from an Instagram story or reel
2. Go to the seal app and paste it 
3. Hit the download button

### Error reports

I don't get any detailed logs. I only see a toast message seen in the screenshot.

### Screenshots & Screen Records

![Screenshot_20230309_064121_Seal](https://user-images.githubusercontent.com/71298659/224014130-c860b544-2dcb-46a5-b02c-4e59c339d1b5.jpg)

### Device info

App version: 1.9.0-rc.2 (10900)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

### Additional context

My device is a Galaxy S23 Ultra updated to the latest available software.

**Comment by Marco-9456** [comment]
To make it simple;
Facebook and Instagram from META are very restricted in Asia especially India, in some countries it works and in others not, and we can't do anything about it.

**Comment by AlvaroBuelvas** [comment]
I'm not in Asia. I'm in Colombia, South America. Also, the behavior seems to be inconsistent when trying between v7a and v8a versions.

Version 1.8.2 (v7a) and 1,9,0rc2 (v7a) - Works fine
Version 1.8.2 (v8a) and 1,9,0rc2 (v8a) - Does not work

I don't think it is location related as I tried with the versions mentioned earlier while at my home, in Colombia.

**Comment by Marco-9456** [comment]
> 

Try with the Cookies option in settings.

**Comment by AlvaroBuelvas** [comment]
I just tried. I see the cookie entry created. I logged in to Instagram in the embedded browser in the Seal app. But I still get the same.

Just to clarify, I didn't do this cookie option when testing the v7a versions and that seemed to work with out it.

**Comment by JunkFood02** [comment]
try generate cookies with your insta account and enable it in v1.9.0-rc.2

**Comment by JunkFood02** [comment]
the issues of meta-related sites are complicated and just cannot be reproduced on every device/internet environment/region. we're actually not able and won't do anything about this

**Comment by AlvaroBuelvas** [comment]
I tried the cookies setting after installing this apk, Seal-1.9.0-rc.2-arm64-v8a-release.apk, but that didn't work

I guess I'll stick to using the v7a version of the 1.9.0rc2 release. It is weird that it will work for one and not the other.

In any case, thanks for replying and for developing this amazing app!

**Comment by John52802** [comment]
Tiene que actualizar parce, me pasaba lo mismo

**Comment by AlvaroBuelvas** [comment]
Cual version tienes que funciona? Me sigue pasando con la ultima estable.

> Tiene que actualizar parce, me pasaba lo mismo

**Comment by John52802** [comment]
1.9.2-(F-DROID)(10924)

**Comment by Aidalz** [comment]
@AlvaroBuelvas En la última versión necesitas cambiar algunas cosas:

1. Activar las cookies. Si quieres descargar videos de las diferentes plataformas, necesitas iniciar sesión de cada una de ellas.
2. Deja pulsado el botón de **yt-dlp version** en el apartado de ### general, y cámbialo a **yt-dlp-nightly-builds**. 
3. En general > privacidad, activa el **modo incógnito**.
