### ISSUE TITLE
[Feature Request] we need to know size of video befor download, and the length of downloaded videos is not shown

### ISSUE THREAD

**Issue by Abdallah-Karam** [JunkFood02/Seal#668]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by Abdallah-Karam** [comment]
The length of videos in downloads not showing

**Comment by Marco-9456** [comment]
> The length of videos in downloads is not shown

1. Fill your Feature request correct in the future, or it will be closed.
2. All what you've asked for is already in the app.

<details>
<summary>Screenrecord</summary>

https://user-images.githubusercontent.com/41828058/224505157-6f92e6f1-9332-4d85-9291-1a4d7cf4d456.mp4

</details>
