### ISSUE TITLE
Share sheet style download option 

### ISSUE THREAD

**Issue by missyraja** [JunkFood02/Seal#67]
When i share a video file from to seal using seal instead of opening the app.. it would be great if we can have an option similar to how powertube does it... A simple overlay card to Change any download option..

**Comment by JunkFood02** [comment]
Hi, do you mean to share the video file itself or the link to the video?

**Comment by Marco-9456** [comment]
> When i share a video file from to seal using seal instead of opening the app.. it would be great if we can have an option similar to how powertube does it... A simple overlay card to Change any download option..

You mean this ?
![Screenshot_20220729-134256_Seal](https://user-images.githubusercontent.com/41828058/181751827-da2c8d3d-5f46-483d-9191-ae5f209f5eff.jpg)

**Comment by missyraja** [comment]
Yes it would be great if this overlay opens directly above the YouTube
app... I'll attach how powertube does it for reference... And please add
FLAC audio format for audios if possible.

Maharajan

**Comment by JunkFood02** [comment]
I get it. But as far as I'm concerned, such a complicated function can't provide much convenience as the effort it will take. As for now, you can send the link to Seal in the system share sheet. Also, if the content contains text other than links, Seal will only read the first link from it. I think this is simple enough to make a download.

As for the FLAC audio format, if the source file is in FLAC format, you can download it without converting. If it's not the case, force converting an audio file to FLAC or any other format will not improve the audio quality.
