### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Shahtehmas** [JunkFood02/Seal#670]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when I want to download multiple apps at once. One can't add another video link to download when there's one already downloading.

### Describe the solution you'd like

Allow multiple links addition & multiple download at once.

**Comment by Marco-9456** [comment]
Already requested, close your request.

**Comment by Shahtehmas** [comment]
ok
