### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by yurua** [JunkFood02/Seal#671]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

Facebook and Instagram don't work.

**Comment by Marco-9456** [comment]
They won't work for users in Asia, join the Telegram group for more info.

**Comment by yurua** [comment]
Asia? I'm from Russia.

вс, 12 мар. 2023 г., 20:32 mohammed_9456 ***@***.***>:

**Comment by Marco-9456** [comment]
> Asia? I'm from Russia. вс, 12 мар. 2023 г., 20:32 mohammed_9456 ***@***.***>:


Bruh, 77% of Russia's area is in Asia, the western 23% of the country is located in Europe
