### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Nasruddin55** [JunkFood02/Seal#672]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I am able to download video from Instagram.

### To Reproduce

App version: 1.9.0 (10900)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://www.instagram.com/p/CpSrQkTSY0S/?igshid=YmMyMTA2M2Y=
ERROR: [Instagram] CpSrQkTSY0S: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Error reports

App version: 1.9.0 (10900)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://www.instagram.com/p/CpSrQkTSY0S/?igshid=YmMyMTA2M2Y=
ERROR: [Instagram] CpSrQkTSY0S: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230312_235020](https://user-images.githubusercontent.com/127621562/224564389-bdc77996-452c-4486-bdc8-73479858c29d.jpg)

### Device info

App version: 1.9.0 (10900)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by nyatnyat** [comment]
Hello there! Apparently the yt-dlp-U already added inbuild of Seal itself. feel free to check this on how to running it properly. https://github.com/JunkFood02/Seal/discussions/673
