### ISSUE TITLE
[Feature Request] Remove video id from filename

### ISSUE THREAD

**Issue by jo-chemla** [JunkFood02/Seal#675]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When downloading a youtube playlist (audio files, converted to mp3), then the id is always appended to the filename before the extension. When using custom commands like `-o '%(title)s.%(ext)s'`, then all other seal options will be deactivated - like download only audio, convert to mp3, etc, and tehrefore greyed out in the UI - which is a great indicator that only the custom command is applied. 

Note: Possble bug: I tried to Modify Command shortcuts, but the + sign is greyed out, so I cannot compose a custom command from many shortcuts which could also help. 

### Describe the solution you'd like

 - Simpler option: It would be great to have a toggle in the options (probably in the download folder) to enable/disable the id from the filename. 
 - More advanced: or even let the user choose custom filename options itself using the yt-dlp formatting

### Additional context

On this thread https://github.com/JunkFood02/Seal/issues/108 there is some comment about corner cases with custom commands and UI options. This option should not bring any conflict as long as the id is simply removed from the output filename.

**Comment by Marco-9456** [comment]
- The template name is Feature Request not Feature `Requests` which mean you can request one thing in the issue you opened.
________________________________________
>When downloading a youtube playlist (audio files, converted to mp3), then the id is always appended to the filename before the extension.

Seal needs the id to be able to find the downloaded media location and list them in the download history page.
________________________________________
>When using custom commands like -o '%(title)s.%(ext)s', then all other seal options will be deactivated - like download only audio, convert to mp3, etc, and tehrefore greyed out in the UI - which is a great indicator that only the custom command is applied.

(By JunkFood02) All of the options in GUI settings are well tested and safe to be used together or separately, if there're 5 options it means we'll have to test for 2^5 = 32 combinations, if we allow users to use them with custom commands, we'll receive tons of reports about incompatible/unexpected behaviours
________________________________________
>Note: Possble bug: I tried to Modify Command shortcuts, but the + sign is greyed out, so I cannot compose a custom command from many shortcuts which could also help.

This isn't a bug you need to tap the empty space near the + icon first tipe the the command you want to make a shortcut for and then click it.
________________________________________
>More advanced: or even let the user choose custom filename options itself using the yt-dlp formatting

Setting--> Download Directory--> Custom subdirectory, there you can change everything about the filename and filefolder by using commands like: 
%(uploader)s or %(uploader)s %(playlist_title)s
________________________________________

**Comment by jo-chemla** [comment]
- Thanks for the shortcuts - don't how I missed that feature, really useful. 
 - I thought Custom subdirectory would only prepend to the filename, hence I was not using it in order to remove the suffixed id from the filename.
 - Understood that without the id, Seal will not be able to display downloaded files. Since I'm using the archive, I do not need to see the downloaded files in seal, because that archive males sure I'm only downloading new files from the playlists - as long as I have not deleted them from the folder of course, they will still be there. 
 - Also totally understood that custom command prevents the users from using standard settings, this would be too cumbersome to analyze all edge cases. I still think some users might want to remove the id from the filename (and accept that seal would then not be able to display already downloaded files), which would make it useful to have it as a toggleable feature.

**Comment by VictoryStar527** [comment]
> > More advanced: or even let the user choose custom filename options itself using the yt-dlp formatting
> 
> Setting--> Download Directory--> Custom subdirectory, there you can change everything about the filename and filefolder by using commands like: %(uploader)s or %(uploader)s %(playlist_title)s

I tried using the custom subdirectory to change the filename, but it only changed what folders it would be put in. What do I type to change the file name? Also, if possible, is there a way to not put the file in a subdirectory?

**Comment by dangerdev004** [comment]
This can pose a new problem suppose you have two songs with same name. I have examples in such a case yt-dlp can overwrite the audio of one to other. Thus a unique identifier must be present also the video id is not seen by any music players if Metadata is embedded. This can apply for videos as well as more than one video can have same title.

**Comment by JunkFood02** [comment]
Custom output template has been added in v1.11.0-beta.1
