### ISSUE TITLE
Can't download YouTube videos

### ISSUE THREAD

**Issue by ApurvZ** [JunkFood02/Seal#676]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Unable to extract uploader id.

### To Reproduce

Share the YT link for example: https://youtube.com/shorts/gaUdE58vu98?feature=share
Then select seal, and it gives the error.

### Error reports

App version: 1.8.3-(F-Droid) (10834)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

URL: https://youtube.com/shorts/gaUdE58vu98?feature=share
ERROR: [youtube] gaUdE58vu98: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230316-234211_Seal](https://user-images.githubusercontent.com/43213555/225714982-3a4d66a3-d748-46dd-afd9-9f3c27c2ec3a.png)

### Device info

App version: 1.8.3-(F-Droid) (10834)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

**Comment by ApurvZ** [comment]
Downloaded the yt-dlp by clicking on it. It should be able to download by default..

**Comment by Marco-9456** [comment]
> Downloaded the yt-dlp by clicking on it. It should be able to download by default..

GitHub Version does this by default, F-Droid has some limitations that we can't do anything about.
