### ISSUE TITLE
Not Showing AAC format 😕

### ISSUE THREAD

**Issue by tusharchopra07** [JunkFood02/Seal#678]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Not showing download in aac format option please fix that 
![Screenshot_2023-03-18-13-16-41-825_com junkfood seal](https://user-images.githubusercontent.com/128215171/226093135-05e08cee-b588-483a-b6d3-e57d9b27a1a0.jpg)

### Error reports

Showing only MP3 or m4a 
![Screenshot_2023-03-18-13-16-31-076_com junkfood seal](https://user-images.githubusercontent.com/128215171/226093117-8485d116-6021-414a-ae08-d83faf9a33ca.jpg)

**Comment by Marco-9456** [comment]
1. Seal/Yt-dlp won't show you formats that aren't available/supported from the site you're downloading from.
2. Converting audio from the source format to another one will `JUST INCREASE` the size of the audio file and `DECREASE` the audio quality.
