### ISSUE TITLE
Downloaded Videos Not Visible to Other Applications

### ISSUE THREAD

**Issue by tdadvocate** [JunkFood02/Seal#681]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

After downloading a video, no other application can see it in their default gallery pickers. No messaging app, no cloud app, no private photo application, no social media app, etc. When using any actual file browser I can navigate to any location for the video file and it is perfectly fine. So something like Google files, material files, simple gallery, Samsung gallery, etc can see it fine. I'm just not able to share or store the file without having to do a bunch of weird workarounds. And this happens using both the default directory location as well as custom ones. 

### To Reproduce

1. Download a video from any supported service
2. Attempt to share the video on any messing application
3. You will not see the file in your recent photos from within the messaging application

### Error reports

No error reports are logged as this is not any form of crash or anything similar. 

### Device info

App Version 1.9.0 
Yt-dlp Version 2023.03.04
Samsung Galaxy Fold 4
Android Version 13
OneUI Version 5.1

**Comment by JunkFood02** [comment]
Did you enable Private directory?

**Comment by JunkFood02** [comment]
The app **does** scan the videos into the media library right after the download finishes, and i can see them in the image picker of Twitter, Telegram etc. I believe this is a OEM-related behavior or something else

**Comment by bibsp** [comment]
I noticed the same issue long ago but never reported because I also thought it's OEM related. Mine is Xiaomi.
This happens wint mkv. Seal always uses mkv container by default.
That's why I use custom commands. Mp4 videos are okay.

There is a hack. Install files app by Google. After downloading video, open files app. Then go to download section and then close it. After that the video will be shown in all other apps.

**Comment by tdadvocate** [comment]
> There is a hack. Install files app by Google. After downloading video, open files app. Then go to download section and then close it. After that the video will be shown in all other apps.

I will have to try that next time. What I normally do currently is just move the files to another folder using either Material Files or Simple Gallery Pro and they are instantly visible. I will have to test this on my Pixel 5a and LG Wing later to confirm if this is an OEM issue or actually an issue with Android 13 or something possibly.

**Comment by bibsp** [comment]
Yes. But even though the video has no subtitles, if this option is enabled seal still uses mkv.
If I'm not wrong yt-dlp can automatically choose required video extension according to the need.
Seal doesn't need to apply any logic here.

Although I have no issue with this. I prefer to use commands. Then it automatically chooses mp4/webm/mkv.

**Comment by bibsp** [comment]
And additionally if you download any video with sub from youtube avc+aac. -f 137+140
Yt+dlp uses mp4 with tx3g sub.
For vp9 it uses mkv with webvtt.
So basically yt-dlp can handle everything automatically.
No need to pass any extra commands here.

**Comment by Marco-9456** [comment]
1. Yt-dlp will automatically do this when the container does not support subtitle embedding, but for some weird reasons it does sometimes convert the subtitle file to suit the container, which is bad, especially if you download videos with .ass subtitles format, they usually have a lot of styles and fonts which will get ruined if they get converted.

2. Users aren't always downloading videos from Youtube, other streaming services like Crunchyroll use .ass subtitles format, and others use .srt, that's why JunkFood02 decided to remux-video to mkv when using embed-subs 
when embed-subs is enabled because it's a flexible container that supports a lot of subtitles formats unlike mp4 and other containers.

Take a look at https://github.com/JunkFood02/Seal/issues/102 for more details.

**Comment by tdadvocate** [comment]
I have mine set to automatically download as mp4 at best quality. So I don't know anything about the mkv issues. 

I have confirmed this issue also occurs on Android 12 on my LG Wing and also Android 13 on a Google Pixel 5a. So this 100% not an OEM issue. This is definitively an issue with the app itself.

**Comment by JunkFood02** [comment]
The real problem seems to be with your chosen download directory. As I've explained in #34, apps won't have permission to access the directories other than `Download/` and `Document/`. The special permission called `MANAGE_EXTERNAL_STORAGE` aka `All files access` might have some conflicts with the system media library. Can you change the download directory to `Downloads/` and try again?

**Comment by tdadvocate** [comment]
> The real problem seems to be with your chosen download directory. As I've explained in #34, apps won't have permission to access the directories other than `Download/` and `Document/`. The special permission called `MANAGE_EXTERNAL_STORAGE` aka `All files access`, which is only available on Android 12+, might have some conflicts with the system media library. Can you change the download directory to `Downloads/` and try again?

Android 13 prevents direct access to downloads. I left the directory to the default settings on my Wing and Pixel 5a. 

The Wing on 12 with default to Downloads will automatically make a Seal folder and has this same issue. I believe 12 also prevents this folder from being used but has a work around. I failed to check on this device though. 

The Pixel 5a on 13 I left on the default to Downloads and it reacts the same. It also won't let me choose strictly the Downloads because of the complete removal of this feature with 13.

Obviously the Fold 4 on 13 reacts identically to the Pixel 5a. 

Additionally, all of my tests have been done with just youtube videos through the share sheet within the youtube application. Actually clicking on the Seal option and not the Quick Download option. I tried both shorts and full videos with the same results.

**Comment by JunkFood02** [comment]
Oh I was meaning `Download/Seal`, but it's quite weird about the behaviors here. I haven't met this issue on any of my devices with Android 12+ (Pixel, Motorola and Xiaomi) Does performing a clean reinstall can do anything different here?

**Comment by tdadvocate** [comment]
I have confirmed now that the issue is 100% the Private Mode within the General settings for the download history. I believe this should not effect anything outside of Seal but instead it trickles down to the other applications. This seems to basically be using the private directories setting perhaps and completely wiping all history of downloads across the entire device. I would think this toggle would only disable the history section of this app rather than completely hiding the files from the device.

**Comment by bibsp** [comment]
> I have confirmed now that the issue is 100% the Private Mode within the General settings for the download history.

Yes, he is correct. I can fix the issue by disabling Private node.

**Comment by 386jdhJd882gHe** [comment]
I have the same problem. 

App version: 1.13.1 
Yt-dlp version: 2025.05.11.232911
