### ISSUE TITLE
Split files with chapters [Feature Request]

### ISSUE THREAD

**Issue by alidan** [JunkFood02/Seal#686]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I tend to find 'best of X month year' videos, for example https://www.youtube.com/watch?v=eKWhjZELdFw

they tend to have many songs, this one has 6 hours of them, and in the metadata they all have timestamps for the audio. 

now for some of these, finding the individual songs is ultimately a better way to do it, just downloading what I like, but for some of these, finding the individual songs is a nightmare if not impossible, for instance this one, https://www.youtube.com/watch?v=fFdeykHRqfs at the time I was trying to find split versions or original versions for download around 2 years ago, I was not able to find any, so the only way to get the files split was to do it manually or with a batch to ffmpeg.

I have no idea what's available to android or how useful this would be to everyone, but I would get alot of use out of this for music. 

### Describe the solution you'd like

If there is a way to do this kind of processing on android, would it be possible to comb the metadata and see if there are time stamps, and be able to split files with data that is either on the left or right of the time stamp to name the file, in a folder with the videos name, possibly with an option to have  thumbnail just copy and pasted over and over again for file names (the music players I use only show a thumbnail in this format)

if this is not implementable in this app, if there is another app which can do this, would it be possible to save the metadata in a way that the video/audio can be imported into the app to make the process easier? 

### Video link

https://www.youtube.com/watch?v=eKWhjZELdFw

for an example of whats normal

https://www.youtube.com/watch?v=fFdeykHRqfs

for an example of where this kind of feature is the only option.

**Comment by alidan** [comment]
ok after trying for a while to do this... would it be possible to add to the program as a simple option?

**Comment by JunkFood02** [comment]
added in [v1.10.0-beta.2](https://github.com/JunkFood02/Seal/releases/tag/v1.10.0-beta.2)
