### ISSUE TITLE
agge restriction from youtube [Feature Request]

### ISSUE THREAD

**Issue by amir385276** [JunkFood02/Seal#695]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

when i try to download some videos from youtube with age restriction - the seal can't download it

like this channel

weeklylowdowndigest

thanks

**Comment by Marco-9456** [comment]
> 

Settings --> Network --> Cookies --> Generat new cookies --> Paste this URL `https://m.youtube.com` --> Click Generat new cookies --> login using your  Youtube Account --> Done --> Confirm --> Enable Use cookies --> try to download again.

**Comment by amir385276** [comment]
Hi again
thanks Marco-9456

the age restriction settings working fine and downloading the videos

but maybe you should compile new ver for downloading queue or downloading some videos in batch mode

thanks a lot

**Comment by amir385276** [comment]
the issue is solved
