### ISSUE TITLE
[Feature Request] Select which video to download from tweets with multiple videos

### ISSUE THREAD

**Issue by teohhanhui** [JunkFood02/Seal#697]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Additional context

See https://github.com/yt-dlp/yt-dlp/issues/5147

**Comment by JunkFood02** [comment]
Enable Download playlist and try again
