### ISSUE TITLE
unable to download videos from twitter

### ISSUE THREAD

**Issue by sage9499** [JunkFood02/Seal#701]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

not able to download video when i copy paste or share links to seal

### To Reproduce

twitter video
share to seal
click download
error

### Error reports

App version: 1.9.0 (10900)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://twitter.com/astrid7890/status/1645016286227996672?t=OCRxf1fHph6vpaigq5i9dg&s=09
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
ERROR: [twitter] 1643909644987842561: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.9.0 (10900)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by mirek190** [comment]
Yep ..the same problem

**Comment by sage9499** [comment]
> Yep ..had same problem
> 
> You have to use cookies configuration in the app. You have to login to your account then you can easily download from Twitter .
> 
> The application should inform about it at first run. Like SOME WEBSITES USES COOKIES AND YOU HAVE TO LOG IN.
> 
> Or during use first time such links from Twitter or other websites which requires it and should redirect automatically.

hey thank you, it helped

**Comment by Marco-9456** [comment]
Great, close the issue as completed, please.

**Comment by sage9499** [comment]
solved

**Comment by jabed11** [comment]
I'm still facing "couldn't fetch video info"

**Comment by TheBarbiter1** [comment]
> Yep ..had same problem 
> 
> You have to use cookies configuration in the app. You have to login to your account then you can easily download from Twitter .
> 
> The application should inform about it at first  run.
> Like 
> SOME WEBSITES USES COOKIES AND YOU HAVE TO LOG IN.
> 
> Or during use first time such links from Twitter or other websites which requires it and should redirect automatically.
> 

How do I do that?

**Comment by Marco-9456** [comment]
> How do I do that?


1. 🔧 Go to "Settings"

2. 🌐 Click "Network"

3. 🍪 Click "Cookies"

4. 🔑 Click "Generate new cookies"

5. 🔗 Type or paste the URL of the website you want to access with the new cookies
>[!Note]
> In your case it's `twitter.com`, the `https://` part is added by default.

6. 🍪 Click "Generate new cookies"

7. 👤 Login to your account on the website using your login credentials

8. ✔️ Click "Done" to finish the process.

9. ✅ Click on "Confirm"
