### ISSUE TITLE
Lost Connecting

### ISSUE THREAD

**Issue by amir385276** [JunkFood02/Seal#704]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Hi guys
I have some issues with seal
1- when my connection lost then the seal have no queue on it
2- can you create a (Pause) button 
3- sometimes aria2c losted and show the error 19

thanks

**Comment by Marco-9456** [comment]
Duplicated of:

#323 

#324 
 
#475 

>3- sometimes aria2c losted and show the error 19

If this happens just pressthe download button again, Seal will then continue from where it left.

>**Note**
Close the issue
