### ISSUE TITLE
Cookies options didn’t work on HarmonyOS devices.

### ISSUE THREAD

**Issue by ewwwda** [JunkFood02/Seal#712]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

All sites are unavailable, even though I have login my accounts, like twitter, Instagram, but nothing happens. Maybe it’s related to WebView? HarmonyOS only uses Huawei WebView and not Android WebView.

### Error reports

App version: 1.9.1 (10910)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://www.instagram.com/reel/CrHcdqzvASH/?utm_source=ig_web_copy_link
WARNING: [Instagram] CrHcdqzvASH: General metadata extraction failed (some metadata might be missing).
WARNING: [Instagram] unable to extract shared data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [Instagram] Main webpage is locked behind the login page. Retrying with embed webpage (some metadata might be missing).
WARNING: [Instagram] unable to extract additional data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CrHcdqzvASH: Requested content is not available, rate-limit reached or login required. Use --cookies, --cookies-from-browser, --username and --password, or --netrc (instagram) to provide account credentials

### Device info

App version: 1.9.1 (10910)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by sharunkumar** [comment]
Does this not work on Samsung either?

**Comment by sharunkumar** [comment]
> Expected behavior. Huawei devices restricts reading cookies from their webview

Is there a way to supply a text file of cookies rather having to depend on web view?

**Comment by Marco-9456** [comment]
> > Expected behavior. Huawei devices restrict reading cookies from their webview
> 
> Is there a way to supply a text file of cookies rather than having to depend on web view?

This was actually what the app did in older versions, but it was replaced with the current method since a LOT of users didn't get the hang of it, you can try passing the cookies file path using custom commands.

**Comment by sharunkumar** [comment]
> > > Expected behavior. Huawei devices restrict reading cookies from their webview
> > 
> > 
> > Is there a way to supply a text file of cookies rather than having to depend on web view?
> 
> This was actually what the app did in older versions, but it was replaced with the current method since a LOT of users didn't get the hang of it, you can try passing the cookies file path using custom commands.
> 
> And yes it works on samsung phones,

Not sure why it's not working, I've logged into the web view but when I hit download, I get an error message saying 404 on Twitter. But I tried it on desktop with yt-dlp with the cookies and I was able to get it downloaded

**Comment by Marco-9456** [comment]
Please join the [Telegram Group](https://t.me/seal_app_group)  to continue this conversation, I'll help you there.

**Comment by JunkFood02** [comment]
@sharunkumar Please file a new issue
