### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by DarkSuffer** [JunkFood02/Seal#715]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

The app is well made and created but there's 1 more missing feature.
Mp3/mp4 cutter-trimmer

### Describe the solution you'd like

Mp3/mp4 cutter-trimmer can edit your music or cut/trim it to make an short music for alarm, etc..

Examples of it: FULL FEATURE FROM mp3cut.net
![Screenshot_20230421_224951_Chrome](https://user-images.githubusercontent.com/102059805/233667280-63565160-84f7-4a98-8ba7-f733c76ea03a.jpg)
![Screenshot_20230421_224808_Chrome](https://user-images.githubusercontent.com/102059805/233667291-a7c0f37e-a079-4b1c-b257-7e8d7ef6cca3.jpg)
![Screenshot_20230421_224419_Chrome](https://user-images.githubusercontent.com/102059805/233667313-bae19a57-1bea-4939-bf90-e8b4dc176910.jpg)
![Screenshot_20230421_224356_Chrome](https://user-images.githubusercontent.com/102059805/233667323-a27b23a0-bc49-44c7-911f-24c6761c5de2.jpg)
![Screenshot_20230421_224313_Chrome](https://user-images.githubusercontent.com/102059805/233667327-74f3f1a5-e279-4ac2-a57b-e316522d6b39.jpg)

- Please add more file type support like ogg, mvv. Etc...

**Comment by Marco-9456** [comment]
Go to settings --> Format --> Enable Clip video.
Now when you want to download an audio or video file you'll see a ✂️ icon in the format selection menu there you can download a part of your selection.

>**Note**
The feature is still experimental and it may not clip the audio/video correctly, 
Please close the issue as completed if that answered your qualifications.
