### ISSUE TITLE
YTDLnis https://github.com/deniscerri/ytdlnis

### ISSUE THREAD

**Issue by Superman1974** [JunkFood02/Seal#716]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by deniscerri** [comment]
@Superman1974 There is no reason to do this whatsoever. Please be respectful as both projects are open source and helping people. Enjoy both apps. Thank you.
