### ISSUE TITLE
[ Improvement Request ] UI/UX Improvements

### ISSUE THREAD

**Issue by s4velyeva** [JunkFood02/Seal#72]
Hello again.
----------------

I've thought about UI/UX design, and made this.
It'll be better if app will have a little bigger and more rounded interface.

I've separated thumbnail and title sections to make separated floating cards, and also moved buttons to the center, also as card.
And one small improvement I see - make progress bar floating, like on picture.

<img src=https://user-images.githubusercontent.com/93286636/181801066-631bf23b-bd66-47e6-8284-408392a59daa.png width=40%>

Hope that helps.

Forever your's
    vicsave XOXO :)

**Comment by Marco-9456** [comment]
> ## Hello again.
> I've thought about UI/UX design, and made this. It'll be better if app will have a little bigger and more rounded interface.
> 
> I've separated thumbnail and title sections to make separated floating cards, and also moved buttons to the center, also as card. And one small improvement I see - make progress bar floating, like on picture.
> 
> <img alt="" width="40%" src="https://user-images.githubusercontent.com/93286636/181801066-631bf23b-bd66-47e6-8284-408392a59daa.png">
> 
> Hope that helps.
> 
> Forever your's vicsave XOXO :)

Good suggestion, 
 I think it would be also great if the Thumbnail show up before clicking on the download button
