### ISSUE TITLE
Videos don't play in discord

### ISSUE THREAD

**Issue by embyveddii** [JunkFood02/Seal#723]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I'm not sure what the issue is as they download as MP4s. I download a TikTok and it plays normally but when sending them on discord they don't play and become a downloadable file embed. I know this isn't a discord issue, as downloading the same tiktoks from in app and other downloaders works totally fine. I assume its something in the mp4 that breaks

### To Reproduce

1. Download any tiktok with Seal
2. Send that MP4 in Discord
3. Try to play the video (it won't play)

### Error reports

N/A. there is no error.

### Screenshots & Screen Records

https://files.catbox.moe/3tvola.mp4
screen recording just to show that when I download through seal, it breaks. when I download through a different site it plays fine.

### Device info

App version: 1.9.1 (10910)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

### Additional context

I still don't really know the issue and I'm not very knowledgeable on video files but I assume it's something encoded in the mp4 that breaks in discord? Every other downloader I use seems to work fine in discord but Seal is just better made and more convenient so I was hoping to use it.

**Comment by JunkFood02** [comment]
If the video is able to be played in your local video player, then the issue is likely about the codec of the video you've downloaded which is not supported by discord. yt-dlp(Seal) directly download the original video without any conversion while other tool might apply a force re-encoding on every video for better compatiblities

**Comment by embyveddii** [comment]
ah that would make sense. Is there anything I could do to automatically do this in seal or not? It's a bit annoying because I download tons of tiktoks to send in discord and Seal was a convenient way to not have them overflow my camera folder

**Comment by zero5enpai** [comment]
`--recode-video mov`
does the job when used as custom command

**Comment by robertsspaceindustries** [comment]
Missing thumbnail?
