### ISSUE TITLE
Privacy options not working

### ISSUE THREAD

**Issue by akashpal-21** [JunkFood02/Seal#725]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The options under Privacy titled "Private Mode" + "Disable Preview" do nothing, 

### To Reproduce

Go to settings > General > Privacy. Turn options On,
Behaviour unchanged. Video history is still stored under "Downloads"

Expected behaviour: No Download History.

### Error reports

N/A

### Device info

1.9.1-(F-Droid)
Yt-dlp version: 2023.03.04
Android 12

**Comment by JunkFood02** [comment]
options don't affect existing download history

**Comment by akashpal-21** [comment]
I have worded it wrongly it seems, Options do not hide subsequent downloads. It is obvious previous downloads wont be hidden that have been done before enabling the option. I am sorry, but I meant to say downloads after enabling the option
