### ISSUE TITLE
Reporting a bug related to downloading a reel / video from instagram

### ISSUE THREAD

**Issue by maulikherma** [JunkFood02/Seal#727]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Unable to download video/reel from instagram.

### To Reproduce

Open instagram
Go to reels
Open / click a reel
Click send
Click share
Select seal app
Click download
It shows error.

### Error reports

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://www.instagram.com/reel/CpA0TV6LktN/?igshid=MDJmNzVkMjY=
WARNING: [Instagram] CpA0TV6LktN: General metadata extraction failed (some metadata might be missing).
ERROR: [Instagram] CpA0TV6LktN: Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))

### Screenshots & Screen Records

![Screenshot_20230427-211816_Seal](https://user-images.githubusercontent.com/131992634/234919316-5b048ae5-99ae-4ce7-871c-a1f81f0f833b.jpg)

### Device info

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

### Additional context

Unable to download reels from instagram

**Comment by JunkFood02** [comment]
#733
