### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Tigger-S** [JunkFood02/Seal#728]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I can't download video with sound on reddit links, it just gives me audio, or video, not both, please check it out, and if you can make it possible to get various quality of video like redditsave.com it'd be awesome 

### Describe the solution you'd like

Enable video with sound for reddit links, preferably with various qualities like redditsave.com 

### Video link

https://www.reddit.com/r/SipsTea/comments/13179vm/is_that_a_yellow_flag/

**Comment by Tigger-S** [comment]
Wait 👀 closed already? Lol

**Comment by JunkFood02** [comment]
if you didn't modify your settings, the "suggested" format is already what you need. Or you can scroll down to the bottom of the format page for more info
