### ISSUE TITLE
Twitter downloads from your app come in weird format 

### ISSUE THREAD

**Issue by Tigger-S** [JunkFood02/Seal#729]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I download a twitter video from your app, I can play it yes but I can't skip on it like skip to 1 minute for example and I cannot send the video through any social media because it says "unsupported format" 

### To Reproduce

Download a twitter video, try and toggle through the video to any point in time, try to send the video through WhatsApp or many other social medias, it will say file format unsupported 

### Error reports

Uhhh idk 💀 

### Device info

App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by Marco-9456** [comment]
A user reported the same issue a couple of months ago in the telegram group, we unfortunately cannot fix this since it's an external issue.

Possible solutions:
1. If the link provides different formats You can try to download the video in another format other than the suggested one.

2. Use the custom command feature and reencode the video.

**Comment by JunkFood02** [comment]
#1133
