### ISSUE TITLE
[Feature Request] Ability to install video from specific timestamp

### ISSUE THREAD

**Issue by Rahuletto** [JunkFood02/Seal#732]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

Instead of installing the whole video, you can provide an option asking from and to timestamp inputs to install the video under the condition. This can be very useful. (If it's not possible, atleast you can try to implement save that specific time of video in gallery and not the whole video)

**Comment by JunkFood02** [comment]
Settings - Format - Clip video

**Comment by Rahuletto** [comment]
Oh we have that already ? Im sorry about that
