### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by krishana9161** [JunkFood02/Seal#734]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/q-2PaG_mQ7k
ERROR: 
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries

### Error reports

App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/q-2PaG_mQ7k
ERROR: 
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries

### Screenshots & Screen Records

![Screenshot_2023-04-30-06-31-45-11](https://user-images.githubusercontent.com/121737546/235330532-fbc84f63-3b2a-4c6f-8ef3-885cc8dc1d33.jpg)

### Additional context

i want to download this video no application can download it

**Comment by Marco-9456** [comment]
That seems like a you problem, I successfully downloaded the video without any issues, check your internet connection.

**Comment by krishana9161** [comment]
Download another video. but unable to download this video
