### ISSUE TITLE
clip video option in quick download 

### ISSUE THREAD

**Issue by Turhvjbufv** [JunkFood02/Seal#735]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There is no clip video option in quick download 

### Describe the solution you'd like

I know there is already clip video option but it's only if go to into the app I would like it to be an option also for quick download

**Comment by Marco-9456** [comment]
Quick download should be quick, if you don't want to open the app to clip the video, you have the option in YouTube under some videos if the button is not visible then unfortunately, you have to open the app to do it.
