### ISSUE TITLE
[Improvement Request] Show file size for every downloadable resolution

### ISSUE THREAD

**Issue by AxeldeWater** [JunkFood02/Seal#74]
I was actually pretty amazed opening the app, but one big feature that I really need that isn't there is the file size of the file you are trying to download. For instance, sometimes there is a file size upload limit where I would like to upload the video, so before uploading I want to see what resolution to download the video at to be below that limit. So for instance: 
"Original (100MB)
1080p (100MB)
720p (50MB)
480p (12MB)"

Maybe it's even possible to add an option to choose a maximum file size, instead of just video format and video resolution.

**Comment by JunkFood02** [comment]
The latter idea is easy to implement, but it may be complicated to fit into the current workflow. Whatever, I will take this feature request into account.

Seal only fetches information of videos after a user starts a download task. And many websites separate audio streams from video streams, so it's hard to get the exact file size for a resolution.

**Comment by JunkFood02** [comment]
> Maybe it's even possible to add an option to choose a maximum file size, instead of just video format and video resolution.

Added in v1.2.0-beta.1

**Comment by JunkFood02** [comment]
![Screenshot_20221210-135724](https://user-images.githubusercontent.com/69683722/206831927-c600b40b-d634-4ff8-9873-e533017eb8a9.png)

**Comment by BobbyESP** [comment]
Bro, that's so f*** amazing. Nice job!
