### ISSUE TITLE
  ERROR: aria2c exited with code 22

### ISSUE THREAD

**Issue by Pintuvictus** [JunkFood02/Seal#742]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Can't download some reels from instagram it just shows error note:- I have permission of owner to use there content kindly helo

### Error reports

ERROR: aria2c exited with code 22

**Comment by JunkFood02** [comment]
turn off aria2c

**Comment by Pintuvictus** [comment]
turn off aria2c I did this but now different this pop-up

ERROR: unable to download video data: HTTP Error 410: Gone

**Comment by JunkFood02** [comment]
#733

**Comment by Pintuvictus** [comment]
App version: 1.9.1-(F-Droid) (10914)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04
