### ISSUE TITLE
Korean Language Translation Block.

### ISSUE THREAD

**Issue by root-kernelhacker** [JunkFood02/Seal#744]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Koream language translation off !

plz.. Koream language translation on !

### Error reports

Koream language translation off !

plz.. Koream language translation on !

**Comment by JunkFood02** [comment]
The project only has 25% of the strings translated to Korean currently, we'll add the language in the preference page when there're more than 40% of them translated

**Comment by JunkFood02** [comment]
If you wants to help translate this app to your language, please sign up on Hosted Weblate and [contribute your translations](https://hosted.weblate.org/projects/seal/strings/) there

**Comment by root-kernelhacker** [comment]
thank you for the mail  I tried to contribute to the Korean translation, but it was stopped so I couldn't translate it.  Please tell me how.
________________________________

**Comment by root-kernelhacker** [comment]
I am planning to finish the Korean translation today.  After the translation is finished, apply it quickly.  please.

**Comment by root-kernelhacker** [comment]
I am planning to finish the Korean translation today.  After the translation is finished, apply it quickly.  please.

**Comment by root-kernelhacker** [comment]
> If you want to help translate this app to your language, please sign up on Hosted Weblate and [contribute your translations](https://hosted.weblate.org/projects/seal/strings/) there

--------


2023-5-8

Korean translation complete!

Please build with Korean language!

**Comment by JunkFood02** [comment]
If you system language is Korean, install this [CI build](https://github.com/JunkFood02/Seal/actions/runs/4912729679) and select **Follow system** in language settings.
If you're not using Korean in your device, please wait for v1.10.0-beta.2

**Comment by root-kernelhacker** [comment]
Install CI build and wait for the beta 2 version to come out rather than rebuilding!  thank you !
