### ISSUE TITLE
[Feature Request] hide video formats when both "save as audio" and "format selection" options is selected

### ISSUE THREAD

**Issue by soredake** [JunkFood02/Seal#750]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [x] This feature is available for most websites, not only the video platform I use.
- [x] This feature is suitable for a large variety of videos.
- [x] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

It makes little sense to show video formats if you enabled "save as audio" option.

### Describe the solution you'd like

Hiding video format when both this options is enabled.

**Comment by JunkFood02** [comment]
Fair enough. And we should hide the video only formats but preserve video formats which also contain audio because we can extract audio tract from them
