### ISSUE TITLE
Unable to download with latest update

### ISSUE THREAD

**Issue by mohanb86** [JunkFood02/Seal#751]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When I copy a link from Instagram and try to download it, I am getting below error. 

### To Reproduce

1. Copy a link of Instagram reel
2. Paste it in the link section of SEAL
3. Press download.
4. We get this error before going to next screen

### Error reports

URL: https://www.instagram.com/reel/CpjZOSejxq4/?igshid=NTc4MTIwNjQ2YQ==
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CpjZOSejxq4: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_2023-05-09-07-20-01-024_com junkfood seal](https://user-images.githubusercontent.com/58220660/236973734-9551b131-ff17-47c3-a8e7-5301ec4cf2ba.jpg)

### Device info

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by JunkFood02** [comment]
#733
