### ISSUE TITLE
[Feature Request] UI...

### ISSUE THREAD

**Issue by root-kernelhacker** [JunkFood02/Seal#755]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Among the various de-downloaders, I couldn't find one that downloads as well as seal ^^.  Thank you.  However, it would be nice if you could make one download UI concise and intuitive by referring to powertube.  Also, the seal is overall large even though the apk size is arm64 (v8a).  Finally, the videos you downloaded or paused on the main screen of seal are still there.  It remains even after closing and reopening seal.  After deleting it from recent apps, you have to run the seal again to disappear.  It would be nice if there was a button on the main screen to stop the download or delete the list after completion.  (For reference, the Korean translation is 100% complete! ^^)

**Comment by Marco-9456** [comment]
Create for each request a new issue + follow the checklist

**Comment by blackholeearth** [comment]
1) the videos you downloaded or paused on the main screen of seal are still there. 
It remains even after closing and reopening seal. After deleting it from recent apps, you have to run the seal again to disappear.

 2) Need a button on the main screen to stop the download or delete the list after completion. 
Button: __Clear completed__  


3) make one download UI concise and intuitive by referring to powertube.

 4) the seal is overall large even though the apk size is arm64 (v8a).
