### ISSUE TITLE
Download issue 

### ISSUE THREAD

**Issue by Doa890** [JunkFood02/Seal#757]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

WARNING:[Instagram] Cr5H-SUsauy:
General metadata extraction failed
(some metadata might be missing).
WARNING: [Instagram] unable to
extract shared data; please report
this issue on https://github.com/yt
-dIp/yt-dlp/issues?q=, filling out the appropriate issue template. Confirm you are on the latest version using
yt-dlp -U....

### Screenshots & Screen Records

![Screenshot_2023-05-13-01-05-12-293_com junkfood seal](https://github.com/JunkFood02/Seal/assets/133416965/a19a7b41-c957-4885-be80-9bc76a860617)

**Comment by JunkFood02** [comment]
#733
