### ISSUE TITLE
When downloading while playing a video, YouTube changes to pip.

### ISSUE THREAD

**Issue by root-kernelhacker** [JunkFood02/Seal#758]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When downloading while playing a video, YouTube changes to pip !

I don't know if it's a problem with the YouTube app, but when a YouTube video is playing, pressing the Share or  button (Revance Extend) to download it will enter pip mode.  When video playback is paused and downloaded, a seal appears on the YouTube screen.

### Error reports

When downloading while playing a video, YouTube changes to pip !

I don't know if it's a problem with the YouTube app, but when a YouTube video is playing, pressing the Share or  button (Revance Extend) to download it will enter pip mode.  When video playback is paused and downloaded, a seal appears on the YouTube screen.

**Comment by Marco-9456** [comment]
This is an external issue which has been  already reported, check issue #506 for more info.
And close the issue
