### ISSUE TITLE
Fetch Video Error

### ISSUE THREAD

**Issue by Awsssm** [JunkFood02/Seal#759]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

App version: 1.10.0-beta.1 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/zQDAi8tI-cU
WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out>
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (1/3)...
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (2/3)...
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (3/3)...
WARNING: [youtube] Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out>
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (1/3)...
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (2/3)...
WARNING: [youtube] <urlopen error _ssl.c:1091: The handshake operation timed out>. Retrying (3/3)...
WARNING: [youtube] Unable to download API page: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))
ERROR: [youtube] zQDAi8tI-cU: Unable to download API page: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))

### Device info

App version: 1.10.0-beta.1 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by Marco-9456** [comment]
Use a stable internet connection.

**Comment by Awsssm** [comment]
> Use a stable internet connection.

It's working fine last week but now I'm facing this issue.  Internet is working fine on every apps.

**Comment by Awsssm** [comment]
![Uploading Screenshot_20230513-174901_Seal.jpg…]()
