### ISSUE TITLE
Can't download Instagram media

### ISSUE THREAD

**Issue by Kpoif** [JunkFood02/Seal#761]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

The video downloader feature of the application is failing to download videos from Instagram. Despite attempting to download various videos from different Instagram profiles, the application consistently fails to initiate the download process. Upon pasting the Instagram video URL into the video downloader application and clicking on the "Download" button, the application fails to initiate the download process. A error message is displayed, and the video is not saved to the device.

### To Reproduce

1.Launch the Seal app.
2.Navigate to the Instagram video you wish to download.
3.Copy the URL of the Instagram video.
4.Paste the URL into the designated field within the video downloader application.
5.Click on the "Download" button.

### Error reports

URL: 
WARNING: [Instagram] CqVwa39jjs9: No csrf token set by Instagram API
WARNING: [Instagram] CqVwa39jjs9: General metadata extraction failed (some metadata might be missing).
ERROR: [Instagram] CqVwa39jjs9: Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))

### Device info

App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

### Additional context

1. The issue is not limited to a specific Instagram profile or video. Multiple videos from different profiles have been tested, all yielding the same result.
2. The video downloader application is up to date, and no recent changes or updates have been made to the application.
3. The device being used to test the application is connected to a stable internet connection throughout the testing process.
4. Clearing the application cache and restarting the device did not resolve the issue.

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/733
