### ISSUE TITLE
Instagram bug

### ISSUE THREAD

**Issue by b-hulk02** [JunkFood02/Seal#764]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I can't download, videos😞

### To Reproduce

I can't describe it

### Error reports

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: 
WARNING: [Instagram] CrTbbUrNWrU: No csrf token set by Instagram API
WARNING: [Instagram] CrTbbUrNWrU: General metadata extraction failed (some metadata might be missing).
ERROR: [Instagram] CrTbbUrNWrU: Unable to download webpage: <urlopen error _ssl.c:1091: The handshake operation timed out> (caused by URLError(timeout('_ssl.c:1091: The handshake operation timed out')))

### Screenshots & Screen Records

![Screenshot_2023-05-15-01-16-40-858_com junkfood seal](https://github.com/JunkFood02/Seal/assets/133603789/b1bd9686-b7ed-4de3-9b16-9c071390547b)

### Device info

App version: 1.9.2 (10920)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by JunkFood02** [comment]
#733
