### ISSUE TITLE
Cobalt backend

### ISSUE THREAD

**Issue by ThatOneCalculator** [JunkFood02/Seal#769]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

ytdlp doesn't support a lot of platforms, like Instagram Reels, TikTok, Vimeo, Twitter Spaces, etc, but Cobalt (https://github.com/wukko/cobalt) does. It has a public facing API and can also be self hosted. 

### Describe the solution you'd like

The option to use Cobalt as a backend instead of ytdlp. 

### Additional context

https://co.wukko.me

**Comment by JunkFood02** [comment]
You might want to take a look at [a full list of sites supported by yt-dlp](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md)

**Comment by ThatOneCalculator** [comment]
- Lots of TikTok is broken
- No watermark removal for TikTok
- No Instagram reels
- No proper Vimeo

**Comment by JunkFood02** [comment]
if you find yt-dlp is broken on certain sites, file an bug report or subscribe to the respective issues for possible fixes. As for Seal, we do want to keep things neat and running locally instead of depending on third-party services 

https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md
> Seal is and will remain a simple GUI for yt-dlp, providing most of the functionality of yt-dlp as is, without modifications. Thus, we'll not take requests for features that yt-dlp does not support.
