### ISSUE TITLE
能否支持使用外置存储 (USB / SD) 做为下载路径？

### ISSUE THREAD

**Issue by TPAXcc** [JunkFood02/Seal#79]

**Comment by Marco-9456** [comment]
> _No description provided._

https://github.com/JunkFood02/Seal/issues/34#issuecomment-1169925592

**Comment by Marco-9456** [comment]
> _No description provided._

https://github.com/JunkFood02/Seal/issues/34

**Comment by JunkFood02** [comment]
#25
