### ISSUE TITLE
[Feature Request]  make title longer (2 or 3 lines ) or slideable in playlist download  . Cant locate exact ep of a series

### ISSUE THREAD

**Issue by blackholeearth** [JunkFood02/Seal#798]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

in download playlist mode. 
İ am downloading free tv show from korean .İt has 50 ep.
İ want to  download  ep 15 16 .
but title is to long.  its trimmed. 
Also videos in list are not ordered by ep no.
 its scrambled.
cant locate  15 16  eps.

Example video title: 
my father is long long text  text ep 17

İts trimmed to this:  
my father is long..

### Describe the solution you'd like

Request::
Can you make title longer (2 or 3 lines ) 

or slideable by touch-drag

Or a button [...] To expand collapse title of single entry

So we can see the ep nos.
 

### Video link

https://youtube.com/playlist?list=PLrVZ06RZCdNgAJetDZpgcMzL8IT77FzAh

### Additional context

![Screenshot_20230527-031307_Seal](https://github.com/JunkFood02/Seal/assets/7512105/0d3faff4-775a-4fa3-8d77-219e6b9bf4ce)

**Comment by JunkFood02** [comment]
Update to v1.10.0-beta.3, you can long-press the video to see the full title
