### ISSUE TITLE
only 1080p download

### ISSUE THREAD

**Issue by root-kernelhacker** [JunkFood02/Seal#814]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

When downloading "https://youtu.be/qRUn7INgRtg" video and other videos in Beta 2, there is a problem that it is fixed to 1080p.  Even after adjusting all the settings, when I download it, it downloads in 1080p.  In the YTDLnis app that uses the same engine, it is not an engine problem because it downloads well at the specified resolution.

-------

The official release version is also the same, but when I tested it, it was confirmed that the download was fixed to 1080p in the following situation.  

1. If you set the video format as default, it will be downloaded at the specified resolution when downloading, but if you set the video format to MP4, depending on the video, it is not downloaded at the resolution you specified, but only 1080p.

2. Assuming the cause, looking at the YTDLnis app using the same engine, the video I illustrated supports all resolutions in the webm format, but the MP4 format seems to support only some resolutions (216p. 1080p, etc.).  Therefore, if I designate and download as MP4 at 1440p in SEAL, it will be downloaded as MP4 at 1080p without settings and negotiations.

3. 3. When SEAL pops up a window when downloading, it is not a method of loading information about the video in advance, but a method applied after download settings, so it seems to show a difference between what I set and what is actually applied.

4. Mentioning the YTDLnis app is also because this app is inspired by SEAL and PowerDL, and although the download setting window appears a little late due to processing image information when downloading, it is an example because you can select and download the correct image information no see.

5. The same problem in full release, beta 1, beta 2

6. Finally, in the menu to update yt-dlp, even though the current yt-dlp is version 2023.5.27, SEAL says that the previous version, March version, is the latest version and is not updated.

**Comment by JunkFood02** [comment]
When there's no MP4 in higher resolution it will download the highest resolution with MP4 format available. It's an intended behavior and I didn't see anything wrong here

> the current yt-dlp is version 2023.5.27
Long-press the yt-dlp version and switch to nightly build
