### ISSUE TITLE
[Improvement Request]

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#83]
Add a function to highlight multiple downloads so users can delete or remove multiple files at once.

Maybe something like this 
![SmartSelect_20220731-151345_Seal](https://user-images.githubusercontent.com/41828058/182028842-4310877b-ec5e-49c0-b3e8-e90a34e15f34.jpg)

**Comment by AxeldeWater** [comment]
I think this would work best with a "long tap" function to highlight each video, and show a little button with a bin in the corner below in the right corner. Then when you tap on this button it opens the window you suggested.

**Comment by JunkFood02** [comment]
Added in v1.2.0-beta.2
