### ISSUE TITLE
Problems unsolved in Seal app

### ISSUE THREAD

**Issue by Manowar79** [JunkFood02/Seal#832]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Can't download videos.

### To Reproduce

![Screenshot_20230530-081056](https://github.com/JunkFood02/Seal/assets/123826518/de1f393b-95e9-4f62-b7a8-865d81918c94)

### Error reports

App version: 1.9.2 (10920)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: 
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
ERROR: [twitter] 1621186862168637448: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_20230530-081056](https://github.com/JunkFood02/Seal/assets/123826518/25a9dd9b-0e1c-4903-931c-76d61353f38a)

### Device info

App version: 1.9.2 (10920)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

### Additional context

Before any kind of video can be downloaded without restriction. But now is impossible. Why?

**Comment by JunkFood02** [comment]
Follow instruction in #733
