### ISSUE TITLE
Download queue

### ISSUE THREAD

**Issue by Innocentzero0** [JunkFood02/Seal#845]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I'm always frustrated when my network fluctuates and the download cancels and I can't view a download queue to resume the specific video that failed to download. It really becomes a big issue when I'm downloading a whole playlist but some videos fail. When that happens I have to start comparing what has already downloaded do what is in the playlist to filter out what I have and don't have 

### Describe the solution you'd like

I would like the app to have a download page listing the completed downloads, the ongoing downloads, the pending downloads and the failed downloads. So i can accurately keep track of what has downloaded and what failed, resume failed download, pause downloads to resume later and check on download progress

### Video link

Any large youtube playlist 

### Additional context

![20230531_173943](https://github.com/JunkFood02/Seal/assets/106754422/dae9d54a-7873-4169-96bf-dceea59361d1)
Something like this

**Comment by Marco-9456** [comment]
Duplicated of:

#323 

#324 
 
#475 

#704


>**Note**
Close the issue
