### ISSUE TITLE
[Feature Request] Choose audio track 

### ISSUE THREAD

**Issue by Urbexed** [JunkFood02/Seal#847]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

For a while now, youtube channels have been able to post videos with several audio tracks, unfortunately you can't choose which one you want

### Describe the solution you'd like

Add a way to be able to choose the audio track from the those available

And maybe choose preferred language for multitrack video in settings 

### Video link

https://youtu.be/FM7Z-Xq8Drc

**Comment by Marco-9456** [comment]
Use the format selection option:


https://github.com/JunkFood02/Seal/assets/41828058/ea511f4e-0cbd-4121-90fd-3f8d42068a70

**Comment by Urbexed** [comment]
Oh Sorry I didn't know we could do that already, thanks for your answer
