### ISSUE TITLE
Twitter no working

### ISSUE THREAD

**Issue by Thevoid30** [JunkFood02/Seal#851]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Not all vide are downloadedNot all videos are downloaded 

### Error reports

URL: 
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
ERROR: [twitter] 1662999607998070784: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Device info

App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by sgreenden** [comment]
If it was a NSFW video, it is because you need to give yt-dlp the --cookies-from-browser option to see nsfw tweets, but I don't know how to do this on mobile

**Comment by Marco-9456** [comment]
> If it was an NSFW video, it is because you need to give yt-dlp the --cookies-from-browser option to see NSFW tweets, but I don't know how to do this on mobile

Seal has a webview built in where you can login with your account and pass the cookies to the app with just a few clicks:


`Settings-->` `Network`--> `Cookies` --> `Generat new cookies`--> `Type/Paste the website URL`--> `Generat new cookies`--> `Login`--> `Click on done`--> `Confirm`--> `enable Use Cookies`.
