### ISSUE TITLE
Feature Request: Downloading Audio/Video files locally

### ISSUE THREAD

**Issue by im-coder-lg** [JunkFood02/Seal#860]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I use Seal to get some tunes for alarms, etc. Now, my phone needs the MP3 file for it to work. I try sharing the downloaded file through many mediums, like mail, WhatsApp, etc. But it doesn't work. 

### Describe the solution you'd like

An option to download the audio/video file locally for usage as alarms, ringtones, clip edits, etc. There are a few of us who use YouTube to get the tunes on the phone. 

### Video link

Well, any link will work

### Additional context

None, but it could be a very useful feature.

**Comment by Marco-9456** [comment]
Enable these 2 options in the format settings:

![Screenshot_20230605_225949_Seal](https://github.com/JunkFood02/Seal/assets/41828058/4866489e-ce7e-49e0-ad2e-96217e5cbe25)

**Comment by Marco-9456** [comment]
> I did that, but still can't download the file.

Share a link.

**Comment by im-coder-lg** [comment]
Well, it's a rickroll which I wanna use as an alarm rone, but while Seal downloads the audio file, it can't share said audio file.

**Comment by Marco-9456** [comment]
> @Marco-9456 it still doesn't work, is this a bug? I use Android 9 by the way.

You didn't provide any screen shots or recordings nor did you give a link to test, do what i did in the following Screenrecord and it should work:

https://github.com/JunkFood02/Seal/assets/41828058/0d5f2eff-3c1f-4519-99d5-f59dbbc0cc06

**Comment by im-coder-lg** [comment]
It works now,but not the way you told me. Seems like my phone is locked to OPUS and MP4, so I downloaded and got the MP3 file from `Internal Storage/Seal/Audio`. Thanks a lot, I followed your download method which worked great. This seems to be a glitch with my phone's Android version, but you gave the download method. I'll follow that from now, and thanks a lot again! :)
