### ISSUE TITLE
I cannot download video's From Youtube & bilibili

### ISSUE THREAD

**Issue by chixteryaki** [JunkFood02/Seal#861]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When im Attempting to download a video from Youtube or Bililibili or Instagram Etc. It wont work and other users have the same experince to. Do you have a newer version of the app Because all the version i am seeing is from '27 April',I tried F-droid Github But it still does not want to download, i tought it was the problem of the wifi but my wifi is 200MBps i dont get it im the only one using it,Then ive been waiting for 2 months already :/
(Please solve this issue/bug i want to download videos now)

### Error reports

URL: https://www.bilibili.tv/en/video/2044322523
WARNING: Extractor failed to obtain "title". Creating a generic title instead
ERROR: unable to download video data: HTTP Error 403: Forbidden

URL: https://m.youtube.com/watch?v=oSTPasj4OUM&pp=ygUGZWdnZG9n
WARNING: [youtube] oSTPasj4OUM: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = UtZslsLMPgLOk3m ; player = https://www.youtube.com/s/player/f55759b8/player_ias.vflset/en_US/base.js
ERROR: [youtube] oSTPasj4OUM: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![SmartSelect_20230606_030746_Seal](https://github.com/JunkFood02/Seal/assets/135656746/aacdb542-4472-413e-a206-55ba3e56c289)
![SmartSelect_20230606_030733_Seal](https://github.com/JunkFood02/Seal/assets/135656746/2c624c04-b18d-4e40-96dd-aa6aaf6b2289)
![SmartSelect_20230606_030648_Seal](https://github.com/JunkFood02/Seal/assets/135656746/5bd8a30d-b496-46d8-85b8-31bdcf914333)

### Device info

App version: 1.8.2-(F-Droid) (10824)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: null

### Additional context

‎

**Comment by Marco-9456** [comment]
You can install the latest update from [here](https://github.com/JunkFood02/Seal/releases/tag/v1.9.2), these are old issues that have been already fixed.

>**Note** :


1. You need to install the F-Droid version to be able to install the one I linked above.
2. After installing the version I linked, go to `Setting`--> `About`--> and enable `Auto update`to get the latest update seconds after it's publishing here

**Comment by chixteryaki** [comment]
Thank you i am going to try it Thank you for your assitance :)

**Comment by chixteryaki** [comment]
Hello it is still not downloading all it reads is "could not fetch video"

**Comment by Marco-9456** [comment]
> Thank you i am going to try it Thank you for your assitance :)

Can you switch yt-dlp channel to nightly? 
Here is a screen record that guides you to do it:


https://github.com/JunkFood02/Seal/assets/41828058/fe46defc-d05e-4e2d-a00e-5091db262016

**Comment by chixteryaki** [comment]
Thank you it works now!
![SmartSelect_20230610_050935_Seal](https://github.com/JunkFood02/Seal/assets/135656746/d930b006-0306-437a-9c01-158ec0f7e862)






But i still can't download from bilibili but i think it is something about bilibili being secure that i can't download i think im doing something wrong. Anyways Thank you
(ill find a way for me to download from bilibili)
