### ISSUE TITLE
Video unable to extract 

### ISSUE THREAD

**Issue by kannapi** [JunkFood02/Seal#862]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

App version: 1.10.0-beta.2 (10920)
Device information: Android 10 (API 29)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://www.instagram.com/reel/CqFjLKeg0q2/?igshid=MTc4MmM1YmI2Ng==
WARNING: [Instagram] unable to extract username; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [Instagram] CqFjLKeg0q2: Unable to extract video url; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Video link

https://www.instagram.com/reel/CqFjLKeg0q2/?igshid=MTc4MmM1YmI2Ng==

**Comment by JunkFood02** [comment]
#733
