### ISSUE TITLE
[Feature Request] Add preferred video codec option to video settings (H.264, H.265, etc)

### ISSUE THREAD

**Issue by andrei-cb** [JunkFood02/Seal#867]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

When downloading videos from Tiktok, the available formats are h264 and h265. Selecting mp4 as the preferred video format will automatically select the h265 version instead of h264. Sharing the h265 version is not supported on all platforms (ex. Discord), so we have to manually select the h264 version each time.

### Describe the solution you'd like

Add a preferred video codec option to settings.

### Video link

Any TikTok video

**Comment by JunkFood02** [comment]
currently you can get this done with custom format sorter, e.g `vcodec:h265`

**Comment by GrayLanterns** [comment]
> currently you can get this done with custom format sorter, e.g `vcodec:h265`

Am I missing something?! How can we set custom 'preferred video format'?

**Comment by JunkFood02** [comment]
@soredake Format sorting is the solution for this, I just forgot to close this after my reply

**Comment by soredake** [comment]
@JunkFood02 can you close it as "won't fix" then? It's confusing to see this closed as "completed" when nothing is done.
