### ISSUE TITLE
Some videos downloaded from Facebook do not appear in the photo gallery 

### ISSUE THREAD

**Issue by HungNoPro** [JunkFood02/Seal#868]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I've been using Seal for a few months now, some of the videos I download from Facebook appear in my photo library but most of the time they don't. Even though I try opening them in the file browser, it still works

### Error reports

No

### Device info

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

**Comment by JunkFood02** [comment]
It might be your gallery app not supporting the video format which is used by facebook

**Comment by HungNoPro** [comment]
Neither the default gallery nor Google photo appear, not even in the video submission in messenger or facebook
