### ISSUE TITLE
[Feature Request]Add proxy setting in settings

### ISSUE THREAD

**Issue by bigsun** [JunkFood02/Seal#875]
### Checklist

- [x] This feature I'm requesting is already implemented in yt-dlp.
- [x] This feature is merely a UI/UX update.
- [x] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

by adding a self defined comand the --proxy parameter, seal can download, but cant use the qulity and format selecting progress the app provided.
please add a proxy setting

### Describe the solution you'd like

please add a proxy setting

**Comment by JunkFood02** [comment]
Could you please share the proxy software you're using? I thought those VPN can be used with Seal without extra configurations
