### ISSUE TITLE
'NoneType' object has no attribute 'format' with latest yt-dlp version

### ISSUE THREAD

**Issue by ayesc9000** [JunkFood02/Seal#878]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When attempting to download videos from Twitter, Seal will fail with the error: 'NoneType' object has no attribute 'format'. I was able to verify that this issue only occurs with Twitter, but I am unable to replicate it at this time on a standalone version of yt-dlp.

This began to occur immediately after Seal downloaded the latest version of yt-dlp.

### To Reproduce

- Use seal 1.9.2 with yt-dlp 2023.06.21.
- Find a tweet with a video and copy the link to it.
- Paste the link into Seal.
- Seal will fail with the aforementioned error message.

### Error reports

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

URL: https://twitter.com/Siroos_/status/1671319738494996481?t=30xI25MaOQQnL8Mk9wAprw&s=19
ERROR: 'NoneType' object has no attribute 'format'

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

**Comment by JunkFood02** [comment]
Thanks for your report! I have reproduced this on my PC which indicates this is an upstream issue which should be reported to upstream maintainers

**Comment by JunkFood02** [comment]
Please switch to the latest nightly build or wait for the next release for a fix

**Comment by AntarCrypto** [comment]
same with Instagram reels

**Comment by temppizza** [comment]
And soundcloud

**Comment by JunkFood02** [comment]
Update yt-dlp to 2023.06.22
