### ISSUE TITLE
App version: 1.9.2 (10920) Device information: Android 11 (API 30) Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi] Yt-dlp version: 2023.06.21  URL: https://www.instagram.com/p/CtCZvewOFTI/?igshid=MzRlODBiNWFlZA== ERROR: 'NoneType' object has no attribute 'format'

### ISSUE THREAD

**Issue by Raviranayt** [JunkFood02/Seal#880]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

URL: https://www.instagram.com/p/CtCZvewOFTI/?igshid=MzRlODBiNWFlZA==
ERROR: 'NoneType' object has no attribute 'format'

### Error reports

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

URL: https://www.instagram.com/p/CtCZvewOFTI/?igshid=MzRlODBiNWFlZA==
ERROR: 'NoneType' object has no attribute 'format'

**Comment by BlastboomStrice** [comment]
Seal could still download insta reels, but the yt-dlp code got updated today (21-6-2023) and now it has issues again...
I could download reels yesterday without any account...
Is there any way to downgrade the yt-dlp version?

**Comment by JunkFood02** [comment]
Long-press the yt-dlp version and switch to nightly build

**Comment by JunkFood02** [comment]
Duplicate of #878
