### ISSUE TITLE
crunchyroll link problem

### ISSUE THREAD

**Issue by kowvac** [JunkFood02/Seal#881]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I was downloading a video from crunchyroll, I managed to download 3 episodes of one piece, when I went to download the fourth, I got this error: App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

URL: https://www.crunchyroll.com/pt-br/watch/GJWU2E1J7/someones-dream
ERROR: 'NoneType' object has no attribute 'format'
After that, I couldn't download anything else from the site. I'm a Premium user, the app was working normally and downloading episodes correctly, but this happened 
![Screenshot_2023-06-21-12-25-14-438_com junkfood seal](https://github.com/JunkFood02/Seal/assets/102343994/ee90a32b-ac0c-4e0d-9ac5-83bc93819173)

### Error reports

URL: https://www.crunchyroll.com/pt-br/watch/GJWU2E1J7/someones-dream
ERROR: 'NoneType' object has no attribute 'format'

### Screenshots & Screen Records

![Screenshot_2023-06-21-12-25-14-438_com junkfood seal](https://github.com/JunkFood02/Seal/assets/102343994/6f66b2f8-7f89-410f-b5e0-f6241bd32a25)

### Device info

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

**Comment by Marco-9456** [comment]
Do this and it should work again.

https://github.com/JunkFood02/Seal/assets/41828058/e028da58-6381-4073-b0b2-54ff67557cd5

**Comment by Marco-9456** [comment]
No problem.
Please close the issue as completed
