### ISSUE TITLE
Nonetype

### ISSUE THREAD

**Issue by sanu199822** [JunkFood02/Seal#882]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Can't download video files from some sites 

### To Reproduce

1.twitter.com
2.select any file with videos
3.share to seal
4.ERROR: 'NoneType' object has no attribute 'format'

### Error reports

ERROR: 'NoneType' object has no attribute 'format'

### Device info

App version: 1.10.0-beta.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.21

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/878
