### ISSUE TITLE
Photos download in seal features

### ISSUE THREAD

**Issue by Artist1513** [JunkFood02/Seal#885]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by Marco-9456** [comment]
Will never happen, forget about it, only  pictures you can download using Seal are the video/audio thumbnails/artworks.
