### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by Sureshkumar7892** [JunkFood02/Seal#888]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Download problem 

### Error reports

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 12 (API 31)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.22

URL: https://www.tamildhool.net/vijay-tv/vijay-tv-show/cooku-with-comali-season-4/cooku-with-comali-25-06-2023-vijay-tv-show-2/
WARNING: [generic] Falling back on generic information extractor
ERROR: Unsupported URL: https://www.tamildhool.net/vijay-tv/vijay-tv-show/cooku-with-comali-season-4/cooku-with-comali-25-06-2023-vijay-tv-show-2/

**Comment by JunkFood02** [comment]
Unsupported site
