### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by killua1232** [JunkFood02/Seal#891]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Yes, after recent updates they added function of direct download and format selections, suggested format does not support in whatsapp only when its download at normal video h.264 format 

### Describe the solution you'd like

Since they is a extra step on selecting format and video option is way under the bottom Last of formats list, i suggest to add a button to save prefered format options so i dont have to manually select every time i want to download a video

**Comment by JunkFood02** [comment]
Turn off format selection and follow #867
