### ISSUE TITLE
Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{fd9fa50 25392:com.junkfood.seal/u0a460} (pid=25392, uid=10460) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

### ISSUE THREAD

**Issue by Chainstopper** [JunkFood02/Seal#892]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{fd9fa50 25392:com.junkfood.seal/u0a460} (pid=25392, uid=10460) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

### Error reports

Permission Denial: opening provider com.android.externalstorage.ExternalStorageProvider from ProcessRecord{fd9fa50 25392:com.junkfood.seal/u0a460} (pid=25392, uid=10460) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

**Comment by Marco-9456** [comment]
Can you provide more info please, like a video link, screenshot a screen record, your phone version the app version and maybe describe what you were trying to do?

**Comment by Jackaru47** [comment]
> @Chainstopper Can you provide more info please, like a video link, screenshot a screen record, your phone version the app version and maybe describe what you were trying to do?

I'm Having the same problem, please reply if you need any Information.

**Comment by Marco-9456** [comment]
Yes please, provide all the info that i asked for if possible

**Comment by Jackaru47** [comment]
![Screenshot_20230627_210340](https://github.com/JunkFood02/Seal/assets/42704108/1f650f29-207e-4159-8637-ae2890c67aba)

No matter the video from YouTube, it will show this error.

**Comment by JunkFood02** [comment]
This seems like a permission issue. Which directory are you using for downloading?

**Comment by Jackaru47** [comment]
> This seems like a permission issue. Which directory are you using for downloading?

Wdym?

**Comment by JunkFood02** [comment]
> > This seems like a permission issue. Which directory are you using for downloading?
> 
> Wdym?

Settings - Download directory

Also, go to Settings - About, tap on the version and paste the information here

**Comment by Chainstopper** [comment]
Here is the link:

https://www.instagram.com/reel/CtvCIfYAwgu/?igshid=MzRlODBiNWFlZA==

Method used is share =>seal=>quick download=>
Then the video is downloading..before it finishes
It always shows that error..  no matter what videos i download  either fro
youtube or insta..the result is the same..even fro. The previous version of
the latest release ver 9..

Im using the beta ver 10 hoping it would resolve the issue ..yet the result
is the same..

Thanks guys for any help and listening to this concern


Samsung A73 5g 256gb/ s23 ultra 512gb

**Comment by Jackaru47** [comment]
> > > This seems like a permission issue. Which directory are you using for downloading?
> > 
> > Wdym?
> 
> Settings - Download directory
> 
> Also, go to Settings - About, tap on the version and paste the information here
> 

I fixed it lol.. ihad to reselect the directory because the old one disappeared lol

**Comment by Chainstopper** [comment]
Haha, thanks!
