### ISSUE TITLE
Crunchyroll download problem HTTP error 403

### ISSUE THREAD

**Issue by kowvac** [JunkFood02/Seal#894]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I put the episode link for download, and this error happened. I tested with both versions of Yt-dlp (Stable/Nightly)

### Error reports

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.27.215123

URL: https://www.crunchyroll.com/watch/G6WEMJNE6?utm_medium=android&utm_source=share
ERROR: [crunchyroll] G6WEMJNE6: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

![Screenshot_2023-06-27-21-33-31-888_com junkfood seal](https://github.com/JunkFood02/Seal/assets/102343994/3882ef71-4811-4b6f-a22e-3fdcbbe42b25)

### Device info

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.27.215123

### Additional context

I'm not sure if it's a problem related to crunchyroll or in the Seal itself

**Comment by Marco-9456** [comment]
![Screenshot_20230628_042719_Seal](https://github.com/JunkFood02/Seal/assets/41828058/6128d459-02c8-4a17-a40a-ab6ab9f3aacc)

1. 🔧 Go to "Settings"

2. 🌐 Click "Network"

3. 🍪 Click "Cookies"

4. 🔑 Click "Generate new cookies"

5. 🔗 Type or paste the URL of the website you want to access with the new cookies

6. 🍪 Click "Generate new cookies"

7. 👤 Login to your account on the website using your login credentials

8. ✔️ Click "Done" to finish the process.

9. ✅ Click on "Confirm"

**Comment by kowvac** [comment]
> 
> ![Screenshot_20230628_042719_Seal](https://github.com/JunkFood02/Seal/assets/41828058/6128d459-02c8-4a17-a40a-ab6ab9f3aacc)
> 
> 1. 🔧 Go to "Settings"
> 
> 2. 🌐 Click "Network"
> 
> 3. 🍪 Click "Cookies"
> 
> 4. 🔑 Click "Generate new cookies"
> 
> 5. 🔗 Type or paste the URL of the website you want to access with the new cookies
> 
> 6. 🍪 Click "Generate new cookies"
> 
> 7. 👤 Login to your account on the website using your login credentials
> 
> 8. ✔️ Click "Done" to finish the process.
> 
> 9. ✅ Click on "Confirm"

Well I had done that before but it hadn't worked, this time it worked.🤷🏻‍♂️
