### ISSUE TITLE
Crunchyroll download problem 

### ISSUE THREAD

**Issue by kowvac** [JunkFood02/Seal#895]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I put the link to the download video and this error appears, yesterday an error similar to this one appeared but I managed to "solve it", but today this other error appeared 😐

### Error reports

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.27.215123

URL: https://www.crunchyroll.com/pt-br/watch/GR8VMNP4R/its-name-is-the-new-world-the-fate-of-the-grand-line
ERROR: [crunchyroll] GR8VMNP4R: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

### Screenshots & Screen Records

https://github.com/JunkFood02/Seal/assets/102343994/5728595c-1e75-40eb-8f94-6522617bbfcc

### Device info

App version: 1.9.2 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.27.215123

**Comment by Marco-9456** [comment]
There is an issue with the Crunchyroll extractor, please wait till it get fixed.

https://github.com/yt-dlp/yt-dlp/issues/7442

**Comment by kowvac** [comment]
> There is an issue with the Crunchyroll extractor, please wait till it get fixed.
> 
> https://github.com/yt-dlp/yt-dlp/issues/7442
> 
> Edit: You can try to refresh the cookies, this worked for some people, according to the comments they left.
> 
> Like this:
> 
> <details>
> <summary>Details</summary>
> 
> 
> https://github.com/JunkFood02/Seal/assets/41828058/f9284a88-db5f-4299-a13c-d86a8e13628a
> 
> 
> 
> </details>

I already tried but the problem remains :(
