### ISSUE TITLE
Still saves as MKV even it's set to MP4. (Instagram)

### ISSUE THREAD

**Issue by emmanueldlauron** [JunkFood02/Seal#896]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I only experience this with Instagram, reels specifically.

I set the preferred video format to MP4, but when I the download is done it's still on MKV format.

Here's the link of the video I'm downloading:
https://www.instagram.com/reel/CtRskhUAOPg/?igshid=MzRlODBiNWFlZA==

### To Reproduce

Steps to reproduce (for me) (Settings are the same from attached screenshot)
1. Open IG app.
2. Play video.
3. Share the video to Seal as Quick Download.
4. After downloading it is saved as MKV. Not as MP4.

### Error reports

No error message.

### Screenshots & Screen Records

My settings:
![Screenshot_20230629_221412_Seal](https://github.com/JunkFood02/Seal/assets/41054824/c6757f33-83f6-42b7-b25f-43784c022446)

I can't attach the screen recording. I don't know why it's not uploading.

### Device info

App version: 1.9.2
Device: Samsung Galaxy A52 4G (Android 13)
Yt-dpl version: 2023.06.22

### Additional context

If there's anything I can provide to explain the problem I'm facing please let me, know.

**Comment by emmanueldlauron** [comment]
The link replied to me is about not being able to download the video, but in my case I can download the video but in other format.

**Comment by Marco-9456** [comment]
No Problem :)
