### ISSUE TITLE
[Feature Request] Adding additional information to the name of the downloaded file.

### ISSUE THREAD

**Issue by NewNewPipe** [JunkFood02/Seal#899]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Adding to the name of the downloaded file the date of its posting on YT and the name of the channel from which it is downloaded, and the ability to edit the file name before downloading.

**Comment by JunkFood02** [comment]
> Adding to the name of the downloaded file the date of its posting on YT and the name of the channel from which it is downloaded

You can append custom prefix to the filename, take a look at Settings - Download directory - Custom subdirectory

> the ability to edit the file name before downloading.

Turn on format selection and tap on the video title on the format page
