### ISSUE TITLE
[Bug] Operation Not Permitted YT

### ISSUE THREAD

**Issue by b-risk** [JunkFood02/Seal#906]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Downloads the entire thing, and when it's about to finish it just says Errrno 1 Operation Not Permitted

### To Reproduce

Download any video and wait until it finishes downloading

### Error reports

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 7.0 (API 24)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.22

URL: https://youtu.be/GAmopOWuKlY
ERROR: [Errno 1] Operation not permitted

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 7.0 (API 24)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.06.22

**Comment by JunkFood02** [comment]
#873 ?

**Comment by JunkFood02** [comment]
#892 ?

**Comment by b-risk** [comment]
> #892 ?

odd, but after replacing the directory that seemed to be missing it seems as if the download is completed, i can open the file in a video player, yet i still get the error within the app? other than that it works just fine, thanks for showing me

![Screenshot_20230701-063321](https://github.com/JunkFood02/Seal/assets/89107446/00d5c6dc-8e7e-4093-9944-f870ca0a3052)
![Screenshot_20230701-063541](https://github.com/JunkFood02/Seal/assets/89107446/fc45d392-ee34-47ea-961e-5ecd965fc16d)

**Comment by JunkFood02** [comment]
Please go to Settings - Download directory and turn on Temporary directory and see if it works

**Comment by b-risk** [comment]
> Please go to Settings - Download directory and turn on Temporary directory and see if it works

already enabled

**Comment by b-risk** [comment]
here's all my settings
![Screenshot_20230701-123227](https://github.com/JunkFood02/Seal/assets/89107446/622356e4-61b8-4527-940e-4b78a32055f0)
![Screenshot_20230701-123214](https://github.com/JunkFood02/Seal/assets/89107446/6e70c759-8c9b-4471-82b0-87117cb2b242)

**Comment by bedouinn** [comment]
Try changigng yt-dlp to yt-dlp-nigtly-builds in general settings
