### ISSUE TITLE
Download issue - 1.10.0-beta.3

### ISSUE THREAD

**Issue by Birraque** [JunkFood02/Seal#909]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Twitter download doesn't work anymore.

### To Reproduce

1. Go to Twitter app
2. Select any video and click to Share it
3. Select Quick Seal
4. Download doesn't start 

### Error reports

None error reported 

### Screenshots & Screen Records

Nothing happened even the file downloading

### Device info

Twitter 9.92.0-release.0
Seal 1.10.0-beta.3

**Comment by Birraque** [comment]
Device: Xiaomi Poco F3
Android 13, MIUI 14

**Comment by Birraque** [comment]
![Screenshot_2023-07-02-14-51-58-538_com junkfood seal](https://github.com/JunkFood02/Seal/assets/44372413/6f2e9a30-d240-4378-b4d6-cd98d8f5db3d)

**Comment by Marco-9456** [comment]
https://github.com/JunkFood02/Seal/issues/912#issuecomment-1616678547

**Comment by Birraque** [comment]
I confirm that when we're getting errors when downloading, go to Settings - Network - Cookies, add https://www.twitter.com, log-in with your account, then enable cookies and try again, WORKAROUND the issue. You can also follow this instruction to add cookies for other sites to the app.

**Comment by Birraque** [comment]
With the above mentioned workaround Seal is flawless again when downloading Twitter videos.
