### ISSUE TITLE
[Feature Request] For tiktok, put account name into filename

### ISSUE THREAD

**Issue by x8086** [JunkFood02/Seal#913]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Right now, for some reason when downloading tiktok videos, the resulting filename only contains the video name but not the account name. The only way to know account name is to go into the seal app and see it in the list. Well one day when I don't have the seal app, all these videos are going to be source less. I need the account name in the filename of every video I download. I don't download from other apps right now but perhaps put account name for every other site too.

### Describe the solution you'd like

When creating video filename for tiktok videos, append tiktok user account name into the filename that already includes video name. 

### Additional context

Perhaps make this feature for every video app too and not just tiktok.

**Comment by Marco-9456** [comment]
Go to `Settings` --> `Download Directory` --> `Custom subdirectory`, and replace everything with this:

`%(uploader)s`

`Confirm` and `enable` the option, and this will make the app add the user name of the video/audio uploader to the file name.
