### ISSUE TITLE
Limited sections download 

### ISSUE THREAD

**Issue by Alexprox7** [JunkFood02/Seal#924]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I'd like the possibility to choose a small part of a video e.g from 3:06 to 5:02 and download it's audio or video.

**Comment by Marco-9456** [comment]
Go to settings--> format --> enable Clip  Video
