### ISSUE TITLE
Facebook : cannot parse data

### ISSUE THREAD

**Issue by Yoanndp** [JunkFood02/Seal#937]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I have been experiencing difficulties in downloading videos from Facebook for quite some time now. I have read through issue #733 in this repository, which seems to address a similar problem, but the suggested workaround of logging into Facebook through the app and storing the cookies did not resolve the issue for me.

Despite following the suggested workaround, I am still unable to download any videos from Facebook using Seal. Could you please provide further guidance on any additional workarounds that might help resolve this issue?

Furthermore, if the suggested workarounds do not solve the problem, what would be the recommended course of action? Are there any alternative methods or troubleshooting steps I can take to troubleshoot this issue further?

Thank you for your attention to this matter.

### To Reproduce

1. Copy the Facebook video URL
2. Launch Seal
3. Paste the copied Facebook video URL into the appropriate field 
4. Click on the download to initiate the video download process

### Error reports

ERROR: [facebook] 1675722746193098: Cannot parse data

### Screenshots & Screen Records

![Screenshot_20230711-204433](https://github.com/JunkFood02/Seal/assets/13591243/0d88739e-e719-48a3-9193-501eb23728f7)

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a]
Yt-dlp version: 2023.07.06

**Comment by Marco-9456** [comment]
> I have read through issue https://github.com/JunkFood02/Seal/issues/733 in this repository, which seems to address a similar problem, but the suggested workaround of logging into Facebook through the app and storing the cookies did not resolve the issue for me.

Nothing else can make it work, you can try using a VPN to a European country, it's a Geo restriction from meta that we can't do anything about, the maintainers of yt-dlp (Seal Engine) also can't do anything this issue is hard to reproduce on their end.
_________________________________________________________
> Furthermore, if the suggested workarounds do not solve the problem, what would be the recommended course of action? Are there any alternative methods or troubleshooting steps I can take to troubleshoot this issue further?

Quoting the part that you've ignored from issue #733 :

> If the issue persists, which unfortunately means there's nothing we can do about it as such problem is hard to reproduce on the developer side.

**Comment by Marco-9456** [comment]
> Thank you for your response. I appreciate your help in addressing this issue. As I am located in Europe, would it still be necessary for me to use a VPN based in Europe?

It's working in Germany, try it, it might work
