### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ahmed18354** [JunkFood02/Seal#938]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [X] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I wish if you can make the app read the files in it download path so when I want to download a couple of new songs from a playlist (that I already downloaded songs from) I can download the new ones only without making duplicates of the same songs downloaded before when I click select all

### Describe the solution you'd like

Add a marker on the songs downloaded before that shows it's already downloaded and prevent the app from downloading it again

**Comment by JunkFood02** [comment]
the app checks if the file exists by its filename and skips duplicated items
