### ISSUE TITLE
Add more control over the output path template

### ISSUE THREAD

**Issue by JunkFood02** [JunkFood02/Seal#946]

**Comment by fillwithjoy1** [comment]
Will this include the -o output path option inside Seal?

**Comment by JunkFood02** [comment]
Custom output template: added in v1.11.0-beta.1

**Comment by wvzxn** [comment]
Hi, I propose to add an option to select output templates in the quick download menu.
Also, add the ability to create not just one template, but multiple ones.
For example,
- Title only: `%(title)s.%(ext)s`
- Channel+Title: `%(channel)s - %(title)s.%(ext)s`

![seal feature request](https://github.com/JunkFood02/Seal/assets/87862400/559f6a41-64fa-46d8-81b3-eff514159de4)

**Comment by fillwithjoy1** [comment]
> Hi, I propose to add an option to select output templates in the quick download menu. Also, add the ability to create not just one template, but multiple ones. For example,
> 
>     * Title only: `%(title)s.%(ext)s`
> 
>     * Channel+Title: `%(channel)s - %(title)s.%(ext)s`
> 
> 
> ![seal feature request](https://private-user-images.githubusercontent.com/87862400/292749657-559f6a41-64fa-46d8-81b3-eff514159de4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MDA4ODgsIm5iZiI6MTcwMzYwMDU4OCwicGF0aCI6Ii84Nzg2MjQwMC8yOTI3NDk2NTctNTU5ZjZhNDEtNjRmYS00NmQ4LTgxYjMtZWZmNTE0MTU5ZGU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE0MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMmZhNjY5Nzk1ZTg2MmU3MDlmZjZiZTUxMmMzOTlmZDkzNTcyNTQ2MmViMGIwNTg4YmYzMzg1ODE1YTFlOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b6i-EiRNKB1Pb7fX54r2CWfNnqk0aGZ51334nnmYJ88)

Maybe a single chip on output path template would be good - reduce clutter, and I also think we should just have the ability to add more output path templates like we currently do with custom commands
