### ISSUE TITLE
Change of video format from .mp4 to .webm when moving videos to an usb flash drive, corrupted videos

### ISSUE THREAD

**Issue by manuelps1** [JunkFood02/Seal#951]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

I downloaded some videos from a Youtube playlist in mp4 format from a tablet. When I move those videos to a usb flash drive, the file name of each video is appended to the end before the extension two braces [] with a sequence of 11 characters and some of the videos are transformed into webm files. When I connect the usb flash drive to a mac and try to open the mp4 videos with QuickTime Player, a message is shown: "This file contains content that is incompatible with QuickTime Player." and when I force it to open the video, only audio is displayed. I can open both webm and mp4 videos with VLC.

To sum up, the problems are the change of file format, the braces with a sequence of characters, and the fact that those videos that preserve the mp4 format appear to be corrupted.

### To Reproduce

1. Open Seal and write the link of a Youtube channel's video list.
2. In "General", choose "Download playlist"
3. Don't choose anything in "Advanced"
4. In "Additional settings", choose as preferred video format "not specified (default)"
5. In "Additional settings", choose as video resolution "360p"
6. Click "download"
7. Select videos to download (I downloaded about 200 videos if it helps)
8. Download them
9. Move them to a usb flash drive

### Error reports

No error report is shown because the problem appers when I try to move the downloaded files to a usb flash drive.

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 12 (API 32)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by manuelps1** [comment]
As an addition, I've just noticed that the braces with characters are added directly when the videos are downloaded.

**Comment by JunkFood02** [comment]
Just install vlc player on your mac too

**Comment by manuelps1** [comment]
> Just install vlc player on your mac too

But, what about the change of file format and the file names? For example, if I download the video "Name of the video" in .mp4 format, when downloaded, I get "Name of the video [6DSbDhgdG4k].webm"

**Comment by JunkFood02** [comment]
> when downloaded, I get "Name of the video [6DSbDhgdG4k].webm"

See #675

> choose as preferred video format "not specified (default)"

select mp4 if you want
