### ISSUE TITLE
Add an option to download videos from a playlist with adding prefixes like 1,2,3 etc in order so it can be viewed offline without struggle 

### ISSUE THREAD

**Issue by Storyspeller** [JunkFood02/Seal#968]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by JunkFood02** [comment]
Use custom subdirectory and use `%(playlist_index)s` in the template
