### ISSUE TITLE
User guide menu [Bug]

### ISSUE THREAD

**Issue by Marco-9456** [JunkFood02/Seal#97]
User guide in German is not showing the don't show up again option, if the user want it to appear he must open the sittings and change to another language and then back to German.

The Bug: https://drive.google.com/file/d/1y2aJguYCFwuLtktijVU2xD7HFRB8Gk6T/view?usp=drivesdk

**Comment by JunkFood02** [comment]
This is intended behavior, the "don't show up again" option is not available in its first launch.

**Comment by Marco-9456** [comment]
> This is intended behavior, the "don't show up again" option is not available in its first launch.

Ah OK I didn't know that
