### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by has9sayed** [JunkFood02/Seal#974]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

There is no mp3 format for audio download.

### Describe the solution you'd like

Please add mp3 format for audio download.

**Comment by Marco-9456** [comment]
If the website you're downloading from doesn't have mp3 then seal won't show it in the format selection page, though you can go to the app settings --> Format --> Enable save as audio --> and click on Convert audio format and choose Convert to mp3 and confirm.
