### ISSUE TITLE
ERROR: [facebook] 1355192142077018: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U[Feature Request]

### ISSUE THREAD

**Issue by amitsaini2** [JunkFood02/Seal#977]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

**Comment by amitsaini2** [comment]
ERROR: [facebook] 1355192142077018: No video formats found!; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by 151071** [comment]
Please saul issues

**Comment by Marco-9456** [comment]
If you see the `No video formats found` error try downloading without the format selection option, usually works.

**Comment by 151071** [comment]
App version: 1.9.2 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://fb.watch/mvewbwp1lO/?mibextid=CDWPTG
ERROR: [facebook] 593967989574346: Cannot parse data; please report this
issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the
appropriate issue template. Confirm you are on the latest version using
yt-dlp -U
