### ISSUE TITLE
An Unknown Error Occurred when depositing LumenDex into liquidity pool

### ISSUE THREAD

**Issue by tatnu** [JunkFood02/Seal#979]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

On LumenDex website I bought LumenDex tokens.  I pressed button to deposit them into liquidity pool when I received an Unknown Error message.  It said to report to github with account:

GDUIMVWDTISRVGPDRBQAU3TMPPTVLZDMYSBBTYVDJBTRYMG3UHENVL7O

### Error reports

Url: https://www.lumendex.online/liquidity/
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Error: Unknown operation type: liquidityPoolDeposit
    at Function.value (https://www.lumendex.online/ledger/:31:5323509)
    at https://www.lumendex.online/ledger/:31:5323792
    at Array.map (<anonymous>)
    at r.value (https://www.lumendex.online/ledger/:31:5323679)
    at r.value (https://www.lumendex.online/ledger/:31:5324843)
    at xs (https://www.lumendex.online/ledger/:31:3435238)
    at Ms (https://www.lumendex.online/ledger/:31:3432470)
    at Sa (https://www.lumendex.online/ledger/:31:3475926)

**Comment by JunkFood02** [comment]
?
