### ISSUE TITLE
Download bug

### ISSUE THREAD

**Issue by hamza0786** [JunkFood02/Seal#981]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

App version: 1.10.0-beta.3 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [x86_64, x86, arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: https://www.dailymotion.com/video/x7wkhff
/data/app/~~kj7Q3_sDcUudzm0eB_lK4g==/com.junkfood.seal-JJpV0OzCnqAS9W7DGkUHnQ==/lib/arm64/libpython.so[1]: syntax error: unexpected '�Q
�o��t��'

### Error reports

/data/app/~~kj7Q3_sDcUudzm0eB_lK4g==/com.junkfood.seal-JJpV0OzCnqAS9W7DGkUHnQ==/lib/arm64/libpython.so[1]: syntax error: unexpected '�Q
�o��t��'

### Device info

App version: 1.10.0-beta.3 (10920)
Device information: Android 11 (API 30)
Supported ABIs: [x86_64, x86, arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by JunkFood02** [comment]
did you try reinstalling the app?

**Comment by hamza0786** [comment]
of course many times again and again same error.any help is appreciated.

**Comment by Marco-9456** [comment]
Are you using the app on a phone or an Android emulator/WSA?

**Comment by hamza0786** [comment]
yes on bluestacks android 11.

**Comment by Marco-9456** [comment]
You should have mentioned that before, Seal wasn't developed to work on emulators, try using WSA it works for me.
