### ISSUE TITLE
[Feature Request] Create a desktop (Linux, Windows, Mac) version of seal

### ISSUE THREAD

**Issue by ayntk-ai** [JunkFood02/Seal#985]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

I mostly download videos on windows or my mac but I always have to use crappy websites, the seal app on my phone works so perfect and seamless, please bring this experience to a desktop app client. Or if this project already exists, what is it called?

### Describe the solution you'd like

Desktop version with no ads, full app features, same clean UI and UX. Full functionality, no popups and so on.

**Comment by Sal7one** [comment]
There are already plenty of tools that do this, I recommened [Cobalt](https://github.com/wukko/cobalt)

**Comment by ayntk-ai** [comment]
Are there any with a Windows application?

**Comment by Sal7one** [comment]
You can self host it, or look up  ```yt-dl gui```, try a bunch see what you like.

**Comment by ayntk-ai** [comment]
Thank you so much
