### ISSUE TITLE
Download videos from youtube is not showing when try to import them

### ISSUE THREAD

**Issue by disc0nct** [JunkFood02/Seal#987]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

When i try to import videos that are downloaded from youtube,I can't. But when i got file manager I find them opens normally.
Ex:when i try to import them to Capcut or try to upload to instagram,I can't select them.
Only happens with youtube

### To Reproduce

Download video from YouTube.

### Error reports

None

### Device info

App version: 1.9.2-(F-Droid) (10924)
Device information: Android 8.0.0 (API 26)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by JunkFood02** [comment]
Enable Format selection and select format 22 or any formats with avc1 codec

**Comment by JunkFood02** [comment]
Update to v1.10.0-rc.1 and set preferred format to legacy
