### ISSUE TITLE
Twitter downloads stopped working

### ISSUE THREAD

**Issue by Birraque** [JunkFood02/Seal#988]
### Checklist

- [x] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Describe the bug

Twitter downloads stopped working after latest update even when Settings \ Network \ Cookies (enabled)
Let me know more information needed.
Thanks in advance,

### To Reproduce

1. Open Twitter (X) app and select a video content
2. Click to Share to... then select Seal Quick
3. Nothing happens (annex)

### Error reports

App version: 1.10.0-beta.4 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

URL: 
ERROR: [twitter] 1691200652410556416: No video could be found in this tweet

### Screenshots & Screen Records

![Screenshot_2023-08-14-22-00-55-657_com junkfood seal](https://github.com/JunkFood02/Seal/assets/44372413/960bfbb3-f047-42b4-8337-234d36496088)

![Screenshot_2023-08-14-22-00-44-922_com junkfood seal](https://github.com/JunkFood02/Seal/assets/44372413/d3755c6e-35fb-49a6-a74c-9443ddbc1001)

[Recorded Video - Error](https://streamable.com/1bgi8c) 

### Device info

Version: 1.10.0-beta.4 (10920)
Device information: Android 13 (API 33)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.07.06

**Comment by JunkFood02** [comment]
Settings - General - Long press on yt-dlp version and switch to nightly build

**Comment by Birraque** [comment]
> Settings - General - Long press on yt-dlp version and switch to nightly build

After yt-dlp version switch to nightly build Seal are working flawlessly again.
Thanks for your prompt response.

![Screenshot_2023-08-14-23-32-19-380_com twitter android-edit](https://github.com/JunkFood02/Seal/assets/44372413/72c95eb0-582f-40ce-b1b6-de3d14e64199)

![Screenshot_2023-08-14-23-25-36-062_com junkfood seal](https://github.com/JunkFood02/Seal/assets/44372413/9f8137a0-08bf-4069-8d3c-281f84776064)

**Comment by Birraque** [comment]
**NOTE**: I just noticed that now with the latest Seal version when click at notifications (screenshot above) the video player doesn't open anymore.
To click on the notification hadn't any effect.

**Comment by JunkFood02** [comment]
Did you download with Incognito mode enabled?

**Comment by Birraque** [comment]
> Did you download with Incognito mode enabled?

Thanks for your input.
My bad! The incognito move were enabled.
Already disabled it again and notifications works flawlessly.
