### ISSUE TITLE
Add and option to pause the downloading tasks

### ISSUE THREAD

**Issue by aransari1** [JunkFood02/Seal#994]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Cant pause the downloading tasks which results in task downloading error.

### Describe the solution you'd like

A an option to pause the task so that the downloading tasks can be paused based on the conditions and preferences. we can download any video firstly and the resume the other tasks. Other Downloader such as new pipe already has this feature.

**Comment by Marco-9456** [comment]
Already requested
