### ISSUE TITLE
[Feature Request] Downloading multiple videos in parallel 

### ISSUE THREAD

**Issue by fillwithjoy1** [JunkFood02/Seal#995]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [X] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Since yt-dlp has some stages, some that are network-dependent then cpu-dependent, I would like if it was possible to download multiple videos concurrently. I looked through yt-dlp and somebody mentioned using aria-2c, that this github repo also uses https://github.com/ytdl-org/youtube-dl/issues/350#issuecomment-244847884

### Describe the solution you'd like

Multiple downloads

### Additional context

Someone else did this, but I don't know if it works currently https://github.com/yt-dlp/yt-dlp/issues/1918#issuecomment-988069516

**Comment by Douile** [comment]
Multi-threaded downloads with aria2c is already supported (network options). Downloading multiple videos in parallel is not though (there is a workaround by sharing URLs and using quick download).

**Comment by fillwithjoy1** [comment]
Right, my bad. I'll change the title of the issue
