### ISSUE TITLE
Youtube and twitter links aren't downloading anymore 

### ISSUE THREAD

**Issue by Tigger-S** [JunkFood02/Seal#996]
### Checklist

- [ ] I'm reporting a bug unrelated to a specific site.
- [X] I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
- [X] I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
- [X] I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
- [X] I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
- [X] I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.

### Error reports

For twitter App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://twitter.com/City_Xtra/status/1692823718962335871?t=XX7AX6iTaEfhMfSdfQ8WHA&s=19
WARNING: [twitter] Twitter API gave 404 response, retrying with deprecated auth token. Only one media item can be extracted
ERROR: [twitter] 1692823718962335871: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

 For youtube
App version: 1.9.2 (10920)
Device information: Android 9 (API 28)
Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
Yt-dlp version: 2023.03.04

URL: https://youtu.be/Xlm2iMsYM2Q
WARNING: Unable to download video thumbnail 41: HTTP Error 404: Not Found
WARNING: The download speed shown is only of one thread. This is a known issue
ERROR: 
[download] Got error: HTTP Error 403: Forbidden. Giving up after 10 retries
ERROR: fragment 1 not found, unable to continue

**Comment by fillwithjoy1** [comment]
You need to post this issue on https://github.com/yt-dlp/yt-dlp as these types of errors need to be posted over there

**Comment by Tigger-S** [comment]
OK thanks, they said, "you or the developer of your app need to update yt-dlp to the nightly version, or wait for the next release"

**Comment by Marco-9456** [comment]
@Tigger-S 


https://github.com/JunkFood02/Seal/assets/41828058/d2e8b4cc-027f-442f-9f31-3a9cb11869f6
