### ISSUE TITLE
[Feature Request] Custom video titles (Very easy to implement)

### ISSUE THREAD

**Issue by fillwithjoy1** [JunkFood02/Seal#998]
### Checklist

- [X] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [X] This feature is available for most websites, not only the video platform I use.
- [X] This feature is suitable for a large variety of videos.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Add the ability to customize the output video's title format. This is implemented as -o in yt-dlp.

**Comment by Marco-9456** [comment]
Click on the video/audio title in the format selection page, you'll get the option to rename it.

**Comment by fillwithjoy1** [comment]
> Click on the video/audio title in the format selection page, you'll get the option to rename it.

It doesn't work for playlists

**Comment by fillwithjoy1** [comment]
Seems like it's being worked on in #946

**Comment by fillwithjoy1** [comment]
Oh I forgot to mark this as closed, thanks for reminding

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>
