### ISSUE TITLE
[Feature Request] Add more choices to audio quality preference

### ISSUE THREAD

**Issue by Ciktri** [JunkFood02/Seal#999]
### Checklist

- [ ] This feature I'm requesting is already implemented in yt-dlp.
- [ ] This feature is merely a UI/UX update.
- [ ] This feature is suitable for primary users with little knowledge about yt-dlp.
- [ ] This feature is available for most websites, not only the video platform I use.
- [ ] This feature is suitable for a large variety of videos.
- [ ] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

Low or "ultra low" Audio quality choice in option, to make playlist download work for low quality audio format, the lowest option is 64kbps...
.
Add more 32, 24,16 kbps
.
So playlist download can donwloading low bitrate audio format, To save storage... 
Thank you

![Screenshot_2023-08-20-17-25-43-83_2b0c70832456616f1f794bb05bb8d2fa](https://github.com/JunkFood02/Seal/assets/142722305/e4891b49-1afb-466a-af52-c5505081100e)

### Describe the solution you'd like

Add more audio quality bitrate option like 32, 24, 16 kbps Bitrate option..
So that the playlist download can work on low or ultra low audio quality.,..

**Comment by JunkFood02** [comment]
Currently you can use `+abr` to the Format sorter option and enable it to download the smallest audio, for more usage refer to https://github.com/yt-dlp/yt-dlp#sorting-formats
